description = 'FOCUS standard devices'

mota = 'SQ:FOCUS:mota:'
motb = 'SQ:FOCUS:motb:'

devices = dict(
    mgo = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator Goniometer',
        motorpv = mota + 'MGO',
        errormsgpv = mota + 'MGO-MsgTxt',
        precision = 0.2,
    ),
    msl = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator SL',
        motorpv = mota + 'MSL',
        errormsgpv = mota + 'MSL-MsgTxt',
        precision = 0.2,
    ),
    mth = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator Rotation',
        motorpv = mota + 'MTH',
        errormsgpv = mota + 'MTH-MsgTxt',
        precision = 0.2,
    ),
    mtt = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator Two Theta',
        motorpv = mota + 'MTT',
        errormsgpv = mota + 'MTT-MsgTxt',
        precision = 0.2,
    ),
    mtx = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator X Translation',
        motorpv = mota + 'MTX',
        errormsgpv = mota + 'MTX-MsgTxt',
        precision = 0.2,
    ),
    mty = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator Y TRanlation',
        motorpv = mota + 'MTY',
        errormsgpv = mota + 'MTY-MsgTxt',
        precision = 0.2,
    ),
    m1cv = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator 1 vertical curvature',
        motorpv = motb + 'M1CV',
        errormsgpv = motb + 'M1CV-MsgTxt',
        precision = 0.2,
    ),
    m1ch = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator 1 horizontal curvature',
        motorpv = motb + 'M1CH',
        errormsgpv = motb + 'M1CH-MsgTxt',
        precision = 0.2,
    ),
    m2cv = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator 2 vertical curvature',
        motorpv = motb + 'M2CV',
        errormsgpv = motb + 'M2CV-MsgTxt',
        precision = 0.2,
    ),
    m2ch = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator 2 horizotal curvature',
        motorpv = motb + 'M2CH',
        errormsgpv = motb + 'M2CH-MsgTxt',
        precision = 0.2,
    ),
    mex = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'Monochromator side',
        motorpv = motb + 'MEX',
        errormsgpv = motb + 'MEX-MsgTxt',
        precision = 0.2,
    ),
    wavelength = device('nicos.devices.tas.Monochromator',
        description = 'FOCUS monochromator wavelength',
        theta = 'mth',
        twotheta = 'mtt',
        material = 'PG',
        reflection = (0, 0, 2),
        dvalue = 3.355,
        unit = 'A',
        scatteringsense = 1,
        abslimits = (2.0, 6.0),
        crystalside = 1,
    ),
    ei = device('nicos.devices.tas.Monochromator',
        description = 'FOCUS monochromator ei',
        theta = 'mth',
        twotheta = 'mtt',
        material = 'PG',
        reflection = (0, 0, 2),
        dvalue = 3.355,
        unit = 'meV',
        scatteringsense = 1,
        abslimits = (0.2, 30),
        crystalside = 1,
    ),
    mdif_lower = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = 'Lower Detector MDIF',
        commandpv = 'SQ:FOCUS:mdiflower' + '.AOUT',
        replypv = 'SQ:FOCUS:mdiflower' + '.AINP',
    ),
    mdif_middle = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = 'Middle Detector MDIF',
        commandpv = 'SQ:FOCUS:mdifmiddle' + '.AOUT',
        replypv = 'SQ:FOCUS:mdifmiddle' + '.AINP',
    ),
    mdif_upper = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = 'Upper Detector MDIF',
        commandpv = 'SQ:FOCUS:mdifupper' + '.AOUT',
        replypv = 'SQ:FOCUS:mdifupper' + '.AINP',
    ),
    mdif_f2d = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = '2D Detector MDIF',
        commandpv = 'SQ:FOCUS:mdif2d' + '.AOUT',
        replypv = 'SQ:FOCUS:mdif2d' + '.AINP',
    ),
    emmi = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = 'Direct communication with Emmenegger',
        commandpv = 'SQ:FOCUS:EMEG' + '.AOUT',
        replypv = 'SQ:FOCUS:EMEG' + '.AINP',
    ),
    el737direct = device('nicos_sinq.devices.epics.extensions.EpicsCommandReply',
        description = 'Direct communication with EL737 counter box',
        commandpv = 'SQ:FOCUS:cter' + '.AOUT',
        replypv = 'SQ:FOCUS:cter' + '.AINP',
    ),
    col = device('nicos_sinq.devices.s5_switch.S5Switch',
        description = 'Switch for the radial collimator',
        readpv = 'SQ:FOCUS:SPS1:DigitalInput',
        commandpv = 'SQ:FOCUS:SPS1:Push',
        byte = 10,
        mapping = {
            'OFF': False,
            'ON': True
        },
        bit = 0,
        commandstr = 'S0000',
    ),
    fbox = device('nicos_sinq.devices.s5_switch.S5Bit',
        description = 'Status of the flight box',
        byte = 12,
        bit = 2,
        readpv = 'SQ:FOCUS:SPS1:DigitalInput',
    ),
    fermidist = device('nicos.devices.generic.manual.ManualMove',
        description = 'Distance sample - fermi chopper',
        unit = 'mm',
        abslimits = (2500, 5000),
        default = 3000
    ),
    sampledist = device('nicos.devices.generic.manual.ManualMove',
        description = 'Distance sample - detector',
        unit = 'mm',
        abslimits = (0, 2500),
        default = 2000
    ),
    slit_width = device('nicos.devices.generic.manual.ManualMove',
        description = 'Width of the sample slit',
        unit = 'mm',
        abslimits = (0, 100),
        default = 20
    ),
    slit_height = device('nicos.devices.generic.manual.ManualMove',
        description = 'Height of the sample slit',
        unit = 'mm',
        abslimits = (0, 100),
        default = 20
    ),
    bef = device('nicos.devices.generic.manual.ManualSwitch',
        description = 'State of the beryllium filter',
        states = ['In', 'Out'],
    ),
)

startupcode = """
mdif_lower.execute('RMT 1')
mdif_lower.execute('ECHO 0')
mdif_middle.execute('RMT 1')
mdif_middle.execute('ECHO 0')
mdif_upper.execute('RMT 1')
mdif_upper.execute('ECHO 0')
mdif_f2d.execute('RMT 1')
mdif_f2d.execute('ECHO 0')
"""
