description = 'POLI slits'

group = 'lowlevel'

includes = ['mono']

devices = dict(
    # bmv = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (114.5, 188),
    # ),
    # bmh = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (6.5, 80),
    # ),
    # bm = device('nicos.devices.generic.TwoAxisSlit',
    #     description = 'Monochromator slit',
    #     pollinterval = 15,
    #     maxage = 61,
    #     fmtstr = '%.2f %.2f',
    #     horizontal = 'bmh',
    #     vertical = 'bmv',
    # ),

    bpr = device('nicos.devices.generic.VirtualMotor',
        description = 'Aperture sample right',
        visibility = (),
        unit = 'mm',
        fmtstr = '%.2f',
        abslimits = (-99, 99),
        speed = 0.666,
        curvalue = 30,
    ),
    bpl = device('nicos.devices.generic.VirtualMotor',
        description = 'Aperture sample left',
        visibility = (),
        unit = 'mm',
        fmtstr = '%.2f',
        abslimits = (-99, 99),
        speed = 0.666,
        curvalue = 30,
    ),
    bpo = device('nicos.devices.generic.VirtualMotor',
        description = 'Aperture sample upper',
        visibility = (),
        unit = 'mm',
        fmtstr = '%.2f',
        abslimits = (-99, 99),
        speed = 0.666,
        curvalue = 60,
    ),
    bpu = device('nicos.devices.generic.VirtualMotor',
        description = 'Aperture sample lower',
        visibility = (),
        unit = 'mm',
        fmtstr = '%.2f',
        abslimits = (-99, 99),
        speed = 0.666,
        curvalue = 60,
    ),
    bp = device('nicos.devices.generic.Slit',
        description = 'Aperture before sample',
        left = 'bpl',
        right = 'bpr',
        bottom = 'bpu',
        top = 'bpo',
        pollinterval = 5,
        maxage = 10,
        coordinates = 'opposite',
        opmode = '4blades_opposite',
    ),

    # bdr = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (-99, 99),
    # ),
    # bdl = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (-99, 99),
    # ),
    # bdo = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (-99, 99),
    # ),
    # bdu = device('nicos.devices.generic.VirtualMotor',
    #     unit = 'mm',
    #     fmtstr = '%.2f',
    #     abslimits = (-99, 99),
    # ),
    # bd = device('nicos.devices.generic.Slit',
    #     description = 'Aperture before detector',
    #     left = 'bdl',
    #     right = 'bdr',
    #     bottom = 'bdu',
    #     top = 'bdo',
    #     pollinterval = 5,
    #     maxage = 10,
    #     coordinates = 'opposite',
    #     opmode = '4blades_opposite',
    # ),
)
