description = 'Attenuators'
group = 'optional'
display_order = 2
tango_base = 'tango://resedahw2.reseda.frm2.tum.de:10000/reseda/iobox'

devices = dict(
    att0 = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'Attenuator 0: factor 3',
        tangodevice = '%s/plc_spare_out_6' % tango_base,
        mapping = {'in': 1,
                   'out': 0},
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att1 = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'Attenuator 1: factor 15',
        tangodevice = '%s/plc_spare_out_7' % tango_base,
        mapping = {'in': 1,
                   'out': 0},
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att2 = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'Attenuator 2: factor 30',
        tangodevice = '%s/plc_spare_out_8' % tango_base,
        mapping = {'in': 1,
                   'out': 0},
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att = device('nicos_mlz.pgaa.devices.Attenuator',
        description = 'Attenuator device',
        moveables = ['att0', 'att1', 'att2'],
        readables = None,
        precision = None,
        unit = '%',
        fmtstr = '%.1f',
        mapping = {
            100.: (0, 0, 0),  # 'out', 'out', 'out'),
            33.3: (1, 0, 0),  # 'in', 'out', 'out'),
            6.7: (0, 1, 0),   # 'out', 'in', 'out'),
            3.3: (0, 0, 1),   # 'out', 'out', 'in'),
            2.2: (1, 1, 0),   # 'in', 'in', 'out'),
            1.1: (1, 0, 1),   # 'in', 'out', 'in'),
            0.2: (0, 1, 1),   # 'out', 'in', 'in'),
            0.07: (1, 1, 1),  # 'in', 'in', 'in'),
        },
        maxage = 119,
        pollinterval = 60,
    ),
)
