#  -*- coding: utf-8 -*-

description = 'Static flippers'
group = 'lowlevel'

tango_base = 'tango://resedahw2.reseda.frm2:10000/reseda'

devices = dict(
    sf_0a = device('nicos.devices.tango.PowerSupply',
        description = 'Static flipper arm 0 - A',
        tangodevice = '%s/coil/sf_0a' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
    sf_0b = device('nicos.devices.tango.PowerSupply',
        description = 'Static flipper arm 0 - B',
        tangodevice = '%s/coil/sf_0b' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
    sf_1 = device('nicos.devices.tango.PowerSupply',
        description = 'Static flipper arm 1',
        tangodevice = '%s/coil/sf_1' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
    hsf_0a = device('nicos.devices.tango.PowerSupply',
        description = 'Helmholtz mezei flipper arm 0 - A',
        tangodevice = '%s/coil/hsf_0a' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
    hsf_0b = device('nicos.devices.tango.PowerSupply',
        description = 'Helmholtz mezei flipper arm 0 - B',
        tangodevice = '%s/coil/hsf_0b' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
    hsf_1 = device('nicos.devices.tango.PowerSupply',
        description = 'Helmholtz mezei flipper arm 1',
        tangodevice = '%s/coil/hsf_1' % tango_base,
        fmtstr = '%.3f',
        tangotimeout = 5.0,
        pollinterval = 5,
        maxage = 15,
    ),
)
