description = 'Slits'

group = 'lowlevel'

s3_offset = 0

devices = dict(
    s1 = device('nicos_mlz.saphir.devices.slits.LSlit',
        description = 'Slit 1',
        m1 = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 50),
            speed = 2,
            unit = 'mm',
        ),
        m2 = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 50),
            speed = 2,
            unit = 'mm',
        ),
    ),
    s2 = device('nicos_mlz.saphir.devices.slits.LSlit',
        description = 'Slit 2',
        m1 = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 100),
            speed = 1,
            unit = 'mm',
        ),
        m2 = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 100),
            speed = 1,
            unit = 'mm',
        ),
        angle = 30,
    ),
    s3 = device('nicos.devices.generic.Switcher',
        description = 'Slit 3',
        moveable = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 300),
            speed = 5,
            unit = 'mm',
            curvalue = 8 + s3_offset,
        ),
        mapping = {
            2: 39 + s3_offset,
            4: 31 + s3_offset,
            6: 21 + s3_offset,
            10: 8 + s3_offset,
        },
        precision = 0.01,
        unit = 'mm',
    ),
)
