# -*- coding: utf-8 -*-

description = 'DNS motors'

group = 'optional'

#tango_host = 'tango://phys.dns.frm2:10000'
tango_host = 'tango://localhost:10000'

devices = dict(
    det_rot        = device('devices.tango.Motor',
                            description = 'Detector bench rotation',
                            tangodevice = '%s/dns/fzjs7/det_rot' % tango_host,
                           ),
    mon_tilt       = device('devices.tango.Motor',
                            description = 'Monochromator tilt',
                            tangodevice = '%s/dns/fzjs7/mon_tilt' % tango_host,
                           ),
    sel_lift       = device('devices.tango.Motor',
                            description = 'Selector lift',
                            tangodevice = '%s/dns/fzjs7/sel_lift' % tango_host,
                           ),

    ap_sam_x_left  = device('devices.tango.Motor',
                            description = 'Aperture sample x left',
                            tangodevice = '%s/dns/fzjs7/ap_sam_x_left' % tango_host,
                            lowlevel = False,
                           ),
    ap_sam_x_right = device('devices.tango.Motor',
                            description = 'Aperture sample x right',
                            tangodevice = '%s/dns/fzjs7/ap_sam_x_right' % tango_host,
                            lowlevel = False,
                           ),
    ap_sam_y_upper = device('devices.tango.Motor',
                            description = 'Aperture sample y upper',
                            tangodevice = '%s/dns/fzjs7/ap_sam_y_upper' % tango_host,
                            lowlevel = False,
                           ),
    ap_sam_y_lower = device('devices.tango.Motor',
                            description = 'Aperture sample y lower',
                            tangodevice = '%s/dns/fzjs7/ap_sam_y_lower' % tango_host,
                            lowlevel = False,
                           ),
    sample_slit       = device('dns.slit.PosOpeningSlit',
                               description = 'Aperture sample slit',
                               left = 'ap_sam_x_left',
                               right = 'ap_sam_x_right',
                               bottom = 'ap_sam_y_lower',
                               top = 'ap_sam_y_upper',
                               pollinterval = 5,
                               maxage = 10,
                              ),

    sample_rot     = device('devices.tango.Motor',
                            description = 'Sample rotation',
                            tangodevice = '%s/dns/fzjs7/sample_rot' % tango_host,
                           ),
    cradle_up      = device('devices.tango.Motor',
                            description = 'Cradle up (phi)',
                            tangodevice = '%s/dns/fzjs7/cradle_up' % tango_host,
                           ),
    cradle_lo      = device('devices.tango.Motor',
                            description = 'Cradle low (chi)',
                            tangodevice = '%s/dns/fzjs7/cradle_lo' % tango_host,
                           ),
    mon_rot        = device('devices.tango.Motor',
                            description = 'Monochromator rotation',
                            tangodevice = '%s/dns/fzjs7/mon_rot' % tango_host,
                           ),
    pol_trans      = device('devices.tango.Motor',
                            description = 'Polarizer translation',
                            tangodevice = '%s/dns/fzjs7/pol_trans' % tango_host,
                           ),
    pol_rot        = device('devices.tango.Motor',
                            description = 'Polarizer rotation',
                            tangodevice = '%s/dns/fzjs7/pol_rot' % tango_host,
                           ),

    m3l_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m3l_rot' % tango_host,
                           ),
    m2l_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m2l_rot' % tango_host,
                           ),
    m1l_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m1l_rot' % tango_host,
                           ),
    m0_rot         = device('devices.tango.Motor',
                            description = 'MC-crystal crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m0_rot' % tango_host,
                           ),
    m1r_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m1r_rot' % tango_host,
                           ),
    m2r_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m2r_rot' % tango_host,
                           ),
    m3r_rot        = device('devices.tango.Motor',
                            description = 'MC-crystal crystal rotation',
                            tangodevice = '%s/dns/fzjs7/m3r_rot' % tango_host,
                           ),

    beam_rot       = device('devices.tango.Motor',
                            description = 'Beam rotation',
                            tangodevice = '%s/dns/fzjs7/beam_rot' % tango_host,
                           ),
    mon_x_left     = device('devices.tango.Motor',
                            description = 'Monochromator slit left',
                            tangodevice = '%s/dns/fzjs7/mon_x_left' % tango_host,
                            lowlevel = True,
                           ),
    mon_x_right    = device('devices.tango.Motor',
                            description = 'Monochromator slit right',
                            tangodevice = '%s/dns/fzjs7/mon_x_right' % tango_host,
                            lowlevel = True,
                           ),
    mon_y_upper    = device('devices.tango.Motor',
                            description = 'Monochromator slit upper',
                            tangodevice = '%s/dns/fzjs7/mon_y_upper' % tango_host,
                            lowlevel = True,
                           ),
    mon_y_lower    = device('devices.tango.Motor',
                            description = 'Monochromator slit lower',
                            tangodevice = '%s/dns/fzjs7/mon_y_lower' % tango_host,
                            lowlevel = True,
                           ),
    mon_slit       = device('devices.generic.Slit',
                            description = 'Monochromator slit',
                            left = 'mon_x_left',
                            right = 'mon_x_right',
                            bottom = 'mon_y_lower',
                            top = 'mon_y_upper',
                            pollinterval = 5,
                            maxage = 10,
                           ),
)

startupcode = '''
'''
