# -*- coding: utf-8 -*-

description = 'DNS monochromator'
group = 'lowlevel'

tango_base = 'tango://phys.dns.frm2:10000/dns/'

devices = dict(
    mon_tilt     = device('devices.tango.Motor',
                          description = 'Monochromator tilt',
                          tangodevice = tango_base + 'fzjs7/mon_tilt',
                          precision = 1.0,
                         ),
    mon_rot      = device('devices.tango.Motor',
                          description = 'Monochromator rotation',
                          tangodevice = tango_base + 'fzjs7/mon_rot',
                          precision = 0.05,
                         ),

    m3l_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m3l_rot',
                          precision = 1.0,
                         ),
    m2l_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m2l_rot',
                          precision = 1.0,
                         ),
    m1l_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m1l_rot',
                          precision = 1.0,
                         ),
    m0_rot       = device('devices.tango.Motor',
                          description = 'MC-crystal crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m0_rot',
                          precision = 1.0,
                         ),
    m1r_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m1r_rot',
                          precision = 1.0,
                         ),
    m2r_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m2r_rot',
                          precision = 1.0,
                         ),
    m3r_rot      = device('devices.tango.Motor',
                          description = 'MC-crystal crystal rotation',
                          tangodevice = tango_base + 'fzjs7/m3r_rot',
                          precision = 1.0,
                         ),

    beam_rot     = device('devices.tango.Motor',
                          description = 'Beam rotation',
                          tangodevice = tango_base + 'fzjs7/beam_rot',
                          precision = 1.0,
                         ),

    mon_lambda   = device('devices.generic.ManualMove',
                          description = 'Monochromator wavelength',
                          abslimits = (3, 5),
                          unit = 'A',
                         ),

    mon_x_left   = device('devices.tango.Motor',
                          description = 'Monochromator slit left',
                          tangodevice = tango_base + 'fzjs7/mon_x_left',
                          lowlevel = True,
                          precision = 1.0,
                         ),
    mon_x_right  = device('devices.tango.Motor',
                          description = 'Monochromator slit right',
                          tangodevice = tango_base + 'fzjs7/mon_x_right',
                          lowlevel = True,
                          precision = 1.0,
                         ),
    mon_y_upper  = device('devices.tango.Motor',
                          description = 'Monochromator slit upper',
                          tangodevice = tango_base + 'fzjs7/mon_y_upper',
                          lowlevel = True,
                          precision = 1.0,
                         ),
    mon_y_lower  = device('devices.tango.Motor',
                          description = 'Monochromator slit lower',
                          tangodevice = tango_base + 'fzjs7/mon_y_lower',
                          lowlevel = True,
                          precision = 1.0,
                         ),
    mon_slit     = device('devices.generic.Slit',
                          description = 'Monochromator slit',
                          left = 'mon_x_left',
                          right = 'mon_x_right',
                          bottom = 'mon_y_lower',
                          top = 'mon_y_upper',
                          pollinterval = 5,
                          maxage = 10,
                         ),

    mccrystal_t1 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 1',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip1',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t2 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 2',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip2',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t3 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 3',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip3',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t4 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 4',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip4',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t5 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 5',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip5',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t6 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 6',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip6',
                          mapping = dict(start=1, stop=0),
                         ),
    mccrystal_t7 = device('devices.tango.NamedDigitalOutput',
                          description = 'Monchromator crystal tilt 7',
                          tangodevice = tango_base + 'fzjdp_digital/MCKristallKip7',
                          mapping = dict(start=1, stop=0),
                         ),
)
