description = 'sample table setup'

group = 'lowlevel'

devices = dict(
    x = device('nicos.devices.generic.Axis',
        description = 'x translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 180),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    y = device('nicos.devices.generic.Axis',
        description = 'y translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 180),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    z = device('nicos.devices.generic.Axis',
        description = 'z translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 50),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    omega = device('nicos.devices.generic.Axis',
        description = 'omega rotation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 360),
            unit = 'deg',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    phi = device('nicos.devices.generic.Axis',
        description = 'phi rotation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 360),
            unit = 'deg',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
)
