[nicos]
user = "data"
group = "unx-lns"
umask = "022"
services = ["cache", "poller", "daemon", "monitor-html_detector",
            "monitor-html_instr0", "monitor-html_instr1", "monitor-html_instr2",
            "monitor-html_sample"]
logging_path = "/home/data/nicosdata/logs"
instrument = "sans"
setup_package = "nicos_sinq"
setup_subdirs = ["sans", "frappy_sinq", "sinq_shared"]

[environment]
SANSHM = "http://sanshm:80/admin"
NICOSDUMP = "/home/data/nicosdata"
PYTHONPATH = "/home/sans/frappy:/home/sans"
