[nicos]
user = "data"
group = "unx-lns"
umask = "022"

instrument = "sans"
setup_package = "nicos_sinq"
setup_subdirs = ["sans", "sinq_shared", "/sq_sw/linse/frappy_sinq", "/home/linse"]
services = ["cache", "poller", "daemon", "monitor-html_detector",
            "monitor-html_instr0", "monitor-html_instr1", "monitor-html_instr2",
            "monitor-html_sample"]

logging_path = "/home/data/nicosdata/logs"

[environment]
SANSHM = "http://sanshm:80/admin"
NICOSDUMP = "/home/data/nicosdata"
PYTHONPATH = "/sq_sw/linse/frappy:/sq_sw/linse"
