description = 'Big ErWIN detector devices'

group = 'optional'

devices = dict(
    b_cathode1 = device('nicos.devices.generic.VirtualMotor',
        lowlevel = True,
        abslimits = [0, 2225],
        unit = 'V',
        speed = 50,
        fmtstr = '%.1f',
    ),
    b_cathode2 = device('nicos.devices.generic.VirtualMotor',
        lowlevel = True,
        abslimits = [0, 2225],
        unit = 'V',
        speed = 50,
        fmtstr = '%.1f',
    ),
    b_window = device('nicos.devices.generic.VirtualMotor',
        lowlevel = True,
        abslimits = [-2225, 0],
        unit = 'V',
        speed = 50,
        fmtstr = '%.1f',
    ),
    b_hv = device('nicos_mlz.erwin.devices.charmhv.HVSwitch',
        description = 'HV supply small detector',
        anodes = ['b_anode%d' % i for i in range(1, 10)],
        banodes = ['b_banode%d' % i for i in range(1, 9)],
        cathodes = ['b_cathode1', 'b_cathode2'],
        window = 'b_window',
        mapping = {
            'on': {
                'b_anode1': 2090,
                'b_anode2': 2092,
                'b_anode3': 2094,
                'b_anode4': 2097,
                'b_anode5': 2100,
                'b_anode6': 2103,
                'b_anode7': 2106,
                'b_anode8': 2108,
                'b_anode9': 2110,
                'b_banode1': 2092,
                'b_banode2': 2094,
                'b_banode3': 2096,
                'b_banode4': 2099,
                'b_banode5': 2099,
                'b_banode6': 2098,
                'b_banode7': 2097,
                'b_banode8': 2096,
                'b_cathode1': 75,
                'b_cathode2': 80,
                'b_window': -1000,
                'ramp': 50,
            },
            'off': {
                'b_anode1': 0,
                'b_anode2': 0,
                'b_anode3': 0,
                'b_anode4': 0,
                'b_anode5': 0,
                'b_anode6': 0,
                'b_anode7': 0,
                'b_anode8': 0,
                'b_anode9': 0,
                'b_banode1': 0,
                'b_banode2': 0,
                'b_banode3': 0,
                'b_banode4': 0,
                'b_banode5': 0,
                'b_banode6': 0,
                'b_banode7': 0,
                'b_banode8': 0,
                'b_cathode1': 0,
                'b_cathode2': 0,
                'b_window': 0,
                'ramp': 100,
            },
            'safe': {
                'b_anode1': 200,
                'b_anode2': 200,
                'b_anode3': 200,
                'b_anode4': 200,
                'b_anode5': 200,
                'b_anode6': 200,
                'b_anode7': 200,
                'b_anode8': 200,
                'b_anode9': 200,
                'b_banode1': 200,
                'b_banode2': 200,
                'b_banode3': 200,
                'b_banode4': 200,
                'b_banode5': 200,
                'b_banode6': 200,
                'b_banode7': 200,
                'b_banode8': 200,
                'b_cathode1': 200,
                'b_cathode2': 200,
                'b_window': 200,
                'ramp': 100,
            },
        },
    ),
)

for i in range(1, 10):
    devices['b_anode%d' % i] = device('nicos.devices.generic.VirtualMotor',
        lowlevel = True,
        abslimits = [0, 2225],
        unit = 'V',
        speed = 50,
        fmtstr = '%.1f',
    )

for i in range(1, 9):
    devices['b_banode%d' % i] = device('nicos.devices.generic.VirtualMotor',
        lowlevel = True,
        abslimits = [0, 2225],
        unit = 'V',
        speed = 50,
        fmtstr = '%.1f',
    )
