description = 'real time monitor for some devices of Amor'
group = 'special'

_beamstatus = Column(
    Block(
        'beam status',
        [   BlockRow(
                Field(name = 'p current',
                      dev = 'proton_current',
                      min = 100,
                      unit = ' ',
                      width = 12,
                      format = '%4.0f uA',
                      fontscale = 2.0,
                      ),
                Field(name = 'pol',
                      dev = 'polarization',
                      istext = True,
                      width = 5,
                      fontscale = 2.0,
                      ),
                Field(name = 'detector rate',
                      dev = 'detector_rate',
                      unit = ' ',
                      width = 12,
                      format = '%9.1f /s',
                      fontscale = 2.0,
                      ),
                ),
            BlockRow(
                Field(widget = 'nicos.guisupport.valuewidgets.ValueGauge',
                      name = 'uA',
                      dev = 'proton_current',
                      width = 26,
                      height = 26,
                      start_value=0.,
                      end_value=1600,
                      start_angle=-140,
                      end_angle=140,
                      #boundary_color='#660022',
                      #background_color='#eeffee',
                      inley_color='#ff0000',
                      ),
                Field(name = ' ',
                      dev = 'shutter',
                      istext = True,
                      width = 7,
                      fontscale = 1.5,
                      ),
                Field(widget = 'nicos.guisupport.valuewidgets.ValueGauge',
                      name = '/s',
                      dev = 'detector_rate',
                      width = 26,
                      height = 26,
                      start_value=0.01,
                      end_value=1e6,
                      ticks=5,
                      start_angle=-140,
                      end_angle=140,
                      #boundary_color='#220066',
                      #background_color='#eeffee',
                      inley_color='#0000ff',
                      log_values=1,
                      ),
                ),
            ],
        setups='shutter',
        ),
    )

_proposalinfo = Column(
    Block(
        'proposal',
        [   BlockRow(
                Field(name = 'title',
                      key = 'exp.title',
                      istext = True,
                      width = 64,
                      fontscale = 2.0,
                      ),
                ),
            BlockRow(
                Field(name = 'proposal',
                      key = 'exp.proposal',
                      width = 12,
                      fontscale = 2.0,
                      ),
                ),
            BlockRow(
                Field(name = 'sample name',
                      key = 'Sample.samplename',
                      width = 82,
                      istext = True,
                      fontscale = 1.5,
                      ),
                ),
            BlockRow(
                Field(name = 'orso model',
                      key = 'Sample.orsomodel["stack"]',
                      istext = True,
                      width = 82,
                      fontscale = 1.5,
                      ),
                ),
            ],
        ),
    )

_measurementinfo = Column(
    Block(
        'measurement',
        [   BlockRow(
                Field(name='file',
                      key='exp.lastpoint',
                      width=12,
                      fontscale = 2.0,
                      ),
                ),
            BlockRow(
                Field(name = 'detector',
                      key = 'det.status[1]',
                      istext = True,
                      fontscale = 1.5,
                      width = 12,
                      ),
                Field(name='time',
                      dev = 'elapsedtime',
                      unit = ' ',
                      format = '%7.f s',
                      fontscale = 1.5,
                      width = 12,
                      ),
                Field(name = 'proton monitor',
                      dev = 'proton_monitor',
                      unit = ' ',
                      format = '%7.f uC',
                      fontscale = 1.5,
                      width = 16,
                      ),
                ),
            BlockRow(
                Field(widget = 'nicos.guisupport.valuewidgets.ValueProgressBar',
                      name = '',
                      dev = 'progress',
                      width = 60,
                      unit = '',
                      fontscale = 1.5,
                      #format = '%3.0f',
                      ),
                ),
            ],
        setups='detector',
        ),
    )

_geometry = Column(
    Block('geometrical parameters',
        [   BlockRow(
                Field(name = 'q_z min',
                      dev = 'qz_l',
                      unit = ' ',
                      width = 12,
                      format = '%6.3f /A',
                      fontscale = 2.0,
                      ),
                Field(name = 'q_z max',
                      dev = 'qz_h',
                      unit = ' ',
                      width = 12,
                      format = '%6.3f /A',
                      fontscale = 2.0,
                      ),
                ),
            BlockRow(
                Field(name = 'divergence',
                      dev = 'div',
                      unit = ' ',
                      width = 12,
                      format = '%6.3f deg',
                      fontscale = 1.5,
                      ),
            #    ),
            #BlockRow(
                Field(name = 'kappa',
                      dev = 'kap',
                      unit = ' ',
                      width = 12,
                      format = '%6.3f deg',
                      fontscale = 1.5,
                      ),
                Field(name = 'kappa offset',
                      dev = 'kad',
                      unit = ' ',
                      width = 12,
                      format = '%6.3f deg',
                      fontscale = 1.5,
                      ),
            #    ),
            #BlockRow(
                Field(name = 'alpha_i',
                      dev = 'alpha_i',
                      unit = ' ',
                      format = '%6.3f deg',
                      width = 12,
                      fontscale = 1.5,
                      ),
                Field(name = 'alpha_f',
                      dev = 'alpha_f',
                      unit = ' ',
                      format = '%6.3f deg',
                      width = 12,
                      fontscale = 1.5,
                      ),
                ),
            BlockRow(
                Field(name = 'mu',
                      dev = 'mu',
                      unit = ' ',
                      format = '%6.3f deg',
                      width = 12,
                      fontscale = 1.0,
                      ),
                Field(name = 'nu',
                      dev = 'nu',
                      unit = ' ',
                      format = '%6.3f deg',
                      width = 12,
                      fontscale = 1.0,
                      ),
            #    ),
            #BlockRow(
                Field(name = 'dvv',
                      dev = 'dvv',
                      unit = ' ',
                      width = 12,
                      fontscale = 1.0,
                      ),
                Field(name = 'dvh',
                      dev = 'dvh',
                      unit = ' ',
                      width = 12,
                      fontscale = 1.0,
                      ),
                ),
            ],
        ),
    )

devices = dict(
    Monitor = device('nicos.services.monitor.qt.Monitor',
                     title = 'Amor status monitor',
                     cache = 'amor',
                     layout = [
                         [_beamstatus, _proposalinfo],
                         [_geometry, _measurementinfo],
                         ],
                     ),
    #HTMLMonitor = device('nicos.services.monitor.html.Monitor',
    #                 title = 'Amor status monitor',
    #                 filename = 'amor_status.html',
    #                 cache = 'amor',
    #                 layout = [
    #                    [_expcolumn],
    #                    [_beamcolumn, _devcolumn],
    #                    ],
    #                 ),
    )
