description = 'real time monitor for some devices of Amor'
group = 'special'

_expcolumn = Column(
    Block('',
        [
        BlockRow(Field(name = '',
                       key = 'exp/title',
                       istext = True,
                       width = 43,
                       maxlen = 43,
                       ),
                ),
        BlockRow(Field(name = 'proposal',
                       key = 'exp/proposal',
                       width = 10,
                       ),
                 Field(name = 'sample name',
                       key = 'Sample/samplename',
                       width = 31,
                       istext = True,
                       ),
                ),
        BlockRow(Field(name = 'orso model',
                       key = 'Sample/orsomodel',
                       istext = True,
                       width = 43,
                       maxlen = 50,
                       ),
                ),
        ],
        # This block will always be displayed
    ),
)

_beamcolumn = Column(
    Block('beam status',
        [BlockRow(
                  Field(name = 'Ip / uA',
                        dev = 'proton_current',
                        min = 100,
                        width = 8,
                        ),
                  Field(name = 'shutter',
                        dev = 'shutter',
                        istext = True,
                        width = 8,
                        maxlen = 6,
                        ),
                  ),
         BlockRow(
                  Field(name = 'det rate',
                        dev = 'detector_rate',
                        min = 10,
                        width = 10,
                        ),
                  Field(name = 'pol',
                        dev = 'polarization',
                        istext = True,
                        width = 6,
                        ),
                  ),
         ],
        setups='shutter',
        ),

    Block('measurement',
        [BlockRow(Field(name = 'detector',
                        key = 'det_timer.status[1]',
                        istext = True,
                        width = 16,
                        ),
                  ),
         BlockRow(Field(name='file',
                        key='exp/lastpoint',
                        width=5,
                        ),
                  Field(name = 'time / s',
                      dev = 'det_timer',
                       unit = ' ',
                       format = '%7.f',
                       width = 9,
                       ),
                 ),
         BlockRow(Field(name = 'detector signal',
                       dev = 'hist_yz',
                       width = 16,
                       ),
                 ),
         BlockRow(Field(name = 'proton monitor',
                       dev = 'proton_monitor',
                       unit = ' ',
                       format = '%7.f',
                       width = 16,
                       ),
                 ),

         ],
        setups='detector',
        ),
    )

_devcolumn = Column(
    Block('q_z * angstrom',
        [BlockRow(Field(name = 'from',
                        dev = 'ql',
                        unit = ' ',
                        width = 10,
                        ),
                  Field(name = 'to',
                        dev = 'qh',
                        unit = ' ',
                        width = 10,
                        ),
                  ),
         ],
        setups='qz',
        ),
    Block('angles / deg',
        [BlockRow(Field(name = 'kappa',
                        dev = 'kap',
                        unit = ' ',
                        width = 10,
                        ),
                  Field(name = 'divergence',
                        dev = 'div',
                        unit = ' ',
                        width = 10,
                        ),
                  ),
         BlockRow(Field(name = 'mu',
                        dev = 'mu',
                        unit = ' ',
                        width = 10,
                        ),
                  Field(name = 'alpha_i',
                        dev = 'alpha_i',
                        unit = ' ',
                        width = 10,
                        ),
                  ),
         BlockRow(Field(name = 'nu',
                        dev = 'nu',
                        unit = ' ',
                        width = 10,
                        ),
                  Field(name = 'alpha_f',
                        dev = 'alpha_f',
                        unit = ' ',
                        width = 10,
                        ),
                  ),
         ],
        setups='base',
        ),
    )

devices = dict(
    Monitor = device('nicos.services.monitor.qt.Monitor',
                     title = '',
                     cache = 'amor',
                     layout = [
                        [_expcolumn],
                        [_beamcolumn, _devcolumn],
                        ],
                     ),
    )
