# -*- coding: utf-8 -*-

description = 'GALAXI motors'

group = 'optional'

tango_base = 'tango://phys.galaxi.kfa-juelich.de:10000/galaxi/'
s7_motor = tango_base + 's7_motor/'

devices = dict(
    detz = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'Detector Z axis',
        tangodevice = s7_motor + 'detz',
        precision = 0.01,
    ),
    detx = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'Detector X axis',
        tangodevice = s7_motor + 'detx',
        offset = 0,
        precision = 0.01,
        fixed = 'Do not move until hardware is in save state',
        fixedby = ('admin', 20),
        lowlevel = True,
    ),
    bssy = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'BSSY axis',
        tangodevice = s7_motor + 'bssy',
        offset = 0,
        precision = 0.01,
    ),
    bspz = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'BSPZ axis',
        tangodevice = s7_motor + 'bspz',
        offset = 0,
        precision = 0.01,
    ),
    bspy = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'BSPY axis',
        tangodevice = s7_motor + 'bspy',
        offset = 0,
        precision = 0.01,
    ),
    pchi = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'PCHI axis',
        tangodevice = s7_motor + 'pchi',
        offset = 0,
        precision = 0.001,
    ),
    pom = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'POM axis',
        tangodevice = s7_motor + 'pom',
        offset = 0,
        precision = 0.001,
    ),
    pz = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'PZ axis',
        tangodevice = s7_motor + 'pz',
        offset = 0,
        precision = 0.01,
    ),
    py = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'PY axis',
        tangodevice = s7_motor + 'py',
        offset = 0,
        precision = 0.01,
    ),
    prefz = device('nicos_mlz.jcns.devices.motor.Motor',
        description = 'PRefZ axis',
        tangodevice = s7_motor + 'prefz',
        offset = 0,
        precision = 0.01,
    ),
)
