# -*- coding: utf-8 -*-

description = 'Mirror area setup'
group = 'lowlevel'
display_order = 30

includes = ['sample']
excludes = ['virtual_mirror']

tango_base = 'tango://phys.kws3.frm2:10000/kws3/'
s7_motor = tango_base + 's7_motor/'

devices = dict(
    mir_x = device('nicos.devices.tango.Motor',
        description = 'mirror x-table',
        tangodevice = s7_motor + 'mir_x',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_y = device('nicos.devices.tango.Motor',
        description = 'mirror y-hub',
        tangodevice = s7_motor + 'mir_y',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_tilt = device('nicos.devices.tango.Motor',
        description = 'mirror tilting',
        tangodevice = s7_motor + 'mir_tilt',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_sam_x = device('nicos.devices.tango.Motor',
        description = 'virtual pair mir_x and sam_hub_x',
        tangodevice = s7_motor + 'mir_sam_x',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_sam_y = device('nicos.devices.tango.Motor',
        description = 'virtual pair mir_y and sam_hub_y',
        tangodevice = s7_motor + 'mir_sam_y',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_sam_tilt = device('nicos.devices.tango.Motor',
        description = 'virtual pair mir_tilt sam_hub_y',
        tangodevice = s7_motor + 'mir_sam_tilt',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_sam_det = device('nicos.devices.tango.Motor',
        description = 'virtual mir_y + mir_tilt + sam_hub_y + det_y',
        tangodevice = s7_motor + 'mir_sam_det',
        unit = 'mm',
        precision = 0.01,
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    mir_ap1 = device('nicos.devices.generic.Slit',
        description = 'jj-xray aperture in front of mirror',
        coordinates = 'opposite',
        opmode = 'offcentered',
        fmtstr = '(%.2f, %.2f) %.2f x %.2f',
        left = 'mir_ap1_x_left',
        right = 'mir_ap1_x_right',
        bottom = 'mir_ap1_y_lower',
        top = 'mir_ap1_y_upper',
        parallel_ref = True,
        lowlevel = True,
    ),
    mir_ap1_x_left = device('nicos.devices.tango.Motor',
        description = 'aperture in front of mirror left',
        tangodevice = s7_motor + 'mir_ap1_x_left',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap1_x_right = device('nicos.devices.tango.Motor',
        description = 'aperture in front of mirror right',
        tangodevice = s7_motor + 'mir_ap1_x_right',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap1_y_upper = device('nicos.devices.tango.Motor',
        description = 'aperture in front of mirror upper',
        tangodevice = s7_motor + 'mir_ap1_y_upper',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap1_y_lower = device('nicos.devices.tango.Motor',
        description = 'aperture in front of mirror lower',
        tangodevice = s7_motor + 'mir_ap1_y_lower',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap2 = device('nicos.devices.generic.Slit',
        description = 'jj-xray aperture behind mirror',
        coordinates = 'opposite',
        opmode = 'offcentered',
        fmtstr = '(%.2f, %.2f) %.2f x %.2f',
        left = 'mir_ap2_x_left',
        right = 'mir_ap2_x_right',
        bottom = 'mir_ap2_y_lower',
        top = 'mir_ap2_y_upper',
        parallel_ref = True,
        lowlevel = True,
    ),
    mir_ap2_x_left = device('nicos.devices.tango.Motor',
        description = 'aperture behind mirror left',
        tangodevice = s7_motor + 'mir_ap2_x_left',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap2_x_right = device('nicos.devices.tango.Motor',
        description = 'aperture behind mirror right',
        tangodevice = s7_motor + 'mir_ap2_x_right',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap2_y_upper = device('nicos.devices.tango.Motor',
        description = 'aperture behind mirror upper',
        tangodevice = s7_motor + 'mir_ap2_y_upper',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
    mir_ap2_y_lower = device('nicos.devices.tango.Motor',
        description = 'aperture behind mirror lower',
        tangodevice = s7_motor + 'mir_ap2_y_lower',
        unit = 'mm',
        precision = 0.01,
        lowlevel = True,
    ),
)

alias_config = {
    'sam_ap': {'mir_ap2': 80},
}
