description = 'Monochroamtor devices SINQ DMC.'

pvprefix = 'SQ:DMC:mota:'

devices = dict(
    mth=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Theta Motor',
               motorpv=pvprefix + 'MTH',
               errormsgpv=pvprefix + 'MTH-MsgTxt',
               precision=0.01,
               ),

    m2t=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Two Theta Motor',
               motorpv=pvprefix + 'M2T',
               errormsgpv=pvprefix + 'M2T-MsgTxt',
               precision=0.01,
               ),

    mtcurve=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Curvature Motor',
               motorpv=pvprefix + 'MTCURVE',
               errormsgpv=pvprefix + 'MTCURVE-MsgTxt',
               ),

    mtx=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator X Translation',
               motorpv=pvprefix + 'MTX',
               errormsgpv=pvprefix + 'MTX-MsgTxt',
               ),
    mty=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Y Translation',
               motorpv=pvprefix + 'MTY',
               errormsgpv=pvprefix + 'MTY-MsgTxt',
               ),

    mtphi=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Phi Rotation',
               motorpv=pvprefix + 'MTPHI',
               errormsgpv=pvprefix + 'MTPHI-MsgTxt',
               ),
    mtchi=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Chi Rotation',
               motorpv=pvprefix + 'MTCHI',
               errormsgpv=pvprefix + 'MTCHI-MsgTxt',
               ),
    wavelength = device('nicos_sinq.devices.mono.SinqMonochromator',
        description = 'PG analyser (default)',
        unit = 'A',
        theta = 'mth',
        twotheta = 'm2t',
        focush = None,
        focusv = 'mtcurve',
        order=1,
        abslimits = (2, 5),
        vfocuspars = [-0.025942, 5.351660],
        dvalue = 3.3537,
        scatteringsense = 1,
        crystalside=1,
    ),

)
