description = 'collimation tube'

includes = ['system']

excludes = ['collimation_config']

group = 'lowlevel'

devices = dict(
    col = device('nicos.devices.generic.LockedDevice',
        description = 'sans1 primary collimation',
        lock = 'instrument_shutter',
        device = 'col_sw',
        unlockvalue = 'close',
        lowlevel = False,
        pollinterval = 15,
        maxage = 60,
    ),
    col_sw = device('nicos.devices.generic.MultiSwitcher',
        description = 'collimator switching device',
        precision = None,
        blockingmove = False,
        unit = 'm',
        fmtstr = '%.1f',
        fallback = 'undefined',
        moveables = ['col_20', 'col_18', 'col_16', 'col_14', 'col_12', 'col_10',
        'col_8', 'col_6', 'col_4', 'col_3', 'col_2'],
        mapping = {
            1.5: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng'],
            2: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'col'],
            3: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'col', 'col'],
            4: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'col', 'col', 'col'],
            6: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'col', 'col', 'col', 'col'],
            8: ['ng',  'ng',  'ng',  'ng',  'ng',  'ng',  'col', 'col', 'col', 'col', 'col'],
            10: ['ng',  'ng',  'ng',  'ng',  'ng',  'col', 'col', 'col', 'col', 'col', 'col'],
            12: ['ng',  'ng',  'ng',  'ng',  'col', 'col', 'col', 'col', 'col', 'col', 'col'],
            14: ['ng',  'ng',  'ng',  'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col'],
            16: ['ng',  'ng',  'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col'],
            18: ['ng',  'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col'],
            20: ['col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col', 'col'],
        },
        lowlevel = True,
    ),
    ng_pol = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Neutronguide polariser',
        mapping = dict(ng=1.060, pol1=117, pol2=234, col=352.7),
        moveable = 'ng_pol_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        precision = 0.05,
    ),
    ng_pol_a = device('nicos.devices.generic.Axis',
        description = 'Neutronguide polariser axis',
        motor = 'ng_pol_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    ng_pol_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Neutronguide polariser motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_20 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 20',
        mapping = dict(ng=1.003, col=117, free1=234, las=351),
        moveable = 'col_20_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = False,
        precision = 0.05,
    ),
    col_20_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 20',
        motor = 'col_20_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_20_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 20 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        precision = 0.0025,
        lowlevel = True,
    ),
    col_18 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 18',
        mapping = dict(ng=0.841, col=117, free1=234, free2=351),
        moveable = 'col_18_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_18_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 18',
        motor = 'col_18_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_18_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 18',
        unit = 'mm',
        abslimits = (-400, 600),
        precision = 0.0025,
        lowlevel = True,
    ),
    col_16 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 16',
        mapping = dict(ng=1.229, col=117, free1=234, free2=351),
        moveable = 'col_16_a',
        blockingmove = False,
        pollinterval = 1,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_16_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 16',
        motor = 'col_16_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_16_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 16 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    bg1 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSlit',
        description = 'Background slit1',
        mapping = {'49mm': 1.0, 'open': 91.3, '19mm': 181.3, '41mm': 271.3 },
        moveable = 'bg1_m',
        table = 'col_16',
        activeposition = 'col',
        pollinterval = 15,
        maxage = 60,
    ),
    bg1_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Background slit1 motor',
        unit = 'deg',
        abslimits = (-40, 300),
        precision = 0.05,
    ),
    col_14 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 14',
        mapping = dict(ng=1.486, col=117, free1=234, free2=351),
        moveable = 'col_14_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_14_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 14',
        motor = 'col_14_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_14_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 14 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        precision = 0.0025,
        lowlevel = True,
    ),
    col_12 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 12',
        mapping = dict(ng=1.310, col=117, free1=234, free2=351),
        moveable = 'col_12_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_12_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 12',
        motor = 'col_12_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_12_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 12 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_10 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 10',
        mapping = dict(ng=1.348, col=117, free1=234, free2=351),
        moveable = 'col_10_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_10_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 10',
        motor = 'col_10_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_10_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 10 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_8 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 8',
        mapping = dict(ng=1.679, col=117, free1=234, free2=351),
        moveable = 'col_8_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_8_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 8',
        motor = 'col_8_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_8_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 8 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_6 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 6',
        mapping = dict(ng=0.909, col=117, free1=234, free2=351),
        moveable = 'col_6_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_6_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 6',
        motor = 'col_6_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_6_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 6 motor',
        abslimits = (-400, 600),
        unit = 'mm',
        lowlevel = True,
    ),
    bg2 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSlit',
        description = 'Background slit2',
        mapping = {'27mm': 270, '19mm': 179.5, '11mm': 90.5, 'open': 1.2 },
        moveable = 'bg2_m',
        table = 'col_6',
        activeposition = 'col',
        pollinterval = 15,
        maxage = 60,
    ),
    bg2_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Background slit2 motor',
        unit = 'deg',
        abslimits = (-40, 300),
        lowlevel = True,
    ),
    col_4 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 4',
        mapping = dict(ng=0.985, col=117, free1=234, free2=351),
        moveable = 'col_4_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_4_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 4',
        motor = 'col_4_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_4_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 4 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_3 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 3',
        mapping = dict(ng=1.010, col=117, free1=234, free2=351),
        moveable = 'col_3_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_3_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 3',
        motor = 'col_3_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_3_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 3 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    col_2 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'Collimotor 2',
        mapping = dict(ng=1, col=117, free1=234, free2=351),
        moveable = 'col_2_a',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
        lowlevel = True,
        precision = 0.05,
    ),
    col_2_a = device('nicos.devices.generic.Axis',
        description = 'Collimotor 2',
        motor = 'col_2_m',
        dragerror = 17,
        precision = 0.05,
        lowlevel = True,
        jitter = 1,
    ),
    col_2_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Collimotor 2 motor',
        unit = 'mm',
        abslimits = (-400, 600),
        lowlevel = True,
    ),
    sa1 = device('nicos_mlz.sans1.devices.collimotor.Sans1ColliSwitcher',
        description = 'attenuation slits',
        mapping = {'29mm': 0, '19mm': 70, '9mm': 140},
        moveable = 'sa1_m',
        blockingmove = False,
        pollinterval = 15,
        maxage = 60,
    ),
    sa1_m = device('nicos.devices.generic.VirtualMotor',
        description = 'attenuation slits motor',
        unit = 'mm',
        abslimits = (-40, 300),
        lowlevel = True,
    ),
)
