description = 'bottom sample table devices'

group = 'lowlevel'

devices = dict(
    st_omg = device('nicos.devices.generic.Axis',
        description = 'table omega axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-180, 180),
            unit = 'deg',
        ),
    ),
    st_chi = device('nicos.devices.generic.Axis',
        description = 'table chi axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-5, 5),
            unit = 'deg',
        ),
    ),
    st_phi = device('nicos.devices.generic.Axis',
        description = 'table phi axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-5, 5),
            unit = 'deg',
        ),
    ),
    st_y = device('nicos.devices.generic.Axis',
        description = 'table y axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-99, 99),
            unit = 'mm',
        ),
    ),
    st_z = device('nicos.devices.generic.Axis',
        description = 'table z axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-50, 50),
            curvalue = -31,
            unit = 'mm',
        ),
    ),
    st_x = device('nicos.devices.generic.Axis',
        description = 'table x axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        abslimits = (-500.9, 110.65),
        precision = 0.01,
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-750, 150),
            unit = 'mm',
        ),
    ),
)
