description = 'CAMEA basic devices: motors, counters and such'

display_order = 20

pvmcu1 = 'SQ:CAMEA:turboPmac1:'
pvmcu2 = 'SQ:CAMEA:turboPmac2:'
pvmcu3 = 'SQ:CAMEA:turboPmac3:'
pvmcu4 = 'SQ:CAMEA:turboPmac4:'

devices = dict(
    s2t = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Sample two theta',
        motorpv = pvmcu1 + '2t',
    ),
    m2t = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator two theta',
        motorpv = pvmcu1 + '2tm',
    ),
    som = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Sample rotation',
        motorpv = pvmcu1 + 'som',
    ),
    tl_sim = device('nicos.devices.generic.ManualMove',
        description = 'Simulated tl motor',
        abslimits = (-15, 15),
        default = 0,
        unit = 'mm',
    ),
    tu_sim = device('nicos.devices.generic.ManualMove',
        description = 'Simulated tu motor',
        abslimits = (-15, 15),
        default = 0,
        unit = 'mm',
    ),
    gl_sim = device('nicos.devices.generic.ManualMove',
        description = 'Simulated gl motor',
        abslimits = (-15, 15),
        default = 0,
        unit = 'degree',
    ),
    gu_sim = device('nicos.devices.generic.ManualMove',
        description = 'Simulated gu motor',
        abslimits = (-15, 15),
        default = 0,
        unit = 'degree',
    ),
    sgl = device('nicos.core.device.DeviceAlias',
        description = 'Alias goniometer lower',
        alias = 'gl_sim',
    ),
    sgu = device('nicos.core.device.DeviceAlias',
        description = 'Alias goniometer upper',
        alias = 'gu_sim',
    ),
    gm = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator goniometer',
        motorpv = pvmcu3 + 'gm',
    ),
    mcv = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator curvature',
        motorpv = pvmcu3 + 'mcv',
    ),
    mch = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator curvature',
        motorpv = pvmcu3 + 'mch',
    ),
    omm = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator rotation',
        motorpv = pvmcu3 + 'omm',
    ),
    tlm = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator lower translation',
        motorpv = pvmcu3 + 'tlm',
    ),
    tum = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Monochromator upper translation',
        motorpv = pvmcu3 + 'tum',
    ),
    vsl = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Virtual slit left',
        motorpv = pvmcu4 + 'vsl',
    ),
    vsr = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Virtual slit rright',
        motorpv = pvmcu4 + 'vsr',
    ),
    mono = device('nicos_sinq.camea.devices.cameamono.CameaMono',
        description = 'Camea monochromator',
        theta = 'omm',
        twotheta = 'm2t',
        material = 'PG',
        reflection = (0, 0, 2),
        dvalue = 3.354,
        scatteringsense = 1,
        crystalside = 1,
        unit = 'meV',
        focmode = 'vertical',
        vfocuspars = [3.72, 102.79],
        abslimits = [2.75, 17],
        focusv = 'mcv',
        focush = 'mch',
        hfocuspars = [10.06, 271.57],
        upper_trans = [0.0, 0.0],
        lower_trans = [0.0, 0.0],
        lower = 'tlm',
        upper = 'tum',
    ),
    a5 = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Virtual a5 motor for analyser',
        speed = 10000,
        unit = 'deg',
        precision = .02,
        abslimits = (-180., 180.)
    ),
    a6 = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Virtual a6 motor for analyser',
        speed = 10000,
        unit = 'deg',
        precision = .02,
        abslimits = (-360., 360.)
    ),
    ana = device('nicos_sinq.devices.mono.SinqMonochromator',
        description = 'Camea analyser',
        theta = 'a5',
        twotheta = 'a6',
        material = 'PG',
        reflection = (0, 0, 2),
        dvalue = 3.354,
        scatteringsense = 1,
        crystalside = 1,
        unit = 'meV',
        focmode = 'flat',
        abslimits = (2.75, 20),
    ),
    ei = device('nicos.core.device.DeviceAlias',
        description = 'Alias for driving the monochromator',
        alias = 'mono',
    ),
    ef = device('nicos.core.device.DeviceAlias',
        description = 'Alias for driving the analyser',
        alias = 'ana',
    ),
    a1 = device('nicos.core.device.DeviceAlias',
        description = 'Alias monochromator theta',
        alias = 'omm',
    ),
    a2 = device('nicos.core.device.DeviceAlias',
        description = 'Alias monochromator two theta',
        alias = 'm2t',
    ),
    a3 = device('nicos.core.device.DeviceAlias',
        description = 'Alias sample rotation',
        alias = 'som',
    ),
    a4 = device('nicos_sinq.camea.devices.a4motor.CameaA4Motor',
        description = 'Real A4 with special offset',
        rawa4 = 's2t',
        unit = 'deg',
    ),
    calib1 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib2 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib3 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib4 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib5 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib6 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib7 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    calib8 = device('nicos_sinq.camea.devices.calibration.CalibrationData',
        description = 'Data class for calibration data'
    ),
    detNo = device('nicos.devices.generic.manual.ManualMove',
        description = 'Number of detector selected for summing',
        unit = 'number',
        abslimits = (0, 104)
    ),
    anaNo = device('nicos.devices.generic.manual.ManualMove',
        description = 'Number of analyser selected for summing',
        unit = 'number',
        abslimits = (0, 8)
    ),
    eis2tcontroller = device('nicos_sinq.camea.devices.eis2tcontroller.EIS2TController',
        description = 'Controller to protect CAMEA moving into the wall',
        ei = 'mono',
        s2t = 's2t',
        ei_values = [
            2, 3.6, 3.8, 5.0,5.5, 6.45,6.5, 6.6, 6.65, 6.8, 6.9,
            7.0, 7.5, 7.7, 8.0, 8.5, 8.6, 8.8, 9, 9.2, 9.4, 9.6, 9.8, 10,
            10.5, 11, 11.5, 12.0, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 16.5, 17
        ],
        s2t_values = [
            -79.501, -79.501, -79.501, -79.001, -79.001, -79.001, -79.001, -78.501, -78.501, -78.501, -77.501,
            -77.001, -77.501, -73.501, -72.001, -72.001, -70.001, -66.001, -64.001, -64.001, -64.001, -63.001, -62.001, -60.001,
            -57.001, -56.001, -54.001, -52.001, -50.001, -47.001, -47.001, -46.001, -44.001, -43.001, -42.001, -41.001, -40.501, -39.501
        ],
        visibility = {},
    ),
)

# when se_om (the sample stick rotation) is present, use this for a3
alias_config = {'a3': {'som': 10,}}

startupcode = """
sgl.alias = 'gl_sim'
sgu.alias = 'gu_sim'
"""
