description = 'setup for the status monitor'
group = 'special'

_collimationcolumn = Column(
    Block('Collimation',[
        BlockRow(
            Field(dev='att', name='att',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['x10','x100','x1000','OPEN'],
                  width=6.5,height=9),
            Field(dev='ng_pol', name='ng_pol',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','POL2','POL1','NG'],
                  width=5.5,height=9),
            Field(dev='col_20', name='20',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_18', name='18',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='bg1', name='bg1',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['50mm','OPEN','20mm','42mm'],
                  disabled_options = ['N.A.'],
                  width=7,height=9),
            Field(dev='col_16', name='16',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_14', name='14',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_12', name='12',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_10', name='10',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_8', name='8',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_6', name='6',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='bg2', name='bg2',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['28mm','20mm','12mm','OPEN'],
                  disabled_options = ['N.A.'],
                  width=7,height=9),
            Field(dev='col_4', name='4',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_3', name='3',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_2', name='2',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='col_2b', name='2b',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['LAS','free','COL','NG'],
                  width=5,height=9),
            Field(dev='sa1', name='sa1',
                  widget='nicos_mlz.sans1.gui.monitorwidgets.CollimatorTable',
                  options=['20mm','30mm','50x50'],
                  disabled_options = ['N.A.'],
                  width=7,height=9),
        ),
        BlockRow(
            Field(dev='bg1_m', name='bg1_m', format='%.1f', width=12),
            Field(dev='bg2_m', name='bg2_m', format='%.1f', width=12),
            Field(dev='sa1_m', name='sa1_m', format='%.1f', width=12),
        ),
        BlockRow(
            Field(dev='att_m', name='att_m', format='%.1f', width=12),
            Field(dev='col_20_m', name='20_m', format='%.1f', width=12),
            Field(dev='col_16_m', name='16_m', format='%.1f', width=12),
            Field(dev='col_12_m', name='12_m', format='%.1f', width=12),
            Field(dev='col_8_m', name='8_m', format='%.1f', width=12),
            Field(dev='col_4_m', name='4_m', format='%.1f', width=12),
            Field(dev='col_2_m', name='2_m', format='%.1f', width=12),
        ),
        BlockRow(
            Field(dev='ng_pol_m', name='ng_pol_m', format='%.1f', width=12),
            Field(dev='col_18_m', name='18_m', format='%.1f', width=12),
            Field(dev='col_14_m', name='14_m', format='%.1f', width=12),
            Field(dev='col_10_m', name='10_m', format='%.1f', width=12),
            Field(dev='col_6_m', name='6_m', format='%.1f', width=12),
            Field(dev='col_3_m', name='3_m', format='%.1f', width=12),
            Field(dev='col_2b_m', name='2b_m', format='%.1f', width=12),
        ),
        BlockRow(
            Field(dev='col', name='col'),
        ),
        ],
    ),
)



devices = dict(
    Monitor = device('nicos.services.monitor.qt.Monitor',
        title = 'SANS-1 status monitor',
        loglevel = 'info',
        cache = 'localhost',
        prefix = 'nicos/',
        font = 'Luxi Sans',
        valuefont = 'Consolas',
        fontsize = 15,
        padding = 0,
        layout = [
            Row(_collimationcolumn),
        ],
    ),
)
