description = 'LakeShore 340 cryo controller for CCR-6 cryostat'
group = 'optional'

includes = ['alias_T']

nethost = 'spodisrv'
domain = 'spodi'

devices = {
    'T_%s_340' % setupname: device('nicos.devices.taco.TemperatureController',
        description = 'CCR6 temperature regulation (LS-340)',
        tacodevice = '//%s/%s/ls340/control' % (nethost, domain),
        pollinterval = 1,
        maxage = 6,
        abslimits = (0, 600),
    ),
    'T_%s_A_340' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = 'CCR6 sensor A (LS-340)',
        tacodevice = '//%s/%s/ls340/sensora' % (nethost, domain),
        pollinterval = 1,
        maxage = 6,
    ),
    'T_%s_B_340' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = 'CCR6 sensor B (LS-340)',
        tacodevice = '//%s/%s/ls340/sensorb' % (nethost, domain),
        pollinterval = 1,
        maxage = 6,
    ),
    # T_ccr6_C = device('nicos.devices.taco.TemperatureSensor',
    #     description = 'CCR6 sensor C',
    #     tacodevice = '//%s/%s/ls340/sensc' % (nethost, domain),
    #     pollinterval = 1,
    #     maxage = 6,
    # ),
    # T_ccr6_D = device('nicos.devices.taco.TemperatureSensor',
    #     description = 'CCR6 sensor D',
    #     tacodevice = '//%s/%s/ls340/sensd' % (nethost, domain),
    #     pollinterval = 1,
    #     maxage = 6,
    # ),
    # ccr6_p1 = device('nicos.devices.taco.AnalogInput',
    #     description = 'Cryo sample tube pressure',
    #     tacodevice = '//%s/%s/ccr/p1' % (nethost, domain),
    #     fmtstr = '%.3f',
    # ),
    # ccr6_p2 = device('nicos.devices.taco.AnalogInput',
    #     description = 'Cryo sample tube pressure (second sensor)',
    #     tacodevice = '//%s/%s/ccr/p2' % (nethost, domain),
    #     fmtstr = '%.3f',
    # ),
    # ccr6_compressor_switch = device('nicos.devices.taco.NamedDigitalOutput',
    #     description = 'CCR6 compressor switch on/off',
    #     mapping = {'off': 0,
    #                'on': 1},
    #     tacodevice = '//%s/%s/ccr/pump' % (nethost, domain),
    # ),
    # ccr6_gas_switch = device('nicos.devices.taco.NamedDigitalOutput',
    #     description = 'CCR6 sample tube gas switch on/off',
    #     mapping = {'off': 0,
    #                'on': 1},
    #     tacodevice = '//%s/%s/ccr/gas' % (nethost, domain),
    # ),
    # ccr6_vacuum_switch = device('nicos.devices.taco.NamedDigitalOutput',
    #     description = 'CCR6 sample tube vacuum switch on/off',
    #     mapping = {'off': 0,
    #                'on': 1},
    #     tacodevice = '//%s/%s/ccr/vacuum' % (nethost, domain),
    # ),
    'T_%s' % setupname: device('nicos_mlz.frm2.devices.ccr.CCRControl',
        description = 'The main temperature control device of the CCR (LS-336)',
        stick = 'T_%s_stick' % setupname,
        tube = 'T_%s_tube' % setupname,
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_stick' % setupname: device('nicos.devices.taco.TemperatureController',
        description = 'The control device of the sample (stick) (LS-336)',
        tacodevice = '//%s/spodi/stick/control2' % nethost,
        abslimits = (0, 600),
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_tube' % setupname: device('nicos.devices.taco.TemperatureController',
        description = 'The control device of the tube (LS-336)',
        tacodevice = '//%s/spodi/tube/control1' % nethost,
        abslimits = (0, 600),
        warnlimits = (0, 600),
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_A' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = '(optional) Sample temperature (LS-336)',
        tacodevice = '//%s/spodi/sample/sensora' % nethost,
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_B' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = '(regulation) Temperature at the stick (LS-336)',
        tacodevice = '//%s/spodi/stick/sensorb' % nethost,
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_C' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = 'Temperature of the coldhead (LS-336)',
        tacodevice = '//%s/spodi/coldhead/sensorc' % nethost,
        warnlimits = (0, 300),
        unit = 'K',
        fmtstr = '%.3f',
    ),
    'T_%s_D' % setupname: device('nicos.devices.taco.TemperatureSensor',
        description = '(regulation) Temperature at thermal coupling to the '
                      'tube (LS-336)',
        tacodevice = '//%s/spodi/tube/sensord' % nethost,
        warnlimits = (0, 600),
        unit = 'K',
        fmtstr = '%.3f',
    ),
}

alias_config = {
    'T': {
        'T_%s' % setupname: 200,
        'T_%s_stick' % setupname: 150,
        'T_%s_tube' % setupname: 100,
        'T_%s_340' % setupname: 80
    },
    'Ts': {
        'T_%s_B' % setupname: 100,
        'T_%s_A' % setupname: 90,
        'T_%s_D' % setupname: 20,
        'T_%s_C' % setupname: 10,
        'T_%s_A_340' % setupname: 8,
        'T_%s_B_340' % setupname: 5,
    },
}
