#  -*- coding: utf-8 -*-

description = 'Monoturm, everything inside the Monochromator housing'

# sampletable.py contains all buses
includes = ['sampletable']

group = 'lowlevel'

devices = dict(
    mgx_step = device('nicos.devices.generic.VirtualMotor',
        unit = 'deg',
        abslimits = (-3, 3),
        speed = 1,
        lowlevel = True,
    ),
    mgx_poti = device('nicos.devices.generic.VirtualCoder',
        motor = 'mgx_step',
        unit = 'deg',
        lowlevel = True,
    ),
    mgx = device('nicos.devices.generic.Axis',
        description = 'mono tilt (up/down)',
        motor = 'mgx_step',
        obs = ['mgx_poti'],
        precision = 0.01,
    ),

    mtx_step = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-15, 3),
        speed = 1,
        lowlevel = True,
    ),
    mtx_poti = device('nicos.devices.generic.VirtualCoder',
        motor = 'mtx_step',
        unit = 'mm',
        lowlevel = True,
    ),
    mtx = device('nicos.devices.generic.Axis',
        description = 'mono translation (left/right) (needed for Si!)',
        motor = 'mtx_step',
        precision = 0.1,
        obs = ['mtx_poti'],
        fmtstr = '%.1f',
    ),

    mty_step = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-11, 11),
        speed = 1,
        lowlevel = True,
    ),
    mty_poti = device('nicos.devices.generic.VirtualCoder',
        motor = 'mty_step',
        unit = 'mm',
        lowlevel = True,
    ),
    mty = device('nicos.devices.generic.Axis',
        description = 'mono translation along Y (thickness correction)',
        motor = 'mty_step',
        obs = ['mty_poti'],
        precision = 0.1,
        fmtstr = '%.1f',
    ),

    mth_step = device('nicos.devices.generic.VirtualMotor',
        unit = 'deg',
        abslimits = (-25, 100),
        speed = 2,
        lowlevel = True,
    ),
    mth_enc = device('nicos.devices.generic.VirtualCoder',
        motor = 'mth_step',
        unit = 'deg',
        lowlevel = True,
    ),
    mth = device('nicos.devices.generic.Axis',
        description = 'rocking angle of monochromator',
        motor = 'mth_step',
        coder = 'mth_enc',
        precision = 0.01,
        # offset = -0.0726863,
        offset = -0.0926863,
    ),

    ms1_step = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-1.0, 51.0),
        userlimits = (0, 50),
        speed = 1,
        lowlevel = True,
        curvalue = 40,
    ),
    ms1_enc = device('nicos.devices.generic.VirtualCoder',
        motor = 'ms1_step',
        unit = 'mm',
        lowlevel = True,
    ),
    ms1 = device('nicos.devices.generic.Axis',
        description = 'primary horizontal slit before mono',
        motor = 'ms1_step',
        coder = 'ms1_enc',
        precision = 0.05,
        fmtstr = '%.1f',
    ),
)
