description = 'Monochromator tower devices'

group = 'lowlevel'

nethost = 'kompasshw.kompass.frm2'

devices = dict(
    # A1
    mth_m = device('devices.taco.Motor',
                   description = 'A1 motor',
                   tacodevice = '//%s/kompass/a1/motor' % nethost,
                   abslimits = (-10, 70),
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mth_c = device('devices.taco.Coder',
                   description = 'A1 coder',
                   tacodevice = '//%s/kompass/a1/coder' % nethost,
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mth = device('devices.generic.Axis',
                 description = 'mth (alias A1)',
                 motor = 'mth_m',
                 coder = 'mth_m',  # 'mth_c',
                 fmtstr = '%.2f',
                 precision = 0.001,
                ),
    mx_m = device('devices.taco.Motor',
                  description = 'Monochromator table X motor',
                  tacodevice = '//%s/kompass/monox/motor' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                  abslimits = (-5, 5),
                 ),
    mx_c = device('devices.taco.Coder',
                  description = 'Monochromator table X coder',
                  tacodevice = '//%s/kompass/monox/coder' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    mx = device('devices.generic.Axis',
                description = 'Monochromator table X',
                motor = 'mx_m',
                coder = 'mx_c',
                fmtstr = '%.1f',
                precision = 0.05,
               ),
    my_m = device('devices.taco.Motor',
                  description = 'Monochromator table Y motor',
                  tacodevice = '//%s/kompass/monoy/motor' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                  abslimits = (-5, 5),
                 ),
    my_c = device('devices.taco.Coder',
                  description = 'Monochromator table Y coder',
                  tacodevice = '//%s/kompass/monoy/coder' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    my = device('devices.generic.Axis',
                description = 'Monochromator table Y',
                motor = 'my_m',
                coder = 'my_c',
                fmtstr = '%.1f',
                precision = 0.05,
               ),
    mc_m = device('devices.taco.Motor',
                  description = 'Monochromator table cradle motor',
                  tacodevice = '//%s/kompass/monoc/motor' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    mc_c = device('devices.taco.Coder',
                  description = 'Monochromator table cradle coder',
                  tacodevice = '//%s/kompass/monoc/coder' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    mc = device('devices.generic.Axis',
                description = 'Monochromator table cradle',
                motor = 'mc_m',
                coder = 'mc_m',  # 'mc_c',
                fmtstr = '%.1f',
                precision = 0.05,
               ),
    mfv_m = device('devices.taco.Motor',
                   description = 'Monochromator vertically focussing motor',
                   tacodevice = '//%s/kompass/mfv/motor' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                   abslimits = (-0.3, 1),
                  ),
    mfv_c = device('devices.taco.Coder',
                   description = 'Monochromator vertically focussing coder',
                   tacodevice = '//%s/kompass/mfv/coder' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                  ),
    mfv = device('devices.generic.Axis',
                 description = 'Monochromator vertically focussing axis',
                 motor = 'mfv_m',
                 coder = 'mfv_c',
                 fmtstr = '%.2f',
                 precision = 0.01,
                ),
    mfh_m = device('devices.taco.Motor',
                   description = 'Monochromator horizontally focussing motor',
                   tacodevice = '//%s/kompass/mfh/motor' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                   abslimits = (-0.3, 1),
                  ),
    mfh_c = device('devices.taco.Coder',
                   description = 'Monochromator horizontally focussing coder',
                   tacodevice = '//%s/kompass/mfh/coder' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                  ),
    mfh = device('devices.generic.Axis',
                 description = 'Monochromator horizontally focussing axis',
                 motor = 'mfh_m',
                 coder = 'mfh_c',
                 fmtstr = '%.2f',
                 precision = 0.01,
                ),
)
