description = 'Beam limiter device at measurement position 2'

pvprefix = 'SQ:NEUTRA:turboPmacSlit:'

display_order = 20

devices = dict(
    bl2top = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Beam Limiter 2 top',
        motorpv = pvprefix + 'bl2_top',
    ),
    bl2bottom = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Beam Limiter 2 bottom',
        motorpv = pvprefix + 'bl2_bot',
    ),
    bl2right = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Beam Limiter 2 right',
        motorpv = pvprefix + 'bl2_rig',
    ),
    bl2left = device('nicos_sinq.devices.epics.motor.SinqMotor',
        description = 'Beam Limiter 2 left',
        motorpv = pvprefix + 'bl2_lef',
    ),
    bl2 = device('nicos.devices.generic.slit.Slit',
        description = 'Beam Limiter 2',
        opmode = 'offcentered',
        left = 'bl2left',
        right = 'bl2right',
        top = 'bl2top',
        bottom = 'bl2bottom',
        coordinates = 'opposite',
        visibility = set(),
    ),
    bl2_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Beam limiter 2 opening width',
        slit = 'bl2',
        unit = 'mm',
    ),
    bl2_height = device('nicos.devices.generic.slit.HeightSlitAxis',
        description = 'Beam limiter 2 opening height',
        slit = 'bl2',
        unit = 'mm',
    ),
    bl2_center_h = device('nicos.devices.generic.slit.CenterXSlitAxis',
        description = 'Beam limiter 2 horizontal center',
        slit = 'bl2',
        unit = 'mm',
    ),
    bl2_center_v = device('nicos.devices.generic.slit.CenterYSlitAxis',
        description = 'Beam limiter 2 vertical center',
        slit = 'bl2',
        unit = 'mm',
    ),
)
