description = 'TOF counter devices'

group = 'lowlevel'

devices = dict(
    monitor = device('nicos.devices.generic.VirtualCounter',
        description = 'TOFTOF monitor',
        fmtstr = '%d',
        type = 'monitor',
        lowlevel = True,
    ),
    timer = device('nicos.devices.generic.VirtualTimer',
        description = 'TOFTOF timer',
        fmtstr = '%.2f',
        unit = 's',
        lowlevel = True,
    ),
    image = device('nicos_mlz.toftof.devices.virtual.VirtualImage',
        description = 'Image data device',
        fmtstr = '%d',
        pollinterval = 86400,
        lowlevel = True,
        datafile = 'nicos_demo/vtoftof/data/test/data.npz',
    ),
    det = device('nicos_mlz.toftof.devices.detector.Detector',
        description = 'The TOFTOF detector device',
        timers = ['timer'],
        monitors = ['monitor'],
        images = ['image'],
        rc = 'rc',
        chopper = 'ch',
        chdelay = 'chdelay',
        maxage = 3,
        pollinterval = 0.5,
        liveinterval = 10.0,
        saveintervals = [30.],
        detinfofile = 'nicos_demo/vtoftof/detinfo.dat',
    ),
)
