description = 'NIAG NGIV2'

pvprefix = 'SQ:BOA:ngiv2:'

devices = dict(
    sgtx = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI sample movement X',
        motorpv = pvprefix + 'sgtx',
        errormsgpv = pvprefix + 'sgtx-MsgTxt',
    ),
    sgty = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI sample movement Y',
        motorpv = pvprefix + 'sgty',
        errormsgpv = pvprefix + 'sgty-MsgTxt',
    ),
    sgtz = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI sample movement Z',
        motorpv = pvprefix + 'sgtz',
        errormsgpv = pvprefix + 'sgtz-MsgTxt',
    ),
    sgry = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI sample rotation Y',
        motorpv = pvprefix + 'sgry',
        errormsgpv = pvprefix + 'sgry-MsgTxt',
    ),
    g1tyl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI G1 translation Y (long range)',
        motorpv = pvprefix + 'g1tyl',
        errormsgpv = pvprefix + 'g1tyl-MsgTxt',
    ),
    g1ty = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI G1 translation Y',
        motorpv = pvprefix + 'g1ty',
        errormsgpv = pvprefix + 'g1ty-MsgTxt',
    ),
    g1rz = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI G1 rotation Z',
        motorpv = pvprefix + 'g1rz',
        errormsgpv = pvprefix + 'g1rz-MsgTxt',
    ),
    g2rz = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'XinGI G2 rotation Z',
        motorpv = pvprefix + 'g2rz',
        errormsgpv = pvprefix + 'g2rz-MsgTxt',
    ),
)
