description = 'BOA Adaptive Obtics 2017 Setup'

pvprefix = 'SQ:BOA:mcu4:'

devices = dict(
    slt = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLT',
        motorpv = pvprefix + 'SLT',
        errormsgpv = pvprefix + 'SLT-MsgTxt',
        can_disable = True,
    ),
    slb = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLB',
        motorpv = pvprefix + 'SLB',
        errormsgpv = pvprefix + 'SLB-MsgTxt',
        can_disable = True,
    ),
    sll = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLL',
        motorpv = pvprefix + 'SLL',
        errormsgpv = pvprefix + 'SLL-MsgTxt',
        can_disable = True,
    ),
    slr = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLR',
        motorpv = pvprefix + 'SLR',
        errormsgpv = pvprefix + 'SLR-MsgTxt',
        can_disable = True,
    ),
    slz = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLZ',
        motorpv = pvprefix + 'SLZ',
        errormsgpv = pvprefix + 'SLZ-MsgTxt',
        can_disable = True
    ),
    slrot = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Motor SLROT',
        motorpv = pvprefix + 'SLROT',
        errormsgpv = pvprefix + 'SLROT-MsgTxt',
        can_disable = True,
    ),
)
