description = 'setup for the velocity selector'

group = 'lowlevel'

tango_base = 'tango://resedahw2.reseda.frm2:10000/reseda/selector'

devices = dict(
    selector_speed = device('devices.tango.WindowTimeoutAO',
        description = 'Selector speed control',
        tangodevice = tango_base + '/speed',
        unit = 'rpm',
        fmtstr = '%.0f',
        warnlimits = (11000, 22000),
        abslimits = (11000, 22000),
        precision = 10,
    ),
    selector_lambda = device('devices.vendor.astrium.SelectorLambda',
        description = 'Selector wavelength control',
        seldev = 'selector_speed',
        unit = 'A',
        fmtstr = '%.2f',
        twistangle = 19.724,
        length = 0.25,
        beamcenter = 0.115,
        maxspeed = 28300,
    ),
    selector_rtemp = device('devices.tango.AnalogInput',
        description = 'Temperature of the selector rotor',
        tangodevice = tango_base + '/rotortemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (10, 45),
    ),
    selector_winlt = device('devices.tango.AnalogInput',
        description = 'Cooling water temperature at inlet',
        tangodevice = tango_base + '/waterintemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (15, 20),
    ),
    selector_woutt = device('devices.tango.AnalogInput',
        description = 'Cooling water temperature at outlet',
        tangodevice = tango_base + '/waterouttemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (15, 20),
    ),
    selector_wflow = device('devices.tango.AnalogInput',
        description = 'Cooling water flow rate through selector',
        tangodevice = tango_base + '/flowrate',
        unit = 'l/min',
        fmtstr = '%.1f',
        warnlimits = (1.5, 10),
    ),
    selector_vacuum = device('devices.tango.AnalogInput',
        description = 'Vacuum in the selector',
        tangodevice = tango_base + '/vacuum',
        unit = 'mbar',
        fmtstr = '%.5f',
        warnlimits = (0, 0.005),
    ),
    selector_vibrt = device('devices.tango.AnalogInput',
        description = 'Selector vibration',
        tangodevice = tango_base + '/vibration',
        unit = 'mm/s',
        fmtstr = '%.2f',
        warnlimits = (0, 1),
    ),
)
