description = 'Setup for RESEDA Power Supplies for guide fields'

group = 'lowlevel'

nethost = 'resedasrv'

devices = dict(
    p6crd_1 = device('devices.taco.AnalogOutput',
        description = 'b5 3-fold Power Supply hpe3631a_1',
        tacodevice = '//%s/reseda/hpe3631a_1/p6crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    p25crd_1 = device('devices.taco.AnalogOutput',
        description = 'b6 3-fold Power Supply hpe3631a_1',
        tacodevice = '//%s/reseda/hpe3631a_1/p25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    n25crd_1 = device('devices.taco.AnalogOutput',
        description = 'b7 3-fold Power Supply hpe3631a_1',
        tacodevice = '//%s/reseda/hpe3631a_1/n25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    p6crd_2 = device('devices.taco.AnalogOutput',
        description = 'b9 3-fold Power Supply hpe3631a_2',
        tacodevice = '//%s/reseda/hpe3631a_2/p25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    p25crd_2 = device('devices.taco.AnalogOutput',
        description = 'b9 3-fold Power Supply hpe3631a_2',
        tacodevice = '//%s/reseda/hpe3631a_2/p25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    n25crd_2 = device('devices.taco.AnalogOutput',
        description = 'b10 3-fold Power Supply hpe3631a_2',
        tacodevice = '//%s/reseda/hpe3631a_2/n25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    p6crd_3 = device('devices.taco.AnalogOutput',
        description = 'b11 3-fold Power Supply hpe3631a_3',
        tacodevice = '//%s/reseda/hpe3631a_3/p25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    p25crd_3 = device('devices.taco.AnalogOutput',
        description = 'b12 3-fold Power Supply hpe3631a_3',
        tacodevice = '//%s/reseda/hpe3631a_3/p25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    n25crd_3 = device('devices.taco.AnalogOutput',
        description = 'b13 3-fold Power Supply hpe3631a_3',
        tacodevice = '//%s/reseda/hpe3631a_3/n25crd' % (nethost,),
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),

    # p6cur = device('devices.taco.AnalogOutput',
    #            description = '3-fold Power Supply hpe3631a_1 current',
    #            tacodevice = '//%s/reseda/hpe3631a_1/p6cur' % (nethost,),
    #            pollinterval = 5,
    #            maxage = 8,
    #            abslimits = (0, 5),
    #           ),
)
