description = 'NICOS startup setup'
group = 'lowlevel'

devices = dict(

    B01 = device('reseda.current.CurrentA',
                     tacodevice = '//resedasrv/reseda/nigpib/ntn1',
                     pollinterval = 10,
                     maxage = 15),

    B21 = device('reseda.current.CurrentA',
                     tacodevice = '//resedasrv/reseda/nigpib/ntn2',
                     pollinterval = 10,
                     maxage = 15),

    B02 = device('reseda.current.CurrentU',
                     tacodevice = '//resedasrv/reseda/nigpib/ntn1',
                     pollinterval = 10,
                     maxage = 15),

    B22 = device('reseda.current.CurrentU',
                     tacodevice = '//resedasrv/reseda/nigpib/ntn2',
                     pollinterval = 10,
                     maxage = 15),

    B51_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B51_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B52_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B52_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B53_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B53_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_1',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B61_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B61_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B62_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B62_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B63_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B63_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_2',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B71_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B71_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B72_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B72_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B73_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B73_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3631_3',
                     pollinterval = 10,
                     channel = 3,
                     maxage = 15),

    B81_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_1',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B81_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_1',
                     channel = 1,
                     pollinterval = 10,
                     maxage = 15),

    B82_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_1',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B82_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_1',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B91_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_2',
                     channel = 1,
                     pollinterval = 10,
                     maxage = 15),

    B91_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_2',
                     channel = 1,
                     pollinterval = 10,
                     maxage = 15),

    B92_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_2',
                     channel = 2,
                     pollinterval = 10,
                     maxage = 15),

    B92_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_2',
                     channel = 2,
                     pollinterval = 10,
                     maxage = 15),

    B101_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_3',
                     channel = 1,
                     pollinterval = 10,
                     maxage = 15),

    B101_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_3',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B102_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_3',
                     channel = 2,
                     pollinterval = 10,
                     maxage = 15),

    B102_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_3',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B111_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_4',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B111_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_4',
                     pollinterval = 10,
                     channel = 1,
                     maxage = 15),

    B112_c = device('reseda.powerSupply.PowerSupplyA',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_4',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

    B112_v = device('reseda.powerSupply.PowerSupplyU',
                     tacodevice = '//resedasrv/reseda/network/hpe3648_4',
                     pollinterval = 10,
                     channel = 2,
                     maxage = 15),

)
