description = 'Frequency generators'
group = 'lowlevel'

taco_base = '//resedasrv.reseda.frm2/reseda'

devices = dict(
    fg0_freq = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F0',
        tacodevice = '%s/hp33250a_1/freq' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5000000),
    ),
    fg1_freq = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F1',
        tacodevice = '%s/hp33250a_2/freq' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5000000),
    ),
    fg2_freq = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F2',
        tacodevice = '%s/hp33250a_3/freq' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5000000),
    ),
    fg0_amp = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F0',
        tacodevice = '%s/hp33250a_1/amp' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5000000),
    ),
    fg1_amp = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F1',
        tacodevice = '%s/hp33250a_2/amp' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    fg2_amp = device('nicos.devices.taco.AnalogOutput',
        description = 'Frequency Generator F2',
        tacodevice = '%s/hp33250a_3/amp' % taco_base,
        pollinterval = 5,
        maxage = 8,
        abslimits = (0, 5),
    ),
    rf0 = device('nicos.devices.taco.AnalogInput',
        description = 'Interface F0',
        tacodevice = '%s/keithley/rc1' % taco_base,
        pollinterval = 5,
        maxage = 8,
    ),
    rf1 = device('nicos.devices.taco.AnalogInput',
        description = 'Interface F1',
        tacodevice = '%s/keithley/rc2' % taco_base,
        pollinterval = 5,
        maxage = 8,
    ),
    rf2 = device('nicos.devices.taco.AnalogInput',
        description = 'Interface F2',
        tacodevice = '%s/keithley/rc3' % taco_base,
        pollinterval = 5,
        maxage = 8,
    ),
)
