# -*- coding: utf-8 -*-

description = "Axes setup"
group = "lowlevel"

tango_base = "tango://phys.kws1.frm2:10000/kws1/"

devices = dict(
    coll_set    = device('devices.tango.DigitalOutput',
                         tangodevice = tango_base + 'fzjdp_digital/coll_write',
                         lowlevel = True,
                        ),
    coll_in     = device('devices.tango.DigitalInput',
                         tangodevice = tango_base + 'fzjdp_digital/coll_in',
                         lowlevel = True,
                        ),
    coll_out    = device('devices.tango.DigitalInput',
                         tangodevice = tango_base + 'fzjdp_digital/coll_out',
                         lowlevel = True,
                        ),
    coll_sync   = device('devices.tango.DigitalOutput',
                         tangodevice = tango_base + 'fzjdp_digital/sync_bit',
                         lowlevel = True,
                        ),
    coll_guides = device('kws1.collimation.CollimationGuides',
                         description = 'positioning of the neutron guide elements',
                         output = 'coll_set',
                         input_in = 'coll_in',
                         input_out = 'coll_out',
                         sync_bit = 'coll_sync',
                        ),

    aperture_20_x = device("devices.tango.Motor",
                           description = "20m aperture horizontal opening",
                           tangodevice = tango_base + "fzjs7/aperture_20_x",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_20_y = device("devices.tango.Motor",
                           description = "20m aperture vertical opening",
                           tangodevice = tango_base + "fzjs7/aperture_20_y",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_20   = device("devices.generic.TwoAxisSlit",
                           description = "20m aperture",
                           horizontal = "aperture_20_x",
                           vertical = "aperture_20_y",
                           fmtstr = "%.1f x %.1f",
                          ),

    aperture_14_x = device("devices.tango.Motor",
                           description = "14m aperture horizontal opening",
                           tangodevice = tango_base + "fzjs7/aperture_14_x",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_14_y = device("devices.tango.Motor",
                           description = "14m aperture vertical opening",
                           tangodevice = tango_base + "fzjs7/aperture_14_y",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_14   = device("devices.generic.TwoAxisSlit",
                           description = "14m aperture",
                           horizontal = "aperture_14_x",
                           vertical = "aperture_14_y",
                           fmtstr = "%.1f x %.1f",
                          ),

    aperture_08_x = device("devices.tango.Motor",
                           description = "8m aperture horizontal opening",
                           tangodevice = tango_base + "fzjs7/aperture_8_x",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_08_y = device("devices.tango.Motor",
                           description = "8m aperture vertical opening",
                           tangodevice = tango_base + "fzjs7/aperture_8_y",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_08   = device("devices.generic.TwoAxisSlit",
                           description = "8m aperture",
                           horizontal = "aperture_08_x",
                           vertical = "aperture_08_y",
                           fmtstr = "%.1f x %.1f",
                          ),

    aperture_04_x = device("devices.tango.Motor",
                           description = "4m aperture horizontal opening",
                           tangodevice = tango_base + "fzjs7/aperture_4_x",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                           abslimits = (1, 49.9),
                          ),
    aperture_04_y = device("devices.tango.Motor",
                           description = "4m aperture vertical opening",
                           tangodevice = tango_base + "fzjs7/aperture_4_y",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                           abslimits = (1, 49.9),
                          ),
    aperture_04   = device("devices.generic.TwoAxisSlit",
                           description = "4m aperture",
                           horizontal = "aperture_04_x",
                           vertical = "aperture_04_y",
                           fmtstr = "%.1f x %.1f",
                          ),

    aperture_02_x = device("devices.tango.Motor",
                           description = "2m aperture horizontal opening",
                           tangodevice = tango_base + "fzjs7/aperture_2_x",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_02_y = device("devices.tango.Motor",
                           description = "2m aperture vertical opening",
                           tangodevice = tango_base + "fzjs7/aperture_2_y",
                           unit = "mm",
                           precision = 0.02,
                           lowlevel = True,
                          ),
    aperture_02   = device("devices.generic.TwoAxisSlit",
                           description = "2m aperture",
                           horizontal = "aperture_02_x",
                           vertical = "aperture_02_y",
                           fmtstr = "%.1f x %.1f",
                          ),
)
