# -*- coding: utf-8 -*-

description = "Sample aperture and table"
group = "lowlevel"

tango_base = "tango://phys.kws1.frm2:10000/kws1/"

devices = dict(
    ap_sam_x0     = device("devices.tango.Motor",
                           description = "sample aperture horz. blade 0",
                           tangodevice = tango_base + "fzjs7/new_ap_sam_x0",
                           unit = "mm",
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_y0     = device("devices.tango.Motor",
                           description = "sample aperture vert. blade 0",
                           tangodevice = tango_base + "fzjs7/new_ap_sam_y0",
                           unit = "mm",
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_x1     = device("devices.tango.Motor",
                           description = "sample aperture horz. blade 1",
                           tangodevice = tango_base + "fzjs7/new_ap_sam_x1",
                           unit = "mm",
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_y1     = device("devices.tango.Motor",
                           description = "sample aperture vert. blade 1",
                           tangodevice = tango_base + "fzjs7/new_ap_sam_y1",
                           unit = "mm",
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam        = device("devices.generic.Slit",
                           description = "sample aperture",
                           coordinates = "opposite",
                           left = "ap_sam_x1",
                           right = "ap_sam_x0",
                           bottom = "ap_sam_y0",
                           top = "ap_sam_y1",
                          ),

    sam_rot       = device("devices.tango.Motor",
                           description = "sample rotation",
                           tangodevice = tango_base + "fzjs7/sample_axis_0",
                           unit = "deg",
                           precision = 0.01,
                           fmtstr = "%.2f",
                          ),
    sam_trans_1   = device("devices.tango.Motor",
                           description = "sample translation 1",
                           tangodevice = tango_base + "fzjs7/sample_axis_1",
                           unit = "mm",
                           precision = 0.01,
                           fmtstr = "%.1f",
                          ),
    sam_trans_2   = device("devices.tango.Motor",
                           description = "sample translation 2",
                           tangodevice = tango_base + "fzjs7/sample_axis_2",
                           unit = "mm",
                           precision = 0.01,
                           fmtstr = "%.1f",
                          ),
)
