# -*- coding: utf-8 -*-

description = "Virtual sample aperture and table"
group = "lowlevel"

devices = dict(
    ap_sam_x0     = device("devices.generic.VirtualMotor",
                           description = "sample aperture horz. blade 0",
                           unit = "mm",
                           abslimits = (0, 50),
                           speed = 2,
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_y0     = device("devices.generic.VirtualMotor",
                           description = "sample aperture vert. blade 0",
                           unit = "mm",
                           abslimits = (0, 50),
                           speed = 3,
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_x1     = device("devices.generic.VirtualMotor",
                           description = "sample aperture horz. blade 1",
                           unit = "mm",
                           abslimits = (0, 50),
                           speed = 2,
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam_y1     = device("devices.generic.VirtualMotor",
                           description = "sample aperture vert. blade 1",
                           unit = "mm",
                           abslimits = (0, 50),
                           speed = 3,
                           precision = 0.01,
                           lowlevel = True,
                          ),
    ap_sam        = device("devices.generic.Slit",
                           description = "sample aperture",
                           coordinates = "opposite",
                           opmode = "offcentered",
                           left = "ap_sam_x1",
                           right = "ap_sam_x0",
                           bottom = "ap_sam_y0",
                           top = "ap_sam_y1",
                          ),

    sam_rot       = device("devices.generic.VirtualMotor",
                           description = "sample rotation",
                           unit = "deg",
                           abslimits = (-180, 180),
                           precision = 0.01,
                           speed = 10,
                           fmtstr = "%.2f",
                          ),
    sam_trans_1   = device("devices.generic.VirtualMotor",
                           description = "sample translation 1",
                           unit = "mm",
                           abslimits = (0, 50),
                           precision = 0.01,
                           speed = 2,
                           fmtstr = "%.1f",
                          ),
    sam_trans_2   = device("devices.generic.VirtualMotor",
                           description = "sample translation 2",
                           unit = "mm",
                           abslimits = (0, 200),
                           precision = 0.01,
                           speed = 20,
                           fmtstr = "%.1f",
                          ),
)
