# -*- coding: utf-8 -*-

description = "Mirror area setup"
group = "lowlevel"
display_order = 30

includes = ['sample']
excludes = ['virtual_mirror']

tango_base = "tango://phys.kws3.frm2:10000/kws3/"

devices = dict(
    mir_x           = device("nicos.devices.tango.Motor",
                             description = "mirror x-table",
                             tangodevice = tango_base + "fzjs7/mir_x",
                             unit = "mm",
                             precision = 0.01,
                             fmtstr = "%.3f",
                            ),
    mir_y           = device("nicos.devices.tango.Motor",
                             description = "mirror y-hub",
                             tangodevice = tango_base + "fzjs7/mir_y",
                             unit = "mm",
                             precision = 0.01,
                             fmtstr = "%.3f",
                            ),
    mir_tilt        = device("nicos.devices.tango.Motor",
                             description = "mirror tilting",
                             tangodevice = tango_base + "fzjs7/mir_tilt",
                             unit = "mm",
                             precision = 0.01,
                             fmtstr = "%.3f",
                            ),
    mir_ap1         = device("nicos.devices.generic.Slit",
                             description = "jj-xray aperture in front of mirror",
                             coordinates = "opposite",
                             opmode = "offcentered",
                             fmtstr = '(%.2f, %.2f) %.2f x %.2f',
                             left = "mir_ap1_x_left",
                             right = "mir_ap1_x_right",
                             bottom = "mir_ap1_y_lower",
                             top = "mir_ap1_y_upper",
                            ),
    mir_ap1_x_left  = device("nicos.devices.tango.Motor",
                             description = "aperture in front of mirror left",
                             tangodevice = tango_base + "fzjs7/mir_ap1_x_left",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap1_x_right = device("nicos.devices.tango.Motor",
                             description = "aperture in front of mirror right",
                             tangodevice = tango_base + "fzjs7/mir_ap1_x_right",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap1_y_upper = device("nicos.devices.tango.Motor",
                             description = "aperture in front of mirror upper",
                             tangodevice = tango_base + "fzjs7/mir_ap1_y_upper",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap1_y_lower = device("nicos.devices.tango.Motor",
                             description = "aperture in front of mirror lower",
                             tangodevice = tango_base + "fzjs7/mir_ap1_y_lower",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap2         = device("nicos.devices.generic.Slit",
                             description = "jj-xray aperture behind mirror",
                             coordinates = "opposite",
                             opmode = "offcentered",
                             fmtstr = '(%.2f, %.2f) %.2f x %.2f',
                             left = "mir_ap2_x_left",
                             right = "mir_ap2_x_right",
                             bottom = "mir_ap2_y_lower",
                             top = "mir_ap2_y_upper",
                            ),
    mir_ap2_x_left  = device("nicos.devices.tango.Motor",
                             description = "aperture behind mirror left",
                             tangodevice = tango_base + "fzjs7/mir_ap2_x_left",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap2_x_right = device("nicos.devices.tango.Motor",
                             description = "aperture behind mirror right",
                             tangodevice = tango_base + "fzjs7/mir_ap2_x_right",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap2_y_upper = device("nicos.devices.tango.Motor",
                             description = "aperture behind mirror upper",
                             tangodevice = tango_base + "fzjs7/mir_ap2_y_upper",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    mir_ap2_y_lower = device("nicos.devices.tango.Motor",
                             description = "aperture behind mirror lower",
                             tangodevice = tango_base + "fzjs7/mir_ap2_y_lower",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
)

alias_config = {
    'sam_ap': {'mir_ap2': 80},
}
