# -*- coding: utf-8 -*-

description = "Selector area setup"
group = "lowlevel"

excludes = ['virtual_selector']

tango_base = "tango://phys.kws3.frm2:10000/kws3/"

devices = dict(
    sel_rot         = device("devices.tango.Motor",
                             description = "selector rotation table",
                             tangodevice = tango_base + "fzjs7/sel_rot",
                             unit = "deg",
                             precision = 0.01,
                            ),
    sel_ap1         = device("devices.generic.TwoAxisSlit",
                             description = "aperture before selector",
                             fmtstr = '%.3f %.3f',
                             horizontal = "sel_ap1_width",
                             vertical = "sel_ap1_hight",
                            ),
    sel_ap1_width   = device("devices.tango.Motor",
                             description = "aperture selector horizontal opening",
                             tangodevice = tango_base + "fzjs7/sel_ap1_x_delta",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    sel_ap1_hight   = device("devices.tango.Motor",
                             description = "aperture selector vertical opening",
                             tangodevice = tango_base + "fzjs7/sel_ap1_y_delta",
                             unit = "mm",
                             precision = 0.01,
                             lowlevel = True,
                            ),
    sel_ap2         = device("devices.generic.Slit",
                             description = "selector jj-xray aperture",
                             left = "sel_ap2_x_left",
                             right = "sel_ap2_x_right",
                             bottom = "sel_ap2_y_lower",
                             top = "sel_ap2_y_upper",
                            ),
    sel_ap2_x_left  = device("devices.tango.Motor",
                             description = "selector jj-xray aperture left",
                             tangodevice = tango_base + "fzjs7/sel_ap2_x_left",
                             unit = "mm",
                             precision = 0.1,
                             lowlevel = True,
                            ),
    sel_ap2_x_right = device("devices.tango.Motor",
                             description = "selector jj-xray aperture right",
                             tangodevice = tango_base + "fzjs7/sel_ap2_x_right",
                             unit = "mm",
                             precision = 0.1,
                             lowlevel = True,
                            ),
    sel_ap2_y_upper = device("devices.tango.Motor",
                             description = "selector jj-xray aperture upper",
                             tangodevice = tango_base + "fzjs7/sel_ap2_y_upper",
                             unit = "mm",
                             precision = 0.1,
                             lowlevel = True,
                            ),
    sel_ap2_y_lower = device("devices.tango.Motor",
                             description = "selector jj-xray aperture lower",
                             tangodevice = tango_base + "fzjs7/sel_ap2_y_lower",
                             unit = "mm",
                             precision = 0.1,
                             lowlevel = True,
                            ),
)
