# -*- coding: utf-8 -*-

description = 'Virtual mirror area setup'
group = 'lowlevel'
display_order = 30

devices = dict(
    mir_x           = device('kws1.virtual.Standin',
                             description = 'mirror x-table',
                            ),
    mir_y           = device('kws1.virtual.Standin',
                             description = 'mirror y-hub',
                            ),
    mir_tilt        = device('kws1.virtual.Standin',
                             description = 'mirror area',
                            ),
    mir_ap1         = device('devices.generic.Slit',
                             description = 'jj-xray aperture in front of mirror',
                             coordinates = 'opposite',
                             opmode = 'offcentered',
                             left = 'mir_ap1_x_left',
                             right = 'mir_ap1_x_right',
                             bottom = 'mir_ap1_y_lower',
                             top = 'mir_ap1_y_upper',
                            ),
    mir_ap1_x_left  = device('kws1.virtual.Standin',
                             description = 'aperture in front of mirror left',
                             lowlevel = True,
                            ),
    mir_ap1_x_right = device('kws1.virtual.Standin',
                             description = 'aperture in front of mirror right',
                             lowlevel = True,
                            ),
    mir_ap1_y_upper = device('kws1.virtual.Standin',
                             description = 'aperture in front of mirror upper',
                             lowlevel = True,
                            ),
    mir_ap1_y_lower = device('kws1.virtual.Standin',
                             description = 'aperture in front of mirror lower',
                             lowlevel = True,
                            ),
    mir_ap2         = device('devices.generic.Slit',
                             description = 'jj-xray aperture behind mirror',
                             coordinates = 'opposite',
                             opmode = 'offcentered',
                             left = 'mir_ap2_x_left',
                             right = 'mir_ap2_x_right',
                             bottom = 'mir_ap2_y_lower',
                             top = 'mir_ap2_y_upper',
                            ),
    mir_ap2_x_left  = device('kws1.virtual.Standin',
                             description = 'aperture behind mirror left',
                             lowlevel = True,
                            ),
    mir_ap2_x_right = device('kws1.virtual.Standin',
                             description = 'aperture behind mirror right',
                             lowlevel = True,
                            ),
    mir_ap2_y_upper = device('kws1.virtual.Standin',
                             description = 'aperture behind mirror upper',
                             lowlevel = True,
                            ),
    mir_ap2_y_lower = device('kws1.virtual.Standin',
                             description = 'aperture behind mirror lower',
                             lowlevel = True,
                            ),
)
