description = 'ZEBRA slits'

pvpref = 'SQ:ZEBRA:mcu4:'
snpref = 'SQ:ZEBRA:mcu2:'

devices = dict(
    s1hl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 left',
        motorpv = pvpref + 'S1HL',
        errormsgpv = pvpref + 'S1HL-MsgTxt',
        precision = 0.5,
    ),
    s1hr = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 right',
        motorpv = pvpref + 'S1HR',
        errormsgpv = pvpref + 'S1HR-MsgTxt',
        precision = 0.5,
    ),
    s1vt = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 top',
        motorpv = pvpref + 'S1VT',
        errormsgpv = pvpref + 'S1VT-MsgTxt',
        precision = 0.5,
    ),
    s1vb = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 bottom',
        motorpv = pvpref + 'S1VB',
        errormsgpv = pvpref + 'S1VB-MsgTxt',
        precision = 0.5,
    ),
    s2hl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 2 left',
        motorpv = pvpref + 'S2HL',
        errormsgpv = pvpref + 'S2HL-MsgTxt',
        precision = 0.5,
    ),
    s2hr = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 2 right',
        motorpv = pvpref + 'S2HR',
        errormsgpv = pvpref + 'S2HR-MsgTxt',
        precision = 0.5,
    ),
    s2vt = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 2 top',
        motorpv = pvpref + 'S2VT',
        errormsgpv = pvpref + 'S2VT-MsgTxt',
        precision = 0.5,
    ),
    s2vb = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Slit 2 bottom',
        motorpv = pvpref + 'S2VB',
        errormsgpv = pvpref + 'S2VB-MsgTxt',
        precision = 0.5,
    ),
    snv = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Nose slit vertical',
        motorpv = snpref + 'SNV',
        errormsgpv = snpref + 'SNV-MsgTxt',
        precision = 0.5,
    ),
    snh = device('nicos_ess.devices.epics.motor.EpicsMotor',
        description = 'Nose slit horizontal',
        motorpv = snpref + 'SNH',
        errormsgpv = snpref + 'SNH-MsgTxt',
        precision = 0.5,
    ),
    slit1 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 1 with left, right, bottom and top motors',
        opmode = '4blades',
        left = 's1hl',
        right = 's1hr',
        top = 's1vt',
        bottom = 's1vb',
        visibility = (),
    ),
    slit1_opening = device('nicos_sinq.amor.devices.slit.SlitOpening',
        description = 'Slit 1 opening controller',
        slit = 'slit1'
    ),
    slit1_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Slit 1 width controller',
        slit = 'slit1',
        unit = 'mm',
    ),
    slit2 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2 with left, right, bottom and top motors',
        opmode = '4blades',
        left = 's2hl',
        right = 's2hr',
        top = 's2vt',
        bottom = 's2vb',
        visibility = (),
    ),
    slit2_opening = device('nicos_sinq.amor.devices.slit.SlitOpening',
        description = 'Slit 2 opening controller',
        slit = 'slit2'
    ),
    slit2_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Slit 2 width controller',
        slit = 'slit2',
        unit = 'mm',
    ),
    snvm = device('nicos_sinq.devices.interpolatedmotor.InterpolatedMotor',
        description = 'Interpolated logical vertical nose slit motor',
        raw_motor = 'snv',
        target_positions = [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17
        ],
        raw_positions = [
            8.65, 10.54, 12.68, 14.94, 17.20, 19.58, 21.97, 24.48, 27.12, 29.94,
            32.89, 36.16, 39.17, 43.88, 48.91, 55.69, 71.10
        ],
        unit = 'mm',
    ),
    snhm = device('nicos_sinq.devices.interpolatedmotor.InterpolatedMotor',
        description = 'Interpolated logical horizontal nose slit motor',
        raw_motor = 'snh',
        target_positions = [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19
        ],
        raw_positions = [
            2, 4, 6.22, 8.51, 10.8, 13.17, 15.60, 18.11, 20.69, 23.41, 26.20,
            29.14, 32.29, 35.66, 39.31, 43.32, 48.05, 53.99, 65.67
        ],
        unit = 'mm',
    ),
)
