description = 'Monochromator tower devices'

group = 'lowlevel'

nethost = 'kompasshw.kompass.frm2'
tango_base = 'tango://kompasshw.kompass.frm2:10000/kompass/'

devices = dict(
    # A1
    mth_m = device('nicos.devices.tango.Motor',
                   description = 'A1 motor',
                   tangodevice = tango_base + 'a1/motor',
                   abslimits = (-10, 70),
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mth_c = device('nicos.devices.tango.Sensor',
                   description = 'A1 coder',
                   tangodevice = tango_base + 'a1/coder',
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mth = device('nicos.devices.generic.Axis',
                 description = 'mth (alias A1)',
                 motor = 'mth_m',
                 coder = 'mth_c',
                 fmtstr = '%.3f',
                 precision = 0.001,
                ),
    # A2
    mtt_m = device('nicos.devices.taco.Motor',
                   description = 'A2 motor',
                   tacodevice = '//%s/kompass/a2/motor' % nethost,
                   abslimits = (-10, 70),
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mtt_c = device('nicos.devices.taco.Coder',
                   description = 'A2 coder',
                   tacodevice = '//%s/kompass/a2/coder' % nethost,
                   fmtstr = '%.4f',
                   lowlevel = True,
                  ),
    mtt = device('nicos.devices.generic.Axis',
                 description = 'mtt (alias A2)',
                 motor = 'mtt_m',
                 coder = 'mtt_c',
                 fmtstr = '%.4f',
                 precision = 0.001,
                ),
    mx_m = device('nicos.devices.tango.Motor',
                  description = 'Monochromator table X motor',
                  tangodevice = tango_base + 'monox/motor',
                  fmtstr = '%.2f',
                  lowlevel = True,
                  abslimits = (-5, 5),
                 ),
    mx_c = device('nicos.devices.tango.Sensor',
                  description = 'Monochromator table X coder',
                  tangodevice = tango_base + 'monox/coder',
                  fmtstr = '%.2f',
                  lowlevel = True,
                 ),
    mx = device('nicos.devices.generic.Axis',
                description = 'Monochromator table X',
                motor = 'mx_m',
                coder = 'mx_c',
                fmtstr = '%.2f',
                precision = 0.05,
               ),
    my_m = device('nicos.devices.tango.Motor',
                  description = 'Monochromator table Y motor',
                  tangodevice = tango_base + 'monoy/motor',
                  fmtstr = '%.2f',
                  lowlevel = True,
                  abslimits = (-5, 5),
                 ),
    my_c = device('nicos.devices.tango.Sensor',
                  description = 'Monochromator table Y coder',
                  tangodevice = tango_base + 'monoy/coder',
                  fmtstr = '%.2f',
                  lowlevel = True,
                 ),
    my = device('nicos.devices.generic.Axis',
                description = 'Monochromator table Y',
                motor = 'my_m',
                coder = 'my_c',
                fmtstr = '%.2f',
                precision = 0.05,
               ),
    mc_m = device('nicos.devices.taco.Motor',
                  description = 'Monochromator table cradle motor',
                  tacodevice = '//%s/kompass/monoc/motor' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    mc_c = device('nicos.devices.taco.Coder',
                  description = 'Monochromator table cradle coder',
                  tacodevice = '//%s/kompass/monoc/coder' % nethost,
                  fmtstr = '%.1f',
                  lowlevel = True,
                 ),
    mc = device('nicos.devices.generic.Axis',
                description = 'Monochromator table cradle',
                motor = 'mc_m',
                coder = 'mc_m',  # 'mc_c',
                fmtstr = '%.1f',
                precision = 0.05,
               ),
    mfv_m = device('nicos.devices.taco.Motor',
                   description = 'Monochromator vertically focussing motor',
                   tacodevice = '//%s/kompass/mfv/motor' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                   abslimits = (-0.3, 1),
                  ),
    mfv_c = device('nicos.devices.taco.Coder',
                   description = 'Monochromator vertically focussing coder',
                   tacodevice = '//%s/kompass/mfv/coder' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                  ),
    mfv = device('nicos.devices.generic.Axis',
                 description = 'Monochromator vertically focussing axis',
                 motor = 'mfv_m',
                 coder = 'mfv_c',
                 fmtstr = '%.2f',
                 precision = 0.01,
                ),
    mfh_m = device('nicos.devices.taco.Motor',
                   description = 'Monochromator horizontally focussing motor',
                   tacodevice = '//%s/kompass/mfh/motor' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                   abslimits = (-0.3, 1),
                  ),
    mfh_c = device('nicos.devices.taco.Coder',
                   description = 'Monochromator horizontally focussing coder',
                   tacodevice = '//%s/kompass/mfh/coder' % nethost,
                   fmtstr = '%.2f',
                   lowlevel = True,
                  ),
    mfh = device('nicos.devices.generic.Axis',
                 description = 'Monochromator horizontally focussing axis',
                 motor = 'mfh_m',
                 coder = 'mfh_c',
                 fmtstr = '%.2f',
                 precision = 0.01,
                ),
)
