description = 'Sample table devices'

group = 'lowlevel'

tango_base = 'tango://kompasshw.kompass.frm2:10000/kompass/'

devices = dict(
    # A3
    sth_st_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/sth_m',
        fmtstr = '%.4f',
        lowlevel = True,
    ),
    # currently broken
    #sth_st_c = device('nicos.devices.tango.Sensor',
    #    tangodevice = tango_base + 'sample/sth_c',
    #    fmtstr = '%.4f',
    #    lowlevel = True,
    #),
    sth_st = device('nicos.devices.generic.Axis',
        description = 'sample theta (A3)',
        motor = 'sth_st_m',
        coder = 'sth_st_m',
        fmtstr = '%.3f',
        precision = 0.001,
    ),
    # A4
    stt_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/stt_m',
        fmtstr = '%.4f',
        lowlevel = True,
    ),
    stt_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'sample/stt_c',
        fmtstr = '%.4f',
        lowlevel = True,
    ),
    air_sample = device('nicos.devices.tango.DigitalOutput',
        tangodevice = tango_base + 'aircontrol/plc_airpads_detector',
        lowlevel = True,
    ),
    stt = device('nicos_mlz.mira.devices.axis.HoveringAxis',
        description = 'secondary spectrometer angle (A4)',
        motor = 'stt_m',
        coder = 'stt_c',
        startdelay = 2,
        stopdelay = 2,
        switch = 'air_sample',
        switchvalues = (0, 1),
        fmtstr = '%.3f',
        precision = 0.001,
    ),
    sx_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/sx_m',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    sx_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'sample/sx_c',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    sx = device('nicos.devices.generic.Axis',
        description = 'sample table X',
        motor = 'sx_m',
        coder = 'sx_c',
        fmtstr = '%.2f',
        precision = 0.05,
    ),
    sy_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/sy_m',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    sy_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'sample/sy_c',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    sy = device('nicos.devices.generic.Axis',
        description = 'sample table Y',
        motor = 'sy_m',
        coder = 'sy_c',
        fmtstr = '%.2f',
        precision = 0.05,
    ),
    scx_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/scx_m',
        fmtstr = '%.1f',
        lowlevel = True,
    ),
    # currently unused
    #scx_c = device('nicos.devices.tango.Sensor',
    #    tangodevice = tango_base + 'sample/scx_c',
    #    fmtstr = '%.1f',
    #    lowlevel = True,
    #),
    scx = device('nicos.devices.generic.Axis',
        description = 'sample table cradle X',
        motor = 'scx_m',
        coder = 'scx_m',
        fmtstr = '%.1f',
        precision = 0.05,
    ),
    scy_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'sample/scy_m',
        fmtstr = '%.1f',
        lowlevel = True,
    ),
    # currently unused
    #scy_c = device('nicos.devices.tango.Sensor',
    #    tangodevice = tango_base + 'sample/scy_c',
    #    fmtstr = '%.1f',
    #    lowlevel = True,
    #),
    scy = device('nicos.devices.generic.Axis',
        description = 'sample table cradle Y',
        motor = 'scy_m',
        coder = 'scy_m',
        fmtstr = '%.1f',
        precision = 0.05,
    ),
)
