description = 'Selene support stages'

display_order = 81

pvprefix_s1 = 'SQ:AMOR:turboPmac1:'
pvprefix_s2 = 'SQ:AMOR:turboPmac2:'

devices = dict(
    s1_height = device('nicos_sinq.devices.epics.motor.SinqMotor',
                       description = 'TODO',
                       motorpv = pvprefix_s1 + 's1_height',
                       visibility = ('devlist', 'metadata', 'namespace'),
                       fmtstr = '%.4f',
                       unit='mm',
                       requires = {'level': 'admin'},
                       ),
    s1_inclination = device('nicos_sinq.devices.epics.motor.SinqMotor',
                            description = 'TODO',
                            motorpv = pvprefix_s1 + 's1_inclination',
                            visibility = ('devlist', 'metadata', 'namespace'),
                            fmtstr = '%.4f',
                            unit='degree',
                            requires = {'level': 'admin'},
                            ),
    s1_o11 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 1.1',
                    motorpv = pvprefix_s1 + 's1_o11',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_o12 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 1.2',
                    motorpv = pvprefix_s1 + 's1_o12',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_o21 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 2.1',
                    motorpv = pvprefix_s1 + 's1_o21',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_o22 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 2.2',
                    motorpv = pvprefix_s1 + 's1_o22',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_o31 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 3.1',
                    motorpv = pvprefix_s1 + 's1_o31',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_o32 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 1 support stage 3.2',
                    motorpv = pvprefix_s1 + 's1_o32',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_rebase_num = device('nicos.devices.epics.pyepics.pyepics.EpicsDigitalMoveable',
                           description = 'Set this device to any value to trigger a normalization of the offsets.',
                           readpv = pvprefix_s1 + 's1_height:Normalize',
	                   writepv = pvprefix_s1 + 's1_height:Normalize',
                           visibility=(),
                           requires = {'level': 'user'},
                           ),
    s1_rebase = device('nicos.devices.generic.switcher.Switcher',
                       description = 'Trigger an offset normalization of the Selene guide. This does not move the motors!',
                       moveable = 's1_rebase_num',
                       mapping = {
                           'Rebase offsets': 1,
                           },
                       precision = 0,
                       visibility=('devlist', 'metadata', 'namespace'),
                       requires = {'level': 'user'},
                       ),
    s1_z11 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o11',
                    readpv = pvprefix_s1 + 's1_o11:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_z12 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o12',
                    readpv = pvprefix_s1 + 's1_o12:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_z21 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o21',
                    readpv = pvprefix_s1 + 's1_o21:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_z22 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o22',
                    readpv = pvprefix_s1 + 's1_o22:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_z31 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o31',
                    readpv = pvprefix_s1 + 's1_o31:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s1_z32 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s1_o32',
                    readpv = pvprefix_s1 + 's1_o32:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_height = device('nicos_sinq.devices.epics.motor.SinqMotor',
                       description = 'TODO',
                       motorpv = pvprefix_s2 + 's2_height',
                       visibility = ('devlist', 'metadata', 'namespace'),
                       fmtstr = '%.4f',
                       unit='mm',
                       requires = {'level': 'admin'},
                       ),
    s2_inclination = device('nicos_sinq.devices.epics.motor.SinqMotor',
                            description = 'TODO',
                            motorpv = pvprefix_s2 + 's2_inclination',
                            visibility = ('devlist', 'metadata', 'namespace'),
                            fmtstr = '%.4f',
                            unit='degree',
                            requires = {'level': 'admin'},
                            ),
    s2_o11 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 1.1',
                    motorpv = pvprefix_s2 + 's2_o11',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_o12 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 1.2',
                    motorpv = pvprefix_s2 + 's2_o12',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_o21 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 2.1',
                    motorpv = pvprefix_s2 + 's2_o21',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_o22 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 2.2',
                    motorpv = pvprefix_s2 + 's2_o22',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_o31 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 3.1',
                    motorpv = pvprefix_s2 + 's2_o31',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_o32 = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'Selene 2 support stage 3.2',
                    motorpv = pvprefix_s2 + 's2_o32',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_rebase_num = device('nicos.devices.epics.pyepics.pyepics.EpicsDigitalMoveable',
                           description = 'Set this device to any value to trigger a normalization of the offsets.',
                           readpv = pvprefix_s2 + 's2_height:Normalize',
	                   writepv = pvprefix_s2 + 's2_height:Normalize',
                           visibility=(),
                           requires = {'level': 'user'},
                           ),
    s2_rebase = device('nicos.devices.generic.switcher.Switcher',
                       description = 'Trigger an offset normalization of the Selene guide. This does not move the motors!',
                       moveable = 's2_rebase_num',
                       mapping = {
                           'Rebase offsets': 1,
                           },
                       precision = 0,
                       visibility=('devlist', 'metadata', 'namespace'),
                       requires = {'level': 'user'},
                       ),
    s2_z11 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o11',
                    readpv = pvprefix_s2 + 's2_o11:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_z12 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o12',
                    readpv = pvprefix_s2 + 's2_o12:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_z21 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o21',
                    readpv = pvprefix_s2 + 's2_o21:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_z22 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o22',
                    readpv = pvprefix_s2 + 's2_o22:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_z31 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o31',
                    readpv = pvprefix_s2 + 's2_o31:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    s2_z32 = device('nicos.devices.epics.pyepics.pyepics.EpicsReadable',
                    description = 'Absolute encoder position of s2_o32',
                    readpv = pvprefix_s2 + 's2_o32:AbsolutePositionRBV',
                    visibility = ('devlist', 'metadata', 'namespace'),
                    fmtstr = '%.4f',
                    pollinterval = 0.5,
                    unit='mm',
                    requires = {'level': 'admin'},
                    ),
    )
