description = 'Setup for the AMOR instrument logic devices'

display_order = 8

includes = [
    'chopper_sim', 'virtual_source', 'diaphragm1', 'diaphragm2', 'sample_stage',
    'diaphragm3', 'detector_stage', 'detector', 'constants'
]

devices = dict(
    distances = device('nicos_sinq.amor.devices.base_defs.Distances',
                       description = 'Parameter class for distances',
                       visibility = ('metadata', 'namespace'),
                       ),
    sx = device('nicos.devices.generic.ReadonlyParamDevice',
                description = 'sample distance',
                device = 'distances',
                parameter = 'sample',
                visibility = ('metadata', 'namespace'),
                ),
    base_defs = device('nicos_sinq.amor.devices.base_defs.AmorBase',
                       description = 'AMOR parameter class',
                       distances = 'distances',
                       d1b = 'd1b',
                       d1t = 'd1t',
                       d2z = 'd2z',
                       d2b = 'd2b',
                       d2t = 'd2t',
                       d3b = 'd3b',
                       d3t = 'd3t',
                       soz = 'soz',
                       som = 'som',
                       d3z = 'd3z',
                       f_zoffset_target = 'f_zoffset_target',
                       s_zoffset_target = 's_zoffset_target',
                       sample_tilt_target = 'sample_tilt_target',
                       det_zoffset = 'det_zoffset',
                       det_nu = 'det_nu',
                       kappa = 'kappa',
                       ka0 = 'ka0',
                       unit = '',
                       visibility = ('metadata', 'namespace'),
                       ),
    div = device('nicos.devices.generic.ParamDevice',
                 description = 'divergence of the incoming beam at the sample position',
                 device = 'base_defs',
                 parameter = 'div',
                 unit = 'deg',
                 copy_status = True,
                 ),
    kad = device('nicos.devices.generic.ParamDevice',
                 description = 'offset of the beam center w.r.t. kappa',
                 device = 'base_defs',
                 parameter = 'kad',
                 unit = 'deg',
                 copy_status = True,
                 ),
    f_zoffset = device('nicos.devices.generic.ParamDevice',
                       description = 'vertical focal point offset',
                       device = 'base_defs',
                       parameter = 'fzoffset',
                       unit = 'mm',
                       copy_status = True,
                       visibility = ('metadata', 'namespace'),
                       ),
    f_zoffset_target = device('nicos.devices.generic.manual.ManualMove',
                              description = 'buffer for the target value of "f_zoffset"',
                              unit = 'mm',
                              abslimits = (-1000, 1000),
                              #default = None,
                              visibility = ('metadata', 'namespace'),
                              ),
    s_zoffset = device('nicos.devices.generic.ParamDevice',
                       description = 'soz used for sample z offset',
                       device = 'base_defs',
                       parameter = 'szoffset',
                       unit = 'mm',
                       copy_status = True,
                       visibility = ('metadata', 'namespace'),
                       ),
    s_zoffset_target = device('nicos.devices.generic.manual.ManualMove',
                              description = 'buffer for the target value of "s_zoffset"',
                              unit = 'mm',
                              abslimits = (-1000, 1000),
                              #default = None,
                              visibility = ('metadata', 'namespace'),
                              ),
    mu = device('nicos.devices.generic.ParamDevice',
                description = 'angle between horizon and sample surface',
                device = 'base_defs',
                parameter = 'mu',
                unit = 'deg',
                maxage = 0.5,
                copy_status = True,
                ),
    sample_tilt_target = device('nicos.devices.generic.manual.ManualMove',
                                description = 'buffer for the target value of "sample_tilt"',
                                unit = 'deg',
                                abslimits = (-10, 10),
                                #default = None,
                                visibility = ('metadata', 'namespace'),
                                ),
    nu = device('nicos.devices.generic.ParamDevice',
                description = 'Angle between horizon and sample-detector',
                device = 'base_defs',
                parameter = 'nu',
                unit = 'deg',
                copy_status = True,
                ),
    monitor_defs = device('nicos_sinq.amor.devices.base_defs.AmorMonitor',
                          description = 'AMOR variables monitor',
                          mu = 'mu',
                          nu = 'nu',
                          kad = 'kad',
                          kappa = 'kappa',
                          pol = 'polarization_config_label',
                          div = 'div',
                          unit = '',
                          visibility = ('metadata', 'namespace'),
                          maxage = 0.5,
                          ),
    alpha_i = device('nicos.devices.generic.ParamDevice',
                     description = 'incident angle on sample',
                     device = 'monitor_defs',
                     parameter = 'alphai',
                     unit = 'deg',
                     copy_status = True,
                     visibility = ('metadata', 'namespace'),
                     ),
    alpha_f = device('nicos.devices.generic.ParamDevice',
                     description = 'final angle on sample',
                     device = 'monitor_defs',
                     parameter = 'alphaf',
                     unit = 'deg',
                     copy_status = True,
                     visibility = ('metadata', 'namespace'),
                     ),
    qz_l = device('nicos.devices.generic.ParamDevice',
                  description = 'low limit of q_z range',
                  device = 'monitor_defs',
                  parameter = 'qzl',
                  unit = '1/angstrom',
                  copy_status = True,
                  visibility = ('metadata', 'namespace'),
                  ),
    qz_h = device('nicos.devices.generic.ParamDevice',
                  description = 'high limit of q_z range',
                  device = 'monitor_defs',
                  parameter = 'qzh',
                  unit = '1/angstrom',
                  copy_status = True,
                  visibility = ('metadata', 'namespace'),
                  ),
    kappa = device('nicos.core.device.DeviceAlias',
                   description = 'dummy to prevent warnings',
                   visibility = ('metadata', 'namespace'),
                   ),

    )
