description = 'Airbus chopper device in SINQ AMOR'

pvprefix = 'SQ:AMOR:chopper:'

devices = dict(
    ch1_speed = device('nicos_sinq.devices.epics.base.EpicsAnalogMoveableSinq',
        description = 'Speed of the master chopper',
        readpv = pvprefix + 'DCU1:Speed',
        writepv = pvprefix + 'DCU1:Speed:SP',
    ),
    ch1_position = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Position of the master chopper',
        readpv = pvprefix + 'DCU1:Position',
    ),
    ch1_flags = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Flags of the master chopper',
        readpv = pvprefix + 'DCU1:Flags',
        fmtstr = '%d',
        visibility = (),
    ),
    ch1_state = device('nicos_sinq.devices.epics.base.EpicsStringReadableSinq',
        description = 'State of the master chopper',
        readpv = pvprefix + 'DCU1:State',
    ),
    ch1_motor_temperature = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Motor temperature of the master chopper',
        readpv = pvprefix + 'DCU1:MotorTemp',
        visibility = (),
    ),
    ch1_drive_temperature = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Drive temperature of the master chopper',
        readpv = pvprefix + 'DCU1:DriveTemp',
        visibility = (),
    ),
    ch1_command = device('nicos.devices.epics.pyepics.EpicsStringMoveable',
        description = 'Command to the master chopper',
        readpv = pvprefix + 'DCU1:Command:SP',
        writepv = pvprefix + 'DCU1:Command:SP',
        visibility = (),
    ),
    ch2_speed = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Speed of the master chopper',
        readpv = pvprefix + 'DCU2:Speed',
    ),
    ch2_position = device('nicos_sinq.devices.epics.base.EpicsAnalogMoveableSinq',
        description = 'Position of the master chopper',
        readpv = pvprefix + 'DCU2:Position',
        writepv = pvprefix + 'DCU2:Position:SP',
    ),
    ch2_gear_ratio = device('nicos_sinq.devices.epics.base.EpicsDigitalMoveableSinq',
        description = 'Position of the master chopper',
        readpv = pvprefix + 'DCU2:GearRatio',
        writepv = pvprefix + 'DCU2:GearRatio:SP',
    ),
    ch2_flags = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Flags of the master chopper',
        readpv = pvprefix + 'DCU2:Flags',
        fmtstr = '%d',
        visibility = (),
    ),
    ch2_state = device('nicos_sinq.devices.epics.base.EpicsStringReadableSinq',
        description = 'State of the master chopper',
        readpv = pvprefix + 'DCU2:State',
    ),
    ch2_motor_temperature = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Motor temperature of the master chopper',
        readpv = pvprefix + 'DCU2:MotorTemp',
        visibility = (),
    ),
    ch2_drive_temperature = device('nicos_sinq.devices.epics.base.EpicsReadableSinq',
        description = 'Drive temperature of the master chopper',
        readpv = pvprefix + 'DCU2:DriveTemp',
        visibility = (),
    ),
    ch2_command = device('nicos.devices.epics.pyepics.EpicsStringMoveable',
        description = 'Command to the master chopper',
        readpv = pvprefix + 'DCU2:Command:SP',
        writepv = pvprefix + 'DCU2:Command:SP',
        visibility = (),
    ),
)
