description = 'Multiblade detector'

display_order = 15

sysconfig = dict(datasinks = ['jbi_liveview', 'FileWriterControl'],)

includes = ['polariser']

#sysconfig = dict(datasinks = ['jbi_liveview', 'synchronize_daq'],)

pvprefix = 'SQ:AMOR:SPC'

devices = dict(
    #det_image = device('nicos_sinq.devices.just_bin_it.JustBinItImage',
    #                   description = 'Detector image channel',
    #                   hist_topic = configdata('config.AMOR_HIST_TOPIC'),
    #                   data_topic = configdata('config.DETECTOR_EVENTS_TOPIC'),
    #                   command_topic = configdata('config.HIST_COMMANDS_TOPIC'),
    #                   brokers = configdata('config.KAFKA_BROKERS'),
    #                   unit = 'evts',
    #                   hist_type = '2-D DET',
    #                   det_width = 32,
    #                   det_height = 448,
    #                   det_range = (0, 32*448),
    #                   pollinterval = 0.5,
    #                   visibility = ('metadata', 'namespace'),
    #                   ),
    hist_yz = device('nicos_sinq.devices.just_bin_it.JustBinItImage',
                     description = 'Detector pixel histogram over all times',
                     hist_topic = configdata('config.DETECTOR_HISTOGRAM_YZ_TOPIC'),
                     data_topic = configdata('config.DETECTOR_EVENTS_TOPIC'),
                     command_topic = configdata('config.HIST_COMMANDS_TOPIC'),
                     brokers = configdata('config.KAFKA_BROKERS'),
                     unit = 'evts',
                     hist_type = '2-D SANSLLB',
                     det_width = 446,
                     det_height = 64,
                     visibility = ('metadata', 'namespace'),
                     ),
    hist_tofz = device('nicos_sinq.devices.just_bin_it.JustBinItImage',
                       description = 'Detector time of flight vs. z-pixel histogram over all y-values',
                       hist_topic = configdata('config.DETECTOR_HISTOGRAM_TOFZ_TOPIC'),
                       data_topic = configdata('config.DETECTOR_EVENTS_TOPIC'),
                       command_topic = configdata('config.HIST_COMMANDS_TOPIC'),
                       brokers = configdata('config.KAFKA_BROKERS'),
                       unit = 'evts',
                       hist_type = '2-D SANSLLB',
                       det_width = 118,
                       det_height = 446,
                       visibility = ('metadata', 'namespace'),
                       ),
    roi1 = device('nicos_sinq.amor.devices.roi_tmp.CutROI',
                  description = "ROI 1",
                  raw_image = 'hist_yz',
                  roi = (0, 200, 64, 46),
                  fmtstr = '%d cts (%.1f cpm)',
                  ),
    progress = device('nicos.devices.generic.manual.ManualMove',
                      description = 'Shows the progress of the current count',
                      default = 0,
                      unit = '%',
                      abslimits = [0, 200],
                      fmtstr = '%5.1f',
                      ),
    elapsedtime = device('nicos_sinq.devices.epics.sinqdaq.DAQTime',
                         daqpvprefix = pvprefix,
                         fmtstr = '%7.1f',
                         unit = 'sec',
                         ),
    proton_monitor = device('nicos_sinq.devices.epics.sinqdaq.DAQChannel',
                            description = 'Proton counter channel',
                            daqpvprefix = pvprefix,
                            channel = 1,
                            type = 'monitor',
                            unit = 'uA',
                            fmtstr = '%4.f',
                            ),
    preset = device('nicos_sinq.devices.epics.sinqdaq.DAQPreset',
                    description = 'Time/Count Preset',
                    daqpvprefix = pvprefix,
                    channels = ['proton_monitor'],
                    time_channel = ['elapsedtime'],
                    ),
    ThresholdChannel = device('nicos_sinq.devices.epics.sinqdaq.DAQMinThresholdChannel',
                              daqpvprefix = pvprefix,
                              channels = ['proton_monitor'],
                              ),
    Threshold = device('nicos_sinq.devices.epics.sinqdaq.DAQMinThreshold',
                       daqpvprefix = pvprefix,
                       min_rate_channel = 'ThresholdChannel',
                       ),
    det = device('nicos_sinq.amor.devices.detector.PolarizationSwitchDetector',
                 description = 'AMOR detector',
                 unit = '',
                 timers = ['elapsedtime'],
                 monitors = ['preset', 'proton_monitor'],
                 preset = 'preset',
                 progress = 'progress',
                 liveinterval = 5.0,
                 counters = ['roi1'],
                 visibility = ('metadata', 'namespace'),
                 polarization = 'polarization',
                 filewritercontrol = 'FileWriterControl',
                 ),
    acquisition_filter = device('nicos.devices.generic.ReadonlyParamDevice',
                     description = 'Acquisition state used for filtering in the data file',
                     device = 'det',
                     parameter = 'acquisition_filter',
                     unit = '',
                     copy_status = True,
                     visibility = ('metadata', 'namespace'),
                     ),
    proton_current = device('nicos.devices.epics.EpicsReadable',
                            description = 'Proton current',
                            readpv = pvprefix + ':R1',
                            fmtstr = '%4.f',
                            ),
    detector_rate = device('nicos_sinq.amor.devices.detector.DetectorRate',
                            description = 'integral detector count rate',
                            brokers = configdata('config.KAFKA_BROKERS'),
                            topic = configdata('config.DETECTOR_RATE_TOPIC'),
                            fmtstr = '%.1f',
                            unit = '/s',
                            ),
    FileWriterStatus = device('nicos_sinq.devices.datasinks.file_writer.FileWriterStatus',
                              description = 'Status of the file-writer',
                              brokers = configdata('config.KAFKA_BROKERS'),
                              statustopic = configdata('config.FILEWRITER_STATUS_TOPIC'),
                              unit = '',
                              ),
    FileWriterControl = device('nicos_sinq.devices.datasinks.sinq_datasinks.SinqFileWriterControlSink',
                               description = 'Control for the file-writer',
                               brokers = configdata('config.KAFKA_BROKERS'),
                               pool_topic = configdata('config.FILEWRITER_POOL_TOPIC'),
                               status = 'FileWriterStatus',
                               nexus = 'NexusStructure',
                               file_output_dir = configdata('config.DATA_PATH'),
                               filenametemplate = ['amor%(year)sn%(pointcounter)06d.hdf'],
                               visibility = ('metadata', 'namespace'),
                               one_file_per_scan = False,
                               ),
    NexusStructure = device('nicos_sinq.amor.devices.datasinks.AmorStructureTemplate',
                            description = 'Provides the NeXus structure',
                            templatesmodule = 'nicos_sinq.amor.nexus.nexus_templates',
                            templatename = 'amor_streaming',
                            ),
    jbi_liveview = device('nicos.devices.datasinks.LiveViewSink'),
    synchronize_daq = device('nicos_sinq.amor.devices.datasinks.SyncDaqSink',
                             settypes={'scan'}),
    )

startupcode = '''
SetDetectors(det)
'''
