description = 'Detector stage'

display_order = 76

pvprefix = 'SQ:AMOR:turboPmac3:'

devices = dict(
    det_nu = device('nicos_sinq.devices.epics.motor.SinqMotor',
                    description = 'detector angle wrt. horizon',
                    motorpv = pvprefix + 'det_nu',
                    visibility = ('metadata', 'namespace'),
                    unit='degree',
                    ),
    det_zoffset = device('nicos_sinq.devices.epics.motor.SinqMotor',
                         description = 'define coz zero position - only for instrument alignment',
                         motorpv = pvprefix + 'det_zoffset',
                         visibility = ('metadata', 'namespace'),
                         unit='mm',
                         precision=0.005,
                         ),
    det_com_origin = device('nicos.devices.epics.pva.epics_devices.EpicsReadable',
                            readpv = pvprefix + 'det_nu:Origin',
                            requires = {'level': 'admin'},
                            visibility = ('metadata', 'namespace'),
                            ),
    det_coz_origin = device('nicos.devices.epics.pva.epics_devices.EpicsReadable',
                            readpv = pvprefix + 'det_zoffset:Origin',
                            requires = {'level': 'admin'},
                            visibility = ('metadata', 'namespace'),
                            ),
    det_ftz_origin = device('nicos.devices.epics.pva.epics_devices.EpicsReadable',
                            readpv = pvprefix + 'det_ftz:Origin',
                            requires = {'level': 'admin'},
                            visibility = ('metadata', 'namespace'),
                            ),
    det_com_corr = device('nicos.devices.epics.pva.epics_devices.EpicsAnalogMoveable',
                          readpv = pvprefix + 'det_nu:AdjustOrigin',
                          writepv = pvprefix + 'det_nu:AdjustOrigin',
                          requires = {'level': 'admin'},
                          visibility = ('metadata', 'namespace'),
                          ),
    det_coz_corr = device('nicos.devices.epics.pva.epics_devices.EpicsAnalogMoveable',
                          readpv = pvprefix + 'det_zoffset:AdjustOrigin',
                          writepv = pvprefix + 'det_zoffset:AdjustOrigin',
                          requires = {'level': 'admin'},
                          visibility = ('metadata', 'namespace'),
                          ),
    det_ftz_corr = device('nicos.devices.epics.pva.epics_devices.EpicsAnalogMoveable',
                          readpv = pvprefix + 'det_ftz:AdjustOrigin',
                          writepv = pvprefix + 'det_ftz:AdjustOrigin',
                          requires = {'level': 'admin'},
                          visibility = ('metadata', 'namespace'),
                          ),
    det_mount_pos_num = device('nicos_sinq.devices.epics.extensions.EpicsControlledDigitalMoveable',
                               readpv = pvprefix + 'det_nu:ChangingStateRBV_int',
                               writepv = pvprefix + 'det_nu:ChangeState',
                               targetpv = pvprefix + 'det_nu:ChangeStateRBV',
                               readypv = pvprefix + 'det_nu.DMOV',
                               visibility=(),
                               requires = {'level': 'admin'},
                               ),
    det_mount_pos = device('nicos.devices.generic.switcher.Switcher',
                           description = 'Switch between flight-tube mount position and operation state',
                           moveable = 'det_mount_pos_num',
                           mapping = {
                               'working state': 0,
                               'mount position': 1,
                               },
                           precision = 0,
                           requires = {'level': 'admin'},
                           visibility = ('metadata', 'namespace'),
                           ),
    )

