description = 'Slit 2 devices in the SINQ AMOR.'

display_order = 45

pvprefix = 'SQ:AMOR:mmac1:'

devices = dict(
    d2t = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Slit 2 top blade',
        motorpv = pvprefix + 'd2t',
        errormsgpv = pvprefix + 'd2t-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d2b = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Slit 2 bottom blade',
        motorpv = pvprefix + 'd2b',
        errormsgpv = pvprefix + 'd2b-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d2l = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Slit 2 left blade',
        motorpv = pvprefix + 'd2l',
        errormsgpv = pvprefix + 'd2l-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d2r = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Slit 2 right blade',
        motorpv = pvprefix + 'd2r',
        errormsgpv = pvprefix + 'd2r-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d2z = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        description = 'Slit 2 z position',
        motorpv = pvprefix + 'd2z',
        errormsgpv = pvprefix + 'd2z-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    slit2 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2 with left, right, bottom and top motors',
        opmode = '4blades',
        left = 'd2l',
        right = 'd2r',
        top = 'd2t',
        bottom = 'd2b',
        visibility = (),
    ),
)
