description = 'Slit 1 devices in the SINQ AMOR.'

display_order = 35

pvprefix = 'SQ:AMOR:mcu4:'

devices = dict(
    d1t = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 top blade',
        motorpv = pvprefix + 'd1t',
        errormsgpv = pvprefix + 'd1t-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d1b = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 bottom blade',
        motorpv = pvprefix + 'd1b',
        errormsgpv = pvprefix + 'd1b-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d1l = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 left blade',
        motorpv = pvprefix + 'd1l',
        errormsgpv = pvprefix + 'd1l-MsgTxt',
        visibility = ('devlist', 'metadata', 'namespace'),
        precision = .01,
        can_disable = True,
    ),
    d1r = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        description = 'Slit 1 right blade',
        motorpv = pvprefix + 'd1r',
        errormsgpv = pvprefix + 'd1r-MsgTxt',
        precision = .01,
        visibility = ('devlist', 'metadata', 'namespace'),
        can_disable = True,
    ),
    slit1 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 1 with left, right, bottom and top motors',
        opmode = '4blades_opposite',
        left = 'd1l',
        right = 'd1r',
        top = 'd1t',
        bottom = 'd1b',
        visibility = ('metadata', 'namespace'),
    ),
)
