description = 'Slit 1 devices in the SINQ AMOR.'

display_order = 35

pvprefix = 'SQ:AMOR:turboPmac4:'

devices = dict(
    d1t = device('nicos_sinq.devices.epics.motor.SinqMotor',
                 description = 'Slit 1 top blade',
                 motorpv = pvprefix + 'd1t',
                 visibility = ('devlist', 'metadata', 'namespace'),
                 fmtstr = '%4.1f',
                 unit = 'mm',
                 valid_pos_after_reference = True,
                 ),
    d1b = device('nicos_sinq.devices.epics.motor.SinqMotor',
                 description = 'Slit 1 bottom blade',
                 motorpv = pvprefix + 'd1b',
                 visibility = ('devlist', 'metadata', 'namespace'),
                 fmtstr = '%4.1f',
                 unit = 'mm',
                 valid_pos_after_reference = True,
                 ),
    d1l = device('nicos_sinq.devices.epics.motor.SinqMotor',
                 description = 'Slit 1 left blade',
                 motorpv = pvprefix + 'd1l',
                 visibility = ('devlist', 'metadata', 'namespace'),
                 fmtstr = '%4.1f',
                 unit = 'mm',
                 valid_pos_after_reference = True,
                 ),
    d1r = device('nicos_sinq.devices.epics.motor.SinqMotor',
                 description = 'Slit 1 right blade',
                 motorpv = pvprefix + 'd1r',
                 visibility = ('devlist', 'metadata', 'namespace'),
                 fmtstr = '%4.1f',
                 unit = 'mm',
                 valid_pos_after_reference = True,
                 ),
    #slit1 = device('nicos.devices.generic.slit.Slit',
    #               description = 'Slit 1 with left, right, bottom and top motors',
    #               opmode = '4blades_opposite',
    #               left = 'd1l',
    #               right = 'd1r',
    #               top = 'd1t',
    #               bottom = 'd1b',
    #               visibility = ('metadata', 'namespace'),
    #               ),
    )
