description = 'Slit 2 devices in the SINQ AMOR.'

pvprefix = 'SQ:AMOR:motc:'

includes = ['logical_motors']

devices = dict(
    d2t = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 top blade',
        motorpv = pvprefix + 'd2t',
        errormsgpv = pvprefix + 'd2t-MsgTxt',
        lowlevel = True,
    ),
    d2b = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 bottom blade',
        motorpv = pvprefix + 'd2b',
        # errormsgpv = pvprefix + 'd2b-MsgTxt',
        lowlevel = True,
    ),
    d2l = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 left blade',
        motorpv = pvprefix + 'd2l',
        # errormsgpv = pvprefix + 'd2l-MsgTxt',
        lowlevel = True,
    ),
    d2r = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 right blade',
        motorpv = pvprefix + 'd2r',
        # errormsgpv = pvprefix + 'd2r-MsgTxt',
        lowlevel = True,
    ),
    d2z = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 x position',
        motorpv = pvprefix + 'd2z',
        # errormsgpv = pvprefix + 'd2z-MsgTxt',
        lowlevel = True,
    ),
    slit2 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2 with left, right, bottom and top motors',
        opmode = '4blades',
        left = 'd2l',
        right = 'd2r',
        top = 'd2t',
        bottom = 'd2b',
        lowlevel = True
    ),
    d2v = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Vertical slit opening',
        motortype = 'd2v',
        controller = 'controller_slm',
        unit = 'mm'
    ),
    d2h = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Horizontal slit opening ',
        motortype = 'd2h',
        controller = 'controller_slm',
        unit = 'mm'
    ),
    d2d = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Vertical slit displacement',
        motortype = 'd2d',
        controller = 'controller_slm',
        unit = 'mm'
    ),
)
