description = 'Sample table devices for SINQ POLDI OLD.'
excludes = ['sample_old', 'sample_new', 'sample_euler']
pvprefix = 'SQ:POLDI:MCU1:'

devices = dict(
    sa=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table rotation',
               motorpv=f'{pvprefix}SA-NZE',
               errormsgpv=f'{pvprefix}SA-NZE-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    shl=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table X translation',
               motorpv=f'{pvprefix}SHL-ZWICK',
               errormsgpv=f'{pvprefix}SHL-ZWICK-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    shu=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table Y translation',
               motorpv=f'{pvprefix}SHU-ZWICK',
               errormsgpv=f'{pvprefix}SHU-ZWICK-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    sv=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table hub Z translation',
               motorpv=f'{pvprefix}SV',
               errormsgpv=f'{pvprefix}SV-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
 )
