description = 'Sample table devices for SINQ POLDI NEW.'
excludes = ['sample_new', 'sample_old', 'sample_zwick']
pvprefix = 'SQ:POLDI:MCU1:'

devices = dict(
    sa=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table rotation',
               motorpv=f'{pvprefix}SA-NZE',
               errormsgpv=f'{pvprefix}SA-NZE-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    shl=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table X translation',
               motorpv=f'{pvprefix}SHL-NE',
               errormsgpv=f'{pvprefix}SHL-NE-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    shu=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table Y translation',
               motorpv=f'{pvprefix}SHU-NE',
               errormsgpv=f'{pvprefix}SHU-NE-MsgTxt',
               precision = 0.01,
               can_disable = True,
               absolute_encoder = True,
               ),
    sv=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Sample table hub Z translation',
               motorpv=f'{pvprefix}SV',
               errormsgpv=f'{pvprefix}SV-MsgTxt',
               precision = 0.01,
               absolute_encoder = True,
               can_disable = True,
               ),
# Check if the nomenclature here is correct, howcome chi/phi and alpha/beta is mixed.
    chi=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Goniometer Alpha',
               motorpv=f'{pvprefix}CHI-EULER',
               errormsgpv=f'{pvprefix}CHI-EULER-MsgTxt',
               precision = 0.01,
               absolute_encoder = True,
               can_disable = True,
               ),
    phi=device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
               description='Rotation table Beta',
               motorpv=f'{pvprefix}PHI-EULER',
               errormsgpv=f'{pvprefix}PHI-EULER-MsgTxt',
               precision = 0.01,
               absolute_encoder = True,
               can_disable = True,
               ),
 )
