#  -*- coding: utf-8 -*-

description = 'Analysator'

includes = ['system', 'motorbus6']

group = 'lowlevel'

devices = dict(
    # Att and ATH
    st_att = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 60,
        slope = -267.8,
        unit = 'deg',
        abslimits = (-117, 117),
        zerosteps = 500000,
        lowlevel = True,
        confbyte = 104,
        startdelay = 1,
        stopdelay = 2,
    ),
    st_ath = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 59,
        slope = -400,
        unit = 'deg',
        abslimits = (-1, 60), #0 changed by AM 2018.09.07
        zerosteps = 500000,
        lowlevel = True,
        confbyte = 108,
    ),
    co_att = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 91,
        poly = [-124422/2912.7111, 1./2912.7111],
        unit = 'deg',
        circular = -360,
        lowlevel = True,
    ),
    co_ath = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 90,
        poly = [-476397/2912.7111, 1./2912.7111],
        unit = 'deg',
        lowlevel = True,
    ),
    att = device('nicos.devices.generic.Axis',
        description = 'Scattering angle two-theta of analyser',
        motor = 'st_att',
        coder = 'co_att',
        precision = 0.01,
        offset = 0.205, # 90.163 / 05.2017 GE
        # offset = 0.307, # with collimator
        jitter = 0.2,
        dragerror = 1,
        maxtries = 30,
    ),
    ath = device('nicos.devices.generic.Axis',
        description = 'Rocking angle theta of analyser',
        motor = 'st_ath',
        coder = 'co_ath',
        precision = 0.01,
        # offset = -0.678, # with collimator
        offset = -0.551, # -0.442 / 05.2017 GE
        maxtries = 8,
    ),

    # Focusing horizontal for PG analyzer
    st_afpg = device('nicos_mlz.puma.devices.ipc.Motor1',
        bus = 'motorbus6',
        addr = 68,
        slope = 380.5,
        unit = 'deg',
        abslimits = (-6, 75),
        zerosteps = 481618,
        lowlevel = True,
    ),
    co_afpg = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 94,
        poly = [-652.2/98.83, 1./98.83],
        unit = 'deg',
        lowlevel = True,
    ),
    afpg = device('nicos_mlz.puma.devices.FocusAxis',
        description = 'Horizontal focus of PG-analyser',
        motor = 'st_afpg',
        coder = 'co_afpg',
        uplimit = 70,
        lowlimit = -8,
        abslimits = (-6, 75),
        flatpos = 4.92,
        startpos = 4,
        precision = 0.05,  # it was 0.25
        maxtries = 15,
    ),

    # Focusing horizontal for Ge311 Analysator
    st_afge = device('nicos_mlz.puma.devices.ipc.Motor1',
        bus = 'motorbus6',
        addr = 68,
        slope = -380.5,
        unit = 'deg',
        abslimits = (-55, 55),
        zerosteps = 508372.6,
        lowlevel = True,
    ),
    co_afge = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 94,
        poly = [-6262.19/-81.13, 1./-81.13],
        unit = 'deg',
        lowlevel = True,
    ),
    afge = device('nicos_mlz.puma.devices.FocusAxis',
        description = 'Horizontal focus of Ge-analyser',
        motor = 'st_afge',
        coder = 'co_afge',
        uplimit = 55,
        lowlimit = -55,
        abslimits = (-55, 55),
        flatpos = 4.92,
        startpos = 4,
        precision = 0.25,
        maxtries = 15,
    ),

    # Tilt and Translation
    st_atx = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 64,
        slope = -2500,
        unit = 'mm',
        abslimits = (-50, 50),  # (-10.1, 7.6),
        zerosteps = 500000,
        lowlevel = True,
    ),
    co_atx = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 96,
        poly = [-5073/157.3, 1./157.3],
        unit = 'mm',
        lowlevel = True,
    ),
    atx = device('nicos.devices.generic.Axis',
        description = 'Translation of analyser',
        motor = 'st_atx',
        coder = 'co_atx',
        precision = 0.1,
        offset = 0,
        maxtries = 10,
        loopdelay = 1,
    ),
    st_aty = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 63,
        slope = -2500,
        unit = 'mm',
        abslimits = (-50, 50),  # (-7.1, 15),
        zerosteps = 500000,
        lowlevel = True,
    ),
    co_aty = device('nicos_mlz.puma.devices.ipc.Coder',
        bus = 'motorbus6',
        addr = 95,
        poly = [-5026/-157.3, 1./-157.3],
        unit = 'mm',
        lowlevel = True,
    ),
    aty = device('nicos.devices.generic.Axis',
        description = 'Translation of analyser (corrects depth of pg-crystals)',
        motor = 'st_aty',
        coder = 'co_aty',
        precision = 0.1,
        offset = 0,
        maxtries = 10,
        loopdelay = 1,
    ),
    st_agx = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 62,
        slope = -5000,
        unit = 'mm',
        abslimits = (-5.5, 5.5),
        zerosteps = 500000,
        lowlevel = True,
    ),
    agx = device('nicos.devices.generic.Axis',
        description = 'Tilt of analyser (up/down scattering)',
        motor = 'st_agx',
        precision = 0.05,
        offset = 0,
        maxtries = 10,
        backlash = 0.2,
    ),
    st_agy = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus6',
        addr = 61,
        slope = 5000,
        unit = 'mm',
        abslimits = (-5.5, 4.5),
        zerosteps = 500000,
        lowlevel = True,
    ),
    agy = device('nicos.devices.generic.Axis',
        description = 'Tilt of analyser',
        motor = 'st_agy',
        precision = 0.05,
        offset = 0,
        maxtries = 10,
        backlash = 0.2,
    ),
)
