#  -*- coding: utf-8 -*-

description = 'Multianalyzer motors'

includes = ['system', 'motorbus13']

modules = ['nicos_mlz.puma.commands']

group = 'optional'

tr_speed = 15
tr_accel = 30
tr_microstep = 1
tr_slope = -516 * tr_microstep
tr_refswitch = 'low'
tr_refdirection = 'upper'
tr_refstep = 25
tr_zerosteps = 500000

ro_microstep = 4
ro_speed = 42
ro_accel = 30
ro_slope = -118 * ro_microstep  # -1797
ro_refstep = 25

devices = dict(
    # Translations
    st_ta1 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 180,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 125.0# 16491, # 7.021
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta2 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 181,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16493, # 7.022
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta3 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 182,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16495, # 7.023
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta4 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 183,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16501, # 7.0257
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta5 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 184,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16495, # 7.023
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta6 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 185,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16470, # 7.0107
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta7 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 186,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16495, # 7.023
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta8 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 187,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16488, # 7.0194
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta9 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 188,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16498, # 7.024
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta10 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 189,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        refpos = 435500, # 16496, # 7.0234
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    st_ta11 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 190,
        slope = tr_slope,
        unit = 'mm',
        abslimits = (-125, 125),
        zerosteps = tr_zerosteps,
        lowlevel = True,
        refpos = 435500, # 16494, # 7.0223
        refswitch = tr_refswitch,
        refdirection = tr_refdirection,
        refstep = tr_refstep,
        # parkpos = 12,
        refmove = 1000,
        microstep = tr_microstep,
        speed = tr_speed,
        accel = tr_accel,
    ),
    co_ta1 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 204,
        slope = -14.68,
        zerosteps = 2168.6,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta2 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 205,
        slope = -14.73,
        zerosteps = 206.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta3 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 206,
        slope = -14.70,
        zerosteps = 219.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta4 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 207,
        slope = -14.68,
        zerosteps = 199.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta5 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 208,
        slope = -14.70,
        zerosteps = 198.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta6 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 209,
        slope = -14.75,
        zerosteps = 211.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta7 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 210,
        slope = -14.66,
        zerosteps = 193.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta8 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 211,
        slope = -14.75,
        zerosteps = 226.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta9 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 212,
        slope = -14.65,
        zerosteps = 132.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta10 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 213,
        slope = -14.70,
        zerosteps = 256.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta11 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus13',
        addr = 214,
        slope = -14.76,
        zerosteps = 213.24,
        unit = 'mm',
        lowlevel = True,
    ),
    ta1 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 1 translation',
        motor = 'st_ta1',
        # obs = ['co_ta1'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta2 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 2 translation',
        motor = 'st_ta2',
        # obs = ['co_ta2'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta3 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 3 translation',
        motor = 'st_ta3',
        # obs = ['co_ta3'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta4 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 4 translation',
        motor = 'st_ta4',
        # obs = ['co_ta4'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta5 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 5 translation',
        motor = 'st_ta5',
        # obs = ['co_ta5'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta6 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 6 translation',
        motor = 'st_ta6',
        # obs = ['co_ta6'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
                   ),
    ta7 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 7 translation',
        motor = 'st_ta7',
        # obs = ['co_ta7'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta8 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 8 translation',
        motor = 'st_ta8',
        # obs = ['co_ta8'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta9 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 9 translation',
        motor = 'st_ta9',
        # obs = ['co_ta9'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta10 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 10 translation',
        motor = 'st_ta10',
        # obs = ['co_ta10'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),
    ta11 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 11 translation',
        motor = 'st_ta11',
        # obs = ['co_ta11'],
        precision = 0.5,
        offset = 5,
        maxtries = 3,
    ),

    # Rotations
    st_ra1 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 192,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 8537, # 0.814, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra2 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 193,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9560, # 0.245, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra3 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 194,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 7161, # 1.58, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra4 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 195,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9686, # 0.175, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra5 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 196,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9784, # 0.12, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra6 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 197,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9344, # 0.365, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra7 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 198,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 8392, # 0.895, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra8 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 199,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9757, # 0.135, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra9 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 200,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9955, # 0.025, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra10 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 201,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9173, # 0.46, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    st_ra11 = device('nicos_mlz.puma.devices.ipc_puma.ReferenceMotor',
        bus = 'motorbus13',
        addr = 202,
        slope = ro_slope,
        unit = 'deg',
        abslimits = (-60.0, 0.5),
        zerosteps = 10000,
        lowlevel = True,
        refswitch = 'high',
        refdirection = 'upper',
        refpos = 9686, # 0.175, 10000, 0
        refspeed = ro_speed,
        microstep = ro_microstep,
        speed = ro_speed,
        accel = ro_accel,
        refstep = ro_refstep,
    ),
    ra1 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 1 rotation',
        motor = 'st_ra1',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.814,
        maxtries = 3,
    ),
    ra2 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 2 rotation',
        motor = 'st_ra2',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.245,
        maxtries = 3,
    ),
    ra3 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 3 rotation',
        motor = 'st_ra3',
        obs = [],
        precision = 0.01,
        offset = 0, # -1.58,
        maxtries = 3,
    ),
    ra4 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 4 rotation',
        motor = 'st_ra4',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.175,
        maxtries = 3,
    ),
    ra5 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 5 rotation',
        motor = 'st_ra5',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.12,
        maxtries = 3,
    ),
    ra6 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 6 rotation',
        motor = 'st_ra6',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.365,
        maxtries = 3,
    ),
    ra7 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 7 rotation',
        motor = 'st_ra7',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.895,
        maxtries = 3,
    ),
    ra8 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 8 rotation',
        motor = 'st_ra8',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.135,
        maxtries = 3,
    ),
    ra9 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 9 rotation',
        motor = 'st_ra9',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.025,
        maxtries = 3,
    ),
    ra10 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 10 rotation',
        motor = 'st_ra10',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.46,
        maxtries = 3,
    ),
    ra11 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 11 rotation',
        motor = 'st_ra11',
        obs = [],
        precision = 0.01,
        offset = 0, # -0.175,
        maxtries = 3,
    ),
    man = device('nicos_mlz.puma.devices.multianalyzer.PumaMultiAnalyzer',
        description = 'PUMA multi analyzer',
        translations = ['ta1', 'ta2', 'ta3', 'ta4', 'ta5', 'ta6', 'ta7', 'ta8',
                        'ta9', 'ta10', 'ta11'],
        rotations = ['ra1', 'ra2', 'ra3', 'ra4', 'ra5', 'ra6', 'ra7', 'ra8',
                     'ra9', 'ra10', 'ra11'],
    ),
)
