#  -*- coding: utf-8 -*-

description = 'Multidetector motors'

includes = ['system', 'motorbus10']

group = 'lowlevel'

devices = dict(
# Translations
    st_ta1 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 180,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta2 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 181,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta3 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 182,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta4 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 183,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta5 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 184,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta6 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 185,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta7 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 186,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta8 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 187,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta9 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 188,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta10 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 189,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    st_ta11 = device('nicos.devices.vendor.ipc.Motor',
        bus = 'motorbus10',
        addr = 190,
        slope = 2064,
        unit = 'deg',
        abslimits = (-0.1, 250.1),
        zerosteps = 2000,
        lowlevel = True,
    ),
    co_ta1 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 204,
        slope = 14.68,
        zerosteps = 219.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta2 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 205,
        slope = 14.73,
        zerosteps = 206.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta3 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 206,
        slope = 14.70,
        zerosteps = 219.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta4 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 207,
        slope = 14.68,
        zerosteps = 199.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta5 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 208,
        slope = 14.70,
        zerosteps = 198.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta6 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 209,
        slope = 14.75,
        zerosteps = 211.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta7 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 210,
        slope = 14.66,
        zerosteps = 193.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta8 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 211,
        slope = 14.75,
        zerosteps = 226.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta9 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 212,
        slope = 14.65,
        zerosteps = 132.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta10 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 213,
        slope = 14.70,
        zerosteps = 256.24,
        unit = 'mm',
        lowlevel = True,
    ),
    co_ta11 = device('nicos.devices.vendor.ipc.Coder',
        bus = 'motorbus10',
        addr = 214,
        slope = 14.76,
        zerosteps = 213.24,
        unit = 'mm',
        lowlevel = True,
    ),
    ta1 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 1 translation',
        motor = 'st_ta1',
        coder = 'co_ta1',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta2 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 2 translation',
        motor = 'st_ta2',
        coder = 'co_ta2',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta3 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 3 translation',
        motor = 'st_ta3',
        coder = 'co_ta3',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta4 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 4 translation',
        motor = 'st_ta4',
        coder = 'co_ta4',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta5 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 5 translation',
        motor = 'st_ta5',
        coder = 'co_ta5',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta6 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 6 translation',
        motor = 'st_ta6',
        coder = 'co_ta6',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
                   ),
    ta7 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 7 translation',
        motor = 'st_ta7',
        coder = 'co_ta7',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta8 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 8 translation',
        motor = 'st_ta8',
        coder = 'co_ta8',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta9 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 9 translation',
        motor = 'st_ta9',
        coder = 'co_ta9',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta10 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 10 translation',
        motor = 'st_ta10',
        coder = 'co_ta10',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),
    ta11 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 11 translation',
        motor = 'st_ta11',
        coder = 'co_ta11',
        obs = [],
        precision = 0.5,
        offset = 5,
        maxtries = 1,
    ),

#rotations
    st_ra1 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 192,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra2 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 193,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra3 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 194,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra4 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 195,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra5 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 196,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra6 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 197,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra7 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 198,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra8 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 199,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra9 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 200,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra10 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 201,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    st_ra11 = device('nicos_mlz.puma.devices.ipc_puma.Motor',
        bus = 'motorbus10',
        addr = 202,
        slope = -1797,
        unit = 'deg',
        abslimits = (-60.0, 0.1),
        zerosteps = 1000,
        lowlevel = True,
    ),
    ra1 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 1 rotation',
        motor = 'st_ra1',
        obs = [],
        precision = 0.01,
        offset = -0.814,
        maxtries = 1,
    ),
    ra2 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 2 rotation',
        motor = 'st_ra2',
        obs = [],
        precision = 0.01,
        offset = -0.245,
        maxtries = 1,
    ),
    ra3 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 3 rotation',
        motor = 'st_ra3',
        obs = [],
        precision = 0.01,
        offset = -1.58,
        maxtries = 1,
    ),
    ra4 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 4 rotation',
        motor = 'st_ra4',
        obs = [],
        precision = 0.01,
        offset = -0.175,
        maxtries = 1,
    ),
    ra5 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 5 rotation',
        motor = 'st_ra5',
        obs = [],
        precision = 0.01,
        offset = -0.12,
        maxtries = 1,
    ),
    ra6 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 6 rotation',
        motor = 'st_ra6',
        obs = [],
        precision = 0.01,
        offset = -0.365,
        maxtries = 1,
    ),
    ra7 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 7 rotation',
        motor = 'st_ra7',
        obs = [],
        precision = 0.01,
        offset = -0.895,
        maxtries = 1,
    ),
    ra8 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 8 rotation',
        motor = 'st_ra8',
        obs = [],
        precision = 0.01,
        offset = -0.135,
        maxtries = 1,
    ),
    ra9 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 9 rotation',
        motor = 'st_ra9',
        obs = [],
        precision = 0.01,
        offset = -0.025,
        maxtries = 1,
    ),
    ra10 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 10 rotation',
        motor = 'st_ra10',
        obs = [],
        precision = 0.01,
        offset = -0.46,
        maxtries = 1,
    ),
    ra11 = device('nicos.devices.generic.Axis',
        description = 'Multianalyzer crystal 11 rotation',
        motor = 'st_ra11',
        obs = [],
        precision = 0.01,
        offset = -0.175,
        maxtries = 1,
    ),
)
