description = 'PUMA secondary collimator unit'

group = 'optional'

includes = ['motorbus9', 'pumabase']

devices = dict(
    sca1b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'sca1 block changer',
        ordnum = 0,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    sca2b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'sca2 block changer',
        ordnum = 1,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    sca3b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'sca3 block changer',
        ordnum = 2,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    scb1b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'scb1 block changer',
        ordnum = 3,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    scb2b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'scb2 block changer',
        ordnum = 4,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    scb3b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'scb3 block changer',
        ordnum = 5,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    scc1b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'scc1 block changer',
        ordnum = 6,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    scc2b = device('nicos_mlz.puma.devices.SecCollBlockChanger',
        description = 'scc2 block changer',
        ordnum = 7,
        a2_setting = 'a2_set',
        a2_status = 'a2_status',
        visibility = (),
    ),
    a2_status = device('nicos.devices.vendor.ipc.Input',
        description = 'status of alpha2 units',
        bus = 'motorbus9',
        addr = 105,
        first = 0,
        last = 15,
        visibility = (),
    ),
    a2_lgon = device('nicos.devices.vendor.ipc.Output',
        description = 'switch on/off logos',
        bus = 'motorbus9',
        addr = 115,
        first = 6,
        last = 6,
        visibility = (),
    ),
    a2_valon = device('nicos.devices.vendor.ipc.Output',
        description = 'switch on/off power of valve unit',
        bus = 'motorbus9',
        addr = 115,
        first = 7,
        last = 7,
        visibility = (),
    ),
    a2_press = device('nicos.devices.vendor.ipc.Output',
        description = 'switch on/off pressure for valve unit',
        bus = 'motorbus9',
        addr = 112,
        first = 0,
        last = 0,
        visibility = (),
    ),
    a2_set = device('nicos.devices.vendor.ipc.Output',
        description = 'request for change of unit',
        bus = 'motorbus9',
        addr = 116,
        first = 0,
        last = 7,
        visibility = (),
    ),
    sca1 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'sca1 - diaphragma',
        angle = -40.030, # 68462,
        # sec = 55996070,
        tt = 'mtt',
        st = 'phi',
        block = 'sca1b',
        visibility = (),
    ),
    sca2 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'sca2 - diaphragma cover',
        angle = -14.952, # 63902,
        # sec = 55996070,
        tt = 'mtt',
        st = 'phi',
        block = 'sca2b',
        visibility = (),
    ),
    sca3 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'sca3 - 30 min. collimator',
        # sec = 55996070,
        angle = -109.732, # 81156,
        stpos = 109.,
        tt = 'mtt',
        st = 'phi',
        block = 'sca3b',
        visibility = (),
    ),
    scb1 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'scb1 - 30 min. cover',
        # sec = 55996070,
        angle = -84.826, # 76627,
        tt = 'mtt',
        st = 'phi',
        block = 'scb1b',
        visibility = (),
    ),
    scb2 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'scb2 - 45 min. collimator',
        # sec = 55996070,
        angle = -97.305, # 13358,
        stpos = 109.,
        tt = 'mtt',
        st = 'phi',
        block = 'scb2b',
        visibility = (),
    ),
    scb3 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'scb3 - 45 min. cover',
        # sec = 55996070,
        angle = -69.856, # 73897,
        tt = 'mtt',
        st = 'phi',
        block = 'scb3b',
        visibility = (),
    ),
    scc1 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'scc1 - 60 min. collimator',
        # sec = 55996070,
        angle = -52.3, # as of 17.02.20 - JTP # -52.696, # 70743,
        tt = 'mtt',
        st = 'phi',
        block = 'scc1b',
        visibility = (),
    ),
    scc2 = device('nicos_mlz.puma.devices.SecCollLift',
        description = 'scc2 - 60 min. cover',
        # sec = 55996070,
        angle = -27.394, # 66167,
        tt = 'mtt',
        st = 'phi',
        block = 'scc2b',
        visibility = (),
    ),
    a2dia = device('nicos_mlz.puma.devices.SecCollPair',
        description = 'a2dia - diaphragma',
        cover = 'sca2',
        frame = 'sca1',
        a2_press = 'a2_press',
        a2_lgon = 'a2_lgon',
        a2_powvalunit = 'a2_valon',
    ),
    scpair1 = device('nicos_mlz.puma.devices.SecCollPair',
        description = 'scpair1 - 200mm collimator',
        cover = 'scb1',
        frame = 'sca3',
        a2_press = 'a2_press',
        a2_lgon = 'a2_lgon',
        a2_powvalunit = 'a2_valon',
    ),
    scpair2 = device('nicos_mlz.puma.devices.SecCollPair',
        description = 'scpair2 - 150mm collimator',
        cover = 'scb3',
        frame = 'scb2',
        a2_press = 'a2_press',
        a2_lgon = 'a2_lgon',
        a2_powvalunit = 'a2_valon',
    ),
    scpair3 = device('nicos_mlz.puma.devices.SecCollPair',
        description = 'scpair3 - 100mm collimator',
        cover = 'scc2',
        frame = 'scc1',
        a2_press = 'a2_press',
        a2_lgon = 'a2_lgon',
        a2_powvalunit = 'a2_valon',
    ),
    alpha2 = device('nicos_mlz.puma.devices.SecondaryCollimator',
        description = 'alpha2 - secondary collimator',
        diaphragma = 'a2dia',
        # pair1 = 'scpair1',
        pair2 = 'scpair2',
        pair3 = 'scpair3',
        a2_status = 'a2_status',
        unit = 'min.',
        fmtstr = '%d',
    ),
)
