description = 'Detector CARESS HWB Devices'

group = 'lowlevel'

includes = ['tensile', 'primaryslit_manual', 'sampletable']

devices = dict(
    mon = device('nicos.devices.generic.VirtualCounter',
        description = 'Monitor (MON)',
        fmtstr = '%d',
        type = 'monitor',
        visibility = (),
    ),
    tim1 = device('nicos.devices.mcstas.McStasTimer',
        description='McStas virtual neutron counts timer channel',
        mcstas = 'mcstas',
        fmtstr = '%.2f',
        unit = 's',
        visibility = (),
    ),
    t_mon = device('nicos.devices.generic.VirtualCounter',
        description = 'Transmission Monitor',
        fmtstr = '%d',
        type = 'monitor',
        countrate = 100,
        visibility = (),
    ),
    mcstas = device('nicos_virt_mlz.stressi.devices.detector.McStasSimulation',
        description = 'McStas simulation',
        mcstasprog = 'stressi_fast',
        intensityfactor = 1e14,
        sample = 'Sample',
        xprime = 'pst',
        yprime = 'psx',
        l_ambda = 'wav',
        xpos = 'xt',
        ypos = 'yt',
        zpos = 'zt',
        phi = 'phis',
        chi = 'chis',
        omega = 'omgs',
        theta2 = 'tths',
        neutronspersec = {
            'localhost': 1.12e5,
            'taco6.ictrl.frm2.tum.de': 8.9e+05,
            'stressictrl02.stressi.frm2.tum.de': 2.7e6,
            configdata('config_data.host'): 1.12e5,
        },
    ),
    image = device('nicos.devices.mcstas.McStasImage',
        description = 'Image data device',
        mcstas = 'mcstas',
        mcstasfile = 'PSD_STRESSI_total.psd',
        size = (256, 256),
        fmtstr = '%d',
        unit = 'cts',
        pollinterval = 86400,
        visibility = (),
    ),
    roi = device('nicos.devices.generic.RectROIChannel',
        description = 'ROI',
        roi = (122, 50, 12, 140),
    ),
    adet = device('nicos.devices.mcstas.Detector',
        description = 'Classical detector with single channels',
        mcstas = 'mcstas',
        timers = ['tim1'],
        monitors = ['mon'],
        counters = ['t_mon', 'roi',],
        images = ['image'],
        pollinterval = None,
        liveinterval = 0.5,
        postprocess = [
            ('roi', 'image'),
        ],
    ),
    ysd = device('nicos.devices.generic.ManualMove',
        description = 'distance sample detector',
        default = 1300.,
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (800, 1500),
    ),
    hv1 = device('nicos.devices.generic.VirtualMotor',
        description = 'HV power supply 1',
        requires = {'level': 'admin'},
        abslimits = (0, 3200),
        speed = 2,
        fmtstr = '%.1f',
        unit = 'V',
        curvalue = 3100,
    ),
    hv2 = device('nicos.devices.generic.VirtualMotor',
        description = 'HV power supply 2',
        requires = {'level': 'admin'},
        abslimits = (-2500, 0),
        speed = 2,
        fmtstr = '%.1f',
        unit = 'V',
        curvalue = -2400,
    ),
)
