description = 'Primary slit devices'

group = 'lowlevel'

devices = dict(
    pst_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-15, 15),
        unit = 'mm',
        curvalue = 0,
        speed = 0.2,
        fmtstr = '%.2f',
        visibility = (),
    ),
    pst = device('nicos.devices.generic.Axis',
        description = 'Primary slit translation (PST)',
        motor = 'pst_m',
        precision = 0.01,
    ),
    psz_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-15, 15),
        unit = 'mm',
        speed = 0.2,
        fmtstr = '%.2f',
        visibility = (),
    ),
    psz = device('nicos.devices.generic.Axis',
        description = 'Primary slit Z translation (PSZ)',
        motor = 'psz_m',
        precision = 0.01,
    ),
    psx_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-120, 120),
        unit = 'mm',
        speed = 2,
        fmtstr = '%.2f',
        visibility = (),
    ),
    psx = device('nicos.devices.generic.Axis',
        description = 'Primary optics translation in beam direction',
        fmtstr = '%.2f',
        motor = 'psx_m',
        precision = 0.01,
    ),
)
