description = 'Primary radial collimator'

group = 'optional'

excludes = ['primaryslit_huber', 'primaryslit_manual']

devices = dict(
    coll_vert_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-2, 2),
        unit = 'deg',
        speed = 0.5,
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    coll_vert = device('nicos.devices.generic.Axis',
        description = 'Primary radial collimator vertical tilt',
        motor = 'coll_vert_m',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    coll_hor_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-2, 2),
        unit = 'deg',
        speed = 0.5,
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    coll_hor = device('nicos.devices.generic.Axis',
        description = 'Primary radial collimator horizontal tilt',
        motor = 'coll_hor_m',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    coll_rot_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (-5, 5),
        unit = 'deg',
        speed = 0.015,
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    coll_rot = device('nicos.devices.generic.Axis',
        description = 'Primary radial collimator rotation',
        motor = 'coll_rot_m',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    gv_coll = device('nicos.devices.generic.TwoAxisSlit',
        description = 'Gauge volume primary collimator',
        fmtstr = '%.2f x %.2f',
        horizontal = device('nicos.devices.generic.Axis',
            motor = device('nicos.devices.generic.VirtualMotor',
                fmtstr = '%.1f',
                curvalue = 1,
                unit = 'mm',
                abslimits = (0, 20),
                speed = 0.,
                requires = {'level': 'admin'},
            ),
            precision = 0.1,
        ),
        vertical = device('nicos.devices.generic.Axis',
            motor = device('nicos.devices.generic.VirtualMotor',
                fmtstr = '%.1f',
                curvalue = 3,
                unit = 'mm',
                abslimits = (0, 20),
                speed = 0.,
                requires = {'level': 'admin'},
            ),
            precision = 0.1,
        ),
    ),
)
