description = 'Sample table CARESS HWB Devices'

group = 'lowlevel'

devices = dict(
    xsd = device('nicos.devices.generic.ManualMove',
        description = 'distance monochromator sample',
        default = 500.,
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (500, 1100.),
    ),
    tths = device('nicos.devices.generic.VirtualMotor',
        description = 'Simulated TTHS',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (20, 130),
        curvalue = 90,
        speed = 1,
    ),
    omgs = device('nicos.devices.generic.VirtualMotor',
        description = 'Simulated OMGS',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (-200, 200),
        speed = 2,
    ),
    omgr = device('nicos.devices.generic.VirtualMotor',
        description = 'Rotation of robot base around the sample',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (-200, 200),
        speed = 1,
    ),
    xt = device('nicos.devices.generic.VirtualMotor',
        description = 'Simulated XT',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-120, 120),
        speed = 2,
    ),
    yt = device('nicos.devices.generic.VirtualMotor',
        description = 'Simulated YT',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-120, 120),
        speed = 2,
    ),
    zt = device('nicos.devices.generic.VirtualMotor',
        description = 'Simulated ZT',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-0, 300),
        speed = 2,
    ),
)
