description = 'Sample table CARESS HWB Devices'

group = 'lowlevel'

devices = dict(
    xsd = device('nicos.devices.generic.ManualMove',
        description = 'distance monochromator sample',
        default = 2300.,
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (1700, 3000),
    ),
    tths = device('nicos.devices.generic.VirtualMotor',
        description = 'TTHS (Rotation of detector around sample)',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (0, 125),
        curvalue = 90,
        speed = 1,
    ),
    omgs = device('nicos.devices.generic.VirtualMotor',
        description = 'OMGS (Rotation of the sample)',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (-200, 200),
        speed = 2,
    ),
    omgr = device('nicos.devices.generic.VirtualMotor',
        description = 'Rotation of robot base around the sample',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (-60, 60),
        curvalue = 30,
        speed = 1,
    ),
    xt = device('nicos.devices.generic.VirtualMotor',
        description = 'X translation sample',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-120, 120),
        speed = 2,
    ),
    yt = device('nicos.devices.generic.VirtualMotor',
        description = 'Y translation of sample',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-120, 120),
        speed = 2,
    ),
    zt = device('nicos.devices.generic.VirtualMotor',
        description = 'Z translation of sample',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-0, 300),
        speed = 2,
    ),
)
