description = 'Virtual monochromator devices'

group = 'lowlevel'

devices = dict(
    mth = device('nicos.devices.generic.Axis',
        description = 'Monochromator Theta',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (5, 175),
            speed = 0.5,
        ),
        precision = 0.011,
        maxtries = 10,
    ),
    mtt = device('nicos.devices.generic.Axis',
        description = 'Monochromator Two Theta',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-110, -14.1),
            speed = 0.5,
        ),
        precision = 0.005,
        maxtries = 10,
        jitter = 0.1,
        dragerror = 10,
    ),
    mfvpg  = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Vertical focus of PG-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-20, 55),
        ),
        uplimit = 38,
        lowlimit = 16.0,
        flatpos = 37,
        startpos = 38,
        precision = 0.1,
    ),
    mfhpg  = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Horizontal focus of PG-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-20, 55),
        ),
        uplimit = 70,
        lowlimit = -12.0,
        flatpos = 4.668,
        startpos = -7.874,
        precision = 0.1,
    ),
    mfhcu = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Horizontal focus of Cu220-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-30, 100),
            speed = 1,
        ),
        uplimit = 45,
        lowlimit = -13.5,
        flatpos = -13.5,
        startpos = -15.,
        precision = 0.2,
        maxtries = 25,
        loopdelay = 2,
    ),
    mfvcu = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Vertical focus of Cu220-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-25, 60),
            speed = 1,
        ),
        uplimit = 54,
        lowlimit = 7,
        flatpos = 54,
        startpos = 56,
        precision = 0.2,
        maxtries = 25,
        loopdelay = 2,
    ),
    mfhcu1 = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Horizontal focus of Cu220-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-20, 100),
            speed = 1,
        ),
        uplimit = 40,
        lowlimit = -3.5,
        flatpos = -3.5,
        startpos = -4.,
        precision = 0.2,
        maxtries = 25,
        loopdelay = 2,
    ),
    mfvcu1 = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'Vertical focus of Cu220-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (-20, 60),
            speed = 1,
        ),
        uplimit = 52,
        lowlimit = 15,
        flatpos = 52,
        startpos = 54,
        precision = 0.2,
        maxtries = 25,
        loopdelay = 2,
    ),
    mfhge = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'horizontal focus of Ge311-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (0, 999999),
            speed = 500,
        ),
        uplimit = 45,
        lowlimit = 5,
        flatpos = 5,
        startpos = 5.,
        precision = 0.8,
        maxtries = 25,
        loopdelay = 2,
    ),
    mfvge = device('nicos_mlz.puma.devices.focus.FocusAxis',
        description = 'orizontal focus of Ge311-Monochromator',
        motor = device('nicos.devices.generic.VirtualMotor',
            unit = 'deg',
            abslimits = (0, 999999),
            speed = 500,
        ),
        uplimit = 45,
        lowlimit = 10,
        flatpos = 74,
        startpos = 74.,
        precision = 0.8,
        maxtries = 25,
        loopdelay = 2,
    ),
)
