description = 'Big ErWIN detector devices'

group = 'optional'

devices = dict(
    b_edge1 = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = [0, 120],
        unit = 'V',
        ramp = 1.5 * 60,
        fmtstr = '%.1f',
        warnlimits = (95, 105),
    ),
    b_edge2 = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = [0, 120],
        unit = 'V',
        speed = 1.5 * 60,
        fmtstr = '%.1f',
        warnlimits = (95, 105),
    ),
    b_window = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = [-1050, 0],
        unit = 'V',
        speed = 1.5 * 60,
        fmtstr = '%.1f',
        warnlimits = (-1050, -950),
    ),
    b_trip = device('nicos.devices.generic.ManualSwitch',
        description = 'Trip indicator',
        states = ['', 'Tripped'],
        pollinterval = 1,
    ),
    b_hv = device('nicos_mlz.erwin.devices.HVSwitch',
        description = 'HV supply big detector',
        anodes = ['b_anode%d' % i for i in range(1, 10)],
        banodes = ['b_banode%d' % i for i in range(1, 9)],
        edges = ['b_edge1', 'b_edge2'],
        window = 'b_window',
        mapping = {
            'on': {
                'b_anode1': 2050,
                'b_anode2': 2052,
                'b_anode3': 2054,
                'b_anode4': 2057,
                'b_anode5': 2050,
                'b_anode6': 2053,
                'b_anode7': 2056,
                'b_anode8': 2058,
                'b_anode9': 2050,
                'b_banode1': 2052,
                'b_banode2': 2054,
                'b_banode3': 2056,
                'b_banode4': 2059,
                'b_banode5': 2059,
                'b_banode6': 2058,
                'b_banode7': 2057,
                'b_banode8': 2056,
                'b_edge1': 100,
                'b_edge2': 100,
                'b_window': -1000,
                'ramp': 1.5 * 60,
            },
            'off': {
                'b_anode1': 0,
                'b_anode2': 0,
                'b_anode3': 0,
                'b_anode4': 0,
                'b_anode5': 0,
                'b_anode6': 0,
                'b_anode7': 0,
                'b_anode8': 0,
                'b_anode9': 0,
                'b_banode1': 0,
                'b_banode2': 0,
                'b_banode3': 0,
                'b_banode4': 0,
                'b_banode5': 0,
                'b_banode6': 0,
                'b_banode7': 0,
                'b_banode8': 0,
                'b_edge1': 0,
                'b_edge2': 0,
                'b_window': 0,
                'ramp': 6 * 10,
            },
            'safe': {
                'b_anode1': 500,
                'b_anode2': 500,
                'b_anode3': 500,
                'b_anode4': 500,
                'b_anode5': 500,
                'b_anode6': 500,
                'b_anode7': 500,
                'b_anode8': 500,
                'b_anode9': 500,
                'b_banode1': 500,
                'b_banode2': 500,
                'b_banode3': 500,
                'b_banode4': 500,
                'b_banode5': 500,
                'b_banode6': 500,
                'b_banode7': 500,
                'b_banode8': 500,
                'b_edge1': 100,
                'b_edge2': 100,
                'b_window': -1000,
                'ramp': 6 * 10,
            },
        },
    ),
    b_hv_offtime = device('nicos_mlz.erwin.devices.charmhv.HVOffDuration',
        description = 'Duration of big detector below operating voltage',
        hv_supply = 'b_hv',
        maxage = 120,
        pollinterval = 15,
    ),
)

for i in range(1, 10):
    devices['b_anode%d' % i] = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = [0, 2160],
        unit = 'V',
        speed = 5,
        fmtstr = '%.1f',
        warnlimits = (1950, 2150),
    )

for i in range(1, 9):
    devices['b_banode%d' % i] = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = [0, 2160],
        unit = 'V',
        speed = 5,
        fmtstr = '%.1f',
        warnlimits = (1950, 2150),
    )
