description = 'memograph readout'

tango_base = 'tango://ictrlfs.ictrl.frm2.tum.de:10000/memograph04/MARIA/'

devices = dict(
    t_in_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'inlet temperature memograph',
        tangodevice = tango_base + 'T_in',
    ),
    t_out_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'outlet temperature memograph',
        tangodevice = tango_base + 'T_out',
    ),
    t_diff_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'temperature difference memograph',
        tangodevice = tango_base + 'T_diff',
    ),
    p_in_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'inlet pressure memograph',
        tangodevice = tango_base + 'P_in',
    ),
    p_out_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'outlet pressure memograph',
        tangodevice = tango_base + 'P_out',
    ),
    flow_in_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'inlet flow memograph',
        tangodevice = tango_base + 'FLOW_in',
    ),
    leak_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'leakage memograph',
        tangodevice = tango_base + 'Leak',
    ),
    cooling_memograph_maria = device('nicos.devices.entangle.Sensor',
        description = 'cooling power memograph',
        tangodevice = tango_base + 'Cooling',
    ),
)
