description = 'Triton Cryostat'
group = 'basic'

includes = ['alias_T']

tango_base = 'tango://localhost:10000/triton/'

devices = dict(
    T_PT2_head = device('nicos.devices.entangle.Sensor',
        description = 'PT2 Head',
        tangodevice = tango_base + 'ri/t1',
        pollinterval = 2,
        maxage = 5,
    ),
    T_PT2_Plate = device('nicos.devices.entangle.Sensor',
        description = 'PT2 Plate',
        tangodevice = tango_base + 'ri/t2',
        pollinterval = 2,
        maxage = 5,
    ),
    T_Still = device('nicos.devices.entangle.Sensor',
        description = 'Still RuO2 thermometer',
        tangodevice = tango_base + 'ri/t3',
        pollinterval = 2,
        maxage = 5,
    ),
    T_ColdPlate = device('nicos.devices.entangle.Sensor',
        description = 'Cold Plate RuO2',
        tangodevice = tango_base + 'ri/t4',
        pollinterval = 2,
        maxage = 5,
    ),
    T_MC_Cernox = device('nicos.devices.entangle.Sensor',
        description = 'Mixing Chamber Cernox',
        tangodevice = tango_base + 'ri/t5',
        pollinterval = 2,
        maxage = 5,
    ),
    T_PT1_head = device('nicos.devices.entangle.Sensor',
        description = 'PT1 Head',
        tangodevice = tango_base + 'ri/t6',
        pollinterval = 2,
        maxage = 5,
    ),
    T_PT1_plate = device('nicos.devices.entangle.Sensor',
        description = 'PT1 Plate',
        tangodevice = tango_base + 'ri/t7',
        pollinterval = 2,
        maxage = 5,
    ),
    T_MC_ROx = device('nicos.devices.entangle.Sensor',
        description = 'Mixing Chamber RuO2 thermometer',
        tangodevice = tango_base + 'ri/t8',
        pollinterval = 2,
        maxage = 5,
    ),
    T_magnet = device('nicos.devices.entangle.Sensor',
        description = 'Magnet cernox thermometer',
        tangodevice = tango_base + 'ri/t13',
        pollinterval = 2,
        maxage = 5,
    ),

    T_control = device('nicos.devices.entangle.TemperatureController',
        description = 'Mixing Chamber control loop',
        tangodevice = tango_base + 'ri/temp',
        pollinterval = 2,
        maxage = 5,
    ),

    p1_mixture = device('nicos.devices.entangle.Sensor',
        description = 'Pressure in mixture tank',
        tangodevice = tango_base + 'ri/p1',
        pollinterval = 2,
        maxage = 5,
    ),
    p2_condens = device('nicos.devices.entangle.Sensor',
        description = 'Pressure in condensing line',
        tangodevice = tango_base + 'ri/p2',
        pollinterval = 2,
        maxage = 5,
    ),
    p3_still = device('nicos.devices.entangle.Sensor',
        description = 'Still Pressure',
        tangodevice = tango_base + 'ri/p3',
        pollinterval = 2,
        maxage = 5,
    ),
    p4_turboback = device('nicos.devices.entangle.Sensor',
        description = 'Turbo back pressure',
        tangodevice = tango_base + 'ri/p4',
        pollinterval = 2,
        maxage = 5,
    ),
    p5_forepump = device('nicos.devices.entangle.Sensor',
        description = 'Pressure in forepump exhaust',
        tangodevice = tango_base + 'ri/p5',
        pollinterval = 2,
        maxage = 5,
    ),
    p_ovc = device('nicos.devices.entangle.Sensor',
        description = 'Pressure in vacuum chamber',
        tangodevice = tango_base + 'ri/p6',
        pollinterval = 2,
        maxage = 5,
    ),

    pump_speed = device('nicos.devices.entangle.Sensor',
        description = 'Current speed of the turbo pump',
        tangodevice = tango_base + 'ri/pump_speed',
        pollinterval = 2,
        maxage = 5,
    ),
    pump_power = device('nicos.devices.entangle.Sensor',
        description = 'Current power of the turbo pump',
        tangodevice = tango_base + 'ri/pump_power',
        pollinterval = 2,
        maxage = 5,
    ),


    T_cooler_water_in = device('nicos.devices.entangle.Sensor',
        description = 'Temperature of the water input to the cooler',
        tangodevice = tango_base + 'ri/cooler_wit',
        pollinterval = 2,
        maxage = 5,
    ),
    T_cooler_water_out = device('nicos.devices.entangle.Sensor',
        description = 'Temperature of the water output from the cooler',
        tangodevice = tango_base + 'ri/cooler_wot',
        pollinterval = 2,
        maxage = 5,
    ),
    T_cooler_oil = device('nicos.devices.entangle.Sensor',
        description = 'Temperature of the oil in the cooler',
        tangodevice = tango_base + 'ri/cooler_oilt',
        pollinterval = 5,
        maxage = 15,
    ),
    T_cooler_gas = device('nicos.devices.entangle.Sensor',
        description = 'Temperature of the helium gas in the cooler',
        tangodevice = tango_base + 'ri/cooler_ht',
        pollinterval = 5,
        maxage = 15,
    ),

    triton_cryostat = device('nicos_mgml.devices.cryostat.DummyCryostat',
        description = 'triton cryostat',
        unit = '',
    ),
)

alias_config = {
    'Cryostat':  {'triton_cryostat': 100},
}

