description = 'Timepix3 Detector at ILL'

group = 'optional'

sysconfig = dict(
    datasinks = ['LumaSink'],
)

excludes = ['detector_neo', 'lumacam']

# base_pv = 'nectar:roadrunner:'
base_pv = 'office:penguin:tpx3cam:cam1:'
# base_pv = 'NECTAR:Penguin:LumaCam:'

devices = dict(
    fastshutter_io = device('nicos.devices.generic.manual.ManualSwitch',
        description = 'fake fast shutter',
        states = [1, 2,],
    ),
    fastshutter = device('nicos.devices.generic.Switcher',
        description = 'Fast shutter',
        moveable = 'fastshutter_io',
        mapping = dict(open = 1, closed = 2),
        fallback = '<undefined>',
        precision = 0,
        unit = '',
    ),
    pointcount_luma = device('nicos.devices.epics.EpicsStringMoveable',
        description = 'TODO:',
        readpv = base_pv + 'RawFilePath_RBV',
        writepv = base_pv + 'RawFilePath',
        # readpv = base_pv + 'MeasurementPathStatus',
        # writepv = base_pv + 'MeasurementPath'
    ),
    FolderNameOut = device('nicos.devices.epics.EpicsStringMoveable',
        readpv = 'lumacam:foldername',
        writepv = 'lumacam:foldername',
        visibility = (),
    ),
    lumasink_prepare_status = device('nicos_mlz.nectar.devices.lumacam.LumaCamFileSinkStatus',
        description = 'TODO: File writer status',
    ),
    LumaSink = device('nicos_mlz.nectar.devices.lumacam.LumaCamSink',
        filenametemplate = ['%(pointcounter)08d'],
        filemode = 0o440,
        pointcounterout = 'pointcount_luma',
        status_prepare = 'lumasink_prepare_status',
        foldernameout = 'FolderNameOut',
    ),
    # trigger_hw = device('nicos.devices.entangle.DigitalOutput',
    #     tangodevice = 'tango://pibox.antareslab:10000/box/piface/out_1',
    #     visibility = (),
    # ),
    # trigger_start_hw = device('nicos.devices.epics.EpicsDigitalMoveable',
    #     readpv = base_pv + 'AcquisitionStart',
    #     writepv = base_pv + 'AcquisitionStart',
    #     targetpv = base_pv + 'AcquisitionStart',
    #     visibility = (),
    # ),
    # trigger_stop_hw = device('nicos.devices.epics.EpicsDigitalMoveable',
    #     readpv = base_pv + 'AcquisitionStop',
    #     writepv = base_pv + 'AcquisitionStop',
    #     targetpv = base_pv + 'AcquisitionStop',
    #     visibility = (),
    # ),
    # trigger_start_hw = device('nicos.devices.generic.manual.ManualSwitch',
    #     states = [0,1],
    # ),
    # trigger_stop_hw = device('nicos.devices.generic.manual.ManualSwitch',
    #     states = [0,1],
    # ),
    # trigger_start_hw = device('nicos.devices.epics.EpicsAnalogMoveable',
    #     readpv = 'lumacam:start',
    #     writepv = 'lumacam:start',
    # ),
    # trigger_stop_hw = device('nicos.devices.epics.EpicsAnalogMoveable',
    #     readpv = 'lumacam:stop',
    #     writepv = 'lumacam:stop',
    # ),

    # trigger_start = device('nicos.devices.generic.Pulse',
    #     onvalue = 1,
    #     offvalue = 0,
    #     ontime = 0.5,
    #     moveable = 'trigger_start_hw',
    #     visibility = (),
    # ),
    # trigger_stop = device('nicos.devices.generic.Pulse',
    #     description = 'Camera trigger',
    #     onvalue = 1,
    #     offvalue = 0,
    #     ontime = 0.5,
    #     moveable = 'trigger_stop_hw',
    #     visibility = (),
    # ),
    # timer_luma = device('nicos_mlz.antares.devices.TriggerTimerStartStop',
    #     description = 'Software timer',
    #     trigger_start = 'trigger_start',
    #     trigger_stop = 'trigger_stop',
    # ),
    # status_luma = device('nicos.devices.epics.EpicsStringReadable',
    #     readpv = 'lumacam:status',
    # ),
    # trigger_acquisition = device('nicos.devices.generic.manual.ManualSwitch',
    #     states = ['true','false'],
    # ),
    trigger_luma = device('nicos.devices.epics.EpicsStringMoveable',
        description = 'TODO: Trigger data acquisition',
        readpv = base_pv + 'Acquisition',
        writepv = base_pv + 'Acquisition',
    ),
    status_luma = device('nicos_mlz.nectar.devices.lumacam.LumaCamStatus',
        description = 'TODO: Acquisition state',
        readpv = base_pv + 'AcquisitionStatus',
    ),
    timer_luma = device('nicos_mlz.nectar.devices.lumacam.LumaCamTrigger',
        description = 'Software timer',
        runvalue = 'true',
        stopvalue = 'false',
        trigger_luma = 'trigger_luma',
        status_luma = 'status_luma',
    ),
    det_lumacam = device('nicos_mlz.nectar.devices.lumacam.ADLumaCam',
        description = 'Detector',
        timers = ['timer_luma'],
        status = 'status_luma',
        prepare_status = 'lumasink_prepare_status',
        pointcounter = 'pointcount_luma',
        pvprefix = '',
        base_raw_file_path = '',
        empir_path_prefix = '',
        empir_path_to_add = 'PathToAdd',
    ),
    PathToAdd = device('nicos.devices.epics.EpicsStringMoveable',
        description = 'Addition to path',
        readpv = base_pv + 'path_toAdd',
        writepv = base_pv + 'path_toAdd',
    ),
    # det_timepix = device('nicos.devices.generic.Detector',
    #     description = 'The ILL detector',
    #     timers = ['timer_timepix'],
    #     # images = ['img_fake'],
    # ),
)
startupcode = """
SetDetectors(det_lumacam)
"""
