[nicos]
user = "data"
group = "unx-lns"
umask = "022"

instrument = "zebra"
setup_package = "nicos_sinq"
setup_subdirs = ["zebra", "sinq_shared", "/sq_sw/linse/frappy_sinq", "/home/linse"]
services = ["cache", "poller", "daemon"]

logging_path = "/home/data/nicosdata/logs"

[environment]
NICOSDUMP = "/home/data/nicosdata"
ZEBRAHM = "http://zebrahm/admin"
PYTHONPATH = "/sq_sw/linse/frappy:/sq_sw/linse"
