description = 'memograph readout'

includes = []

group = 'optional'

devices = dict(
    t_in_panda     = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'T_in PANDA',
                            description = 'inlet temperature memograph',
                            fmtstr = '%.2F',
                            warnlimits = (-1, 17.5), #-1 no lower value
                            unit = 'degC',
                           ),
    t_out_panda    = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'T_out PANDA',
                            description = 'outlet temperature memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'degC',
                           ),
    p_in_panda     = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'P_in PANDA',
                            description = 'inlet pressure memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'bar',
                           ),
    p_out_panda    = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'P_out PANDA',
                            description = 'outlet pressure memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'bar',
                           ),
    flow_in_panda  = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'FLOW_in PANDA',
                            description = 'inlet flow memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            warnlimits = (0.2, 100), #100 no upper value
                            unit = 'l/min',
                           ),
    flow_out_panda = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'FLOW_out PANDA',
                            description = 'outlet flow memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'l/min',
                           ),
    leak_panda     = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'Leak PANDA',
                            description = 'leakage memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            warnlimits = (-1, 1), #-1 no lower value
                            unit = 'l/min',
                           ),
    cooling_panda  = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja04.care.frm2',
                            group = 3,
                            valuename = 'Cooling PANDA',
                            description = 'cooling power memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'kW',
                           ),
)
