description = 'Chopper devices'

group = 'lowlevel'

instrument_values = configdata('instrument.values')

tango_host = instrument_values['tango_base'] + 'test/chopper/io'

includes = ['shutter', 'vsd']

devices = dict(
    chopper_io = device('nicos.devices.tango.StringIO',
        tangodevice = tango_host,
        lowlevel = True,
    ),
    chopper = device('nicos_mlz.refsans.devices.chopper.real.ChopperMaster',
        description = 'Interface',
        fmtstr = '%s',
        unit = 'foo',
        chopper1 = 'chopper_speed',
        chopper2 = 'chopper2',
        chopper3 = 'chopper3',
        chopper4 = 'chopper4',
        chopper5 = 'chopper5',
        chopper6 = 'chopper6',
        shutter = 'shutter',
        comm = 'chopper_io',
    ),
    chopper_speed = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper speed; reguler 100rpm/min Nothalt 400rpm/min',
        comm = 'chopper_io',
        fmtstr = '%d',
        unit = 'rpm',
        chopper = 1,
        gear = 0,
        edge = 'open',
    ),
    chopper2 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc2',
        description = 'disk2',
        comm = 'chopper_io',
        translation = 'chopper2_pos',
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 2,
        gear = 1,
        edge = 'close',
        reference = -18.05,
    ),
    chopper2_pos = device('nicos_mlz.refsans.devices.chopper.real.ChopperDiscTranslation',
        description = 'position of chopper disc 2',
        comm = 'chopper_io',
        disc = 'chopper2', # because of speed
    ),
    chopper3 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper3',
        comm = 'chopper_io',
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 3,
        gear = 1,
        edge = 'open',
        reference = 23.85,
    ),
    chopper4 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper4',
        comm = 'chopper_io',
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 4,
        gear = 1,
        edge = 'close',
        reference = 29.2,
    ),
    chopper5 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper5',
        comm = 'chopper_io',
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 5,
        gear = 2,
        edge = 'open',
        reference = 220.19,
    ),
    chopper6 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper6',
        comm = 'chopper_io',
        fmtstr = '%d',
        unit = 'rpm',
        lowlevel = True,
        chopper = 6,
        gear = 2,
        edge = 'close',
        reference = 129.7,
    ),
    core1 = device('nicos_mlz.refsans.devices.analogencoder.AnalogEncoder',
        description = 'Temperature of motorcoil 1',
        device = 'Temperature8',
        poly = [-6.9, 1],
        unit = 'degC',
        lowlevel = True,
    ),
    core2 = device('nicos_mlz.refsans.devices.analogencoder.AnalogEncoder',
        description = 'Temperature of motorcoil 2',
        device = 'Temperature7',
        poly = [-9.3, 1],
        unit = 'degC',
        lowlevel = True,
    ),
    core3 = device('nicos_mlz.refsans.devices.analogencoder.AnalogEncoder',
        description = 'Temperature of motorcoil 3',
        device = 'Temperature6',
        poly = [-10.1, 1],
        unit = 'degC',
        lowlevel = True,
    ),
    core4 = device('nicos_mlz.refsans.devices.analogencoder.AnalogEncoder',
        description = 'Temperature of motorcoil 4',
        device = 'Temperature5',
        poly = [-9.7, 1],
        unit = 'degC',
        lowlevel = True,
    ),
)
