description = 'Chopper phase timing, readout for light barrier and coder index'

group = 'optional'

window_delay = 120

all_lowlevel = False  # or True
# atts = 'nicos.devices.generic.ParamDevice'
atts = 'nicos_mlz.refsans.devices.gkssjson.CPTReadout'
URL = 'http://cpt.refsans.frm2/json?1'

devices = dict(
    cpt0 = device(atts,
        description = 'Disc 1 light barrier ' + description + ' Phase of Disk1!',
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = -1,
        offset = -106.8,
        unit = 'deg',
        lowlevel = True,
    ),
    cpt1 = device(atts,
        description = 'Disc 1 light barrier ' + description,
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = 0,
        # offset = 0,
        unit = 'rpm',
    ),
     cpt2 = device(atts,
         description = 'Disc 2 light barrier ' + description,
         url = URL,
         valuekey = 'chopper_act',
         timeout = .3,
         channel = 7,
         offset = 5.993 + window_delay,
         unit = 'deg',
     ),
    cpt3 = device(atts,
        description = 'Disc 3 light barrier ' + description,
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = 8,
        offset = -44.2 + window_delay,
        unit = 'deg',
    ),
    cpt4 = device(atts,
        description = 'Disc 4 light barrier ' + description,
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = 9,
        offset = 174.65 + window_delay,
        unit = 'deg',
    ),
    cpt5 = device(atts,
        description = 'Disc 5 index ' + description,
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = 10,
        offset = 146.74 + window_delay,
        unit = 'deg',
    ),
    cpt6 = device(atts,
        description = 'Disc 6 index ' + description,
        url = URL,
        valuekey = 'chopper_act',
        timeout = .3,
        channel = 11,
        offset = 56.17 + window_delay,
        unit = 'deg',
    ),
)
