description = 'Chopper devices'

group = 'lowlevel'

tango_host = 'tango://refsanshw.refsans.frm2:10000/test/chopper/io'

includes = ['shutter']

devices = dict(
    chopper = device('nicos_mlz.refsans.devices.chopper.real.ChopperMaster',
        description = 'Interface',
        tangodevice = tango_host,
        fmtstr = '%s',
        unit = 'foo',
        chopper1 = 'chopper1',
        chopper2 = 'chopper2',
        chopper3 = 'chopper3',
        chopper4 = 'chopper4',
        chopper5 = 'chopper5',
        chopper6 = 'chopper6',
        shutter = 'shutter',
    ),
    chopper1 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper1',
        tangodevice = tango_host,
        fmtstr = '%d',
        unit = 'rpm',
        chopper = 1,
        gear = 0,
        edge = 'open',
    ),
    chopper2 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc2',
        description = 'disk2',
        tangodevice = tango_host,
        translation = 'chopper2_pos',
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 2,
        gear = 1,
        edge = 'close',
        reference = -18.05,
    ),
    chopper2_pos = device('nicos_mlz.refsans.devices.chopper.real.ChopperDiscTranslation',
        description = 'position of chopper disc 2',
        tangodevice = tango_host,
        disc = 'chopper1',
    ),
    chopper3 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper3',
        tangodevice = tango_host,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 3,
        gear = 1,
        edge = 'open',
        reference = 23.85,
    ),
    chopper4 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper4',
        tangodevice = tango_host,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 4,
        gear = 1,
        edge = 'close',
        reference = 29.2,
    ),
    chopper5 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper5',
        tangodevice = tango_host,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 5,
        gear = 2,
        edge = 'open',
        reference = 220.19,
    ),
    chopper6 = device('nicos_mlz.refsans.devices.chopper.real.ChopperDisc',
        description = 'chopper6',
        tangodevice = tango_host,
        fmtstr = '%d',
        unit = 'rpm',
        lowlevel = True,
        chopper = 6,
        gear = 2,
        edge = 'close',
        reference = 129.7,
    ),
)
