description = 'Chopper devices'

group = 'lowlevel'
#group = 'optional'
#uribase = 'tango://refsansctrl01.refsans.frm2:10000/refsans/chopper/'
nethost = 'refsanssrv.refsans.frm2'

includes = ['shutter']

devices = dict(
    chopper = device('nicos_mlz.refsans.devices.chopper.ChopperMaster',
        description = 'Interface',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%s',
        unit = 'foo',
        chopper1 = 'chopper1',
        chopper2 = 'chopper2',
        chopper2_pos = 'chopper2_pos',
        chopper3 = 'chopper3',
        chopper4 = 'chopper4',
        chopper5 = 'chopper5',
        chopper6 = 'chopper6',
        chopper_mode = 'chopper_mode',
        shutter = 'shutter',
    ),
    chopper_mode = device('nicos.devices.generic.ManualSwitch',
        description = 'Modus Disc2_ pos, normal or virtual_disc2_pos_6',
        states = ['normal_mode', 'virtual_disc2_pos_6'],
    ),
    chopper1 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'chopper1',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        unit = 'rpm',
        chopper = 1,
        gear = 0,
        edge = 'open',
    ),
    chopper1_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 1',
        device = 'chopper1',
        parameter = 'phase',
        lowlevel = True,
        unit = 'deg',
    ),
    chopper1_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 1',
        device = 'chopper1',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
    chopper1_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 1',
        device = 'chopper1',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper2 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'disk2',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 2,
        gear = 1,
        edge = 'close',
    ),
    chopper2_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 2',
        device = 'chopper2',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper2_pos = device('nicos_mlz.refsans.devices.chopper.ChopperDisc2Pos',
        description = 'position of chopper disc 2',
        tacodevice = '//%s/test/network/chopper' % nethost,
        disc = 'chopper1',
    ),
    chopper2_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 2',
        device = 'chopper2',
        parameter = 'phase',
        unit = 'deg',
    ),
    chopper2_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 2',
        device = 'chopper2',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
    chopper3 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'chopper3',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 3,
        gear = 1,
        edge = 'open',
    ),
    chopper3_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 3',
        device = 'chopper3',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper3_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 3',
        device = 'chopper3',
        parameter = 'phase',
        unit = 'deg',
    ),
    chopper3_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 3',
        device = 'chopper3',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
    chopper4 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'chopper4',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 4,
        gear = 1,
        edge = 'close',
    ),
    chopper4_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 4',
        device = 'chopper4',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper4_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 4',
        device = 'chopper4',
        parameter = 'phase',
        unit = 'deg',
    ),
    chopper4_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 4',
        device = 'chopper4',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
    chopper5 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'chopper5',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        lowlevel = True,
        unit = 'rpm',
        chopper = 5,
        gear = 2,
        edge = 'open',
    ),
    chopper5_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 5',
        device = 'chopper5',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper5_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 5',
        device = 'chopper5',
        parameter = 'phase',
        unit = 'deg',
    ),
    chopper5_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 5',
        device = 'chopper5',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
    chopper6 = device('nicos_mlz.refsans.devices.chopper.ChopperDisc',
        description = 'chopper6',
        tacodevice = '//%s/test/network/chopper' % nethost,
        fmtstr = '%d',
        unit = 'rpm',
        lowlevel = True,
        chopper = 6,
        gear = 2,
        edge = 'close',
    ),
    chopper6_mode = device('nicos.devices.generic.ParamDevice',
        description = 'mode of chopper disc 6',
        device = 'chopper6',
        parameter = 'mode',
        lowlevel = True,
        fmtstr = '%d',
        unit = '',
    ),
    chopper6_phase = device('nicos.devices.generic.ParamDevice',
        description = 'phase of chopper disc 6',
        device = 'chopper6',
        parameter = 'phase',
        unit = 'deg',
    ),
    chopper6_current = device('nicos.devices.generic.ParamDevice',
        description = 'current of chopper disc 6',
        device = 'chopper6',
        parameter = 'current',
        lowlevel = True,
        unit = 'A',
    ),
)
