description = 'alias for the switch12 for channel4'

group = 'lowlevel'

ana4gpio = 'ddgana4gpio'

instrument_values = configdata('instrument.values')
tango_base = f'tango://{ana4gpio}:10000/test/ads/'
code_base = instrument_values['code_base']
lowlevel = ()

visibility = ()
Vadd = 2.5 # Volt

devices = {
    f'{ana4gpio}_ch1': device('nicos.devices.entangle.Sensor',
        description = 'ADin0',
        tangodevice = tango_base + 'ch1',
        unit = 'V',
        fmtstr = '%.4f',
        visibility = lowlevel,
    ),
    f'{ana4gpio}_ch2': device('nicos.devices.entangle.Sensor',
        description = 'ADin1',
        tangodevice = tango_base + 'ch2',
        unit = 'V',
        fmtstr = '%.4f',
        visibility = lowlevel,
    ),
    f'{ana4gpio}_ch3': device('nicos.devices.entangle.Sensor',
        description = 'ADin2',
        tangodevice = tango_base + 'ch3',
        unit = 'V',
        fmtstr = '%.4f',
        visibility = lowlevel,
    ),
    f'{ana4gpio}_ch4': device('nicos.devices.entangle.Sensor',
        description = 'ADin3',
        tangodevice = tango_base + 'ch4',
        unit = 'V',
        fmtstr = '%.4f',
        visibility = lowlevel,
    ),
    'ddg_detection_gas_pressure' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Pressure detection gas',
        device = f'{ana4gpio}_ch1',
        poly = [0, 10], # /100R0.1% *1000mA
        unit = 'mA',
        visibility = {'metadata', 'devlist', 'namespace'},
    ),
    'ddg_tank_temperature_resistor' : device(code_base + 'analogencoder.Ohmmeter',
        description = 'Tank Resistor PT1000',
        device = f'{ana4gpio}_ch2',
        u_high = 2.5,
        u_low = 0.0,
        r_arb = 1000,
        unit = 'Ohm',
        visibility = visibility,
    ),
    'ddg_tank_temperature' : device(code_base + 'analogencoder.PTxxlinearC',
        description = 'Tank Temperature PT1000',
        device = 'ddg_tank_temperature_resistor',
        #poly = [-551.45, 440.02],
        r0 = 1000,
        r_cable = 0.5,  #2023-09-05 11:58:34
        alpha = 0.003851,
        unit = 'degC',
        visibility = {'metadata', 'devlist', 'namespace'},
    ),
    'ddg_device_temp_resistor' : device(code_base + 'analogencoder.Ohmmeter',
        description = 'Device Intern Resistor PT1000',
        device = f'{ana4gpio}_ch3',
        u_high = 2.5,
        u_low = 0.0,
        r_arb = 1000,
        unit = 'Ohm',
        visibility = visibility,
    ),
    'ddg_device_temp' : device(code_base + 'analogencoder.PTxxlinearC',
        description = 'Tank Temperature PT1000',
        device = 'ddg_device_temp_resistor',
        #poly = [-551.45, 440.02],
        r0 = 1000,
        r_cable = 0.0,
        alpha = 0.003851,
        unit = 'degC',
        visibility = {'metadata', 'devlist', 'namespace'},
    ),
    'ddg_sw01_extern_temp' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'SHT3x Temperature Extern',
        device = f'{ana4gpio}_ch4',
        poly = [-66.875, 218.75 / Vadd],
        unit = 'degC',
        visibility = {'metadata', 'devlist', 'namespace'},
    ),
    'ddg_sw02_LT1034BCZ_1V2' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Refvoltage 1.2V  LT1034BCZ',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 1.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw03_AVDD' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'AVDD',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 3.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw04_15V' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Pressure sensor source 15V',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 7.2],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw05_5V0' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Raspi 5V0',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 3.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw06_5V0_in' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Supply 5V0',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 3.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw07_3V3' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Raspi 3V3',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 2.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw08_extern_rh' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'SHT3x Humidity Extern',
        device = f'{ana4gpio}_ch4',
        poly = [-12.5, 125.0 / Vadd],
        unit = 'percent',
        visibility = visibility,
    ),
    'ddg_sw09_Pressuresensor_Voltage' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'Pressure sensor Voltage need JUMPER!',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 12.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw10_GND' : device(code_base + 'analogencoder.AnalogEncoder',
        description = 'just GND',
        device = f'{ana4gpio}_ch4',
        poly = [0.0, 1.0],
        unit = 'V',
        visibility = visibility,
    ),
    'ddg_sw11_2nd_detection_gas_pressure' : device(code_base + 'analogencoder.AnalogEncoder',
        description = '2nd Pressure detection gas',
        device = f'{ana4gpio}_ch4',
        poly = [0, 10], # /100R0.1% *1000mA
        unit = 'mA',
        visibility = visibility,
    ),
    'ddg_channel4' : device('nicos.devices.generic.DeviceAlias',
        visibility = {'metadata', 'devlist', 'namespace'},
    ),
}

alias_config = {
    'ddg_channel4': {
        'ddg_sw01_extern_temp': 120,
        'ddg_sw02_LT1034BCZ_1V2': 110,
        'ddg_sw03_AVDD': 100,
        'ddg_sw04_15V':  90,
        'ddg_sw05_5V0':  80,
        'ddg_sw06_5V0_in':  70,
        'ddg_sw07_3V3':  60,
        'ddg_sw08_extern_rh':  50,
        'ddg_sw09_Pressuresensor_Voltage':  40,
        'ddg_sw10_GND':  30,
        'ddg_sw11_2nd_detection_gas_pressure':  20,
    },
}
