description = '%s readout devices' % setupname

group = 'lowlevel'

instrument_values = configdata('instrument.values')

tango_base = instrument_values['tango_base'] + '%s/io/modbus' % setupname
code_base = instrument_values['code_base'] + '%s.' % setupname

devices = {
    '_%sio' % setupname : device(code_base + 'Base',
        description = 'Modbus Device for communication with %s' % setupname,
        tangodevice = tango_base,
        #visibility = (),
    ),
    '%s_trigger_1' % setupname : device(code_base + 'AnalogValue',
        description = '%s trigger 1' % setupname,
        iodev = '_%sio' % setupname,
        channel = 0 + 0,
    ),
    '%s_Amplitude_1' % setupname : device(code_base + 'AnalogValue',
        description = '%s Amplitude 1' % setupname,
        iodev = '_%sio' % setupname,
        channel = 1 + 0,
    ),
    '%s_Phase_1' % setupname : device(code_base + 'AnalogValue',
        description = '%s Phase 1' % setupname,
        iodev = '_%sio' % setupname,
        channel = 2 + 0,
    ),
    '%s_Frequenz_1' % setupname : device(code_base + 'AnalogValue',
        description = '%s Frequenz 1' % setupname,
        iodev = '_%sio' % setupname,
        channel = 3 + 0,
    ),
    '%s_trigger_2' % setupname : device(code_base + 'AnalogValue',
        description = '%s trigger 2' % setupname,
        iodev = '_%sio' % setupname,
        channel = 0 + 4,
    ),
    '%s_Amplitude_2' % setupname : device(code_base + 'AnalogValue',
        description = '%s Amplitude 2' % setupname,
        iodev = '_%sio' % setupname,
        channel = 1 + 4,
    ),
    '%s_Phase_2' % setupname : device(code_base + 'AnalogValue',
        description = '%s Phase 2' % setupname,
        iodev = '_%sio' % setupname,
        channel = 2 + 4,
    ),
    '%s_Frequenz_2' % setupname : device(code_base + 'AnalogValue',
        description = '%s Frequenz 2' % setupname,
        iodev = '_%sio' % setupname,
        channel = 3 + 4,
    ),
    '%s_trigger_3' % setupname : device(code_base + 'AnalogValue',
        description = '%s trigger 3' % setupname,
        iodev = '_%sio' % setupname,
        channel = 0 + 8,
    ),
    '%s_Amplitude_3' % setupname : device(code_base + 'AnalogValue',
        description = '%s Amplitude 3' % setupname,
        iodev = '_%sio' % setupname,
        channel = 1 + 8,
    ),
    '%s_Phase_3' % setupname : device(code_base + 'AnalogValue',
        description = '%s Phase 3' % setupname,
        iodev = '_%sio' % setupname,
        channel = 2 + 8,
    ),
    '%s_Frequenz_3' % setupname : device(code_base + 'AnalogValue',
        description = '%s Frequenz 3' % setupname,
        iodev = '_%sio' % setupname,
        channel = 3 + 8,
    ),
    '%s_trigger_4' % setupname : device(code_base + 'AnalogValue',
        description = '%s trigger 4' % setupname,
        iodev = '_%sio' % setupname,
        channel = 0 + 12,
    ),
    '%s_Amplitude_4' % setupname : device(code_base + 'AnalogValue',
        description = '%s Amplitude 4' % setupname,
        iodev = '_%sio' % setupname,
        channel = 1 + 12,
    ),
    '%s_Phase_4' % setupname : device(code_base + 'AnalogValue',
        description = '%s Phase 4' % setupname,
        iodev = '_%sio' % setupname,
        channel = 2 + 12,
    ),
    '%s_Frequenz_4' % setupname : device(code_base + 'AnalogValue',
        description = '%s Frequenz 4' % setupname,
        iodev = '_%sio' % setupname,
        channel = 3 + 12,
    ),
}
