description = 'Sample table devices'

group = 'optional'

nethost = 'refsanssrv.refsans.frm2'
tacodev = '//%s/test' % nethost


devices = dict(
    gonio_theta = device('nicos.devices.generic.Axis',
        description = 'Theta axis',
        motor = 'gonio_theta_m',
        coder = 'gonio_theta_m',
        precision = 0.01,
    ),
    gonio_theta_m = device('nicos.devices.taco.Motor',
        description = 'Theta axis motor',
        tacodevice = '%s/phytron/kanal_01' % tacodev,
        abslimits = (-2, 10),
        lowlevel = True,
    ),
    gonio_phi = device('nicos.devices.generic.Axis',
        description = 'Phi axis',
        motor = 'gonio_phi_m',
        coder = 'gonio_phi_m',
        precision = 0.01,
    ),
    gonio_phi_m = device('nicos.devices.taco.Motor',
        description = 'Phi axis motor',
        tacodevice = '%s/phytron/kanal_02' % tacodev,
        abslimits = (-9.75, 9.5),
        lowlevel = True,
    ),
    omega = device('nicos.devices.generic.Axis',
        description = 'Omega axis',
        motor = 'omega_m',
        coder = 'omega_m',
        precision = 0.01,
    ),
    omega_m = device('nicos.devices.taco.Motor',
        description = 'Omega axis motor',
        tacodevice = '%s/phytron/kanal_03' % tacodev,
        abslimits = (-2.5, 2.5),
        lowlevel = True,
    ),
    y = device('nicos.devices.generic.Axis',
        description = 'Y axis',
        motor = 'y_m',
        coder = 'y_m',
        precision = 0.01,
    ),
    y_m = device('nicos.devices.taco.Motor',
        description = 'Y axis motor',
        tacodevice = '%s/phytron/kanal_04' % tacodev,
        abslimits = (-78.0, 75.0),
        lowlevel = True,
    ),
    gonio_z = device('nicos.devices.generic.Axis',
        description = 'Z axis',
        motor = 'gonio_z_m',
        coder = 'gonio_z_m',
        precision = 0.01,
    ),
    gonio_z_m = device('nicos.devices.taco.Motor',
        description = 'Z axis motor',
        tacodevice = '%s/phytron/kanal_05' % tacodev,
        abslimits = (-300.0, 188.0),
        lowlevel = True,
    ),
)
