description = 'Sample table devices'

group = 'optional'

tango_base1 = 'tango://refsanshw:10000/sample/phy_mo1/'
tango_base2 = 'tango://refsanshw:10000/sample/phy_mo2/'
# coder_ss = 'm'
coder_ss = 'e'

devices = dict(
    gonio_theta = device('nicos.devices.generic.Axis',
        description = 'Theta axis',
        motor = 'gonio_theta_m',
        coder = 'gonio_theta_%s' % coder_ss,
        precision = 0.01,
    ),
    gonio_theta_m = device('nicos.devices.tango.Motor',
        description = 'Theta axis motor',
        tangodevice = tango_base1 + 'theta_m',
        lowlevel = True,
    ),
    gonio_theta_e = device('nicos.devices.tango.Sensor',
        description = 'Theta axis coder',
        tangodevice = tango_base1 + 'theta_e',
        lowlevel = True,
    ),
    gonio_phi = device('nicos.devices.generic.Axis',
        description = 'Phi axis',
        motor = 'gonio_phi_m',
        coder = 'gonio_phi_%s' % coder_ss,
        precision = 0.01,
    ),
    gonio_phi_m = device('nicos.devices.tango.Motor',
        description = 'Phi axis motor',
        tangodevice = tango_base1 + 'phi_m',
        lowlevel = True,
    ),
    gonio_phi_e = device('nicos.devices.tango.Sensor',
        description = 'Phi axis coder',
        tangodevice = tango_base1 + 'phi_e',
        lowlevel = True,
    ),
    gonio_omega = device('nicos.devices.generic.Axis',
        description = 'Omega axis',
        motor = 'gonio_omega_m',
        coder = 'gonio_omega_%s' % coder_ss,
        precision = 0.01,
    ),
    gonio_omega_m = device('nicos.devices.tango.Motor',
        description = 'Omega axis motor',
        tangodevice = tango_base1 + 'omega_m',
        lowlevel = True,
    ),
    gonio_omega_e = device('nicos.devices.tango.Sensor',
        description = 'Omega axis coder',
        tangodevice = tango_base1 + 'omega_e',
        lowlevel = True,
    ),
    gonio_y = device('nicos.devices.generic.Axis',
        description = 'Y axis. towards TOFTOF is plus',
        motor = 'gonio_y_m',
        coder = 'gonio_y_%s' % coder_ss,
        precision = 0.01,
    ),
    gonio_y_m = device('nicos.devices.tango.Motor',
        description = 'y axis motor',
        tangodevice = tango_base2 + 'y_m',
        lowlevel = True,
    ),
    gonio_y_e = device('nicos.devices.tango.Sensor',
        description = 'y axis coder',
        tangodevice = tango_base2 + 'y_e',
        lowlevel = True,
    ),
    gonio_z = device('nicos.devices.generic.Axis',
        description = 'Z axis',
        motor = 'gonio_z_m',
        coder = 'gonio_z_%s' % coder_ss,
        precision = 0.01,
    ),
    gonio_z_m = device('nicos.devices.tango.Motor',
        description = 'Z axis motor',
        tangodevice = tango_base1 + 'z_m',
        lowlevel = True,
    ),
    gonio_z_e = device('nicos.devices.tango.Sensor',
        description = 'Z axis coder',
        tangodevice = tango_base1 + 'z_e',
        lowlevel = True,
    ),
)
