description = 'Langmuir trough'

group = 'optional'

includes = ['gonio', 'height']

instrument_values = configdata('instrument.values')
lowlevel_devel = ('namespace', 'devlist', 'metadata')

tango_host = instrument_values['tango_base'] + 'test/nima_nima/io'
code_base = instrument_values['code_base']

devices = dict(
    nima_z = device('nicos.devices.generic.ManualMove',
        description = 'generic to handle height of gonio_z',
        abslimits = (-0.5, 9.5),
        fmtstr = '%.6f',
        unit = 'mm',
    ),
    nima_acc = device(code_base + 'accuracy.Accuracy',
        description = 'calc error Motor and heigt',
        motor = 'gonio_z',
        analog = 'height',
        unit = 'mm'
    ),
    nima_com = device('nicos.devices.entangle.StringIO',
        tangodevice = tango_host,
        visibility = (),
    ),
    nima_io = device(code_base + 'nima.Base',
        comm = 'nima_com',
        unit = 'foo',
        visibility = (),
    ),
    nima_area = device(code_base + 'nima.Area',
        description = 'Area of Langmuir trough',
        comm = 'nima_io',
        fmtstr = '%.1f',
        abslimits = (60, 1100),
        speed = 600,
        unit = 'cm x cm',
    ),
    nima_speed = device(code_base + 'nima.ReadName',
        description = 'Regulation speed',
        comm = 'nima_io',
        fmtstr = '%.1f',
        unit = 'cm x cm/min',
        visibility = lowlevel_devel,
    ),
    nima_pressure = device(code_base + 'nima.Press',
        description = 'Surface pressure interface',
        comm = 'nima_io',
        abslimits = (0, 70),
        fmtstr = '%.1f',
        speed = 500,
        #precision = 0.5,
        unit = 'mN/m',
    ),
    nima_pressure_A = device(code_base + 'nima.ReadName',
        description = 'Surface pressure raw integer',
        comm = 'nima_io',
        fmtstr = '%d',
        unit = 'foo',
        visibility = lowlevel_devel,
    ),
    nima_commin = device(code_base + 'nima.ReadName',
        description = 'Com time Host UI4 min',
        comm = 'nima_io',
        fmtstr = '%.3f',
        unit = 'sec',
        visibility = lowlevel_devel,
    ),
    nima_commax = device(code_base + 'nima.ReadName',
        description = 'Com time Host UI4 max',
        comm = 'nima_io',
        fmtstr = '%.3f',
        unit = 'sec',
        visibility = lowlevel_devel,
    ),
    nima_comakt = device(code_base + 'nima.ReadName',
        description = 'Com time Host UI4 akt',
        comm = 'nima_io',
        fmtstr = '%.3f',
        unit = 'sec',
        visibility = lowlevel_devel,
    ),
)
