description = 'shs SicherHeitsSystem'

group = 'lowlevel'

nethost = 'refsanssrv.refsans.frm2'
tango_base = 'tango://refsanshw.refsans.frm2.tum.de:10000/'

devices = dict(
    safetysystem = device('nicos_mlz.refsans.devices.safetysystem.Shs',
        description = 'io device for Pilz',
        tangodevice = tango_base + 'safetysystem/io/modbus',
        lowlevel = True,
    ),
    techOK = device('nicos_mlz.refsans.devices.safetysystem.Group4',
        description = ' ',
        p1 = 'chopper_drive',
        p2 = 'Shspressure_CB',
        p3 = 'Shspressure_SFK',
        p4 = 'Shspressure_SR',
        unit = '',
        lowlevel = False,
    ),
    chopper_drive = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0008,
        bit_index = 6,
    ),
    Shspressure_CB = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0001,
        bit_index = 6,
    ),
    Shspressure_SFK = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0002,
        bit_index = 6,
    ),
    Shspressure_SR = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0004,
        bit_index = 6,
    ),
    sampleposition_clear = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBitReverse',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0004,
        bit_index = 14,
    ),
    Streurohr_clear = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBitReverse',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0008,
        bit_index = 14,
    ),
    Verbindungstuer = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0100,
        bit_index = 4,
    ),
    Tuer_PO_auf = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0040,
        bit_index = 3,
    ),
    Tuer_PO_zu = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBitReverse',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0080,
        bit_index = 3,
    ),
    Tuer_PO = device('nicos_mlz.refsans.devices.safetysystem.ShsInversBit',
        description = '',
        unit = '',
        even = 'Tuer_PO_zu',
        odd  = 'Tuer_PO_auf',
        lowlevel = True,
    ),
    Tuer_SR_auf = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBit',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0400,
        bit_index = 4,
    ),
    Tuer_SR_zu = device('nicos_mlz.refsans.devices.safetysystem.ShsSingleBitReverse',
        description = '',
        shs = 'safetysystem',
        unit = '',
        lowlevel = True,
        word_address = 0x0800,
        bit_index = 4,
    ),
    Tuer_SR = device('nicos_mlz.refsans.devices.safetysystem.ShsInversBit',
        description = '',
        unit = '',
        even = 'Tuer_SR_zu',
        odd  = 'Tuer_SR_auf',
        lowlevel = True,
    ),
    doors = device('nicos_mlz.refsans.devices.safetysystem.Group3',
        description = ' ',
        p1 = 'Tuer_PO',
        p2 = 'Verbindungstuer',
        p3 = 'Tuer_SR',
        unit = '',
        lowlevel = False,
    ),
    place = device('nicos_mlz.refsans.devices.safetysystem.Group2',
        description = ' ',
        p1 = 'sampleposition_clear',
        p2 = 'Streurohr_clear',
        unit = '',
        lowlevel = False,
    ),
)
