description = 'Sample table devices'

group = 'lowlevel'

devices = dict(
    xs = device('nicos.devices.generic.Axis',
        description = 'X translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-25, 25),
            unit = 'mm',
        ),
        precision = 0.01,
    ),
    ys = device('nicos.devices.generic.Axis',
        description = 'Y translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-25, 25),
            unit = 'mm',
        ),
        precision = 0.01,
    ),
    zs = device('nicos.devices.generic.Axis',
        description = 'Z translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-125, 125),
            unit = 'mm',
        ),
        precision = 0.01,
    ),
    omgs = device('nicos.devices.generic.Axis',
        description = 'Omega of sample',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-150, 150),
            unit = 'deg',
        ),
        precision = 0.01,
    ),
    tths = device('nicos.devices.generic.Axis',
        description = '2theta of sample',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-150, 150),
            unit = 'deg',
        ),
        precision = 0.01,
    ),
    tths2 = device('nicos.devices.generic.Axis',
        description = '2theta of sample',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-180, 180),
            unit = 'deg',
        ),
        precision = 0.01,
    ),
)
