#!/usr/bin/env python3
#  -*- coding: utf-8 -*-

import sys

from isort.hooks import git_hook

if __name__ == '__main__':
    res = git_hook(strict=True)
    if res:
        print("""The code contains wrongly sorted imports, use:
        git diff --staged --name-only --diff-filter d '*.py' | xargs isort""")

    sys.exit(0)
