[nicos]
instrument = "sans"
setup_package = "nicos_virt_sinq"
setup_subdirs = ["sans"]  # , "frappy_sinq", "sinq_shared"]
services = ["cache", "poller", "daemon"]

logging_path = "log"

[environment]
NICOSDUMP = "data"
