devices = dict(
    alphastorage = device('nicos_mlz.panda.devices.guidefield.AlphaStorage',
        abslimits = (-360, 360),
        unit = 'deg',
    ),
    gf4 = device('nicos_virt_mlz.kompass.devices.gf.Guidefield4',
        alpha = 'alphastorage',
        coils = [
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0.2, 0, 0),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (-0.1, 0.17320508, 0),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (-0.1, -0.173205080, 0),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0, 0, 0.9),
                calibrationcurrent = 1,
            ),
        ],
        alphaoffset = 0,
        field = 0.9,
        mapping = {
            'off': None,
            'x': (1., 0., 0.),
            '-x': (-1., 0., 0.),
            'y': (0., 1., 0.),
            '-y': (0., -1., 0.),
            'z': (0., 0., 1.),
            '-z': (0., 0., -1.),
            'up': (0., 0., 1.),
            'down': (0., 0., -1.),
            '0': (0., 0., 0.),
        },
    ),
    gf4_f = device('nicos_virt_mlz.kompass.devices.gf.Guidefield4',
        alpha = 'alphastorage',
        alphaoffset = 0,
        field = 0.9,
        coils = [
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                # orientation = (0.2, 0, 1e-2),
                orientation = (0.2, 0, 0),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (-0.1, -0.17320508, 1e-2),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (-0.1, -0.173205080, 0),
                calibrationcurrent = 1,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0, 0, 0.9),
                calibrationcurrent = 1,
            ),
        ],
    ),
    gf3 = device('nicos_virt_mlz.kompass.devices.gf.Guidefield3',
        alpha = 'alphastorage',
        alphaoffset = 0,
        coils = [
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0.53, 0.53, 0),
                calibrationcurrent = 10,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0.53, -0.53, 0),
                calibrationcurrent = 10,
            ),
            device('nicos_virt_mlz.kompass.devices.gf.VectorCoil',
                abslimits = (-20, 20),
                orientation = (0, 0, 2.33),
                calibrationcurrent = 2,
            ),
        ],
    ),
)
