# -*- coding: utf-8 -*-

description = 'GALAXI digital in- and outputs'

group = 'optional'

includes = []

#tango_host = 'tango://phys.galaxi.fz-juelich.de:10000'
tango_host = 'tango://localhost:10000'

devices = dict(

    vacuumtube1 = device('devices.tango.AnalogInput',
                         description = 'Tango device for Vacuum tube 1',
                         tangodevice = '%s/galaxi/FZJDP_Analog/VacuumTube1' % tango_host,
                         ),
    vacuumtube2 = device('devices.tango.AnalogInput',
                         description = 'Tango device for Vacuum tube 2',
                         tangodevice = '%s/galaxi/FZJDP_Analog/VacuumTube2' % tango_host,
                         ),
    vacuumtube3 = device('devices.tango.AnalogInput',
                         description = 'Tango device for Vacuum tube 3',
                         tangodevice = '%s/galaxi/FZJDP_Analog/VacuumTube3' % tango_host,
                         ),
    detcountrate = device('devices.tango.DigitalInput',
                          description = 'Tango device for Detector countrate',
                          tangodevice = '%s/galaxi/FZJDP_Digital/DetectorCountrate' % tango_host,
                         ),
    ionchamber = device('devices.tango.DigitalInput',
                        description = 'Tango device for Ionisation chamber',
                        tangodevice = '%s/galaxi/FZJDP_Digital/IonisationChamber' % tango_host,
                        ),
    pindiode1 = device('devices.tango.DigitalInput',
                        description = 'Tango device for Pindiode 1',
                        tangodevice = '%s/galaxi/FZJDP_Digital/PinDiode1' % tango_host,
                        ),
    pindiode2 = device('devices.tango.DigitalInput',
                        description = 'Tango device for calibrated Pindiode 2',
                        tangodevice = '%s/galaxi/FZJDP_Digital/PinDiode2' % tango_host,
                        ),
    pindiode3 = device('devices.tango.DigitalInput',
                        description = 'Tango device for Pindiode 3',
                        tangodevice = '%s/galaxi/FZJDP_Digital/PinDiode3' % tango_host,
                        ),
    pindiode4 = device('devices.tango.DigitalInput',
                        description = 'Tango device for calibrated Pindiode 4',
                        tangodevice = '%s/galaxi/FZJDP_Digital/PinDiode4' % tango_host,
                        ),
    channel5 = device('devices.tango.DigitalInput',
                        description = 'Tango device for Channel5',
                        tangodevice = '%s/galaxi/FZJDP_Digital/Channel5' % tango_host,
                        ),
    channel6 = device('devices.tango.DigitalInput',
                        description = 'Tango device for Channel6',
                        tangodevice = '%s/galaxi/FZJDP_Digital/Channel6' % tango_host,
                        ),
    channel7 = device('devices.tango.DigitalInput',
                        description = 'Tango device for Channel7',
                        tangodevice = '%s/galaxi/FZJDP_Digital/Channel7' % tango_host,
                        ),


    pumpe02_io = device('devices.tango.DigitalInput',
                        description = 'Tango device for Pumpe 2',
                        tangodevice = '%s/galaxi/FZJDP_Digital/Pumpe2' % tango_host,
                        lowlevel = True,
                        ),
    pumpe02 = device('devices.generic.ReadonlySwitcher',
                        description = 'Pumpe 2',
                        readable = 'pumpe02_io',
                        mapping = dict( on=1, off=2 ),
                        precision = 0,
                        ),
    pumpe03_io = device('devices.tango.DigitalInput',
                        description = 'Tango device for Pumpe 3',
                        tangodevice = '%s/galaxi/FZJDP_Digital/Pumpe3' % tango_host,
                        lowlevel = True,
                        ),
    pumpe03 = device('devices.generic.ReadonlySwitcher',
                        description = 'Pumpe 3',
                        readable = 'pumpe03_io',
                        mapping = dict( on=1, off=2 ),
                        precision = 0,
                        ),

    detectorpos_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Detectorposition',
                        tangodevice = '%s/galaxi/FZJDP_Digital/DetectorPos' % tango_host,
                        lowlevel = True,
                        ),
    detectorpos = device('devices.generic.Switcher',
                        description = 'Detectorposition',
                        moveable = 'detectorpos_io',
                        #mapping = {1:1, 2:2, 3:4, 4:8, 5:16},
                        mapping = dict(pos1=1, pos2=2, pos3=4, pos4=8, pos5=16),
                        precision = 0,
                        ),

    detectube01_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Detectortube 1',
                        tangodevice = '%s/galaxi/FZJDP_Digital/DetectorTube1' % tango_host,
                        lowlevel = True,
                        ),
    detectube01 = device('devices.generic.Switcher',
                        description = 'Detectortube 1',
                        moveable = 'detectube01_io',
                        mapping = dict( up=1, down=2 ),
                        precision = 0,
                        ),
    detectube02_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Detectortube 2',
                        tangodevice = '%s/galaxi/FZJDP_Digital/DetectorTube2' % tango_host,
                        lowlevel = True,
                        ),
    detectube02 = device('devices.generic.Switcher',
                        description = 'Detectortube 2',
                        moveable = 'detectube02_io',
                        mapping = dict( up=1, down=2 ),
                        precision = 0,
                        ),
    detectube03_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Detectortube 3',
                        tangodevice = '%s/galaxi/FZJDP_Digital/DetectorTube3' % tango_host,
                        lowlevel = True,
                        ),
    detectube03 = device('devices.generic.Switcher',
                        description = 'Detectortube 3',
                        moveable = 'detectube03_io',
                        mapping = dict( up=1, down=2 ),
                        precision = 0,
                        ),
    detectube04_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Detectortube 4',
                        tangodevice = '%s/galaxi/FZJDP_Digital/DetectorTube4' % tango_host,
                        lowlevel = True,
                        ),
    detectube04 = device('devices.generic.Switcher',
                        description = 'Detectortube 4',
                        moveable = 'detectube04_io',
                        mapping = dict( up=1, down=2 ),
                        precision = 0,
                     ),

    vavalve01_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 1  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve1' % tango_host,
                        lowlevel = True,
                        ),
    vavalve01 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 1',
                        moveable = 'vavalve01_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vavalve02_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 2  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve2' % tango_host,
                        lowlevel = True,
                        ),
    vavalve02 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 2',
                        moveable = 'vavalve02_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vavalve03_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 2  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve2' % tango_host,
                        lowlevel = True,
                        ),
    vavalve03 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 3',
                        moveable = 'vavalve03_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vavalve04_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 4  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve4' % tango_host,
                        lowlevel = True,
                        ),
    vavalve04 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 4',
                        moveable = 'vavalve04_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vavalve05_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 5  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve5' % tango_host,
                        lowlevel = True,
                        ),
    vavalve05 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 5',
                        moveable = 'vavalve05_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vavalve06_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Vacuumvalve 6  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VacuumValve6' % tango_host,
                        lowlevel = True,
                        ),
    vavalve06 = device('devices.generic.Switcher',
                        description = 'Vacuumvalve 6',
                        moveable = 'vavalve06_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vevalve01_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Ventilationvalve 1  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VentilationValve1' % tango_host,
                        lowlevel = True,
                        ),
    vevalve01 = device('devices.generic.Switcher',
                        description = 'Ventilationvalve 1',
                        moveable = 'vevalve01_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vevalve02_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Ventilationvalve 2  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VentilationValve2' % tango_host,
                        lowlevel = True,
                        ),
    vevalve02 = device('devices.generic.Switcher',
                        description = 'Ventilationvalve 2',
                        moveable = 'vevalve02_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),
    vevalve03_io = device('devices.tango.DigitalOutput',
                        description = 'Tango device for Ventilationvalve 3  in/out',
                        tangodevice = '%s/galaxi/FZJDP_Digital/VentilationValve3' % tango_host,
                        lowlevel = True,
                        ),
    vevalve03 = device('devices.generic.Switcher',
                        description = 'Ventilationvalve 3',
                        moveable = 'vevalve03_io',
                        mapping = dict(open=1, close=0),
                        precision = 0,
                        ),

    absorber01_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 1  in/out',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate1' % tango_host,
                         lowlevel = True,
                        ),
    absorber01 = device('devices.generic.Switcher',
                      description = 'Absorberplate 1',
                      moveable = 'absorber01_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber02_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 2 in/out',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate2' % tango_host,
                         lowlevel = True,
                        ),
    absorber02 = device('devices.generic.Switcher',
                      description = 'Absorberplate 2',
                      moveable = 'absorber02_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber03_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 3 in/out',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate3' % tango_host,
                         lowlevel = True,
                        ),
    absorber03 = device('devices.generic.Switcher',
                      description = 'Absorberplate 3',
                      moveable = 'absorber03_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber04_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 4 in/out',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate4' % tango_host,
                         lowlevel = True,
                        ),
    absorber04 = device('devices.generic.Switcher',
                      description = 'Absorberplate 4',
                      moveable = 'absorber04_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber05_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 5',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate5' % tango_host,
                         lowlevel = True,
                        ),
    absorber05 = device('devices.generic.Switcher',
                      description = 'Absorberplate 5',
                      moveable = 'absorber05_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber06_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 6',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate6' % tango_host,
                         lowlevel = True,
                        ),
    absorber06 = device('devices.generic.Switcher',
                      description = 'Absorberplate 6',
                      moveable = 'absorber06_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber07_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 7',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate7' % tango_host,
                         lowlevel = True,
                        ),
    absorber07 = device('devices.generic.Switcher',
                      description = 'Absorberplate 7',
                      moveable = 'absorber07_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber08_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 8',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate8' % tango_host,
                         lowlevel = True,
                        ),
    absorber08 = device('devices.generic.Switcher',
                      description = 'Absorberplate 8',
                      moveable = 'absorber08_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber09_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 9',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate9' % tango_host,
                         lowlevel = True,
                        ),
    absorber09 = device('devices.generic.Switcher',
                      description = 'Absorberplate 9',
                      moveable = 'absorber09_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber10_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 10',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate10' % tango_host,
                         lowlevel = True,
                        ),
    absorber10 = device('devices.generic.Switcher',
                      description = 'Absorberplate 10',
                      moveable = 'absorber10_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber11_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 11',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate11' % tango_host,
                         lowlevel = True,
                        ),
    absorber11 = device('devices.generic.Switcher',
                      description = 'Absorberplate 11',
                      moveable = 'absorber11_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber12_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 12',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate12' % tango_host,
                         lowlevel = True,
                        ),
    absorber12 = device('devices.generic.Switcher',
                      description = 'Absorberplate 12',
                      moveable = 'absorber12_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber13_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 13',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate13' % tango_host,
                         lowlevel = True,
                        ),
    absorber13 = device('devices.generic.Switcher',
                      description = 'Absorberplate 13',
                      moveable = 'absorber13_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber14_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 14',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate14' % tango_host,
                         lowlevel = True,
                        ),
    absorber14 = device('devices.generic.Switcher',
                      description = 'Absorberplate 14',
                      moveable = 'absorber14_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber15_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 15',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate15' % tango_host,
                         lowlevel = True,
                        ),
    absorber15 = device('devices.generic.Switcher',
                      description = 'Absorberplate 15',
                      moveable = 'absorber15_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    absorber16_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Absorberplate 16',
                         tangodevice = '%s/galaxi/FZJDP_Digital/AbsorberPlate16' % tango_host,
                         lowlevel = True,
                        ),
    absorber16 = device('devices.generic.Switcher',
                      description = 'Absorberplate 16',
                      moveable = 'absorber16_io',
                      mapping = {'in' : 1, 'out' : 0},
                      precision = 0,
                     ),

    pindiode_io = device('devices.tango.DigitalOutput',
                         description = 'Tango device for Pin diode',
                         tangodevice = '%s/galaxi/FZJDP_Digital/PinDiode' % tango_host,
                         lowlevel = True,
                        ),

    pindiode = device('devices.generic.Switcher',
                         description = 'Pin diode',
                         moveable = 'pindiode_io',
                         mapping = {'in' : 1, 'out' : 2},
                         precision = 0,
                        ),

)

startupcode = '''
'''
