# -*- coding: utf-8 -*-

description = 'GALAXI motors'

group = 'optional'

#tango_host = 'tango://slow:10000'
tango_host = 'tango://localhost:10000'

devices = dict(
    det_z       = device('devices.tango.Motor',
                        description = 'Detector Z axis',
                        tangodevice = '%s/galaxi/fzjs7/DetZ' % tango_host,
                        lowlevel = True,
                      ),
    detz        = device('devices.generic.axis.Axis',
                        description = 'Detector Z axis',
                        motor = 'det_z',
                        coder = 'det_z',
                        precision = 0.001,
                      ),
    det_x       = device('devices.tango.Motor',
                        description = 'Detector X axis',
                        tangodevice = '%s/galaxi/fzjs7/DetX' % tango_host,
                        lowlevel = True,
                      ),
    detx        = device('devices.generic.axis.Axis',
                        description = 'Detector X axis',
                        motor = 'det_x',
                        coder = 'det_x',
                        offset = 0,
                        precision = 0.001,
                      ),
    det_2th     = device('devices.tango.Motor',
                        description = 'Detector 2th axis',
                        tangodevice = '%s/galaxi/fzjs7/Det2th' % tango_host,
                        lowlevel = True,
                     ),
    det2th      = device('devices.generic.axis.Axis',
                        description = 'Detector 2th axis',
                        motor = 'det_2th',
                        coder = 'det_2th',
                        offset = 0,
                        precision = 0.001,
                   ),
    bss_y       = device('devices.tango.Motor',
                        description = 'BSSY axis',
                        tangodevice = '%s/galaxi/fzjs7/BSSY' % tango_host,
                        lowlevel = True,
                      ),
    bssy        = device('devices.generic.axis.Axis',
                        description = 'BSSY axis',
                        motor = 'bss_y',
                        coder = 'bss_y',
                        offset = 0,
                        precision = 0.001,
                   ),
    bsp_z       = device('devices.tango.Motor',
                        description = 'BSPZ axis',
                        tangodevice = '%s/galaxi/fzjs7/BSPZ' % tango_host,
                        lowlevel = True,
                      ),
    bspz        = device('devices.generic.axis.Axis',
                        description = 'BSPZ axis',
                        motor = 'bsp_z',
                        coder = 'bsp_z',
                        offset = 0,
                        precision = 0.001,
                  ),
    bsp_kipp    = device('devices.tango.Motor',
                        description = 'BSPKipp axis',
                        tangodevice = '%s/galaxi/fzjs7/BSPKipp' % tango_host,
                        lowlevel = True,
                      ),
    bspkipp     = device('devices.generic.axis.Axis',
                        description = 'BSPKipp axis',
                        motor = 'bsp_kipp',
                        coder = 'bsp_kipp',
                        offset = 0,
                        precision = 0.001,
                  ),
    bsp_y       = device('devices.tango.Motor',
                        description = 'BSPY axis',
                        tangodevice = '%s/galaxi/fzjs7/BSPY' % tango_host,
                        lowlevel = True,
                      ),
    bspy        = device('devices.generic.axis.Axis',
                        description = 'BSPY axis',
                        motor = 'bsp_y',
                        coder = 'bsp_y',
                        offset = 0,
                        precision = 0.001,
                  ),
    p_chi       = device('devices.tango.Motor',
                        description = 'PCHI axis',
                        tangodevice = '%s/galaxi/fzjs7/PCHI' % tango_host,
                        lowlevel = True,
                      ),
    pchi        = device('devices.generic.axis.Axis',
                        description = 'PCHI axis',
                        motor = 'p_chi',
                        coder = 'p_chi',
                        offset = 0,
                        precision = 0.001,
                  ),
    p_om        = device('devices.tango.Motor',
                        description = 'POM axis',
                        tangodevice = '%s/galaxi/fzjs7/POM' % tango_host,
                        lowlevel = True,
                      ),
    pom         = device('devices.generic.axis.Axis',
                        description = 'POM axis',
                        motor = 'p_om',
                        coder = 'p_om',
                        offset = 0,
                        precision = 0.001,
                  ),
    p_z         = device('devices.tango.Motor',
                        description = 'PZ axis',
                        tangodevice = '%s/galaxi/fzjs7/PZ' % tango_host,
                        lowlevel = True,
                      ),
    pz          = device('devices.generic.axis.Axis',
                        description = 'PZ axis',
                        motor = 'p_z',
                        coder = 'p_z',
                        offset = 0,
                        precision = 0.001,
                  ),
    p_y         = device('devices.tango.Motor',
                        description = 'PY axis',
                        tangodevice = '%s/galaxi/fzjs7/PY' % tango_host,
                        lowlevel = True,
                      ),
    py          = device('devices.generic.axis.Axis',
                        description = 'PY axis',
                        motor = 'p_y',
                        coder = 'p_y',
                        offset = 0,
                        precision = 0.001,
                  ),
    p_refz      = device('devices.tango.Motor',
                        description = 'PRefZ axis',
                        tangodevice = '%s/galaxi/fzjs7/PRefZ' % tango_host,
                        lowlevel = True,
                      ),
    prefz       = device('devices.generic.axis.Axis',
                        description = 'PRefZ axis',
                        motor = 'p_refz',
                        coder = 'p_refz',
                        offset = 0,
                        precision = 0.001,
                   ),
    ro_y        = device('devices.tango.Motor',
                        description = 'ROY axis',
                        tangodevice = '%s/galaxi/fzjs7/ROY' % tango_host,
                        lowlevel = True,
                      ),
    roy         = device('devices.generic.axis.Axis',
                        description = 'ROY axis',
                        motor = 'ro_y',
                        coder = 'ro_y',
                        offset = 0,
                        precision = 0.001,
                 ),
    ro_z        = device('devices.tango.Motor',
                        description = 'ROZ axis',
                        tangodevice = '%s/galaxi/fzjs7/ROZ' % tango_host,
                        lowlevel = True,
                      ),
    roz         = device('devices.generic.axis.Axis',
                        description = 'ROZ axis',
                        motor = 'ro_z',
                        coder = 'ro_z',
                        offset = 0,
                        precision = 0.001,
                      ),
    b1_h        = device('devices.tango.Motor',
                        description = 'Collimation slit B1 Height',
                        tangodevice = '%s/galaxi/fzjs7/B1H' % tango_host,
                        lowlevel = True,
                     ),
    b1h         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B1 Height',
                        motor = 'b1_h',
                        coder = 'b1_h',
                        offset = 0,
                        precision = 0.001,
                    ),
    b1_b        = device('devices.tango.Motor',
                        description = 'Collimation slit B1 Width',
                        tangodevice = '%s/galaxi/fzjs7/B1B' % tango_host,
                        lowlevel = True,
                     ),
    b1b         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B1 Width',
                        motor = 'b1_b',
                        coder = 'b1_b',
                        offset = 0,
                        precision = 0.001,
                  ),
    b1_y        = device('devices.tango.Motor',
                        description = 'Collimation slit B1 Left Right',
                        tangodevice = '%s/galaxi/fzjs7/B1Y' % tango_host,
                        lowlevel = True,
                      ),
    b1y         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B1 Left Right',
                        motor = 'b1_y',
                        coder = 'b1_y',
                        offset = 0,
                        precision = 0.001,
                    ),
    b1_z        = device('devices.tango.Motor',
                        description = 'Collimation slit B1 Up Down',
                        tangodevice = '%s/galaxi/fzjs7/B1Z' % tango_host,
                        lowlevel = True,
                      ),
    b1z         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B1 Up Down',
                        motor = 'b1_z',
                        coder = 'b1_z',
                        offset = 0,
                        precision = 0.001,
                    ),
    b2_h        = device('devices.tango.Motor',
                        description = 'Collimation slit B2 Height',
                        tangodevice = '%s/galaxi/fzjs7/B2H' % tango_host,
                        lowlevel = True,
                      ),
    b2h         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B2 Height',
                        motor = 'b2_h',
                        coder = 'b2_h',
                        offset = 0,
                        precision = 0.001,
                      ),
    b2_b        = device('devices.tango.Motor',
                        description = 'Collimation slit B2 Width',
                        tangodevice = '%s/galaxi/fzjs7/B2B' % tango_host,
                        lowlevel = True,
                      ),
    b2b         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B2 Width',
                        motor = 'b2_b',
                        coder = 'b2_b',
                        offset = 0,
                        precision = 0.001,
                      ),
    b2_y        = device('devices.tango.Motor',
                        description = 'Collimation slit B2 Left Right',
                        tangodevice = '%s/galaxi/fzjs7/B2Y' % tango_host,
                        lowlevel = True,
                      ),
    b2y         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B2 Left Right',
                        motor = 'b2_y',
                        coder = 'b2_y',
                        offset = 0,
                        precision = 0.001,
                     ),
    b2_z        = device('devices.tango.Motor',
                        description = 'Collimation slit B2 Up Down',
                        tangodevice = '%s/galaxi/fzjs7/B2Z' % tango_host,
                        lowlevel = True,
                      ),
    b2z         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B2 Up Down',
                        motor = 'b2_z',
                        coder = 'b2_z',
                        offset = 0,
                        precision = 0.001,
                      ),
    b3_h        = device('devices.tango.Motor',
                        description = 'Collimation slit B3 Height',
                        tangodevice = '%s/galaxi/fzjs7/B3H' % tango_host,
                        lowlevel = True,
                      ),
    b3h         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B3 Height',
                        motor = 'b3_h',
                        coder = 'b3_h',
                        offset = 0,
                        precision = 0.001,
                      ),
    b3_b        = device('devices.tango.Motor',
                        description = 'Collimation slit B3 Width',
                        tangodevice = '%s/galaxi/fzjs7/B3B' % tango_host,
                        lowlevel = True,
                      ),
    b3b         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B3 Width',
                        motor = 'b3_b',
                        coder = 'b3_b',
                        offset = 0,
                        precision = 0.001,
                      ),
    b3_y        = device('devices.tango.Motor',
                        description = 'Collimation slit B3 Left Right',
                        tangodevice = '%s/galaxi/fzjs7/B3Y' % tango_host,
                        lowlevel = True,
                      ),
    b3y         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B3 Left Right',
                        motor = 'b3_y',
                        coder = 'b3_y',
                        offset = 0,
                        precision = 0.001,
                      ),
    b3_z        = device('devices.tango.Motor',
                        description = 'Collimation slit B3 Up Down',
                        tangodevice = '%s/galaxi/fzjs7/B3Z' % tango_host,
                        lowlevel = True,
                      ),
    b3z         = device('devices.generic.axis.Axis',
                        description = 'Collimation slit B3 Up Down',
                        motor = 'b3_z',
                        coder = 'b3_z',
                        offset = 0,
                        precision = 0.001,
                     ),
)

startupcode = '''
'''
