# -*- coding: utf-8 -*-

description = 'GALAXI digital in- and outputs'

group = 'optional'

tango_base = 'tango://localhost:10000/galaxi/'
tango_digital = tango_base + 'fzjdp_digital/'
tango_analog  = tango_base + 'fzjdp_analog/'

devices = dict(
    pintimer            = device('devices.tango.AnalogOutput',
                                 description = 'Timer for PIN diode counting',
                                 tangodevice = tango_analog + 'IntegralTime',
                                 unit = 's',
                                 fmtstr = '%d',
                                ),
    pinstate            = device('devices.tango.NamedDigitalInput',
                                 description = 'Status of PIN diode counting',
                                 tangodevice = tango_digital + 'StatIntegralPin',
                                 mapping = {'counting':1, 'ready':0},
                                 fmtstr = '%s',
                                 lowlevel = True,
                                ),
    pincontrol          = device('devices.tango.DigitalInput',
                                 description = 'Status control of PIn diode counting',
                                 tangodevice = tango_digital + 'StatIntegralPin2',
                                 lowlevel = True,
                                ),
    singledetectors     = device('galaxi.pindiode.SingleDetectors',
                                 description = 'Integrated PIN diode values',
                                 pintimer = 'pintimer',
                                 pinstate = 'pinstate',
                                 pincontrol = 'pincontrol',
                                 pindiodes = ['ionichamber1_int','ionichamber2_int',
                                              'pindiode1_int','pindiodecal_int',
                                              'pindiodesample_int'],
                                ),
    ionichamber1        = device('devices.tango.AnalogInput',
                                 description = 'Ionisation chamber 1',
                                 tangodevice = tango_analog + 'PinDiode4',
                                ),
    ionichamber1_int    = device('devices.tango.AnalogInput',
                                 description = 'Integral of ionisation chamber 1',
                                 tangodevice = tango_analog + 'IntPinDiode4',
                                 fmtstr = '%.10g',
                                ),
    ionichamber1_off    = device('devices.tango.AnalogOutput',
                                 description = 'Offset ionisation chamber 1',
                                 tangodevice = tango_analog + 'PinDiode4_Offset',
                                ),
    ionichamber2        = device('devices.tango.AnalogInput',
                                 description = 'Ionisation chamber 2',
                                 tangodevice = tango_analog + 'IonisationChamber',
                                ),
    ionichamber2_int    = device('devices.tango.AnalogInput',
                                 description = 'Integral ionisation chamber 2',
                                 tangodevice = tango_analog + 'IntIonisationChamber',
                                 fmtstr = '%.10g',
                                ),
    ionichamber2_off    = device('devices.tango.AnalogOutput',
                                 description = 'Offset Ionisation chamber 2',
                                 tangodevice = tango_analog + 'IonChamber_Offset',
                                ),
    pindiode1_move      = device('devices.tango.NamedDigitalOutput',
                                 description = 'Moving of PIN diode in chamber 1',
                                 tangodevice = tango_digital + 'AbsorberPlate16',
                                 mapping = {'in':1, 'out':0},
                                 fmtstr = '%s',
                                ),
    pindiode1           = device('devices.tango.AnalogInput',
                                 description = 'PIN diode in chamber 1',
                                 tangodevice = tango_analog + 'PinDiode3',
                                ),
    pindiode1_int       = device('devices.tango.AnalogInput',
                                 description = 'Integral of PIN diode in chamber 1',
                                 tangodevice = tango_analog + 'IntPinDiode3',
                                 fmtstr = '%.10g',
                                ),
    pindiode1_off       = device('devices.tango.AnalogOutput',
                                 description = 'Offset PIN diode in chamber 1',
                                 tangodevice = tango_analog + 'PinDiode3_Offset',
                                ),
    pindiodesample_move = device('devices.tango.NamedDigitalOutput',
                                 description = 'Moving of PIN diode behind sample place',
                                 tangodevice = tango_digital + 'PinDiode',
                                 mapping = {'in':1, 'out':2},
                                 fmtstr = '%s',
                                ),
    pindiodesample      = device('devices.tango.AnalogInput',
                                 description = 'PIN diode behind sample place',
                                 tangodevice = tango_analog + 'PinDiode1',
                                ),
    pindiodesample_int  = device('devices.tango.AnalogInput',
                                 description = 'Integral of PIN diode behind sample place',
                                 tangodevice = tango_analog + 'IntPinDiode1',
                                 fmtstr = '%.10g',
                                ),
    pindiodesample_off  = device('devices.tango.AnalogOutput',
                                 description = 'Offset PIN diode behind sample place',
                                 tangodevice = tango_analog + 'PinDiode1_Offset',
                                ),
    pindiodecal         = device('devices.tango.AnalogInput',
                                 description = 'Calibrated PIN diode at sample place',
                                 tangodevice = tango_analog + 'PinDiode2',
                                ),
    pindiodecal_int     = device('devices.tango.AnalogInput',
                                 description = 'Integral of calibrated PIN diode at sample place',
                                 tangodevice = tango_analog + 'IntPinDiode2',
                                fmtstr = '%.10g',
                                ),
    pindiodecal_off     = device('devices.tango.AnalogOutput',
                                 description = 'Offset Calibrated PIN diode at sample place',
                                 tangodevice = tango_analog + 'PinDiode2_Offset',
                                ),
)
