description = 'JCNS humidity cell'
group = 'plugplay'

tango_base = 'tango://%s:10000/box/' % setupname

devices = {
    'T_%s_heater' % setupname: device('devices.tango.TemperatureController',
                               description = 'Temperature of heater',
                               tangodevice = tango_base + 'heater/control',
                               fmtstr = '%.1f',
                               unit = 'degC',
                               timeout = 600.0,
                               precision = 0.2,
                              ),
    'T_%s_julabo' % setupname: device('devices.tango.TemperatureController',
                               description = 'Temperature of Julabo',
                               tangodevice = tango_base + 'julabo/control',
                               fmtstr = '%.1f',
                               unit = 'degC',
                               timeout = 600.0,
                               precision = 0.2,
                              ),
    '%s_flowrate' % setupname: device('devices.tango.WindowTimeoutAO',
                               description = 'Flow rate through humidity cell',
                               tangodevice = tango_base + 'mhg/flowrate',
                               fmtstr = '%.1f',
                               unit = 'ml',
                               timeout = 600.0,
                               precision = 0.2,
                              ),
    '%s_humidity' % setupname: device('devices.tango.WindowTimeoutAO',
                               description = 'Humidity in humidity cell',
                               tangodevice = tango_base + 'mhg/humidity',
                               fmtstr = '%.1f',
                               unit = '%',
                               timeout = 600.0,
                               precision = 1,
                              ),
    'T_%s_cell' % setupname: device('devices.tango.Sensor',
                               description = 'Temperature in humidity cell',
                               tangodevice = tango_base + 'mhg/temperature',
                               fmtstr = '%.1f',
                               unit = 'degC',
                              ),
}
