description = 'vacuum system monitoring'

group = 'lowlevel'

tango_base = 'tango://phys.kws1.frm2:10000/kws1/'

devices = dict(
    pressure_p10 = device('nicos.devices.tango.Sensor',
        description = 'pressure at pump 11',
        tangodevice = tango_base + 'sps/pressure_p10',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p11 = device('nicos.devices.tango.Sensor',
        description = 'pressure in collimation chamber',
        tangodevice = tango_base + 'sps/pressure_p11',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p12 = device('nicos.devices.tango.Sensor',
        description = 'pressure in sample chamber',
        tangodevice = tango_base + 'sps/pressure_p12',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p13 = device('nicos.devices.tango.Sensor',
        description = 'pressure in detector tube',
        tangodevice = tango_base + 'sps/pressure_p13',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p14 = device('nicos.devices.tango.Sensor',
        description = 'pressure in KWS1 connection to Pfeiffer pump',
        tangodevice = tango_base + 'sps/pressure_p14',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p15 = device('nicos.devices.tango.Sensor',
        description = 'pressure in lens chamber',
        tangodevice = tango_base + 'sps/pressure_p15',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p16 = device('nicos.devices.tango.Sensor',
        description = 'pressure in chopper chamber',
        tangodevice = tango_base + 'sps/pressure_p16',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p24 = device('nicos.devices.tango.Sensor',
        description = 'pressure in KWS2 connection to Pfeiffer pump',
        tangodevice = tango_base + 'sps/pressure_p24',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),
    pressure_p34 = device('nicos.devices.tango.Sensor',
        description = 'pressure in SANS1 connection to Pfeiffer pump',
        tangodevice = tango_base + 'sps/pressure_p34',
        unit = 'mbar',
        fmtstr = '%.1e',
        lowlevel = True,
    ),

    pump_status = device('nicos.devices.tango.DigitalInput',
        description = 'pump status',
        tangodevice = tango_base + 'sps/pump_status',
        fmtstr = '%#02x',
        lowlevel = True,
    ),
    pump_manual_mode = device('nicos.devices.tango.DigitalInput',
        description = 'pump manual mode',
        tangodevice = tango_base + 'sps/pump_manual_mode',
        fmtstr = '%#02x',
        lowlevel = True,
    ),
    pump_request_mode = device('nicos.devices.tango.DigitalInput',
        description = 'pump request mode',
        tangodevice = tango_base + 'sps/pump_request_mode',
        fmtstr = '%#02x',
        lowlevel = True,
    ),
    pump_components_1 = device('nicos.devices.tango.DigitalInput',
        description = 'pump components state',
        tangodevice = tango_base + 'sps/pump_components_1',
        fmtstr = '%#016x',
        lowlevel = True,
    ),
    pump_components_2 = device('nicos.devices.tango.DigitalInput',
        description = 'pump components state',
        tangodevice = tango_base + 'sps/pump_components_2',
        fmtstr = '%#08x',
        lowlevel = True,
    ),
    ge_interlock = device('nicos.devices.tango.DigitalInput',
        description = 'state of SPS/GE power interlock',
        tangodevice = tango_base + 'sps/ge_interlock',
        fmtstr = '%#x',
        lowlevel = True,
    ),
    ge_interlock_timeout = device('nicos.devices.tango.DigitalInput',
        description = 'timeout state of individual 8-packs',
        tangodevice = tango_base + 'sps/ge_interlock_timeout',
        fmtstr = '%#x',
        lowlevel = True,
    ),
)
