description = 'Shutter and attenuators via Pilz box'

group = 'lowlevel'

tango_base = 'tango://pgaahw.pgaa.frm2.tum.de:10000/pgaa/pilz/'

devices = dict(
    shutter = device('nicos_mlz.pgaa.devices.pilz.Switch',
        description = 'secondary experiment shutter',
        tangodevice = tango_base + 'shutter',
        readback = tango_base + 'ishutter',
        error = tango_base + 'eshutter',
        remote = tango_base + 'erc',
        mapping = {'closed': 2,
                   'open': 1},
        maxage = 5,
        pollinterval = 2,
        timeout = 3,
    ),
    att1 = device('nicos_mlz.pgaa.devices.pilz.Attenuator',
        description = 'attenuator 1',
        tangodevice = tango_base + 'satt1',
        error = tango_base + 'eatt1',
        readback = tango_base + 'iatt1',
        remote = tango_base + 'erc',
        mapping = {'out': 0,
                   'in': 1},
        maxage = 5,
        pollinterval = 2,
        timeout = 3,
    ),
    att2 = device('nicos_mlz.pgaa.devices.pilz.Attenuator',
        description = 'attenuator 2',
        tangodevice = tango_base + 'satt2',
        error = tango_base + 'eatt2',
        readback = tango_base + 'iatt2',
        remote = tango_base + 'erc',
        mapping = {'out': 0,
                   'in': 1},
        maxage = 5,
        pollinterval = 2,
        timeout = 3,
    ),
    att3 = device('nicos_mlz.pgaa.devices.pilz.Attenuator',
        description = 'attenuator 3',
        tangodevice = tango_base + 'satt3',
        error = tango_base + 'eatt3',
        readback = tango_base + 'iatt3',
        remote = tango_base + 'erc',
        mapping = {'out': 0,
                   'in': 1},
        maxage = 5,
        pollinterval = 2,
        timeout = 3,
    ),
    att = device('nicos_mlz.pgaa.devices.Attenuator',
        description = 'Attenuator device',
        moveables = ['att1', 'att2', 'att3'],
        readables = None,
        precision = None,
        unit = '%',
        fmtstr = '%.1f',
        mapping = {
            100.: ('out', 'out', 'out'),
            47.: ('out', 'in', 'out'),
            16.: ('in', 'out', 'out'),
            7.5: ('in', 'in', 'out'),
            5.9: ('out', 'out', 'in'),
            3.5: ('out', 'in', 'in'),
            2.7: ('in', 'out', 'in'),
            1.6: ('in', 'in', 'in'),
        },
    ),
)
