description = 'monochromator setup'

group = 'lowlevel'

devices = dict(
    mtt = device('nicos.devices.generic.Axis',
        description = '2 theta axis moving sample table arm',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (40, 95),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    crystal_m = device('nicos.devices.generic.Axis',
        description = 'monochromator changer rotation table',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (1, 3),
            unit = 'deg',
        ),
        precision = 0.01,
    ),
    crystal = device('nicos.devices.generic.Switcher',
        description = 'monochromator changer',
        moveable = 'crystal_m',
        mapping = {
            'BPC': 1,
            'Ge': 2,
            'PG': 3,
        },
        precision = 0.01,
        unit = '',
    ),
    lms = device("nicos.devices.generic.Axis",
        description = "sample table arm translation",
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (1600, 2800),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = "%.2f",
    ),
)