description = 'monochromator setup'

group = 'lowlevel'

devices = dict(
    mtt = device('nicos.devices.generic.Axis',
        description = '2 theta axis moving sample table arm',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (40, 110),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    mtt_opMode = device('nicos.devices.generic.Switcher',
        description = '2 theta axis operation modes',
        moveable = 'mtt',
        mapping = {
            'min': 40,
            'hf': 70,
            'hi2': 42,
        },
        precision = 0.01,
        unit = '',
        lowlevel = True,
    ),
    crystal_m = device('nicos.devices.generic.Axis',
        description = 'monochromator changer translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 50),
            unit = 'cm',
        ),
        precision = 0.01,
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    crystal = device('nicos.devices.generic.Switcher',
        description = 'monochromator changer',
        moveable = 'crystal_m',
        mapping = {
            'BPC': 0,
            'Ge': 25,
            'PG': 50,
        },
        precision = 0.01,
        unit = '',
    ),
    omgm = device('nicos.devices.generic.Axis',
        description = 'OMGM',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (12, 63),
                unit = 'deg',
                speed = 1,
                curvalue = 39.4,
        ),
        precision = 0.005,
        fmtstr = '%.2f',
    ),
    tran_bpc = device('nicos.devices.generic.Axis',
        description = 'BPC translation',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'steps',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    inc_bpc = device('nicos.devices.generic.Axis',
        description = 'BPC inclination',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    cur_bpc = device('nicos.devices.generic.Axis',
        description = 'BPC curved',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    tran_ge = device('nicos.devices.generic.Axis',
        description = 'Ge translation',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'steps',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    inc_ge = device('nicos.devices.generic.Axis',
        description = 'Ge inclination',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    cur_ge = device('nicos.devices.generic.Axis',
        description = 'Ge curved',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    tran_pg = device('nicos.devices.generic.Axis',
        description = 'PG translation',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'steps',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    inc_pg = device('nicos.devices.generic.Axis',
        description = 'PG inclination',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    cur_pg = device('nicos.devices.generic.Axis',
        description = 'PG curved',
        motor = device('nicos.devices.generic.VirtualMotor',
                abslimits = (1, 5),
                unit = 'deg',
                speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    tthm_r = device('nicos_mlz.stressi.devices.wavelength.TransformedMoveable',
        description = 'Base hardware device',
        dev = 'mtt',
        informula = '1./0.956 * x - 11.5 / 0.956',
        outformula = '0.956 * x + 11.5',
        precision = 0.01,
        lowlevel = True,
    ),
    wavelength = device('nicos_mlz.stressi.devices.wavelength.Wavelength',
        description = 'The incoming wavelength',
        omgm = 'omgm',
        crystal = 'crystal',
        plane = '311',
        base = 'tthm_r',
        unit = 'AA',
        fmtstr = '%.2f',
        abslimits = (0.9, 2.5),
    ),
)
