description = 'memograph readout'

includes = []

group = 'optional'

devices = dict(
    t_in_resi      = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'T_in RESI',
                            description = 'inlet temperature memograph',
                            fmtstr = '%.2F',
                            warnlimits = (-1, 17.5), #-1 no lower value
                            unit = 'degC',
                           ),
    t_out_resi     = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'T_out RESI',
                            description = 'outlet temperature memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'degC',
                           ),
    p_in_resi      = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'P_in RESI',
                            description = 'inlet pressure memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'bar',
                           ),
    p_out_resi     = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'P_out RESI',
                            description = 'outlet pressure memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'bar',
                           ),
    flow_in_resi   = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'FLOW_in RESI',
                            description = 'inlet flow memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            warnlimits = (0.2, 100), #100 no upper value
                            unit = 'l/min',
                           ),
    flow_out_resi  = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'FLOW_out RESI',
                            description = 'outlet flow memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'l/min',
                           ),
    leak_resi      = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'Leak RESI',
                            description = 'leakage memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            warnlimits = (-1, 1), #-1 no lower value
                            unit = 'l/min',
                           ),
    cooling_resi   = device('nicos_mlz.frm2.devices.memograph.MemographValue',
                            hostname = 'memograph-uja01.care.frm2',
                            group = 1,
                            valuename = 'Cooling RESI',
                            description = 'cooling power memograph',
                            pollinterval = 30,
                            maxage = 60,
                            fmtstr = '%.2F',
                            unit = 'kW',
                           ),
)
