description = 'PGAA detectors'

group = 'lowlevel'

devices = dict(
    truetim = device('nicos_virt_mlz.pgaa.devices.DSPecTimer',
        description = 'True time timer',
        type = 'truetime',
        fmtstr = '%.2f',
        unit = 's',
        visibility = (),
    ),
    livetim = device('nicos_virt_mlz.pgaa.devices.DSPecTimer',
        description = 'Live time timer',
        type = 'livetime',
        fmtstr = '%.2f',
        unit = 's',
        visibility = (),
    ),
    image_60p = device('nicos_virt_mlz.pgaa.devices.DSPecSpectrum',
        description = 'Image data device',
        fmtstr = '%d',
        pollinterval = 86400,
        size = (16384, 1),
        visibility = (),
        prefix = 'P'
    ),
    _60p = device('nicos_virt_mlz.pgaa.devices.DSPec',
        description = 'DSPec detector for high energy gamma x-rays ',
        timers = ['truetim', 'livetim'],
        images = ['image_60p', ],  # 'image_lege',],
        gates = ['shutter'],
        enablevalues = ['open'],
        disablevalues = ['closed'],
        pollinterval = None,
        liveinterval = 0.5,
        prefix = 'P'
    ),
    image_lege = device('nicos_virt_mlz.pgaa.devices.DSPecSpectrum',
        description = 'Image data device',
        fmtstr = '%d',
        pollinterval = 86400,
        size = (16384, 1),
        visibility = (),
        prefix = 'L',
    ),
    LEGe = device('nicos_virt_mlz.pgaa.devices.DSPec',
        description = 'DSPec detector for low energy gamma x-rays',
        timers = ['truetim', 'livetim'],
        images = ['image_lege'],
        gates = ['shutter'],
        enablevalues = ['open'],
        disablevalues = ['closed'],
        pollinterval = None,
        liveinterval = 0.5,
        prefix = 'L'
    ),
    # image_lege = device('nicos_virt_mlz.pgaa.devices.DSPecSpectrum',
    #     description = 'Image data device',
    #     fmtstr = '%d',
    #     pollinterval = 86400,
    #     size = (16384, 1),
    #     visibility = (),
    #     prefix = 'L'
    # ),
    # LEGe = device('nicos_virt_mlz.pgaa.devices.DSPec',
    #     description = 'DSPec detector for low energy gamma x-rays',
    #     timers = ['truetim', 'livetim'],
    #     images = ['image_lege'],
    #     gates = ['shutter'],
    #     enablevalues = ['open'],
    #     disablevalues = ['closed'],
    #     pollinterval = None,
    #     liveinterval = 0.5,
    #     prefix = 'L'
    # ),
)
