description = 'correction coil motors'
group = 'optional'

devices = dict(
    mo_cc11a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil A4 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc11b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil A3 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc12a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil B2 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc12b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil B1 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc21a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata', 'namespace')
    ),
    mo_cc21b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil',
        userlimits = (-5, 5),
        abslimits=(-5, 5),
        speed=1.,
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata', 'namespace')
    ),
    mo_cc22a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata', 'namespace')
    ),
    mo_cc22b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata', 'namespace')
    ),
    mo_cc31a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil A2 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc31b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil A1 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc32a = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil B3 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
    mo_cc32b = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'correction coil B4 position',
        userlimits = (-5, 5),
        abslimits = (-5, 5),
        speed = 1.,
        unit = 'mm',
        fmtstr = '%.6f',
        pollinterval = 0.5,
    ),
)
