description = 'PLCs analog inputs'
group = 'optional'

devices = dict(
    cc1r1 = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'Temp cc1r1',
        userlimits = (0, 100),
        abslimits = (0, 100),
        speed = 20.,
        unit = 'degC',
        fmtstr = '%.3g',
    ),
    cc1r2 = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'Temp cc1r2',
        userlimits = (0, 100),
        abslimits = (0, 100),
        speed = 20.,
        unit = 'degC',
        fmtstr = '%.3g',
    ),
    cc3r1 = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'Temp cc3r1',
        userlimits = (0, 100),
        abslimits = (0, 100),
        speed = 20.,
        unit = 'degC',
        fmtstr = '%.3g',
    ),
    cc3r2 = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'Temp cc3r2',
        userlimits = (0, 100),
        abslimits = (0, 100),
        speed = 20.,
        unit = 'degC',
        fmtstr = '%.3g',
    ),
    HeMon = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'He percentage',
        userlimits = (0, 100),
        abslimits = (0, 100),
        speed = 20.,
        unit = '%',
        fmtstr = '%.3g',
    ),
    MagB1x = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 1 x component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagB1y = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 1 y component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagB1z = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 1 z component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagB2x = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 2 x component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagB2y = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 2 y component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagB2z = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi/2 2 z component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagBx = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi flipper x component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagBy = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi flipper y component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
    MagBz = device(
        'nicos.devices.generic.virtual.VirtualMotor',
        description = 'B sensor pi flipper z component',
        userlimits = (-10, 10),
        abslimits = (-10, 10),
        speed = 4.,
        unit = 'G',
        fmtstr = '%.3g',
    ),
)
