description = 'Cryopad'

group = 'optional'

includes = []

nethost = 'cryopad.poli.frm2'

devices = dict(
#    LHe = device('devices.taco.AnalogInput',
#                 description = 'The helium filling level',
#                 tacodevice = '//%s/heidi2/clmhe/level' % (nethost, ),
#                 fmtstr = '%.1f',
#                 unit = '%',
#                 pollinterval = 120,
#                 maxage = 241,
#                ),
#    LN2 = device('devices.taco.AnalogInput',
#                 description = 'The nitrogen filling level',
#                 tacodevice = '//%s/heidi2/clmhe/level' % (nethost, ),
#                 fmtstr = '%.1f',
#                 unit = '%',
#                 pollinterval = 120,
#                 maxage = 241,
#                ),
    decpolcorr1 = device('devices.taco.CurrentSupply',
                         description = 'De(te)c(tor)pol(arizer) correction current 1',
                         tacodevice = '//%s/heidi2/decpolcorr1/current' % (nethost,),
                         fmtstr = '%.2f',
                         abslimits = (0, 2),
                         unit = 'A',
                         pollinterval = 60,
                         maxage = 65,
                        ),
    decpolcorr2 = device('devices.taco.CurrentSupply',
                         description = 'De(te)c(tor)pol(arizer) correction current 2',
                         tacodevice = '//%s/heidi2/decpolcorr2/current' % (nethost,),
                         fmtstr = '%.2f',
                         abslimits = (0, 2),
                         unit = 'A',
                         pollinterval = 60,
                         maxage = 65,
                        ),
    decpolmain = device('devices.taco.CurrentSupply',
                        description = 'De(te)c(tor)pol(arize) main current',
                        tacodevice = '//%s/heidi2/decpolmain/current' % (nethost,),
                        fmtstr = '%.2f',
                        unit = 'A',
                        pollinterval = 10,
                        maxage = 15,
                        abslimits = (0, 2),
                       ),
    polarcorr1 = device('devices.taco.CurrentSupply',
                        description = 'Polarizer correction current 1',
                        tacodevice = '//%s/heidi2/polarbeam/current' % (nethost,),
                        fmtstr = '%.2f',
                        abslimits = (0, 2),
                        unit = 'A',
                        pollinterval = 60,
                        maxage = 65,
                       ),
    polarmain = device('devices.taco.CurrentSupply',
                       description = 'Polarizer main current',
                       tacodevice = '//%s/heidi2/polarmain/current' % (nethost,),
                       fmtstr = '%.2f',
                       abslimits = (0, 2),
                       unit = 'A',
                       pollinterval = 60,
                       maxage = 65,
                      ),
    polarcorr2 = device('devices.taco.CurrentSupply',
                        description = 'Polarizer correction current 2',
                        tacodevice = '//%s/heidi2/polarnut/current' % (nethost,),
                        fmtstr = '%.2f',
                        abslimits = (0, 2),
                        unit = 'A',
                        pollinterval = 60,
                        maxage = 65,
                       ),
#    cryo_t1 = device('devices.taco.TemperatureSensor',
#                     description = 'The cryopad temperature',
#                     tacodevice = '//%s/heidi2/ls211/sens1' % (nethost,),
#                     unit = 'K',
#                     fmtstr = '%.3f',
#                     pollinterval = 15,
#                     maxage = 31,
#                    ),
    nutator1c = device('devices.taco.CurrentSupply',
                       description = 'Nutator 1 current',
                       tacodevice = '//%s/heidi2/nutator1/current' % (nethost,),
                       fmtstr = '%.2f',
                       abslimits = (-3, 3),
                       unit = 'A',
                       pollinterval = 60,
                       maxage = 65,
                      ),
    nutator2c = device('devices.taco.CurrentSupply',
                       description = 'Nutator 2 current',
                       tacodevice = '//%s/heidi2/nutator2/current' % (nethost,),
                       fmtstr = '%.2f',
                       abslimits = (-3, 3),
                       unit = 'A',
                       pollinterval = 60,
                       maxage = 65,
                      ),
    nutax = device('devices.taco.CurrentSupply',
                   description = 'Nutator axial current',
                   tacodevice = '//%s/heidi2/nutax12/current' % (nethost,),
                   fmtstr = '%.2f',
                   abslimits = (0, 3),
                   unit = 'A',
                   pollinterval = 60,
                   maxage = 65,
                  ),
    pc1   = device('devices.taco.CurrentSupply',
                   description = 'Precession coil 1 current',
                   tacodevice = '//%s/heidi2/pc1/current' % (nethost,),
                   fmtstr = '%.2f',
                   abslimits = (-5, 5),
                   unit = 'A',
                   pollinterval = 60,
                   maxage = 65,
                  ),
    pc2   = device('devices.taco.CurrentSupply',
                   description = 'Precession coil 2 current',
                   tacodevice = '//%s/heidi2/pc2/current' % (nethost,),
                   fmtstr = '%.2f',
                   abslimits = (-5, 5),
                   unit = 'A',
                   pollinterval = 60,
                   maxage = 65,
                  ),
)
