description = 'POLI silicon monochromator'

group = 'lowlevel'

includes = ['mono', ]

excludes = []

tango_base = 'tango://phys.poli.frm2:10000/poli/'

devices = dict(
    bmv = device('devices.tango.Motor',
                 description = 'Monochromator vertical opening slit',
                 tangodevice = tango_base + 'fzjs7/bmv',
                 fmtstr = '%.2f',
                 abslimits = (114, 190),
                 precision = 0.2,
                 lowlevel = False,
                ),
    bmh = device('devices.tango.Motor',
                 description = 'Monochromator horizontal opening slit',
                 tangodevice = tango_base + 'fzjs7/bmh',
                 fmtstr = '%.2f',
                 abslimits = (6.5, 80),
                 precision = 0.2,
                 lowlevel = False,
                ),
    bm  = device('devices.generic.TwoAxisSlit',
                 description = 'Monochromator slit',
                 pollinterval = 15,
                 maxage = 61,
                 fmtstr = '%.2f %.2f',
                 horizontal = 'bmh',
                 vertical = 'bmv',
                ),

    bpl = device('devices.tango.Motor',
                 description = 'Aperture sample left',
                 tangodevice = tango_base + 'fzjs7/bpl',
                 lowlevel = True,
                 precision = 0.1,
                ),
    bpr = device('devices.tango.Motor',
                 description = 'Aperture sample right',
                 tangodevice = tango_base + 'fzjs7/bpr',
                 lowlevel = True,
                 precision = 0.1,
                ),
    bpo = device('devices.tango.Motor',
                 description = 'Aperture sample upper',
                 tangodevice = tango_base + 'fzjs7/bpo',
                 lowlevel = True,
                 precision = 0.1,
                ),
    bpu = device('devices.tango.Motor',
                 description = 'Aperture sample lower',
                 tangodevice = tango_base + 'fzjs7/bpu',
                 lowlevel = True,
                 precision = 0.1,
                ),
    bp  = device('devices.generic.Slit',
                 description = 'Aperture before sample',
                 left = 'bpl',
                 right = 'bpr',
                 bottom = 'bpu',
                 top = 'bpo',
                 pollinterval = 5,
                 maxage = 10,
                 coordinates = 'opposite',
                 opmode = '4blades_opposite',
                ),
)
