description = 'POLI sample table'

group = 'lowlevel'
includes = ['alias_sth']
excludes = ['table']

tango_base = 'tango://phys.poli.frm2:10000/poli/'

devices = dict(
    co_omega = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/omegaenc',
                      unit = 'deg',
                     ),
    mo_omega = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/omegamot',
                      abslimits = (-180, 180),
                      unit = 'deg',
                      precision = 0.005,
                     ),
    omega    = device('devices.generic.Axis',
                      description = 'table omega axis',
                      motor = 'mo_omega',
                      coder = 'co_omega',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.005,
                     ),

    co_gamma = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/2thetaenc',
                      unit = 'deg',
                     ),
    mo_gamma = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/2thetamot',
                      abslimits = (-20, 130),
                      unit = 'deg',
                      precision = 0.005,
                     ),
    gamma    = device('devices.generic.Axis',
                      description = 'table gamma axis',
                      motor = 'mo_gamma',
                      coder = 'co_gamma',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.005,
                     ),

    co_chi1  = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/chi1enc',
                      unit = 'deg',
                     ),
    mo_chi1  = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/chi1mot',
                      abslimits = (-5, 5),
                      unit = 'deg',
                      precision = 0.005,
                     ),
    chi1     = device('devices.generic.Axis',
                      description = 'table chi1 axis',
                      motor = 'mo_chi1',
                      coder = 'co_chi1',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.005,
                     ),

    co_chi2  = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/chi2enc',
                      unit = 'deg',
                     ),
    mo_chi2  = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/chi2mot',
                      abslimits = (-5, 5),
                      unit = 'deg',
                      precision = 0.005,
                     ),
    chi2     = device('devices.generic.Axis',
                      description = 'table chi2 axis',
                      motor = 'mo_chi2',
                      coder = 'co_chi2',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.005,
                     ),

    co_xtrans = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/xenc',
                      unit = 'mm',
                     ),
    mo_xtrans = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/xmot',
                      abslimits = (-15, 15),
                      unit = 'mm',
                      precision = 0.01,
                     ),
    xtrans   = device('devices.generic.Axis',
                      description = 'table x translation axis',
                      motor = 'mo_xtrans',
                      coder = 'co_xtrans',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),

    co_ytrans = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/yenc',
                      unit = 'mm',
                     ),
    mo_ytrans = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'table/ymot',
                      abslimits = (-15, 15),
                      unit = 'mm',
                      precision = 0.01,
                     ),
    ytrans   = device('devices.generic.Axis',
                      description = 'table y translation axis',
                      motor = 'mo_ytrans',
                      coder = 'co_ytrans',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),

    co_lftctr = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = tango_base + 'lftctr/lftctrenc',
                      unit = 'deg',
                     ),
    mo_lftctr = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = tango_base + 'lftctr/lftctrmot',
                      unit = 'deg',
                      precision = 0.01,
                     ),
    liftingctr = device('devices.generic.Axis',
                      description = 'lifting counter axis',
                      motor = 'mo_lftctr',
                      coder = 'co_lftctr',
                      pollinterval = 15,
                      maxage = 61,
                      fmtstr = '%.2f',
                      abslimits = (-4.2, 25),
                      precision = 0.01,
                     ),
#    liftingctr = device('devices.generic.VirtualMotor',
#                      description = 'lifting counter axis',
#                      pollinterval = 15,
#                      maxage = 61,
#                      fmtstr = '%.2f',
#                      abslimits = (-5, 30),
#                      precision = 0.01,
#                      unit = 'deg',
#                     ),


    lubrication = device('poli.lubrication.LubeSwitch',
                      description = 'lubrication switch',
                      tangodevice = tango_base + 'fzjdp_digital/lubrication',
                      lowlevel = True,
                     ),
)

alias_config = {
    'sth': {'omega': 100}
}
