description = 'motors from the huber euler cratle'

group = 'optional'
excludes = ['eulercradle']

devices = dict(
    # x-axis
    stex_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Sample translation x-Axis motor',
        abslimits = (-50, 50),
        speed = 10,
        unit = 'mm',
        visibility = (),
    ),
    stex = device('nicos.devices.generic.Axis',
        description = 'Sample translation x-Axis motor',
        motor = 'stex_m',
        precision = 0.001,
    ),
    # y-axis
    stey_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Sample translation y-Axis motor',
        abslimits = (-50, 50),
        speed = 10,
        unit = 'mm',
        visibility = (),
    ),
    stey = device('nicos.devices.generic.Axis',
        description = 'Sample translation y-Axis motor',
        motor = 'stey_m',
        precision = 0.001,
    ),
    # z-axis
    stez_m = device('nicos.devices.generic.VirtualMotor',
        abslimits = (0, 20),
        speed = 10,
        unit = 'mm',
        visibility = (),
    ),
    stez = device('nicos.devices.generic.Axis',
        description = 'Sample translation z-Axis motor',
        motor = 'stez_m',
        precision = 0.001,
    ),
    # Chi-axis
    sphi_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Sample Rotation phi-Axis motor',
        abslimits = (0, 360),
        speed = 10,
        unit = 'deg',
        visibility = (),
    ),
    sphi = device('nicos.devices.generic.Axis',
        description = 'Sample Rotation phi-Axis motor',
        motor = 'sphi_m',
        precision = 0.001,
    ),
    # Phi-axis
    schi_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Sample Rotation Pchihi-Axis motor',
        abslimits = (0, 90),
        speed = 10,
        unit = 'deg',
        visibility = (),
    ),
    schi = device('nicos.devices.generic.Axis',
        description = 'Sample Rotation chi-Axis motor',
        motor = 'schi_m',
        precision = 0.001,
    ),
)
