description = 'HERMES collimation system'
group = 'optional'
display_order = 2

tango_base = 'tango://phys.hermes.jcns.fz-juelich.de:10000/hermes/'

devices = dict(
    m1theta = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/m1theta',
        description = 'Collimator 1 mirror rotation.',
    ),
    m1z = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/m1z',
        description = 'Collimator 1 mirror vertical translation.',
    ),
    m2theta = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/m2theta',
        description = 'Collimator 2 mirror rotation.',
    ),
    m2z = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/m2z',
        description = 'Collimator 2 vertical translation.',
    ),
    d0t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d0t',
        description = 'Detector collimator 1 top blade.',
        fixed = 'slit d0 must remain completely open',
        fixedby = ('ADMIN', 20),
    ),
    d0b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d0b',
        description = 'Detector collimator 0 bottom blade.',
        fixed = 'slit d0 must remain completely open',
        fixedby = ('ADMIN', 20),
    ),
    d0 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 0 slit.',
        bottom = 'd0b',
        top = 'd0t',
        coordinates = 'opposite',
        opmode = 'offcentered',
    ),
    d1t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d1t',
        description = 'Detector collimator 1 top blade.',
    ),
    d1b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d1b',
        description = 'Detector collimator 1 bottom blade.',
    ),
    d1 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 1 slit.',
        bottom = 'd1b',
        top = 'd1t',
        coordinates = 'opposite',
        opmode = 'offcentered',
    ),
    d2t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d2t',
        description = 'Detector collimator 2 top blade.',
    ),
    d2b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d2b',
        description = 'Detector collimator 2 bottom blade.',
    ),
    d2 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 2 slit.',
        bottom = 'd2b',
        top = 'd2t',
        coordinates = 'opposite',
        opmode = 'offcentered',
    ),
    d3t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d3t',
        description = 'Detector collimator 3 top blade.',
    ),
    d3b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'euromove_motor/d3b',
        description = 'Detector collimator 3 bottom blade.',
    ),
    d3 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 3 slit.',
        bottom = 'd3b',
        top = 'd3t',
        coordinates = 'opposite',
        opmode = 'offcentered',
    ),

)
