description = 'HERMES detector collimator and Helium-3 tube'
group = 'optional'
display_order = 4

tango_base = 'tango://phys.hermes.jcns.fz-juelich.de:10000/hermes/euromove/'

devices = dict(
    detangle = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'detangle',
        description = 'Detector angle.',
    ),
    detz = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'detz',
        description = 'Detector vertical translation.',
    ),
    d0t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd0t',
        description = 'Detector collimator 1 top blade.',
        fixed = 'slit d0 must remain completely open',
        fixedby = ('ADMIN', 20),
    ),
    d0b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd1b',
        description = 'Detector collimator 0 bottom blade.',
        fixed = 'slit d0 must remain completely open',
        fixedby = ('ADMIN', 20),
    ),
    d0 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 0 slit.',
        bottom = 'd0b',
        top = 'd0t',
        opmode = 'centered',
    ),
    d1t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd1t',
        description = 'Detector collimator 1 top blade.',
    ),
    d1b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd1b',
        description = 'Detector collimator 1 bottom blade.',
    ),
    d1 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 1 slit.',
        bottom = 'd1b',
        top = 'd1t',
        opmode = 'centered',
    ),
    d2t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd2t',
        description = 'Detector collimator 2 top blade.',
    ),
    d2b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd2b',
        description = 'Detector collimator 2 bottom blade.',
    ),
    d2 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 2 slit.',
        bottom = 'd2b',
        top = 'd2',
        opmode = 'centered',
    ),
    d3t = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd3t',
        description = 'Detector collimator 3 top blade.',
    ),
    d3b = device('nicos.devices.entangle.Motor',
        tangodevice = tango_base + 'd3b',
        description = 'Detector collimator 3 bottom blade.',
    ),
    d3 = device('nicos.devices.generic.slit.VerticalGap',
        description = 'Detector collimator 3 slit.',
        bottom = 'd3b',
        top = 'd3t',
        opmode = 'centered',
    ),
)
