description = "DoubleSlit [slit k1] between nok8 and nok9"

group = 'lowlevel'

includes = ['nok_ref', 'nokbus4']
global_values = configdata('global.GLOBAL_Values')

nethost = 'refsanssrv.refsans.frm2'
tango_host = 'tango://refsanshw:10000/test/'

devices = dict(
    bs1 = device('nicos_mlz.refsans.devices.slits.DoubleSlit',
        description = 'BS1 double between nok8 and nok9',
        fmtstr = 'opening: %.3f mm, zpos: %.3f mm',
        unit = '',
        slit_r = 'bs1r',
        slit_s = 'bs1s',
    ),
    bs1r = device('nicos_mlz.refsans.devices.slits.SingleSlit',
        description = 'bs1 slit, reactor side',
        motor = 'bs1r_axis',
        nok_start = 9764.5,
        nok_length = 6.0,
        # nok_motor = [9764.75, 9770.25],
        nok_end = 9770.5,
        nok_gap = 18.0,
        masks = {
            'slit':   -1.725,  # -2.325, #2.425, #-2.325,  # 0,
            'point':  -2.325,  # 0,
            'gisans': -40.915,  # -40,
        },
        lowlevel = True,
        unit = 'mm',
    ),
    bs1s = device('nicos_mlz.refsans.devices.slits.SingleSlit',
        description = 'bs1 slit, sample side',
        motor = 'bs1s_axis',
        nok_start = 9764.5,
        nok_length = 6.0,
        # nok_motor = [9764.75, 9770.25],
        nok_end = 9770.5,
        nok_gap = 18.0,
        masks = {
            'slit':   -2.255,  # -1.655, # -6.405, #-1.655,  # 0,
            'point':  -1.655,  # 0,
            'gisans': 0.915,  # 0,
        },
        lowlevel = True,
        unit = 'mm',
    ),
    bs1r_axis = device('nicos.devices.generic.Axis',
        description = 'Axis of BS1, reactor side',
        motor = 'bs1r_motor',
        # coder = 'bs1r_motor',
        # obs = ['bs1r_obs'],
        backlash = 0,
        precision = 0.05,
        unit = 'mm',
        lowlevel = True,
    ),
    bs1_srll = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srll of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srll' % nethost,
        lowlevel = True,
    ),
    bs1_srhl = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srhl of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srhl' % nethost,
        lowlevel = True,
    ),
    bs1_srref = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srref of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srref' % nethost,
        lowlevel = True,
    ),
    bs1_srrel = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srrel of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srrel' % nethost,
        lowlevel = True,
    ),
    bs1_srsll = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srsll of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srsll' % nethost,
        lowlevel = True,
    ),
    bs1_srshl = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/srshl of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/srshl' % nethost,
        lowlevel = True,
    ),
    bs1r_motor = device('nicos_mlz.refsans.devices.nok_support.NOKMotorIPC',
        description = 'IPC controlled Motor of BS1, reactor side',
        abslimits = (-178.0, 10.0),
        bus = 'nokbus4',     # from ipcsms_*.res
        addr = 0x67,     # from resources.inf
        slope = 800.0,   # FULL steps per physical unit
        speed = 50,
        accel = 50,
        confbyte = 32,
        ramptype = 2,
        microstep = 1,
        refpos = -41.8,  # from ipcsms_*.res
        zerosteps = int(791.825 * 800),  # offset * slope
        lowlevel = global_values['hide_poti'],
    ),
    bs1r_acc = device('nicos_mlz.refsans.devices.nok_support.MotorEncoderDifference',
         description = 'calc error Motor and poti',
         motor = 'bs1r_motor',
         analog = 'bs1r_obs',
         lowlevel = global_values['hide_acc'],
         unit = 'mm'
    ),
    bs1r_obs = device('nicos_mlz.refsans.devices.nok_support.NOKPosition',
        description = 'Position sensing for BS1, reactor side',
        reference = 'nok_refc2',
        measure = 'bs1r_poti',
        poly = [-103.9, 998.068 / 3.835],   # off, mul * 1000 / sensitivity, higher orders...
        serial = 7542,
        length = 250.0,
        lowlevel = global_values['hide_poti'],
    ),
    bs1r_poti = device('nicos_mlz.refsans.devices.nok_support.NOKMonitoredVoltage',
        description = 'Poti for BS1, reactor side',
        tangodevice = tango_host + 'wb_c/2_1',
        scale = 1,   # mounted from bottom
        lowlevel = True,
    ),
    bs1s_axis = device('nicos.devices.generic.Axis',
        description = 'Axis of BS1, sample side',
        motor = 'bs1s_motor',
        # coder = 'bs1s_motor',
        # obs = ['bs1s_obs'],
        backlash = 0,
        precision = 0.05,
        unit = 'mm',
        lowlevel = True,
    ),
    bs1_ssll = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/ssll of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/ssll' % nethost,
        lowlevel = True,
    ),
    bs1_sshl = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/sshl of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/sshl' % nethost,
        lowlevel = True,
    ),
    bs1_ssref = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/ssref of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/ssref' % nethost,
        lowlevel = True,
    ),
    bs1_ssrel = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/ssrel of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/ssrel' % nethost,
        lowlevel = True,
    ),
    bs1_sssll = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/sssll of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/sssll' % nethost,
        lowlevel = True,
    ),
    bs1_ssshl = device('nicos.devices.taco.DigitalInput',
        description = 'Device test/bs1/ssshl of Server ipcsmsserver bs1',
        tacodevice = '//%s/test/bs1/ssshl' % nethost,
        lowlevel = True,
    ),
    bs1s_motor = device('nicos_mlz.refsans.devices.nok_support.NOKMotorIPC',
        description = 'IPC controlled Motor of BS1, sample side',
        abslimits = (-177.002, 139.998),
        bus = 'nokbus4',     # from ipcsms_*.res
        addr = 0x68,     # from resources.inf
        slope = 800.0,   # FULL steps per physical unit
        speed = 50,
        accel = 50,
        confbyte = 32,
        ramptype = 2,
        microstep = 1,
        refpos = 89.529,     # from ipcsms_*.res
        zerosteps = int(660.44 * 800),   # offset * slope
        lowlevel = global_values['hide_poti'],
    ),
    bs1s_acc = device('nicos_mlz.refsans.devices.nok_support.MotorEncoderDifference',
         description = 'calc error Motor and poti',
         motor = 'bs1s_motor',
         analog = 'bs1s_obs',
         lowlevel = global_values['hide_acc'],
         unit = 'mm'
    ),
    bs1s_obs = device('nicos_mlz.refsans.devices.nok_support.NOKPosition',
        description = 'Position sensing for BS1, sample side',
        reference = 'nok_refc2',
        measure = 'bs1s_poti',
        poly = [41.2, 999.452 / 1.919],  # off, mul * 1000 / sensitivity, higher orders...
        serial = 7784,
        length = 500.0,
        lowlevel = global_values['hide_poti'],
    ),
    bs1s_poti = device('nicos_mlz.refsans.devices.nok_support.NOKMonitoredVoltage',
        description = 'Poti for BS1, sample side',
        tangodevice = tango_host + 'wb_c/2_5',
        scale = 1,   # mounted from bottom
        lowlevel = True,
    ),
)
