description = 'h3 aperture devices MANUAL only'

# group = 'lowlevel'
group = 'optional'

#h3 not in full function, therefore copy of b1
if False:
    uribase = 'tango://refsansctrl01.refsans.frm2:10000/refsans/h3/'
    devices = dict(
        h3_m1 = device('nicos.devices.tango.Actuator',
            tangodevice = uribase + '_blende_h3_m1',
            lowlevel = True,
        ),
        h3_m2 = device('nicos.devices.tango.Actuator',
            tangodevice = uribase + '_blende_h3_m2',
            lowlevel = True,
        ),
        h3_m3 = device('nicos.devices.tango.Actuator',
            tangodevice = uribase + '_blende_h3_m3',
            lowlevel = True,
        ),
        h3_m4 = device('nicos.devices.tango.Actuator',
            tangodevice = uribase + '_blende_h3_m4',
            lowlevel = True,
        ),
        h3 = device('nicos.devices.generic.Slit',
            description = 'h3 aperture',
            top = 'h3_m4',
            bottom = 'h3_m3',
            left = 'h3_m1',
            right = 'h3_m2',
            coordinates = 'opposite',
            opmode = '4blades',
        ),
    )
elif False:
  devices = dict(
      h3_width = device('nicos.devices.generic.ManualMove',
          description = 'width of h3 MANUAL',
          abslimits = (0, 100),
          fmtstr = '%.1f',
          unit = 'mm',
      ),
      h3_center = device('nicos.devices.generic.ManualMove',
          description = 'center of h3 MANUAL',
          abslimits = (-100, 100),
          fmtstr = '%.1f',
          unit = 'mm',
      ),
  )
if True:
    nethost = 'refsanssrv.refsans.frm2'
    devices = dict(
        h3 = device('nicos_mlz.refsans.devices.slits.DoubleSlit',
            description = 'h3 together with b3',
            fmtstr = 'opening: %.3f mm, xpos: %.3f mm',
            unit = '',
            slit_r = 'h3r',
            slit_s = 'h3s',
        ),
        h3_mode = device('nicos.devices.generic.ReadonlyParamDevice',
            description = 'h3 mode',
            device = 'h3',
            parameter = 'mode',
        ),
        h3r = device('nicos_mlz.refsans.devices.slits.SingleSlit',
            description = 'h3 blade side?',
            motor = 'h3_r',
            nok_start = -1,
            nok_length = -1,
            # nok_motor = [11049.50, 11064.50],
            nok_end = -1,
            nok_gap = -1,
            masks = {
                'slit':   0,
                'point':  0,
                'gisans': 0,
            },
            lowlevel = True,
            unit = 'mm',
        ),
        h3s = device('nicos_mlz.refsans.devices.slits.SingleSlit',
            description = 'h3 blade side?',
            motor = 'h3_s',
            nok_start = -1,
            nok_length = -1,
            # nok_motor = [11049.50, 11064.50],
            nok_end = -1,
            nok_gap = -1,
            masks = {
                'slit':   0,
                'point':  0,
                'gisans': 0,
            },
            lowlevel = True,
            unit = 'mm',
        ),
        h3_r = device('nicos.devices.generic.Axis',
            description = 'h3, reactorside',
            motor = 'h3_rm',
            coder = 'h3_rm',
            #offset = 0.0,
            precision = 0.03,
            lowlevel = True,
        ),
        h3_s = device('nicos.devices.generic.Axis',
            description = 'h3, sampleside',
            motor = 'h3_sm',
            coder = 'h3_sm',
            #offset = 0.0,
            precision = 0.03,
            lowlevel = True,
        ),
        h3_rm = device('nicos_mlz.refsans.devices.beckhoff.nok.BeckhoffMotorCab1M0x',
            description = 'tbd',
            tacodevice = '//%s/test/modbus/probenort'% (nethost,),
            address = 0x3214+0*10, # dez12820
            slope = -10000,
            unit = 'mm',
            # abslimits = (-193.0, 130.0),
            abslimits = (-393.0, 330.0),
            ruler = -200.0,
            lowlevel = True,
        ),
        h3_sm = device('nicos_mlz.refsans.devices.beckhoff.nok.BeckhoffMotorCab1M0x',
            description = 'tbd',
            tacodevice = '//%s/test/modbus/probenort'% (nethost,),
            address = 0x3214+1*10, # dez12820
            slope = 10000,
            unit = 'mm',
            abslimits = (-102.0, 170.0),
            ruler = 0.0,
            lowlevel = True,
        ),
    )
else:
    nethost = 'refsanssrv.refsans.frm2'
    devices = dict(
        h3 = device('nicos_mlz.refsans.devices.nok_support.DoubleSlit',
            description = 'tbd',
            nok_start = -1,
            nok_length =-1,
            nok_end = -1,
            nok_gap = -1,
            inclinationlimits = (-1000, 1000),
            masks = dict(
                slit = [0.0, 0.0, 0.0, 82.0],
                pinhole = [0.0, 0.0, 0.0, 0.0],
                gisans = [0.0, 0.0, 0.0, 0.0],
            ),
            motor_r = 'h3_r',
            motor_s = 'h3_s',
            nok_motor = [-1, -1],
            backlash = 0,
            precision = 0.03,
        ),
        h3_r = device('nicos.devices.generic.Axis',
            description = 'h3, reactorside',
            motor = 'h3_rm',
            coder = 'h3_rm',
            #offset = 0.0,
            precision = 0.03,
            lowlevel = True,
        ),
        h3_s = device('nicos.devices.generic.Axis',
            description = 'h3, sampleside',
            motor = 'h3_sm',
            coder = 'h3_sm',
            #offset = 0.0,
            precision = 0.03,
            lowlevel = True,
        ),
        h3_rm = device('nicos_mlz.refsans.devices.beckhoff.nok.BeckhoffMotorCab1M0x',
            description = 'tbd',
            tacodevice = '//%s/test/modbus/probenort'% (nethost,),
            address = 0x3214+0*10, # dez12820
            slope = -10000,
            unit = 'mm',
            abslimits = (-193.0, 130.0),
            userlimits = (-193.0, 130.0),
            ruler = -200.0,
            lowlevel = True,
        ),
        h3_sm = device('nicos_mlz.refsans.devices.beckhoff.nok.BeckhoffMotorCab1M0x',
            description = 'tbd',
            tacodevice = '//%s/test/modbus/probenort'% (nethost,),
            address = 0x3214+1*10, # dez12820
            slope = 10000,
            unit = 'mm',
            abslimits = (-102.0, 170.0),
            userlimits = (-102.0, 170.0),
            ruler = 0.0,
            lowlevel = True,
        ),
    )
