description = 'The PACE5000 in the E03 lab.'

pv_root = 'SE-PS01:SE-PACE5000-001:'

devices = dict(
    pace_setpoint=device(
        'nicos.devices.epics.pva.EpicsAnalogMoveable',
        description='The pressure set-point',
        readpv='{}Setpoint_RBV'.format(pv_root),
        writepv='{}Setpoint'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
    pace_pressure=device(
        'nicos.devices.epics.pva.EpicsReadable',
        description='The current pressure',
        readpv='{}Pressure_RBV'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
    pace_effort=device(
        'nicos.devices.epics.pva.EpicsReadable',
        description='The current effort',
        readpv='{}Effort_RBV'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
    pace_vent=device(
        'nicos.devices.epics.pva.EpicsMappedMoveable',
        description='The vent status',
        readpv='{}Vent_RBV'.format(pv_root),
        writepv='{}Vent'.format(pv_root),
        visibility=(),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
    pace_slew=device(
        'nicos.devices.epics.pva.EpicsAnalogMoveable',
        description='The current slew',
        readpv='{}Slew_RBV'.format(pv_root),
        writepv='{}Slew'.format(pv_root),
        visibility=(),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
    pace_slew_mode=device(
        'nicos.devices.epics.pva.EpicsMappedMoveable',
        description='The slew mode',
        readpv='{}SlewMode_RBV'.format(pv_root),
        writepv='{}SlewMode'.format(pv_root),
        visibility=(),
        pva=True,
        monitor=True,
        pollinterval=0.5,
        maxage=None,
    ),
)
