description = 'The Vinci high pressure syringe pump'

pv_root = 'SE-SEE:SE-VINP-001:'

devices = dict(
    vinci_pressure=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='Pressure',
        readpv='{}Pressure-R'.format(pv_root),
        writepv='{}PM_Pressure-S'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_pressure_SP=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='Pressure setpoint',
        readpv='{}PM_Pressure-S'.format(pv_root),
        writepv='{}PM_Pressure-S'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_volume=device(
        'nicos.devices.epics.EpicsReadable',
        description='Pump volume',
        readpv='{}Volume-R'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_flowrate=device(
        'nicos.devices.epics.EpicsReadable',
        description='Pump flow-rate',
        readpv='{}Flow-R'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_process_valve=device(
        'nicos.devices.epics.EpicsMappedMoveable',
        description='Status of the process valve',
        readpv='{}ProcValveOpened-RB'.format(pv_root),
        writepv='{}ProcValveOpen-S'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_tank_valve=device(
        'nicos.devices.epics.EpicsMappedMoveable',
        description='Status of the tank valve',
        readpv='{}TankValveOpened-RB'.format(pv_root),
        writepv='{}TankValveOpen-S'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
    vinci_pump=device(
        'nicos.devices.epics.EpicsMappedMoveable',
        description='Status of the pump',
        readpv='{}Stopped-RB'.format(pv_root),
        writepv='{}Start-S'.format(pv_root),
        pva=True,
        monitor=True,
        pollinterval=None,
        maxage=None,
    ),
)
