# -*- coding: utf-8 -*-

description = 'GALAXI PIN diodes'

group = 'optional'

display_order = 20

tango_base = 'tango://phys.galaxi.kfa-juelich.de:10000/galaxi/'
tango_analog = tango_base + 'plc_io/'
tango_digital = tango_base + 'fzjdp_digital/'

devices = dict(
    pintimer = device('nicos.devices.tango.AnalogOutput',
        description = 'Timer for PIN diode counting',
        tangodevice = tango_analog + 'pin_diode_timer',
        unit = 's',
        fmtstr = '%d',
    ),
    pinstate = device('nicos.devices.tango.NamedDigitalInput',
        description = 'Status of PIN diode counting',
        tangodevice = tango_digital + 'StatIntegralPin',
        mapping = {
            'counting': 1,
            'ready': 0
        },
        fmtstr = '%s',
        lowlevel = True,
    ),
    pincontrol = device('nicos.devices.tango.DigitalInput',
        description = 'Status control of PIN diode counting',
        tangodevice = tango_digital + 'StatIntegralPin2',
        lowlevel = True,
    ),
    singledetectors = device('nicos_jcns.galaxi.devices.pindiode.SingleDetectors',
        description = 'Integrated PIN diode values',
        pintimer = 'pintimer',
        pinstate = 'pinstate',
        pincontrol = 'pincontrol',
        pindiodes = [
            'ionichamber1_int', 'ionichamber2_int', 'pindiode1_int',
            'pindiodecal_int', 'pindiodesample_int'
        ],
    ),
    ionichamber1 = device('nicos.devices.tango.AnalogInput',
        description = 'Ionisation chamber 1',
        tangodevice = tango_analog + 'ionisation_chamber1',
        unit = 'cps',
    ),
    ionichamber1_int = device('nicos.devices.tango.AnalogInput',
        description = 'Integral of ionisation chamber 1',
        tangodevice = tango_analog + 'ionisation_chamber1_int',
        unit = 'cts',
        fmtstr = '%.10g',
    ),
    ionichamber1_off = device('nicos.devices.tango.AnalogOutput',
        description = 'Offset ionisation chamber 1',
        tangodevice = tango_analog + 'ionisation_chamber1_offset',
        unit = 'cps',
    ),
    ionichamber2 = device('nicos.devices.tango.AnalogInput',
        description = 'Ionisation chamber 2',
        tangodevice = tango_analog + 'ionisation_chamber2',
        unit = 'cps',
    ),
    ionichamber2_int = device('nicos.devices.tango.AnalogInput',
        description = 'Integral of ionisation chamber 2',
        tangodevice = tango_analog + 'ionisation_chamber2_int',
        unit = 'cts',
        fmtstr = '%.10g',
    ),
    ionichamber2_off = device('nicos.devices.tango.AnalogOutput',
        description = 'Offset of ionisation chamber 2',
        tangodevice = tango_analog + 'ionisation_chamber2_offset',
        unit = 'cps',
    ),
    pindiode1_move = device('nicos.devices.tango.NamedDigitalOutput',
        description = 'Moving of PIN diode in chamber 1',
        tangodevice = tango_digital + 'AbsorberPlate16',
        mapping = {
            'in': 1,
            'out': 0
        },
        fmtstr = '%s',
    ),
    pindiode1 = device('nicos.devices.tango.AnalogInput',
        description = 'PIN diode in chamber 1',
        tangodevice = tango_analog + 'pin_diode_chamber1',
        unit = 'cps',
    ),
    pindiode1_int = device('nicos.devices.tango.AnalogInput',
        description = 'Integral of PIN diode in chamber 1',
        tangodevice = tango_analog + 'pin_diode_chamber1_int',
        unit = 'cts',
        fmtstr = '%.10g',
    ),
    pindiode1_off = device('nicos.devices.tango.AnalogOutput',
        description = 'Offset of PIN diode in chamber 1',
        tangodevice = tango_analog + 'pin_diode_chamber1_offset',
        unit = 'cps',
    ),
    pindiodesample_move = device('nicos.devices.tango.NamedDigitalOutput',
        description = 'Moving of PIN diode behind sample place',
        tangodevice = tango_digital + 'PinDiode',
        mapping = {
            'in': 1,
            'out': 2
        },
        fmtstr = '%s',
    ),
    pindiodesample = device('nicos.devices.tango.AnalogInput',
        description = 'PIN diode behind sample place',
        tangodevice = tango_analog + 'pin_diode_sample',
        unit = 'cps',
    ),
    pindiodesample_int = device('nicos.devices.tango.AnalogInput',
        description = 'Integral of PIN diode behind sample place',
        tangodevice = tango_analog + 'pin_diode_sample_int',
        unit = 'cts',
        fmtstr = '%.10g',
    ),
    pindiodesample_off = device('nicos.devices.tango.AnalogOutput',
        description = 'Offset of PIN diode behind sample place',
        tangodevice = tango_analog + 'pin_diode_sample_offset',
        unit = 'cps',
    ),
    pindiodecal = device('nicos.devices.tango.AnalogInput',
        description = 'Calibrated PIN diode at sample place',
        tangodevice = tango_analog + 'pin_diode_calibrated',
        unit = 'cps',
    ),
    pindiodecal_int = device('nicos.devices.tango.AnalogInput',
        description = 'Integral of calibrated PIN diode at sample place',
        tangodevice = tango_analog + 'pin_diode_calibrated_int',
        fmtstr = '%.10g',
        unit = 'cts',
    ),
    pindiodecal_off = device('nicos.devices.tango.AnalogOutput',
        description = 'Offset of calibrated PIN diode at sample place',
        tangodevice = tango_analog + 'pin_diode_calibrated_offset',
        unit = 'cps',
    ),
)
