description = 'correction coil motors'

group = 'optional'

tango_base = 'tango://phys.j-nse.frm2:10000/j-nse/'

devices = dict(
    mo_cc11a = device('nicos.devices.entangle.Motor',
        description = 'correction coil A4 position',
        tangodevice = tango_base + 'pimotor/mo_cc11a',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc11b = device('nicos.devices.entangle.Motor',
        description = 'correction coil A3 position',
        tangodevice = tango_base + 'pimotor/mo_cc11b',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc12a = device('nicos.devices.entangle.Motor',
        description = 'correction coil B2 position',
        tangodevice = tango_base + 'pimotor/mo_cc12a',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc12b = device('nicos.devices.entangle.Motor',
        description = 'correction coil B1 position',
        tangodevice = tango_base + 'pimotor/mo_cc12b',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc21a = device(
        'nicos.devices.entangle.Motor',
        description = 'correction coil',
        tangodevice = tango_base + 's7_motor/mo_cc21a',
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata',)
    ),
    mo_cc21b = device(
        'nicos.devices.entangle.Motor',
        description = 'correction coil',
        tangodevice = tango_base + 's7_motor/mo_cc21b',
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata',)
    ),
    mo_cc22a = device(
        'nicos.devices.entangle.Motor',
        description = 'correction coil',
        tangodevice = tango_base + 's7_motor/mo_cc22a',
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata',)
    ),
    mo_cc22b = device(
        'nicos.devices.entangle.Motor',
        description = 'correction coil',
        tangodevice = tango_base + 's7_motor/mo_cc22b',
        unit = 'mm',
        fmtstr = '%.6f',
        visibility = ('metadata',)
    ),
    mo_cc31a = device('nicos.devices.entangle.Motor',
        description = 'correction coil A2 position',
        tangodevice = tango_base + 'pimotor/mo_cc31a',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc31b = device('nicos.devices.entangle.Motor',
        description = 'correction coil A1 position',
        tangodevice = tango_base + 'pimotor/mo_cc31b',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc32a = device('nicos.devices.entangle.Motor',
        description = 'correction coil B3 position',
        tangodevice = tango_base + 'pimotor/mo_cc32a',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
    mo_cc32b = device('nicos.devices.entangle.Motor',
        description = 'correction coil B4 position',
        tangodevice = tango_base + 'pimotor/mo_cc32b',
        unit = 'mm',
        fmtstr = '%.6f',
    ),
)
