description = 'ZEA-2 counter card setup'
group = 'lowlevel'

tango_base = 'tango://phys.j-nse.frm2:10000/j-nse/'

devices = dict(
    selector = device('nicos.devices.entangle.CounterChannel',
        description = 'Selector',
        tangodevice = tango_base + 'count/sel',
        type = 'monitor',
    ),
    selector_speed_countercard = device('nicos.devices.entangle.Sensor',
        description = 'Selector frequency according to counter card',
        tangodevice = tango_base + 'count/sel_freq',
        unit = 'rpm',
        fmtstr = '%.0f',
        visibility = (),
    ),
    anode_events = device('nicos.devices.entangle.CounterChannel',
        description = 'Anode events',
        tangodevice = tango_base + 'count/anodeevents',
        type = 'monitor',
    ),
    monbgr = device('nicos.devices.entangle.CounterChannel',
        description='Background monitor',
        tangodevice=tango_base + 'count/monbgr',
        type='monitor',
    ),
    mon1 = device('nicos.devices.entangle.CounterChannel',
        description = 'Monitor',
        tangodevice = tango_base + 'count/mon1',
        type = 'monitor',
    ),
    mon1rate = device('nicos.devices.entangle.AnalogInput',
        description = 'Instantaneous rate of monitor 1',
        tangodevice = tango_base + 'count/mon1rate',
        pollinterval = 1.0,
        fmtstr = '%.1f',
    ),
    timer = device('nicos_mlz.jcns.devices.fpga.FPGATimerChannel',
        description = 'Counter card timer channel',
        tangodevice = tango_base + 'count/timer',
    ),
)
