description = 'PLCs analog inputs'

group = 'optional'

tango_base = 'tango://phys.j-nse.frm2:10000/j-nse/'

devices = dict(
    cc1r1 = device('nicos.devices.tango.Sensor',
        description = 'Temp cc1r1',
        tangodevice = tango_base + 'FZJDP_Analog/CC1R1',
        unit = 'degC',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    cc1r2 = device('nicos.devices.tango.Sensor',
        description = 'Temp cc1r2',
        tangodevice = tango_base + 'FZJDP_Analog/CC1R2',
        unit = 'degC',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    cc3r1 = device('nicos.devices.tango.Sensor',
        description = 'Temp cc3r1',
        tangodevice = tango_base + 'FZJDP_Analog/CC3R1',
        unit = 'degC',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    cc3r2 = device('nicos.devices.tango.Sensor',
        description = 'Temp cc3r2',
        tangodevice = tango_base + 'FZJDP_Analog/CC3R2',
        unit = 'degC',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    HeMon = device('nicos.devices.tango.Sensor',
        description = 'He percentage',
        tangodevice = tango_base + 'FZJDP_Analog/HeMon',
        unit = 'percent',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB1x = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 1 x component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB1x',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB1y = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 1 y component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB1y',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB1z = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 1 z component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB1z',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB2x = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 2 x component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB2x',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB2y = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 2 y component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB2y',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagB2z = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi/2 2 z component',
        tangodevice = tango_base + 'FZJDP_Analog/MagB2z',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagBx = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi flipper x component',
        tangodevice = tango_base + 'FZJDP_Analog/MagBx',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagBy = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi flipper y component',
        tangodevice = tango_base + 'FZJDP_Analog/MagBy',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
    MagBz = device('nicos.devices.tango.Sensor',
        description = 'B sensor pi flipper z component',
        tangodevice = tango_base + 'FZJDP_Analog/MagBz',
        unit = 'G',
        fmtstr = '%.3g',
        pollinterval = 60,
        maxage = 130,
    ),
)
