description = 'REFSANS full setup does not make sense!'

group = 'basic'

includes = [
    #'chiller',
    #'polarizer',
    #'Pt1000x4x01',
    'attenuators',
    'autocollimator',
    'b3h3',
    'backguard',
    'beamstop',
    'chamber',
    'chopper',
    'chopperphasentiming',
    'd_last_slit_sample',
    'ddg',
    'detector',
    'expertvibro8',
    'fak40',
    'gonio',
    'gonio_top',
    'guidehall',
    'h2',
    'height',
    'humidity',
    'humidity01',
    'julabo',
    'memograph',
    'nl2b',
    'optic_elements',
    # 'poti_ref',
    'prim_monitor',
    'psutil',
    'pumpstand',
    'qmesydaq',
    'reactor',
    'resolution',
    'safedetectorsystem',
    'safetysystem',
    'samplechanger',
    'shutter',
    'shutter_gamma',
    'vsd',
]
