description = 'REFSANS basic setup no sense yet'

group = 'basic'

includes = [
    # 'autocollimator',
    # 'b3h3',
    # 'backguard',
    'beamstop',
    'chamber',
    'chopper',
    'chopperphasentiming',
    'detector',
    'fak40',
    'gonio',
    # 'gonio_top',
    'guidehall',
    'h2',
    'memograph',
    'nl2b',
    'optic_elements',
    'poti_ref',
    'prim_monitor',
    'pumpstand',
    'qmesydaq',
    'reactor',
    'resolution',
    'safedetectorsystem',
    'detector',
    'safetysystem',
    'd_last_slit_sample',
    # 'samplechanger',
    'shutter',
    'shutter_gamma',
    'vsd',
]
