NOK = 'NOK1'

description = '%s setup' % (NOK)

nok = NOK.lower()

nethost = 'refsanssrv.refsans.frm2'

includes = ['nokref', 'motorbus',]

devices = {
    nok + 'port' : device('devices.taco.io.AnalogInput',
                          description = 'Voltage input of the %s coder' % NOK,
                          tacodevice = '//%s/test/wb_a/1_0' % (nethost,),
                          lowlevel = True,
                         ),
    nok + 'obs' : device('refsans.nok.Coder',
                         description = '%s potentiometer coder' % NOK,
                         mul = 0.996393,
                         off = -13.748035,
                         snr = 6505,
                         sensitivity = 3.856,
                         port = '%sport' % (nok,),
                         ref = 'nrefa1',
                         lowlevel = True,
                        ),
    nok + 'motor' : device('devices.taco.motor.Motor',
                           description = 'Motor of the %s' % NOK,
                           tacodevice = '//%s/test/%s/mr' % (nethost, nok),
                           lowlevel = True,
                          ),
    nok + 'sll' : device('devices.taco.io.DigitalInput',
                         description = 'low limit switch of %s' % NOK,
                         tacodevice = '//%s/test/%s/srll' % (nethost, nok),
                         lowlevel = True,
                        ),
    nok + 'shl' : device('devices.taco.io.DigitalInput',
                         description = 'high limit switch of %s' % NOK,
                         tacodevice = '//%s/test/%s/srhl' % (nethost, nok),
                         lowlevel = True,
                        ),
    nok + 'sref' : device('devices.taco.io.DigitalInput',
                          description = 'reference switch of %s' % NOK,
                          tacodevice = '//%s/test/%s/srref' % (nethost, nok),
                          lowlevel = True,
                         ),
    nok + 'axis' : device('refsans.nok.Axis',
                          description = '%s Axis ' % NOK,
                          motor = '%smotor' % (nok,),
                          coder = '%smotor' % (nok,),
                          obs = ['%sobs' % (nok,), ],
                          bus = 'motorbus2',
                          sll = '%ssll' % (nok,),
                          shl = '%sshl' % (nok,),
                          sref = '%ssref' % (nok,),
                          backlash = -2.0,
                          precision = 0.05,
                          refpoint = -14.419,
                         ),
         }
#   nok1 = device('refsans.nok.Nok',
#                 unit = 'mm',
#                 fmtstr = '%.5f',
#                 bus = 'motorbus2',
#                 motor = nethost + 'test/nok1/ngm',
#                 encoder = nethost + 'test/nok1/nge',
#                 refswitch = nethost + 'test/nok1/ngsref',
#                 lowlimitswitch = [nethost + 'test/nok1/ngsll',],
#                 highlimitswitch = [nethost + 'test/nok1/ngshl',],
#                 #refpos = [-14.419, ],
#                 refpos = [-14.729 ], #JFM07_06_2010
#                 backlash = 2,
#                 posinclination = 0,
#                 neginclination = 0,
#                ),
