description = 'NOK reference voltage setup'

nethost = 'refsanssrv.refsans.frm2'

devices = dict(
    nrefa1 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_a/1_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
    nrefa2 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_a/2_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
    nrefb1 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_b/1_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
    nrefb2 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_b/2_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
    nrefc1 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_c/1_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
    nrefc2 = device('refsans.nok.CoderReference',
                    description = 'Reference voltage device for the NOK coders',
                    tacodevice = '//%s/test/wb_c/2_6' % (nethost,),
                    lowlevel = True,
                    refhigh = 19.8,
                    reflow = 18.0,
                    refwarn = 17.0,
                   ),
)
