description = 'Standard setup for TASP'

motaprefix = 'SQ:TASP:mota:'
motbprefix = 'SQ:TASP:motb:'
cterprefix = 'SQ:TASP:counter'

devices = dict(
    a1 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator omega',
        motorpv = motaprefix + 'A1',
        errormsgpv = motaprefix + 'A1-MsgTxt',
        precision = 0.02,
    ),
    mcv = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator curvature',
        motorpv = motaprefix + 'MCV',
        errormsgpv = motaprefix + 'MCV-MsgTxt',
        precision = 0.02,
    ),
    mtl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator lower translation',
        motorpv = motaprefix + 'MTL',
        errormsgpv = motaprefix + 'MTL-MsgTxt',
        precision = 0.02,
    ),
    mtu = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator upper translation',
        motorpv = motaprefix + 'MTU',
        errormsgpv = motaprefix + 'MTU-MsgTxt',
        precision = 0.02,
    ),
    mgl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator goniometer',
        motorpv = motaprefix + 'MGL',
        errormsgpv = motaprefix + 'MGL-MsgTxt',
        precision = 0.02,
    ),
    a2 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator tow that',
        motorpv = motaprefix + 'A2',
        errormsgpv = motaprefix + 'A2-MsgTxt',
        precision = 0.02,
    ),
    a3 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample rotation',
        motorpv = motaprefix + 'A3',
        errormsgpv = motaprefix + 'A3-MsgTxt',
        precision = 0.02,
    ),
    a4 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample two theta',
        motorpv = motaprefix + 'A1',
        errormsgpv = motaprefix + 'A1-MsgTxt',
        precision = 0.02,
    ),
    sro = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample auxiliary rotation',
        motorpv = motaprefix + 'SRO',
        errormsgpv = motaprefix + 'SRO-MsgTxt',
        precision = 0.02,
    ),
    stl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample lower translation',
        motorpv = motbprefix + 'STL',
        errormsgpv = motbprefix + 'STL-MsgTxt',
        precision = 0.02,
    ),
    stu = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample upper translation',
        motorpv = motbprefix + 'STU',
        errormsgpv = motbprefix + 'STU-MsgTxt',
        precision = 0.02,
    ),
    sgl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample lower tilt',
        motorpv = motbprefix + 'SGL',
        errormsgpv = motbprefix + 'SGL-MsgTxt',
        precision = 0.02,
    ),
    sgu = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample upper tilt',
        motorpv = motbprefix + 'SGU',
        errormsgpv = motbprefix + 'SGU-MsgTxt',
        precision = 0.02,
    ),
    a5 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser rotation',
        motorpv = motbprefix + 'A5',
        errormsgpv = motbprefix + 'A5-MsgTxt',
        precision = 0.02,
    ),
    ach = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser curvature',
        motorpv = motbprefix + 'ACH',
        errormsgpv = motbprefix + 'ACH-MsgTxt',
        precision = 0.02,
    ),
    atl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser lower translation',
        motorpv = motbprefix + 'ATL',
        errormsgpv = motbprefix + 'ATL-MsgTxt',
        precision = 0.02,
    ),
    atu = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser upper translation',
        motorpv = motbprefix + 'ATU',
        errormsgpv = motbprefix + 'ATU-MsgTxt',
        precision = 0.02,
    ),
    a6 = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser two theta',
        motorpv = motbprefix + 'A6',
        errormsgpv = motbprefix + 'A6-MsgTxt',
        precision = 0.02,
    ),
    agl = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Analyser goniometer',
        motorpv = motbprefix + 'AGL',
        errormsgpv = motbprefix + 'AGL-MsgTxt',
        precision = 0.02,
    ),
    timepreset = device('nicos_ess.devices.epics.detector.EpicsTimerActiveChannel',
        epicstimeout = 3.0,
        description = 'Used to set and view time preset',
        unit = 'sec',
        readpv = cterprefix + '.TP',
        presetpv = cterprefix + '.TP',
    ),
    elapsedtime = device('nicos_ess.devices.epics.detector.EpicsTimerPassiveChannel',
        epicstimeout = 3.0,
        description = 'Used to view elapsed time while counting',
        unit = 'sec',
        readpv = cterprefix + '.T',
    ),
    monitorpreset = device('nicos_ess.devices.epics.detector.EpicsCounterActiveChannel',
        epicstimeout = 3.0,
        description = 'Used to set and view monitor preset',
        type = 'monitor',
        readpv = cterprefix + '.PR2',
        presetpv = cterprefix + '.PR2',
    ),
    ctr1 = device('nicos_ess.devices.epics.detector.EpicsCounterPassiveChannel',
        epicstimeout = 3.0,
        description = 'The real neutron counter',
        type = 'monitor',
        readpv = cterprefix + '.S2',
    ),
    mon1 = device('nicos_ess.devices.epics.detector.EpicsCounterPassiveChannel',
        epicstimeout = 3.0,
        description = 'First scalar counter channel',
        type = 'monitor',
        readpv = cterprefix + '.S3',
    ),
    mon2 = device('nicos_ess.devices.epics.detector.EpicsCounterPassiveChannel',
        epicstimeout = 3.0,
        description = 'Second scalar counter channel',
        type = 'monitor',
        readpv = cterprefix + '.S4',
    ),
    protoncount = device('nicos_ess.devices.epics.detector.EpicsCounterPassiveChannel',
        epicstimeout = 3.0,
        description = 'Fourth scalar counter channel',
        type = 'monitor',
        readpv = cterprefix + '.S5',
    ),
    counter = device('nicos_sinq.devices.detector.SinqDetector',
        epicstimeout = 3.0,
        description = 'EL737 counter box that counts neutrons and '
        'starts streaming events',
        startpv = cterprefix + '.CNT',
        pausepv = cterprefix + ':Pause',
        statuspv = cterprefix + ':Status',
        errormsgpv = cterprefix + ':MsgTxt',
        thresholdpv = cterprefix + ':Threshold',
        monitorpreset = 'monitorpreset',
        timepreset = 'timepreset',
        timers = ['elapsedtime'],
        monitors = [
            'ctr1',
            'mon1',
            'mon2',
            'protoncount',
        ],
        liveinterval = 7,
        saveintervals = [60]
    ),
    mono = device('nicos_sinq.devices.mono.SinqMonochromator',
        description = 'TASP monochromator',
        theta = 'a1',
        twotheta = 'a2',
        dvalue = 3.354,
        scatteringsense = -1,
        crystalside = -1,
        unit = 'meV',
        focmode = 'vertical',
        vfocuspars = [2.9, 8.45714],
        abslimits = [2.75, 20],
        focusv = 'mcv'
    ),
    ana = device('nicos_sinq.devices.mono.SinqMonochromator',
        description = 'TASP analyser',
        theta = 'a5',
        twotheta = 'a6',
        dvalue = 3.354,
        scatteringsense = -1,
        crystalside = -1,
        unit = 'meV',
        focmode = 'vertical',
        vfocuspars = [0.25, 4.01],
        abslimits = [2.75, 20],
        focusv = 'ach'
    ),
    ei = device('nicos.core.device.DeviceAlias',
        description = 'Alias for driving the monochromator',
        alias = 'mono',
    ),
    ef = device('nicos.core.device.DeviceAlias',
        description = 'Alias for driving the analyser',
        alias = 'ana',
    ),
)
startupcode = """
SetDetectors(counter)
"""
