description = 'Shutter and attenuators via Pilz box'

group = 'lowlevel'

includes = []

nethost= 'pgaasrv.pgaa.frm2'

devices = dict(
    shutter = device('pgaa.pilz.Switch',
                     description = 'secondary experiment shutter',
                     tacodevice = '//%s/pgaa/pilz/shutter' % (nethost,),
                     readback = '//%s/pgaa/pilz/ishutter' % (nethost,),
                     error = '//%s/pgaa/pilz/eshutter' % (nethost,),
                     remote = '//%s/pgaa/pilz/erc' % (nethost,),
                     mapping = {'closed': 2, 'open': 1},
                     maxage = 5,
                     pollinterval = 2,
                     timeout = 3,
                    ),
    att1 = device('pgaa.pilz.Attenuator',
                  description = 'attenuator 1',
                  tacodevice = '//%s/pgaa/pilz/satt1' % (nethost,),
                  error = '//%s/pgaa/pilz/eatt1' % (nethost,),
                  readback = '//%s/pgaa/pilz/iatt1' % (nethost,),
                  remote = '//%s/pgaa/pilz/erc' % (nethost,),
                  mapping = {'out': 0, 'in': 1},
                  maxage = 5,
                  pollinterval = 2,
                  timeout = 3,
                 ),
    att2 = device('pgaa.pilz.Attenuator',
                  description = 'attenuator 2',
                  tacodevice = '//%s/pgaa/pilz/satt2' % (nethost,),
                  error = '//%s/pgaa/pilz/eatt2' % (nethost,),
                  readback = '//%s/pgaa/pilz/iatt2' % (nethost,),
                  remote = '//%s/pgaa/pilz/erc' % (nethost,),
                  mapping = {'out': 0, 'in': 1},
                  maxage = 5,
                  pollinterval = 2,
                  timeout = 3,
                 ),
    att3 = device('pgaa.pilz.Attenuator',
                  description = 'attenuator 3',
                  tacodevice = '//%s/pgaa/pilz/satt3' % (nethost,),
                  error = '//%s/pgaa/pilz/eatt3' % (nethost,),
                  readback = '//%s/pgaa/pilz/iatt3' % (nethost,),
                  remote = '//%s/pgaa/pilz/erc' % (nethost,),
                  mapping = {'out': 0, 'in': 1},
                  maxage = 5,
                  pollinterval = 2,
                  timeout = 3,
                 ),
    att = device('pgaa.attenuator.Attenuator',
                 description = 'Attenuator device',
                 moveables = ['att1', 'att2', 'att3', ],
                 readables = None,
                 precision = None,
                 unit = '%',
                 fmtstr = '%.1f',
                 mapping = {100.: ('out', 'out', 'out'),
                            47.: ('out', 'in', 'out'),
                            16.: ('in', 'out', 'out'),
                            7.5: ('in', 'in', 'out'),
                            5.9: ('out', 'out', 'in'),
                            3.5: ('out', 'in', 'in'),
                            2.7: ('in', 'out', 'in'),
                            1.6: ('in', 'in', 'in'),
                           },
                ),
)
