#  -*- coding: utf-8 -*-

description = 'PANDA-version of a setup for the FRM2 7T5 Magnet'

includes = ['alias_B']

group = 'optional'

TACOBASE = '//magnet.panda.frm2/magnet/'

devices = dict(
    # There are 8 thermometers to check temperatures inside the magnet....
    m7T5_T1   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens1',
                       unit = 'K',
                       description = '7.5T magnet Sensor1',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T2   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens2',
                       unit = 'K',
                       description = '7.5T magnet Sensor2',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T3   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens3',
                       unit = 'K',
                       description = '7.5T magnet Sensor3',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T4   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens4',
                       unit = 'K',
                       description = '7.5T magnet Sensor4',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T5   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens5',
                       unit = 'K',
                       description = '7.5T magnet Sensor5',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T6   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens6',
                       unit = 'K',
                       description = '7.5T magnet Sensor6',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T7   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens7',
                       unit = 'K',
                       description = '7.5T magnet Sensor7',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    m7T5_T8   = device('devices.taco.AnalogInput',
                       tacodevice = TACOBASE + 'ls218/sens8',
                       unit = 'K',
                       description = '7.5T magnet Sensor8',
                       fmtstr = '%.2f',
                       pollinterval = 30,
                      ),
    # Magnet power supply. it is supposed to be able to switch polarity....
    B_7T5 = device('devices.taco.AnalogOutput',
                   tacodevice = TACOBASE + 'smc120/t',
                   description = '7.5T magnet field drive',
                   userlimits = ( 0, 7.0 ),
                   abslimits = (-7.5, 7.5 ),
                   fmtstr = '%.2f',
                   unit = 'T',
                   pollinterval = 15,
                  ),
    # Nicos based access to phytron in magnet rack
    magnetmotorbus = device('panda.mcc2.TacoSerial',
                            tacodevice = TACOBASE + 'rs232/phytron',
                            lowlevel = True,
                           ),
    sth_B7T5_step = device('panda.mcc2.MCC2Motor',
                           bus = 'magnetmotorbus',
                           precision = 0.01,
                           fmtstr = '%.3f',
                           description = '7.5T magnet sample rotation MOTOR using only the RS232 TACOSERVER and talking to mcc2',
                           channel = 'Y',
                           addr = 0,
                        #~ slope = -480000.0/(360.0*6),
                           slope = -75000.0 / 360.0,
                           abslimits = (-360, 360),
                           userlimits = (0, 120),
                           unit = 'deg',
                           idlecurrent = 0.4,
                           movecurrent = 1.0,
                           rampcurrent = 1.2,
                           microstep = 8,
                           speed = 2.0,
                          ),
    sth_B7T5_coder = device('panda.mcc2.MCC2Coder',
                            bus = 'magnetmotorbus',
                            fmtstr = '%.3f',
                            description = '7.5T magnet sample rotation CODER using only the RS232 TACOSERVER and talking to mcc2',
                            channel = 'Y',
                            addr = 0,
                            slope = -480000.0 / 360.0,
                            unit = 'deg',
                            zerosteps = 0,
                            codertype = 'incremental',
                             coderbits = 25,
                           ),
    sth_B7T5 = device('devices.generic.Axis',
                      description = '7.5T magnet sample rotation',
                      motor = 'sth_B7T5_step',
                      coder = 'sth_B7T5_coder',
                      obs = [],
                      precision = 0.01,
                      backlash = -1,
                     ),
#~ # Phytron controlled cryo rotation....
#    sth_B7T5_Taco_motor = device('devices.taco.Motor',
#                                 tacodevice = TACOBASE+'phytron/motor',
#                                 description = '7.5T magnet sample rotation TACO-Motor',
#                                 userlimits=( 0, 7.0 ),
#                                 abslimits = (0, 360 ),
#                                 fmtstr = '%.3f',
#                                 unit = 'deg',
#                                ),
#    sth_B7T5_Taco_coder = device('devices.taco.Coder',
#                              #~ tacodevice = TACOBASE+'phytron/coder',  # old value
#                                 tacodevice = TACOBASE+'phytron/encoder',   # new value as of 2012-07-30 EF
#                                 description = '7.5T magnet sample rotation TACO-coder',
#                                 fmtstr = '%.3f',
#                                 unit = 'deg',
#                                ),
)

startupcode = '''
B.alias = 'B_7T5'
sth.alias = 'sth_B7T5'
'''
