#  -*- coding: utf-8 -*-

description = 'Sampletable complete'

includes = ['system']

group = 'lowlevel'

 # sth,stt,sgx,sgy,stx,sty,stz,--

devices = dict(
    bus2 = device('devices.vendor.ipc.IPCModBusTaco',
            tacodevice='//pandasrv/panda/moxa/port2',
            loglevel='info',
            tacotimeout=0.5,
            lowlevel=True,
    ),

    # STT is first device and has 1 stepper, 0 poti, 1 coder
    stt_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x51,                # 0x5.. = stepper, 0x6.. = poti, 0x7.. = coder ; .. = channel
            slope = 2000,
            unit = 'deg',
            abslimits = (-100,130),
            zerosteps = 500000,
            confbyte = 8,
            speed = 100,
            accel = 17,
            microstep = 2,
            startdelay = 0.2,
            stopdelay = 0.1,
            ramptype = 1,
            lowlevel = True,
            #~ current = 2.0,
    ),
    stt_enc = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x71,
            slope = -2**20/360.0,
            zerosteps = 543767,
            confbyte = 148,
            unit = 'deg',
            circular = -360, # map values to -180..0..180 degree
            lowlevel = True,
    ),
    stt = device('devices.generic.Axis',
            motor = 'stt_step',
            coder = 'stt_enc',
            obs = [],
            precision = 0.025,
            #offset = -0.925,
            offset = -1.045,
    ),

    # STH is second device and has 1 stepper, 0 poti, 1 coder
    sth_st_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x52,
            slope = 2000,
            unit = 'deg',
            abslimits = (1, 359),
            zerosteps = 100000,
            speed = 100,
            accel = 24,
            microstep = 2,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            lowlevel = True,
            #~ current = 2.0,
    ),
    sth_st_enc = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x72,
            slope = -2**20/360.0,
            zerosteps = 831380,
            confbyte = 148,
            unit = 'deg',
            circular = 360, # map values to -180..0..180 degree
            lowlevel = True,
    ),
    sth_st = device('devices.generic.Axis',
            motor = 'sth_st_step',
            coder = 'sth_st_enc',
            obs = [],
            precision = 0.02,
            description = 'sth mounted on sampletable',
    ),

    # SGX is third device and has 1 stepper, 0 poti, 1 coder
    sgx_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x53,
            slope = -3200,
            unit = 'deg',
            abslimits = (-15.1,15.1),
            zerosteps = 500000,
            speed = 50,
            accel = 24,
            microstep = 16,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            lowlevel = True,
            #~ current = 2.0,
    ),
    sgx_enc = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x73,
            slope = -2**13/1.0,
            #zerosteps = 33513471,
            zerosteps = 33554431,
            confbyte = 121,
            unit = 'deg',
            circular = -4096,    # 12 bit (4096) for turns, times 2 deg per turn divided by 2 (+/-)
            lowlevel = True,
    ),
    sgx = device('devices.generic.Axis',
            motor = 'sgx_step',
            coder = 'sgx_enc',
            obs = [],
            precision = 0.05,
            #~ rotary = True,
    ),

    # SGY is fourth device and has 1 stepper, 0 poti, 1 coder
    sgy_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x54,
            slope = 3200,
            unit = 'deg',
            abslimits = (-15.1,15.1),
            zerosteps = 500000,
            speed = 50,
            accel = 24,
            microstep = 16,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            lowlevel = True,
            #~ current = 2.0,
    ),
    sgy_enc = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x74,
            slope = 2**13/1.0,
            #zerosteps = 33562602,
            zerosteps = 33554410,
            confbyte = 121,
            unit = 'deg',
            circular = -4096,    # 12 bit (4096) for turns, times 2 deg per turn divided by 2 (+/-)
            lowlevel = True,
    ),
    sgy = device('devices.generic.Axis',
            motor = 'sgy_step',
            coder = 'sgy_enc',
            obs = [],
            precision = 0.05,
            #~ rotary = True,
    ),


    # STX is fith device and has 1 stepper, 1 poti, 0 coder
    stx_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x55,
            slope = 12800,
            unit = 'mm',
            abslimits = (-20,20),
            zerosteps = 500000,
            speed = 100,
            accel = 24,
            microstep = 16,
            lowlevel = True,
            #~ divider = 4,
            #~ current = 1.5,
    ),
    stx_poti = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x65,
            slope = 79.75,
            zerosteps = 1840.02,
            unit = 'mm',
            lowlevel = True,
    ),
    stx = device('devices.generic.Axis',
            motor = 'stx_step',
            coder = 'stx_step',
            obs = ['stx_poti'],
            precision = 0.05,
            fmtstr='%.1f',
    ),

    # STY is sixth device and has 1 stepper, 1 poti, 0 coder
    sty_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x56,
            slope = 12800,
            unit = 'mm',
            abslimits = (-15,15),
            zerosteps = 500000,
            speed = 100,
            accel = 24,
            microstep = 16,
            lowlevel = True,
            #~ divider = 4,
            #~ current = 1.5,
    ),
    sty_poti = device('devices.vendor.ipc.Coder',
            bus = 'bus2',
            addr = 0x66,
            slope = 79.65,
            zerosteps = 1968.05,
            unit = 'mm',
            lowlevel = True,
    ),
    sty = device('devices.generic.Axis',
            motor = 'sty_step',
            coder = 'sty_step',
            obs = ['sty_poti'],
            precision = 0.05,
            fmtstr='%.1f',
    ),

    # STZ is seventh device and has 1 stepper, 0 poti, 0 coder
    stz_step = device('devices.vendor.ipc.Motor',
            bus = 'bus2',
            addr = 0x57,
            slope = 20000,
            unit = 'mm',
            abslimits = (-20,20),
            zerosteps = 500000,
            speed = 50,
            accel = 24,
            microstep = 2,
            lowlevel = True,
            #~ divider = 4,
            #~ current = 1.5,
    ),

    stz = device('devices.generic.Axis',
            motor = 'stz_step',
            coder = 'stz_step',
            obs = [],
            precision = 0.1,
            fmtstr = '%.3f',
    ),

    # eigth device is not used yet......

)

startupcode = '''
sth.alias='sth_st'
'''
