#  -*- coding: utf-8 -*-

name = 'Sampletable complete'

includes = ['system']
 
 # sth,stt,sgx,sgy,stx,sty,stz,--

devices = dict(
    bus2 = device('nicos.ipc.IPCModBusTaco',
            tacodevice='//pandasrv/panda/moxa/port2',
            loglevel='info',
            timeout=0.5,
    ),
    
    # STT is first device and has 1 stepper, 0 poti, 1 coder
    stt_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x51,                # 0x5.. = stepper, 0x6.. = poti, 0x7.. = coder ; .. = channel
            slope = -2000,
            unit = 'deg',
            abslimits = (-100,130),
            zerosteps = 500000,
            confbyte = 8,
            speed = 50,
            accel = 20,
            microstep = 2,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            #~ current = 2.0,
    ),
    stt_enc = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x71,
            slope = -2**20/360.0,
            zerosteps = 546546,
            confbyte = 148,
            unit = 'deg',
            circular = -360, # map values to -180..0..180 degree
    ),
    stt = device('nicos.generic.Axis',
            motor = 'stt_step',
            coder = 'stt_enc',
            obs = [],
            precision = 0.05,
            #~ rotary = True,
    ),
    
    # STH is second device and has 1 stepper, 0 poti, 1 coder
    sth_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x52,
            slope = -2000,
            unit = 'deg',
            abslimits = (-180,180),
            zerosteps = 500000,
            speed = 50,
            accel = 20,
            microstep = 2,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            #~ current = 2.0,
    ),
    sth_enc = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x72,
            slope = -2**20/360.0,
            zerosteps = 831380,
            confbyte = 148,
            unit = 'deg',
            circular = -360, # map values to -180..0..180 degree
    ),
    sth = device('nicos.generic.Axis',
            motor = 'sth_step',
            coder = 'sth_enc',
            obs = [],
            precision = 0.02,
            #~ rotary = True,
    ),
    
    # SGX is third device and has 1 stepper, 0 poti, 1 coder
    sgx_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x53,
            slope = 400,
            unit = 'deg',
            abslimits = (-15.1,15.1),
            zerosteps = 500000,
            speed = 50,
            accel = 20,
            microstep = 2,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            #~ current = 2.0,
    ),
    sgx_enc = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x73,
            slope = -2**13/1.0,
            zerosteps = 33538047,
            confbyte = 121,
            unit = 'deg',
            circular = -4096,    # 12 bit (4096) for turns, times 2 deg per turn divided by 2 (+/-)
    ),
    sgx = device('nicos.generic.Axis',
            motor = 'sgx_step',
            coder = 'sgx_enc',
            obs = [],
            precision = 0.05,
            #~ rotary = True,
    ),
    
    # SGY is fourth device and has 1 stepper, 0 poti, 1 coder
    sgy_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x54,
            slope = 400,
            unit = 'deg',
            abslimits = (-15.1,15.1),
            zerosteps = 500000,
            speed = 50,
            accel = 20,
            microstep = 2,
            startdelay = 0,
            stopdelay = 0,
            ramptype = 1,
            #~ current = 2.0,
    ),
    sgy_enc = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x74,
            slope = 2**13/1.0,
            zerosteps = 33554410,
            confbyte = 121,
            unit = 'deg',
            circular = -4096,    # 12 bit (4096) for turns, times 2 deg per turn divided by 2 (+/-)
    ),
    sgy = device('nicos.generic.Axis',
            motor = 'sgy_step',
            coder = 'sgy_enc',
            obs = [],
            precision = 0.05,
            #~ rotary = True,
    ),
    
    
    # STX is fith device and has 1 stepper, 1 poti, 0 coder
    stx_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x55,
            slope = -1600,
            unit = 'mm',
            abslimits = (-20,20),
            zerosteps = 500000,
            speed = 50,
            accel = 20,
            microstep = 2,
            #~ divider = 4,
            #~ current = 1.5,
    ),
    stx_poti = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x65,
            slope = -159.5,
            zerosteps = 4472,
            unit = 'mm',
    ),
    stx = device('nicos.generic.Axis',
            motor = 'stx_step',
            coder = 'stx_step',
            obs = ['stx_poti'],
            precision = 0.05,
            fmtstr='%.1f',
    ),
    
    # STY is sixth device and has 1 stepper, 1 poti, 0 coder
    sty_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x56,
            slope = 1600,
            unit = 'mm',
            abslimits = (-15,15),
            zerosteps = 500000,
            speed = 50,
            accel = 20,
            microstep = 2,
            #~ divider = 4,
            #~ current = 1.5,
    ),
    sty_poti = device('nicos.ipc.Coder',
            bus = 'bus2',
            addr = 0x66,
            slope = -159.3,
            zerosteps = 4144,
            unit = 'mm',
    ),
    sty = device('nicos.generic.Axis',
            motor = 'sty_step',
            coder = 'sty_step',
            obs = ['sty_poti'],
            precision = 0.05,
            fmtstr='%.1f',
    ),
    
    # STZ is seventh device and has 1 stepper, 0 poti, 0 coder
    stz_step = device('nicos.ipc.Motor',
            bus = 'bus2',
            addr = 0x57,
            slope = 20000,
            unit = 'mm',
            abslimits = (-20,20),
            zerosteps = 500000,
            speed = 150,
            accel = 20,
            microstep = 2,
            #~ divider = 4,
            #~ current = 1.5,
    ),

    stz = device('nicos.generic.Axis',
            motor = 'stz_step',
            coder = 'stz_step',
            obs = [],
            precision = 0.1,
            fmtstr='%.1f',
    ),
    
    # eigth device is not used yet......
    
)
