description = 'Attenuators'
group = 'optional'
display_order = 2

devices = dict(
    att0 = device('nicos.devices.generic.ManualSwitch',
        description = 'Attenuator 0: factor 3',
        states = ['in', 'out'],
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att1 = device('nicos.devices.generic.ManualSwitch',
        description = 'Attenuator 1: factor 15',
        states = ['in', 'out'],
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att2 = device('nicos.devices.generic.ManualSwitch',
        description = 'Attenuator 2: factor 30',
        states = ['in', 'out'],
        unit = '',
        maxage = 119,
        pollinterval = 60,
        visibility = (),
    ),
    att = device('nicos_mlz.pgaa.devices.Attenuator',
        description = 'Attenuator device',
        moveables = ['att0', 'att1', 'att2'],
        readables = None,
        precision = None,
        unit = '%',
        fmtstr = '%.1f',
        mapping = {
            100.: ('out', 'out', 'out'),
            47.: ('out', 'in', 'out'),
            16.: ('in', 'out', 'out'),
            7.5: ('in', 'in', 'out'),
            5.9: ('out', 'out', 'in'),
            3.5: ('out', 'in', 'in'),
            2.7: ('in', 'out', 'in'),
            1.6: ('in', 'in', 'in'),
        },
        maxage = 119,
        pollinterval = 60,
    ),
)
