description = 'Resonance flippers'
group = 'lowlevel'
display_order = 24

devices = dict(
    hrf_0a = device('nicos.devices.generic.ManualMove',
        description = 'Helmholtz coils for resonant flippers arm 0 - A',
        fmtstr = '%.3f',
        pollinterval = 60,
        maxage = 120,
        unit = 'A',
        abslimits = (0, 100),
        # precision = 0.02,
    ),
    hrf_0a_rot = device('nicos.devices.generic.Axis',
        description = 'Rotation of the coil A',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-10, 10),
            unit = 'deg',
        ),
        precision = 0.05,
    ),
    hrf_0b = device('nicos.devices.generic.ManualMove',
        description = 'Helmholtz coils for resonant flipper arm 0 - B',
        fmtstr = '%.3f',
        pollinterval = 60,
        maxage = 120,
        unit = 'A',
        abslimits = (0, 100),
        # precision = 0.02,
    ),
    hrf_0b_rot = device('nicos.devices.generic.Axis',
        description = 'Rotation of the coil B',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-10, 10),
            unit = 'deg',
        ),
        precision = 0.05,
    ),
    hrf_1a = device('nicos.devices.generic.ManualMove',
        description = 'Helmholtz coils for resonant flipper arm 1 - A',
        fmtstr = '%.3f',
        pollinterval = 60,
        maxage = 120,
        unit = 'A',
        abslimits = (0, 100),
        # precision = 0.02,
    ),
    hrf_1b = device('nicos.devices.generic.ManualMove',
        description = 'Helmholtz coils for resonant flipper arm 1 - B',
        fmtstr = '%.3f',
        pollinterval = 60,
        maxage = 120,
        unit = 'A',
        abslimits = (0, 100),
        # precision = 0.02,
    ),
)
