description = 'Neutron Grating Interferometer at ICON'

group = 'optional'

tango_host = 'phytron2.psi.ch'

tango_base = f'tango://{tango_host}:10000/box/'

devices = dict(
    G0rz = device('nicos.devices.entangle.Motor',
        speed = 2.5,
        unit = 'deg',
        description = 'Rotation of G0 grating around beam direction',
        tangodevice = tango_base + 'phytron1/mot',
        abslimits = (-20, 20),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
    G1tx = device('nicos.devices.entangle.Motor',
        speed = 100,
        unit = 'um',
        description = 'Stepping of G1 perpendicular to the beam direction',
        tangodevice = tango_base + 'phytron4/mot',
        abslimits = (-12500, 12500),
        userlimits = (-12500, 12500),
        maxage = 5,
        pollinterval = 3,
        precision = 0.1,
    ),
    G1tz = device('nicos.devices.entangle.Motor',
        speed = 5,
        unit = 'mm',
        description = 'Translation of G1 parallel to the beam direction',
        tangodevice = tango_base + 'phytron3/mot',
        abslimits = (-80, 80),
        userlimits = (-80, 80),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
    G1rz = device('nicos.devices.entangle.Motor',
        speed = 5,
        unit = 'deg',
        description = 'Rotation of G1 around the beam axis',
        tangodevice = tango_base + 'phytron2/mot',
        abslimits = (-20, 20),
        userlimits = (-20, 20),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
    srz = device('nicos.devices.entangle.Motor',
        speed = 5,
        unit = 'deg',
        description = 'Sample rotation',
        tangodevice = tango_base + 'phytron8/mot',
        abslimits = (-999, 999),
        userlimits = (-999, 999),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
    stx = device('nicos.devices.entangle.Motor',
        speed = 5,
        unit = 'mm',
        description = 'Sample translation across',
        tangodevice = tango_base + 'phytron6/mot',
        abslimits = (0, 100),
        userlimits = (0, 100),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
    stz = device('nicos.devices.entangle.Motor',
        speed = 5,
        unit = 'mm',
        description = 'Sample translation along the beam direction',
        tangodevice = tango_base + 'phytron7/mot',
        abslimits = (0, 400),
        userlimits = (0, 400),
        maxage = 5,
        pollinterval = 3,
        precision = 0.001,
    ),
)
