description = 'Setup for NIST G1 NGI.'

display_order = 20

pvprefix= 'NCNR:'

devices = dict(
    g1m1 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m1 motor',
        motorpv = pvprefix + 'G1:m1',
        errormsgpv = pvprefix + 'G1:m1-MsgTxt',
        precision = 0.01,
    ),
    g1m2 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m2 motor',
        motorpv = pvprefix + 'G1:m2',
        errormsgpv = pvprefix + 'G1:m2-MsgTxt',
        precision = 0.01,
    ),
    g1m3 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m3 motor',
        motorpv = pvprefix + 'G1:m3',
        errormsgpv = pvprefix + 'G1:m3-MsgTxt',
        precision = 0.01,
    ),
    g1m4 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m4 motor',
        motorpv = pvprefix + 'G1:m4',
        errormsgpv = pvprefix + 'G1:m4-MsgTxt',
        precision = 0.01,
    ),
    g1m5 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m1 motor',
        motorpv = pvprefix + 'G1:m5',
        errormsgpv = pvprefix + 'G1:m5-MsgTxt',
        precision = 0.01,
    ),
    g1m6 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G1 m1 motor',
        motorpv = pvprefix + 'G1:m6',
        errormsgpv = pvprefix + 'G1:m6-MsgTxt',
        precision = 0.01,
    ),
    g2m1 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m1 motor',
        motorpv = pvprefix + 'G2:m1',
        errormsgpv = pvprefix + 'G2:m1-MsgTxt',
        precision = 0.01,
    ),
    g2m2 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m2 motor',
        motorpv = pvprefix + 'G2:m2',
        errormsgpv = pvprefix + 'G2:m2-MsgTxt',
        precision = 0.01,
    ),
    g2m3 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m3 motor',
        motorpv = pvprefix + 'G2:m3',
        errormsgpv = pvprefix + 'G2:m3-MsgTxt',
        precision = 0.01,
    ),
    g2m4 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m4 motor',
        motorpv = pvprefix + 'G2:m4',
        errormsgpv = pvprefix + 'G2:m4-MsgTxt',
        precision = 0.01,
    ),
    g2m5 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m1 motor',
        motorpv = pvprefix + 'G2:m5',
        errormsgpv = pvprefix + 'G2:m5-MsgTxt',
        precision = 0.01,
    ),
    g2m6 = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G2 m1 motor',
        motorpv = pvprefix + 'G2:m6',
        errormsgpv = pvprefix + 'G2:m6-MsgTxt',
        precision = 0.01,
    ),
    g0x = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G0 x motor',
        motorpv = pvprefix + 'G0:x',
        errormsgpv = pvprefix + 'G0:x-MsgTxt',
        precision = 0.01,
    ),
    g0y = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST G0 y motor',
        motorpv = pvprefix + 'G0:y',
        errormsgpv = pvprefix + 'G0:y-MsgTxt',
        precision = 0.01,
    ),
    g0d = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        description = 'NIST d motor',
        motorpv = pvprefix + 'D',
        errormsgpv = pvprefix + 'D-MsgTxt',
        precision = 0.01,
    ),
)
