description = 'detector moving devices'

group = 'lowlevel'

devices = dict(
    det_drift = device('nicos.devices.generic.ManualSwitch',
        description = 'depth of detector drift1=40mm drift2=65mm',
        states = ['off', 'drift1', 'drift2'],
    ),
    det_pivot = device('nicos_mlz.refsans.devices.pivot.PivotPoint',
        description = 'Pivot point at floor of samplechamber',
        states = list(range(1, 15)),
        fmtstr = 'Point %d',
        unit = '',
    ),
    table_z_motor = device('nicos.devices.generic.VirtualMotor',
        description = 'table inside tube',
        unit = 'mm',
        abslimits = (620, 11025),
        lowlevel = True,
        curvalue = 620,
    ),
    det_table = device('nicos.devices.generic.Axis',
        description = 'detector table inside tube',
        motor = 'table_z_motor',
        dragerror = 10.,
        precision = 0.05,
    ),
    tube_m = device('nicos.devices.generic.VirtualMotor',
        description = 'tube Motor',
        abslimits = (-120, 1100),
        lowlevel = True,
        unit = 'mm',
        speed = 10,
        fmtstr = '%.0f',
        # lowlevel = True,
    ),
    det_yoke = device('nicos.devices.generic.Axis',
        description = 'tube height',
        motor = 'tube_m',
        precision = 0.05,
        dragerror = 10.,
    ),
    tube_angle = device('nicos_mlz.refsans.devices.tube.TubeAngle',
        description = 'Angle between flight tube and ground',
        yoke = 'det_yoke',
    ),
)
