description = 'Sample table devices'

group = 'optional'

devices = dict(
    gonio_theta = device('nicos.devices.generic.Axis',
        description = 'Theta axis',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-500, 500),
            speed = 0.125,
            unit = 'deg',
        ),
        precision = 0.01,
    ),
    gonio_phi = device('nicos.devices.generic.Axis',
        description = 'Phi axis',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-500, 500),
            speed = 1.,
            unit = 'deg',
        ),
        precision = 0.01,
    ),
    gonio_omega = device('nicos.devices.generic.Axis',
        description = 'Omega axis',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-500, 500),
            speed = 0.1,
            unit = 'deg',
        ),
        coder = 'gonio_omega_e',
        precision = 0.01,
    ),
    gonio_y = device('nicos.devices.generic.Axis',
        description = 'Y axis',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-500, 500),
            speed = 0.2,
            unit = 'mm',
        ),
        precision = 0.01,
    ),
    gonio_z = device('nicos.devices.generic.Axis',
        description = 'Z axis',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-500, 500),
            speed = 0.5,
            unit = 'mm',
        ),
        precision = 0.01,
    ),
)
