description = 'Monochromator tower devices'

group = 'lowlevel'

tango_base = 'tango://kompasshw.kompass.frm2.tum.de:10000/kompass/'

devices = dict(
    # A1
    mth = device('nicos.devices.generic.Axis',
        description = 'monochromator theta (A1)',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 70),
            unit = 'deg',
        ),
        fmtstr = '%.3f',
        precision = 0.001,
    ),
    # A2
    mtt = device('nicos.devices.generic.Axis',
        description = 'primary spectrometer angle (A2)',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (31, 120),
            unit = 'deg',
        ),
        fmtstr = '%.4f',
        precision = 0.001,
    ),
    mx = device('nicos.devices.generic.Axis',
        description = 'monochromator table X',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-4.8, 4.8),
            unit = 'deg',
        ),
        fmtstr = '%.2f',
        precision = 0.05,
    ),
    my = device('nicos.devices.generic.Axis',
        description = 'monochromator table Y',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-4.8, 4.8),
            unit = 'mm',
        ),
        fmtstr = '%.2f',
        precision = 0.05,
    ),
    mc = device('nicos.devices.generic.Axis',
        description = 'monochromator table cradle',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-5, 5),
            unit = 'mm',
        ),
        fmtstr = '%.1f',
        precision = 0.05,
    ),
    mfv = device('nicos.devices.generic.Axis',
        description = 'monochromator vertical focus',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 300),
            unit = 'deg',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    mfh = device('nicos.devices.generic.Axis',
        description = 'monochromator horizontal focus',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 300),
            unit = 'deg',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    mono = device('nicos.devices.tas.Monochromator',
        description = 'monochromator unit to move incoming wavevector',
        unit = 'A-1',
        theta = 'mth',
        twotheta = 'mtt',
        focush = 'mfh',
        focusv = 'mfv',
        # abslimits = (0.1, 10),
        abslimits = (1.08, 3.3),
        focmode = 'manual',  # for now
        hfocuspars = [0],
        vfocuspars = [0],
        scatteringsense = 1,
        crystalside = 1,
        dvalue = 3.355,
    ),
    mshl = device('nicos.devices.generic.Axis',
        description = 'monochromator slit left',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 95),
            unit = 'mm',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
        visibility = (),
    ),
    mshr = device('nicos.devices.generic.Axis',
        description = 'monochromator slit right',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 95),
            unit = 'mm',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
        visibility = (),
    ),
    msvb = device('nicos.devices.generic.Axis',
        description = 'monochromator slit bottom',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 95),
            unit = 'mm',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
        visibility = (),
    ),
    msvt = device('nicos.devices.generic.Axis',
        description = 'monochromator slit top',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (0, 95),
            unit = 'mm',
        ),
        fmtstr = '%.2f',
        precision = 0.01,
        visibility = (),
    ),
    ms = device('nicos.devices.generic.Slit',
        description = 'slit before monochromator',
        left = 'mshl',
        right = 'mshr',
        bottom = 'msvb',
        top = 'msvt',
        opmode = 'offcentered',
        coordinates = 'opposite',
    ),
)
