description = 'JJ XRAY sample slits'
group = 'lowlevel'

devices = dict(
    ss1r = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 30),
        unit = 'mm',
        precision = 0.1,
    ),
    ss1l = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 30),
        unit = 'mm',
        precision = 0.1,
    ),
    ss1b = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-20, 50),
        unit = 'mm',
        precision = 0.1,
    ),
    ss1t = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-20, 50),
        unit = 'mm',
        precision = 0.1,
    ),
    ss1 = device('nicos.devices.generic.Slit',
        description = 'First sample slit',
        left = 'ss1l',
        right = 'ss1r',
        bottom = 'ss1b',
        top = 'ss1t',
        opmode = 'offcentered',
        coordinates = 'opposite',
    ),
    ss2r = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 30),
        unit = 'mm',
        precision = 0.1,
    ),
    ss2l = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 30),
        unit = 'mm',
        precision = 0.1,
    ),
    ss2b = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 50),
        unit = 'mm',
        precision = 0.1,
    ),
    ss2t = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        abslimits = (-10, 50),
        unit = 'mm',
        precision = 0.1,
    ),
    ss2 = device('nicos.devices.generic.Slit',
        description = 'Second sample slit',
        left = 'ss2l',
        right = 'ss2r',
        bottom = 'ss2b',
        top = 'ss2t',
        opmode = 'offcentered',
        coordinates = 'opposite',
    ),
)
