description = 'sample table devices'

group = 'lowlevel'

devices = dict(
    samplerot = device('nicos.devices.generic.VirtualMotor',
        description = 'Motor to change the sample position',
        fmtstr = '%7.1f',
        abslimits = (-5, 365),
        speed = 10,
        unit = 'deg',
        lowlevel = True,
    ),
    samplemotor = device('nicos.devices.generic.MultiSwitcher',
        description = 'Sample switcher',
        moveables = ['samplerot'],
        mapping = {
            1: [0.0],
            2: [22.5],
            3: [45.0],
            4: [67.5],
            5: [90.0],
            6: [112.5],
            7: [135.0],
            8: [157.5],
            9: [180.0],
            10: [202.5],
            11: [225.0],
            12: [247.5],
            13: [270.0],
            14: [292.5],
            15: [315.0],
            16: [337.5],
        },
        precision = [0.1],
        blockingmove = False,
        fmtstr = '%d',
        lowlevel = True,
    ),
    push = device('nicos.devices.generic.ManualSwitch',
        description = 'Push sample up and down',
        states = ['up', 'down'],
    ),
    sc = device('nicos_mlz.pgaa.devices.SampleChanger',
        description = 'The sample changer',
        motor = 'samplemotor',
        push = 'push',
    ),
)
