description = 'XYZ-Omega sample table'

group = 'lowlevel'

excludes = ['samplechanger']

devices = dict(
    x_m = device('nicos.devices.generic.VirtualMotor',
        description = 'X axis sample table motor',
        abslimits = (0, 200),
        speed = 5,
        lowlevel = True,
        unit = 'mm',
    ),
    x = device('nicos.devices.generic.Axis',
        description = 'X translation of the sample table',
        motor = 'x_m',
        precision = 0.01,
    ),
    y_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Y axis sample table motor',
        abslimits = (0, 200),
        speed = 5,
        lowlevel = True,
        unit = 'mm',
    ),
    y = device('nicos.devices.generic.Axis',
        description = 'Y translation of the sample table',
        motor = 'y_m',
        precision = 0.01,
    ),
    z_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Z axis sample table motor',
        abslimits = (0, 200),
        speed = 5,
        lowlevel = True,
        unit = 'mm',
    ),
    z = device('nicos.devices.generic.Axis',
        description = 'Z translation of the sample table',
        motor = 'z_m',
        precision = 0.01,
    ),
    omega_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Omega axis sample table motor',
        abslimits = (0, 361),
        speed = 5,
        lowlevel = True,
        unit = 'deg',
    ),
    omega = device('nicos.devices.generic.Axis',
        description = 'Rotation of the sample table',
        motor = 'omega_m',
        precision = 0.01,
    ),
)
