description = 'sample table devices'

group = 'lowlevel'

devices = dict(
    samplemotor = device('nicos.devices.generic.VirtualMotor',
        description = 'Motor to change the sample position',
        abslimits = (1, 16),
        speed = 0.1,
        unit = 'Pos',
        curvalue = 1,
        lowlevel = True,
        fmtstr = '%.1f',
    ),
    pushactuator = device('nicos.devices.generic.ManualSwitch',
        description = 'Push sample up and down',
        states = ['up', 'down'],
        fmtstr = '%d',
        lowlevel = True,
    ),
    sensort = device('nicos_demo.vpgaa.devices.sampledevices.PushReader',
        moveable = 'pushactuator',
        inverse = True,
        lowlevel = True,
    ),
    sensorl = device('nicos_demo.vpgaa.devices.sampledevices.PushReader',
        moveable = 'pushactuator',
        lowlevel = True,
    ),
    push = device('nicos_mlz.pgaa.devices.sampledevices.SamplePusher',
        description = 'Push sample up and down',
        unit = '',
        actuator = 'pushactuator',
        sensort = 'sensort',
        sensorl = 'sensorl',
    ),
    sc = device('nicos_mlz.pgaa.devices.SampleChanger',
        description = 'The sample changer',
        motor = 'samplemotor',
        push = 'push',
    ),
)
