description = 'The Lakeshore 224 in the ESSIIP-lab.'

pv_root = 'SES-FLUC:Tmonit-LS224-001:'

devices = dict(
    Chan_A = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel A temperature reading',
        readpv = '{}KRDGA'.format(pv_root),
    ),
    Chan_B = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel B temperature reading',
        readpv = '{}KRDGB'.format(pv_root),
    ),
    Chan_C1 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel C1 temperature reading',
        readpv = '{}KRDGC1'.format(pv_root),
    ),
    Chan_C2 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel C2 temperature reading',
        readpv = '{}KRDGC2'.format(pv_root),
    ),
    Chan_C3 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel C3 temperature reading',
        readpv = '{}KRDGC3'.format(pv_root),
    ),
    Chan_C4 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel C4 temperature reading',
        readpv = '{}KRDGC4'.format(pv_root),
    ),
    Chan_C5 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel C5 temperature reading',
        readpv = '{}KRDGC5'.format(pv_root),
    ),
    Chan_D1 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel D1 temperature reading',
        readpv = '{}KRDGD1'.format(pv_root),
    ),
    Chan_D2 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel D2 temperature reading',
        readpv = '{}KRDGD2'.format(pv_root),
    ),
    Chan_D3 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel D3 temperature reading',
        readpv = '{}KRDGD3'.format(pv_root),
    ),
    Chan_D4 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel D4 temperature reading',
        readpv = '{}KRDGD4'.format(pv_root),
    ),
    Chan_D5 = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'Channel D5 temperature reading',
        readpv = '{}KRDGD5'.format(pv_root),
    ),
    LS224_Firmware = device('nicos_ess.devices.epics.base.EpicsStringReadableEss',
        description = 'The device firmware',
        readpv = '{}FIRMWARE'.format(pv_root),
        lowlevel=True,
    ),
    LS224_Model = device('nicos_ess.devices.epics.base.EpicsStringReadableEss',
        description = 'The device model',
        readpv = '{}MODEL'.format(pv_root),
        lowlevel=True,
    ),
    LS224_Serial = device('nicos_ess.devices.epics.base.EpicsStringReadableEss',
        description = 'The serial number',
        readpv = '{}SERIAL'.format(pv_root),
        lowlevel=True,
    ),
    LS224_Relay1 = device('nicos_ess.devices.epics.base.EpicsDigitalMoveableEss',
        description = 'Relay 1 setting',
        readpv = '{}RELAY1'.format(pv_root),
        writepv = '{}RELAYST1'.format(pv_root),
        lowlevel=True,
    ),
    LS224_Relay2 = device('nicos_ess.devices.epics.base.EpicsDigitalMoveableEss',
        description = 'Relay 2 setting',
        readpv = '{}RELAY2'.format(pv_root),
        writepv = '{}RELAYST2'.format(pv_root),
        lowlevel=True,
    ),
)
