description = 'Cryopad current settings'

group = 'lowlevel'

tango_base = 'tango://phys.poli.frm2:10000/poli/'

devices = dict(
    nutator1c = device('nicos.devices.entangle.PowerSupply',
        description = 'Nutator 1 current',
        tangodevice = tango_base + 'kepco/cur1',
        fmtstr = '%.2f',
        abslimits = (-3, 3),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    nutator2c = device('nicos.devices.entangle.PowerSupply',
        description = 'Nutator 2 current',
        tangodevice = tango_base + 'kepco/cur3',
        fmtstr = '%.2f',
        abslimits = (-3, 3),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    nutax = device('nicos.devices.entangle.PowerSupply',
        description = 'Nutator axial current',
        tangodevice = tango_base + 'nutax12/current',
        fmtstr = '%.2f',
        abslimits = (0, 3),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    pc1 = device('nicos.devices.entangle.PowerSupply',
        description = 'Precession coil 1 current',
        tangodevice = tango_base + 'kepco/cur2',
        fmtstr = '%.3f',
        abslimits = (-5, 5),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    pc2 = device('nicos.devices.entangle.PowerSupply',
        description = 'Precession coil 2 current',
        tangodevice = tango_base + 'kepco/cur4',
        fmtstr = '%.3f',
        abslimits = (-5, 5),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    decpolcorr1 = device('nicos.devices.entangle.PowerSupply',
        description = 'Detector polarizer correction current 1',
        tangodevice = tango_base + 'decpolcorr1/current',
        fmtstr = '%.2f',
        abslimits = (0, 5),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    decpolcorr2 = device('nicos.devices.entangle.PowerSupply',
        description = 'Detector polarizer correction current 2',
        tangodevice = tango_base + 'decpolcorr2/current',
        fmtstr = '%.2f',
        abslimits = (0, 5),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    decpolmain = device('nicos.devices.entangle.PowerSupply',
        description = 'Detector polarizer main current',
        tangodevice = tango_base + 'decpolmain/current',
        fmtstr = '%.2f',
        unit = 'A',
        pollinterval = 10,
        maxage = 15,
        abslimits = (0, 2),
    ),
    polarmain = device('nicos.devices.entangle.PowerSupply',
        description = 'Polarizer main current',
        tangodevice = tango_base + 'polarmain/current',
        fmtstr = '%.2f',
        abslimits = (0, 2),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    polarcorr1 = device('nicos.devices.entangle.PowerSupply',
        description = 'Polarizer correction current 1',
        tangodevice = tango_base + 'polarbeam/current',
        fmtstr = '%.2f',
        abslimits = (0, 2),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),
    polarcorr2 = device('nicos.devices.entangle.PowerSupply',
        description = 'Polarizer correction current 2',
        tangodevice = tango_base + 'polarnut/current',
        fmtstr = '%.2f',
        abslimits = (0, 2),
        unit = 'A',
        pollinterval = 60,
        maxage = 65,
    ),

    pcflipper = device('nicos.devices.polarized.MezeiFlipper',
        description = 'Mezei flipper using pc1 and pc2 supplies',
        flip = 'decpolcorr2',
        corr = 'decpolcorr1',
    ),
)
