description = 'memograph readout'

includes = []

group = 'optional'

devices = dict(
    t_in_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'T_in POLI',
        description = 'inlet temperature memograph',
        fmtstr = '%.2F',
        warnlimits = (-1, 17.5),  # -1 no lower value
        unit = 'degC',
    ),
    t_out_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'T_out POLI',
        description = 'outlet temperature memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        unit = 'degC',
    ),
    p_in_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'P_in POLI',
        description = 'inlet pressure memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        unit = 'bar',
    ),
    p_out_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'P_out POLI',
        description = 'outlet pressure memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        unit = 'bar',
    ),
    flow_in_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'FLOW_in POLI',
        description = 'inlet flow memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        warnlimits = (0.2, 100),  # 100 no upper value
        unit = 'l/min',
    ),
    flow_out_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'FLOW_out POLI',
        description = 'outlet flow memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        unit = 'l/min',
    ),
    leak_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'Leak POLI',
        description = 'leakage memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        warnlimits = (-1, 1),  # -1 no lower value
        unit = 'l/min',
    ),
    cooling_poli = device('nicos_mlz.frm2.devices.memograph.MemographValue',
        hostname = 'memograph-uja01.care.frm2',
        group = 2,
        valuename = 'Cooling POLI',
        description = 'cooling power memograph',
        pollinterval = 30,
        maxage = 60,
        fmtstr = '%.2F',
        unit = 'kW',
    ),
)
