description = 'Shutter devices'
group = 'lowlevel'

tango_base = 'tango://192.168.168.1:10000/tomo/sw/'

devices = dict(
    open_shutter = device('nicos.devices.generic.Pulse',
        description = 'Instrument shutter open button',
        onvalue = 1,
        offvalue = 0,
        ontime = 20,
        moveable = device('nicos.devices.entangle.DigitalOutput',
            tangodevice = tango_base + 'out0',
        ),
        fmtstr = '%d',
        visibility = (),
    ),
    close_shutter = device('nicos.devices.generic.Pulse',
        description = 'Instrument shutter close button',
        onvalue = 1,
        offvalue = 0,
        ontime = 20,
        moveable = device('nicos.devices.entangle.DigitalOutput',
            tangodevice = tango_base + 'out1',
        ),
        fmtstr = '%d',
        visibility = (),
    ),
    open_signal = device('nicos.devices.entangle.DigitalInput',
        description = 'Instrument shutter open signal lamp',
        tangodevice = tango_base + 'in0',
        fmtstr = '%d',
        visibility = (),
    ),
    closed_signal = device('nicos.devices.entangle.DigitalInput',
        description = 'Instrument shutter closed signal lamp',
        tangodevice = tango_base + 'in1',
        fmtstr = '%d',
        visibility = (),
    ),
    shutter = device('nicos_cvut.tomo.devices.Shutter',
        description = 'Instrument shutter',
        opener = 'open_shutter',
        closer = 'close_shutter',
        open_signal = 'open_signal',
        closed_signal = 'closed_signal',
        fullopening_time = 60,
    ),
)
