description = 'Monochroamtor devices SINQ MORPHEUS.'

pvprefix = 'SQ:MORPHEUS:motc:'

devices = dict(
    mth = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator Theta Motor',
        motorpv = pvprefix + 'mth',
        errormsgpv = pvprefix + 'mth-MsgTxt',
        precision = 0.01,
    ),
    mtt = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator Two Theta Motor',
        motorpv = pvprefix + 'mtt',
        errormsgpv = pvprefix + 'mtt-MsgTxt',
        precision = 0.01,
    ),
    mfv = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        precision = .1,
        description = 'Monochromator Curvature Motor',
        motorpv = pvprefix + 'mfv',
        errormsgpv = pvprefix + 'mfv-MsgTxt',
    ),
    mtx = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator X Translation',
        motorpv = pvprefix + 'mtx',
        precision = .1,
        errormsgpv = pvprefix + 'mtx-MsgTxt',
    ),
    mty = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator Y Translation',
        motorpv = pvprefix + 'mty',
        precision = .1,
        errormsgpv = pvprefix + 'mty-MsgTxt',
    ),
    mgx = device('nicos.devices.epics.pyepics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Monochromator Goniometer Rotation',
        motorpv = pvprefix + 'mgx',
        precision = .1,
        errormsgpv = pvprefix + 'mgx-MsgTxt',
    ),
    wavelength = device('nicos_sinq.devices.mono.SinqMonochromator',
        description = 'PG 002',
        unit = 'A',
        theta = 'mth',
        twotheta = 'mtt',
        focush = None,
        focusv = 'mfv',
        order = 1,
        abslimits = (2, 5),
        vfocuspars = [-0.025942, 5.351660],
        material = 'PG',
        reflection = (0, 0, 2),
        dvalue = 3.3537,
        scatteringsense = -1,
        crystalside = -1,
    ),
)
