description = 'MORPHEUS Slit motors'

pvprefix = 'SQ:MORPHEUS:mota:'

devices = dict(
    mota = device('nicos_ess.devices.epics.extensions.EpicsCommandReply',
        epicstimeout = 3.0,
        description = 'Mota controller direct',
        commandpv = 'SQ:MORPHEUS:MOTA' + '.AOUT',
        replypv = 'SQ:MORPHEUS:MOTA' + '.AINP',
    ),
    vd1r = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd1l = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd1t = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd1b = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd2r = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd2l = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd2t = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd2b = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd3r = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd3l = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd3t = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    vd3b = device('nicos.devices.generic.VirtualMotor',
        visibility = (),
        fmtstr = '%.2f',
        abslimits = (-600, 600),
        speed = 10,
        unit = 'mm',
    ),
    d1r = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 1 right motor',
        motorpv = pvprefix + 'd1r',
        errormsgpv = pvprefix + 'd1r-MsgTxt',
        precision = 0.01,
    ),
    d1l = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 1 left motor',
        motorpv = pvprefix + 'd1l',
        errormsgpv = pvprefix + 'd1l-MsgTxt',
        precision = 0.01,
    ),
    d2r = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 right motor',
        motorpv = pvprefix + 'd2r',
        errormsgpv = pvprefix + 'd2r-MsgTxt',
        precision = 0.01,
    ),
    d2l = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 2 left motor',
        motorpv = pvprefix + 'd2l',
        errormsgpv = pvprefix + 'd2l-MsgTxt',
        precision = 0.01,
    ),
    d3r = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 3 right motor',
        motorpv = pvprefix + 'd3r',
        errormsgpv = pvprefix + 'd3r-MsgTxt',
        precision = 0.01,
    ),
    d3l = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 3 left motor',
        motorpv = pvprefix + 'd3l',
        errormsgpv = pvprefix + 'd3l-MsgTxt',
        precision = 0.01,
    ),
    dxb = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Shared slit bottom motor',
        motorpv = pvprefix + 'dxb',
        errormsgpv = pvprefix + 'dxb-MsgTxt',
        precision = 0.01,
    ),
    dxt = device('nicos_ess.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Shared slit top motor',
        motorpv = pvprefix + 'dxt',
        errormsgpv = pvprefix + 'dxt-MsgTxt',
        precision = 0.01,
    ),
    sps = device('nicos_ess.devices.epics.extensions.EpicsCommandReply',
        epicstimeout = 3.0,
        description = 'SPS direct',
        commandpv = 'SQ:MORPHEUS:spsdirect' + '.AOUT',
        replypv = 'SQ:MORPHEUS:spsdirect' + '.AINP',
    ),
    aldi = device('nicos_sinq.morpheus.devices.aldimotor.AldiController',
        description = 'Controller for slit stage switching',
        motors = ['dxt', 'dxb'],
        motor_controller = 'mota',
        readpv = 'SQ:MORPHEUS:SPS1:DigitalInput',
        writepv = 'SQ:MORPHEUS:SPS1:Push'
    ),
    d1t = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 1 top motor',
        stage_number = 1,
        real_motor = 'dxt',
        unit = 'mm',
        controller = 'aldi'
    ),
    d1b = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 1 bottom motor',
        stage_number = 1,
        real_motor = 'dxb',
        unit = 'mm',
        controller = 'aldi'
    ),
    d2t = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 2 top motor',
        stage_number = 2,
        real_motor = 'dxt',
        unit = 'mm',
        controller = 'aldi'
    ),
    d2b = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 2 bottom motor',
        stage_number = 2,
        real_motor = 'dxb',
        unit = 'mm',
        controller = 'aldi'
    ),
    d3t = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 3 top motor',
        stage_number = 3,
        real_motor = 'dxt',
        unit = 'mm',
        controller = 'aldi'
    ),
    d3b = device('nicos_sinq.morpheus.devices.aldimotor.AldiMotor',
        description = 'Slit 3 bottom motor',
        stage_number = 3,
        real_motor = 'dxb',
        unit = 'mm',
        controller = 'aldi'
    ),
    slit1h = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 1 with left, right motors, virtual bottom and top',
        opmode = '4blades',
        left = 'd1l',
        right = 'd1r',
        top = 'vd1t',
        bottom = 'vd1b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit1v = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 1 with bottom and top motors, virtual left, right',
        opmode = '4blades',
        left = 'vd1l',
        right = 'vd1r',
        top = 'd1t',
        bottom = 'd1b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit2h = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2 with left, right motors, virtual bottom and top',
        opmode = '4blades',
        left = 'd2l',
        right = 'd2r',
        top = 'vd2t',
        bottom = 'vd2b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit2v = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2 with bottom and top motors, virtual left, right',
        opmode = '4blades',
        left = 'vd2l',
        right = 'vd2r',
        top = 'd2t',
        bottom = 'd2b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit3h = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 3 with left, right motors, virtual bottom and top',
        opmode = '4blades',
        left = 'd3l',
        right = 'd3r',
        top = 'vd3t',
        bottom = 'vd3b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit3v = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 3 with bottom and top motors, virtual left, right',
        opmode = '4blades',
        left = 'vd3l',
        right = 'vd3r',
        top = 'd3t',
        bottom = 'd3b',
        coordinates = 'opposite',
        visibility = (),
    ),
    slit1_height = device('nicos_sinq.amor.devices.slit.SlitOpening',
        description = 'Slit 1 opening controller',
        slit = 'slit1v',
    ),
    slit1_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Slit 1 width controller',
        slit = 'slit1h',
        unit = 'mm',
    ),
    #    slit2 = device('nicos.devices.generic.slit.Slit',
    #        description = 'Slit 2 with left, right, bottom and top motors',
    #        opmode = '4blades',
    #        coordinates='opposite',
    #        left = 'd2l',
    #        right = 'd2r',
    #        top = 'd2t',
    #        bottom = 'd2b',
    #        visibility = (),
    #    ),
    slit2_height = device('nicos_sinq.amor.devices.slit.SlitOpening',
        description = 'Slit 2 opening controller',
        slit = 'slit2v',
    ),
    slit2_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Slit 2 width controller',
        slit = 'slit2h',
        unit = 'mm',
    ),
    #    slit3 = device('nicos.devices.generic.slit.Slit',
    #        description = 'Slit 3 with left, right, bottom and top motors',
    #        opmode = '4blades',
    #        coordinates='opposite',
    #        left = 'd3l',
    #        right = 'd3r',
    #        top = 'd3t',
    #        bottom = 'd3b',
    #        visibility = (),
    #    ),
    slit3_height = device('nicos_sinq.amor.devices.slit.SlitOpening',
        description = 'Slit 3 opening controller',
        slit = 'slit3v',
    ),
    slit3_width = device('nicos.devices.generic.slit.WidthSlitAxis',
        description = 'Slit 3 width controller',
        slit = 'slit3h',
        unit = 'mm',
    ),
)
