#  -*- coding: utf-8 -*-

description = 'Analysator'

includes = ['system', 'motorbus6']

group = 'lowlevel'

devices = dict(
# Att and ATH
    st_att = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus6',
                    addr = 60,
                    slope = -267.8,
                    unit = 'deg',
                    abslimits = (-117, 117),
                    zerosteps = 500000,
                    lowlevel = True,
                    confbyte = 104,
                    startdelay = 1,
                    stopdelay = 2,
                   ),

    st_ath = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus6',
                    addr = 59,
                    slope = -400,
                    unit = 'deg',
                    abslimits = (0, 60),
                    zerosteps = 500000,
                    lowlevel = True,
                    confbyte = 108,
                   ),

    co_att = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 91,
                    slope = 2912.7111,
                    zerosteps = 124422,
                    unit = 'deg',
                    circular = -360,
                    lowlevel = True,
                   ),

    co_ath = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 90,
                    slope = 2912.7111,
                    zerosteps = 476397,
                    unit = 'deg',
                    lowlevel = True,
                   ),

    att = device('devices.generic.Axis',
                 description = 'Scattering angle two-theta of analyser',
                 motor = 'st_att',
                 coder = 'co_att',
                 obs = [],
                 precision = 0.01,
                 offset = -0.037, # 90.163 / 05.2017 GE
                 # offset = 0.307, # with collimator
                 jitter = 0.2,
                 dragerror = 1,
                 maxtries = 30,
                ),

    ath = device('devices.generic.Axis',
                 description = 'Rocking angle theta of analyser',
                 motor = 'st_ath',
                 coder = 'co_ath',
                 obs = [],
                 precision = 0.01,
                 # offset = -0.678, # with collimator
                 offset = -0.44176, # -0.442 / 05.2017 GE
                 maxtries = 8,
                ),

# Focusing horizontal for PG analyzer

   st_afpg = device('puma.ipc_puma.Motor1',
                    bus = 'motorbus6',
                    addr = 68,
                    slope = 368.4,
                    unit = 'deg',
                    abslimits = (-55, 55),
                    zerosteps = 482230,
                    lowlevel = True,
                   ),

   co_afpg = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 94,
                    slope = 79.48,
                    zerosteps = 482.63,
                    unit = 'deg',
                    lowlevel = True,
                   ),
   afpg   = device('puma.focus.FocusAxis',
                   description = 'Horizontal focus of PG-analyser',
                   motor = 'st_afpg',
                   coder = 'co_afpg',
                   obs = [],
                   uplimit = 55,
                   lowlimit = -55,
                   abslimits = (-55, 55),
                   flatpos = 4.92,
                   startpos = 4,
                   precision = 0.05,#it was 0.25
                   maxtries = 15,
                  ),

# Focusing horizontal for Ge311 Analysator
   st_afge = device('puma.ipc_puma.Motor1',
                    bus = 'motorbus6',
                    addr = 68,
                    slope = -372.9,
                    unit = 'deg',
                    abslimits = (-55, 55),
                    zerosteps = 508372.6,
                    lowlevel = True,
                   ),

   co_afge = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 94,
                    slope = -81.13,
                    zerosteps = 6262.19,
                    unit = 'deg',
                    lowlevel = True,
                   ),
   afge   = device('puma.focus.FocusAxis',
                   description = 'Horizontal focus of Ge-analyser',
                   motor = 'st_afge',
                   coder = 'co_afge',
                   obs = [],
                   uplimit = 55,
                   lowlimit = -55,
                   abslimits = (-55, 55),
                   flatpos = 4.92,
                   startpos = 4,
                   precision = 0.25,
                   maxtries = 15,
                  ),


# Tilt and Translation

   st_atx = device('devices.vendor.ipc.Motor',
                   bus = 'motorbus6',
                   addr = 64,
                   slope = -2500,
                   unit = 'mm',
                   abslimits = (-10.1, 7.6),
                   zerosteps = 500000,
                   lowlevel = True,
                  ),

   co_atx = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 96,
                    slope = 157.3,
                    zerosteps = 5073,
                    unit = 'mm',
                    lowlevel = True,
                   ),

    atx    = device('devices.generic.Axis',
                    description = 'Translation of analyser',
                    motor = 'st_atx',
                    coder = 'co_atx',
                    obs = [],
                    precision = 0.1,
                    offset = 0,
                    maxtries = 10,
                    loopdelay = 1,
                   ),

   st_aty = device('devices.vendor.ipc.Motor',
                   bus = 'motorbus6',
                   addr = 63,
                   slope = -2500,
                   unit = 'mm',
                   abslimits = (-7.1, 7.1),
                   zerosteps = 500000,
                   lowlevel = True,
                  ),


   co_aty = device('puma.ipc_puma.Coder',
                    bus = 'motorbus6',
                    addr = 95,
                    slope = -157.3,
                    zerosteps = 5026,
                    unit = 'mm',
                    lowlevel = True,
                   ),

    aty    = device('devices.generic.Axis',
                    description = 'Translation of analyser (corrects depth of pg-crystals)',
                    motor = 'st_aty',
                    coder = 'co_aty',
                    obs = [],
                    precision = 0.1,
                    offset = 0,
                    maxtries = 10,
                    loopdelay = 1,
                   ),

   st_agx = device('devices.vendor.ipc.Motor',
                   bus = 'motorbus6',
                   addr = 62,
                   slope = -5000,
                   unit = 'mm',
                   abslimits = (-5.5, 5.5),
                   zerosteps = 500000,
                   lowlevel = True,
                  ),

    agx   = device('devices.generic.Axis',
                    description = 'Tilt of analyser (up/down scattering)',
                    motor = 'st_agx',
                    coder = 'st_agx',
                    obs = [],
                    precision = 0.05,
                    offset = 0,
                    maxtries = 10,
                    backlash = 0.2,
                   ),

    st_agy = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus6',
                    addr = 61,
                    slope = 5000,
                    unit = 'mm',
                    abslimits = (-5.5, 4.5),
                    zerosteps = 500000,
                    lowlevel = True,
                   ),

    agy   = device('devices.generic.Axis',
                   description = 'Tilt of analyser',
                   motor = 'st_agy',
                   coder = 'st_agy',
                   obs = [],
                   precision = 0.05,
                   offset = 0,
                   maxtries = 10,
                   backlash = 0.2,
                  ),
    st_dslit = device('puma.ipc_puma.Motor',
                      bus = 'motorbus6',
                      addr = 67,
                      slope = 4500,
                      unit = 'mm',
                      abslimits = (-5.5, 30),
                      zerosteps = 500000,
                      lowlevel = True,
                     ),

    co_dslit = device('puma.ipc_puma.Coder',
                      bus = 'motorbus6',
                      addr = 97,
                      slope = 80,
                      zerosteps = 159,
                      unit = 'mm',
                      lowlevel = True,
                     ),

    dslit   = device('devices.generic.Axis',
                     description = 'Slit before detector',
                     motor = 'st_dslit',
                     coder = 'co_dslit',
                     obs = [],
                     precision = 0.05,
                     offset = 0,
                     maxtries = 10,
                    ),

)
