#  -*- coding: utf-8 -*-

description = 'Sample table'


includes = ['motorbus1', 'motorbus2', 'motorbus4', 'motorbus5', 'motorbus11']

devices = dict(
    st_phi = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus4',
                    addr = 53,
                    slope = 400,
                    unit = 'deg',
                    abslimits = (-5, 114.1),
                    zerosteps = 500000,
                    #confbyte = ,
                    #speed = ,
                    #accel = ,
                    #microstep = ,
                    #startdelay = ,
                    #stopdelay = ,
                    #ramptype = ,
                    lowlevel = True,
                    ),

    co_phi = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus1',
                    addr = 128,
                    slope = -(2**26)/360.,
                    zerosteps = 9392590,
                    #confbyte = ,
                    unit = 'deg',
                    circular = 360, # map values to -180..0..180 degree
                    lowlevel = True,
                    ),

    phi    = device('devices.generic.Axis',
                    motor = 'st_phi',
                    coder = 'co_phi',
                    obs = [],
                    precision = 0.005,
                    offset = 0.21,
                    maxtries = 5,
                    loopdelay = 1,
                    ),

    st_psi  = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus2',
                    addr = 58,
                    slope = -400,
                    unit = 'deg',
                    abslimits = (5, 355),
                    zerosteps = 602799,
                    lowlevel = True,
                    ),

    co_psi  = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus1',
                    addr = 129,
                    slope = -(2**20)/360.,
#                    zerosteps = 206142,
                    zerosteps = 954700,
                    unit = 'deg',
                    lowlevel = True,
                    circular = 360,
                    ),

    psi    = device('devices.generic.Axis',
                    motor = 'st_psi',
                    coder = 'co_psi',
                    obs = [],
                    precision = 0.005,
#                    offset = -256.997,
                    offset = 0,
                    userlimits = (5, 355),
                    maxtries = 5,
                    ),

# Tilting

    st_sgx = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus11',
                    addr = 64,
                    slope = -3200,
                    unit = 'deg',
                    abslimits = (-15.6, 15.6),
                    zerosteps = 500000,
                    lowlevel = True,
                    ),

    st_sgy = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus11',
                    addr = 65,
                    slope = -3200,
                    unit = 'deg',
                    abslimits = (-15.6, 15.6),
                    zerosteps = 500000,
                    lowlevel = True,
                    ),

    co_sgx = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus11',
                    addr = 70,
                    slope = -8192,
                    zerosteps = 33466203,
                    unit = 'deg',
                    lowlevel = True,
                    ),

    co_sgy = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus11',
                    addr = 71,
                    slope = -8192,
                    zerosteps = 33553860,
                    unit = 'deg',
                    lowlevel = True,
                    ),

    sgx    = device('devices.generic.Axis',
                    motor = 'st_sgx',
                    coder = 'co_sgx',
                    obs = [],
                    precision = 0.02,
                    offset = 0,
                    fmtstr = '%.3f',
                    maxtries = 5,
                    ),

    sgy    = device('devices.generic.Axis',
                    motor = 'st_sgy',
                    coder = 'co_sgy',
                    obs = [],
                    precision = 0.02,
                    offset = 0,
                    fmtstr = '%.3f',
                    maxtries = 5,
                    ),

# Translation

    st_stx = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus11',
                    addr = 66,
                    slope = -3165.36,
                    unit = 'mm',
                    abslimits = (-18, 13.5),
                    zerosteps = 500000,
                    lowlevel = True,
                    ),

    st_sty = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus11',
                    addr = 67,
                    slope = -3211,
                    unit = 'mm',
                    abslimits = (-18.1, 18.1),
                    zerosteps = 500000,
                    lowlevel = True,
                    ),

    co_stx = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus11',
                    addr = 74,
                    slope = -154,
                    zerosteps = 3798,
                    unit = 'mm',
                    lowlevel = True,
                    ),

    co_sty = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus11',
                    addr = 75,
                    slope = -160,
                    zerosteps = 4256,
                    unit = 'mm',
                    lowlevel = True,
                    ),

    stx    = device('devices.generic.Axis',
                    motor = 'st_stx',
                    coder = 'co_stx',
                    obs = [],
                    precision = 0.05,
                    offset = 0.5,
                    fmtstr = '%.3f',
                    maxtries = 9,
                    loopdelay = 1,
                    ),

    sty    = device('devices.generic.Axis',
                    motor = 'st_sty',
                    coder = 'co_sty',
                    obs = [],
                    precision = 0.05,
                    offset = -0.15,
                    fmtstr = '%.3f',
                    maxtries = 9,
                    loopdelay = 1,
                    ),

    st_stz = device('devices.vendor.ipc.Motor',
                    bus = 'motorbus11',
                    addr = 68,
                    slope = -20000,
                    unit = 'mm',
                    abslimits = (-20, 20),
                    zerosteps = 500000,
                    lowlevel = True,
                    ),

    co_stz = device('devices.vendor.ipc.Coder',
                    bus = 'motorbus11',
                    addr = 76,
                    slope = 155,
                    zerosteps = 4055,
                    unit = 'mm',
                    lowlevel = True,
                    ),

    stz    = device('devices.generic.Axis',
                    motor = 'st_stz',
                    coder = 'co_stz',
                    obs = [],
                    precision = 0.1,
                    offset = 0,
                    fmtstr = '%.2f',
                    maxtries = 10,
                    loopdelay = 2,
                    ),


#    st_echi= device('devices.vendor.ipc.Motor',
#                    bus = 'motorbus2',
#                    addr = 61,
#                    slope = 200,
#                    unit = 'deg',
#                    abslimits = (-355, 355),
#                    zerosteps = 500000,
#                    lowlevel = True,
#                    ),
#    st_ephi= device('devices.vendor.ipc.Motor',
#                    bus = 'motorbus5',
#                    addr = 84,
#                    slope = -200,
#                    unit = 'deg',
#                    abslimits = (-180, 180),
#                    zerosteps = 500000,
#                    lowlevel = True,
#                    ),


#    co_echi= device('devices.vendor.ipc.Coder',
#                    bus = 'motorbus1',
#                    addr = 132,
#                    slope = -8192.5,
#                    zerosteps = 5334445,
#                    unit = 'deg',
#                    lowlevel = True,
#                    ),
#    co_ephi= device('devices.vendor.ipc.Coder',
#                    bus = 'motorbus1',
#                    addr = 133,
#                    slope = 4096,
#                    zerosteps = 9059075,
#                    unit = 'deg',
#                    circular = -360, # map values to -180..0..180 degree
#                    lowlevel = True,
#                    ),


#    echi   = device('devices.generic.Axis',
#                    motor = 'st_echi',
#                    coder = 'co_echi',
#                    obs = [],
#                    precision = 0.01,
#                    offset = -189.99926762282576,
#                    fmtstr = '%.3f',
#                    maxtries = 5,
#                    ),
#    ephi   = device('devices.generic.Axis',
#                    motor = 'st_ephi',
#                    coder = 'co_ephi',
#                    obs = [],
#                    precision = 0.01,
#                    offset = 0,
#                    fmtstr = '%.3f',
#                    maxtries = 5,
#                    ),

)
