description = 'top sample table devices'

includes = ['sample_table_1']

group = 'optional'

tango_base = 'tango://sans1hw.sans1.frm2:10000/sans1/table/'

devices = dict(
    st2_z = device('nicos.devices.generic.Axis',
        description = 'table 2 z axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        abslimits = (-10, 10),
        precision = 0.01,
        motor = 'st2_zmot',
        coder = 'st2_zenc',
    ),
    st2_zmot = device('nicos.devices.tango.Motor',
        description = 'sample table 2 z motor',
        tangodevice = tango_base + 'st2_zmot',
        fmtstr = '%.2f',
        abslimits = (-10, 10),
        lowlevel = True,
    ),
    st2_zenc = device('nicos.devices.tango.Sensor',
        description = 'sample table 2 z encoder',
        tangodevice = tango_base + 'st2_zenc',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    st2_y = device('nicos.devices.generic.Axis',
        description = 'table 2 y axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        abslimits = (-25, 25),
        precision = 0.01,
        motor = 'st2_ymot',
        coder = 'st2_yenc',
    ),
    st2_ymot = device('nicos.devices.tango.Motor',
        description = 'sample table 2 y motor',
        tangodevice = tango_base + 'st2_ymot',
        fmtstr = '%.2f',
        abslimits = (-25, 25),
        lowlevel = True,
    ),
    st2_yenc = device('nicos.devices.tango.Sensor',
        description = 'sample table 2 y ',
        tangodevice = tango_base + 'st2_yenc',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    st2_x = device('nicos.devices.generic.Axis',
        description = 'table 2 x axis',
        pollinterval = 15,
        maxage = 60,
        fmtstr = '%.2f',
        abslimits = (-25, 25),
        precision = 0.01,
        motor = 'st2_xmot',
        coder = 'st2_xenc',
    ),
    st2_xmot = device('nicos.devices.tango.Motor',
        description = 'sample table 2 x motor',
        tangodevice = tango_base + 'st2_xmot',
        fmtstr = '%.2f',
        abslimits = (-25, 25),
        lowlevel = True,
    ),
    st2_xenc = device('nicos.devices.tango.Sensor',
        description = 'sample table 2 x encoder',
        tangodevice = tango_base + 'st2_xenc',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
)
