description = 'motors moving the detector in the detector chamber.'

group = 'lowlevel'

excludes = ['detector_motors']

devices = dict(
    det_Tx_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Detector translation x-Axis motor',
        fmtstr = '%.2f',
        abslimits = (37, 500),
        lowlevel = True,
#       ramp = 1000,
        speed = 2,
        requires = dict(level='guest'),
        unit = 'mm',
    ),
    det_Tx = device('nicos.devices.generic.Axis',
        description = 'Detector translation x-axis',
        motor = 'det_Tx_m',
        precision = 0.01,
    ),
    det_Ty_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Detector translation y-Axis motor',
        fmtstr = '%.2f',
        abslimits = (-5, 5),
        lowlevel = True,
#       ramp = 1000,
        speed = 2,
        requires = dict(level='guest'),
        unit = 'mm',
    ),
    det_Ty = device('nicos.devices.generic.Axis',
        description = 'Detector translation y-axis',
        motor = 'det_Ty_m',
        precision = 0.01,
    ),
    det_Tz_Upper_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Upper Detector half translation z-Axis motor',
        fmtstr = '%.2f',
        abslimits = (-10, 40),
        lowlevel = True,
#       ramp = 1000,
        speed = 2,
        requires = dict(level='guest'),
        unit = 'mm',
    ),
    det_Tz_Upper = device('nicos.devices.generic.Axis',
        description = 'Upper Detector half translation z-axis',
        motor = 'det_Tz_Upper_m',
        precision = 0.01,
    ),
    det_Tz_Lower_m = device('nicos.devices.generic.VirtualMotor',
        description = 'Lower Detector half translation z-Axis motor',
        fmtstr = '%.2f',
        abslimits = (-40, 12),
        lowlevel = True,
#       ramp = 1000,
        speed = 2,
        requires = dict(level='guest'),
        unit = 'mm',
    ),
    det_Tz_Lower = device('nicos.devices.generic.Axis',
        description = 'Lower Detector half translation z-axis',
        motor = 'det_Tz_Lower_m',
        precision = 0.01,
    ),
)
