description = 'Actuators and feedback of the shutter, detector, and valves'

group = 'lowlevel'

excludes = ['IOcard']

devices = dict(
    I1_pnCCD_Active = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Detector is turned on',
        states = [0, 1],
    ),
    I2_Shutter_safe = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Detector is turned on',
        states = [0, 1],
    ),
    I3_Det_chamber_vent_open = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Detector Chamber venting gauge open',
        states = [0, 1],
    ),
    I4_Exp_ch_vent_open = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Experiment Chamber venting gauge open',
        states = [0, 1],
    ),
    I5_Det_ch_pump_open = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Detector Chamber pumping gauge open',
        states = [0, 1],
    ),
    I6_Exp_ch_pump_open  = device('nicos.devices.generic.ManualSwitch',
        description = 'high: Experiment Chamber pumping gauge open',
        states = [0, 1],
    ),
    I7_Exp_ch_vent_gas_selection = device('nicos.devices.generic.ManualSwitch',
        description = 'Venting either with air or nitrogen',
        states = [0, 1],
    ),
    I8_unused = device('nicos.devices.generic.ManualSwitch',
        description = '1 Bit wide digital input starting at E8',
        states = [0, 1],
    ),
    O1_pnCCD_Trigger = device('nicos.devices.generic.ManualSwitch',
        description = 'Send Trigger to detector to start collecting data',
        states = [0, 1],
    ),
    O2_Shutter_open = device('nicos.devices.generic.ManualSwitch',
        description = 'Open the shutter from LMJ',
        states = [0, 1],
    ),
    O3_Det_ch_vent = device('nicos.devices.generic.ManualSwitch',
        description = 'Vent Detector Chamber',
        states = [0, 1],
    ),
    O4_Exp_ch_vent= device('nicos.devices.generic.ManualSwitch',
        description = 'Vent Experiment Chamber',
        states = [0, 1],
    ),
    O5_Det_ch_pump = device('nicos.devices.generic.ManualSwitch',
        description = 'Open gauge from pump to Detector Chamber',
        states = [0, 1],
    ),
    O6_Exp_ch_pump = device('nicos.devices.generic.ManualSwitch',
        description = 'Open gauge from pump to Experiment Chamber',
        states = [0, 1],
    ),
    O7_Exp_ch_vent_gas = device('nicos.devices.generic.ManualSwitch',
        description = 'Choose either air or Nitrogen for venting',
        states = [0, 1],
    ),
    O8_unused = device('nicos.devices.generic.ManualSwitch',
        description = '1 Bit wide digital output starting at A8',
        states = [0, 1],
    ),
)
