description = 'sample table and radial collimator'
includes = ['system']

nethost= '//toftofsrv.toftof.frm2/'

devices = dict(
    gx    = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gxm',
                   fmtstr = "%7.3f",
                   abslimits = (-20.0, 20.)),
    gy    = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gym',
                   fmtstr = "%7.3f",
                   abslimits = (-20.0, 20.)),
    gz    = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gzm',
                   fmtstr = "%7.3f",
                   abslimits = (-14.8, 50.)),
    gcx   = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gcxm',
                   fmtstr = "%7.3f",
                   abslimits = (-20.0, 20.)),
    gcy   = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gcym',
                   fmtstr = "%7.3f",
                   abslimits = (-20.0, 20.)),
    gphi  = device('devices.taco.motor.Motor',
                   tacodevice = nethost + 'toftof/huber/gphim',
                   fmtstr = "%7.3f",
                   abslimits = (-20.0, 150.)),

    rcbus = device('toftof.rc.ModBusDriverHP',
                   tacodevice = nethost + 'toftof/rs232/ifhubermot1',
                   maxtries = 5,
                   lowlevel = True),
    rc    = device('toftof.rc.RadialCollimator',
                   bus = 'rcbus',
                   address = 13,
                   start_angle = 1.0,
                   stop_angle = 5.4,
                   std_speed = 120,
                   ref_speed = 100,
                   timeout = 120,
#		   pollinterval = 5,
                   unit = 'deg',
                   fmtstr = '%g'),
)
