description = 'Julabo F25 at Utgard Lab.'

pv_root = 'SES-FLUC:WTctrl-JULABO-001:'

devices = dict(
    T_julabo = device('nicos_ess.ymir.devices.epics_julabo_controller.EpicsJulaboController',
        description = 'Julabo F25',
        readpv = '{}TEMP'.format(pv_root),
        writepv = '{}TEMP:SP1'.format(pv_root),
        targetpv = '{}TEMP:SP1:RBV'.format(pv_root),
        statuscodepv = '{}STATUS'.format(pv_root),
        statusmsgpv = '{}STATUSc'.format(pv_root),
        switchpvs={'read': '{}MODE'.format(pv_root), 'write': '{}MODE:SP'.format(pv_root)},
        switchstates = {'on': 1, 'off': 0},
        epicstimeout = 3.0,
        precision = 0.1,
        timeout = None,
        window = 30.0,
    ),
    T_julabo_external = device('nicos_ess.devices.epics.base.EpicsReadableEss',
        description = 'The external sensor temperature',
        readpv = '{}EXTT'.format(pv_root),
        lowlevel = True,
        epicstimeout = 3.0,
    ),
    julabo_external_enabled = device('nicos_ess.devices.epics.base.EpicsStringReadableEss',
        description = 'Whether the external sensor is enabled',
        readpv = '{}EXTSENS'.format(pv_root),
        lowlevel = True,
        epicstimeout = 3.0,
    ),
    julabo_internal_P = device('nicos_ess.devices.epics.base.EpicsAnalogMoveableEss',
        description = 'The internal P value',
        readpv = '{}INTP'.format(pv_root),
        writepv = '{}INTP:SP'.format(pv_root),
        lowlevel = True,
        epicstimeout = 3.0,
    ),
    julabo_internal_I = device('nicos_ess.devices.epics.base.EpicsAnalogMoveableEss',
         description = 'The internal I value',
         readpv = '{}INTI'.format(pv_root),
         writepv = '{}INTI:SP'.format(pv_root),
         lowlevel = True,
         epicstimeout = 3.0,
    ),
    julabo_internal_D = device('nicos_ess.devices.epics.base.EpicsAnalogMoveableEss',
         description = 'The internal D value',
         readpv = '{}INTD'.format(pv_root),
         writepv = '{}INTD:SP'.format(pv_root),
         lowlevel = True,
         epicstimeout = 3.0,
    ),
)
