description = 'Detector 5 HV devices'

group = 'lowlevel'

devices = dict(
    det5_anode = device('nicos.devices.generic.VirtualMotor',
        description = 'Anode HV of detector 5',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (0, 3200),
        curvalue = 0,
        jitter = 2,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
        visibility = {'namespace', 'metadata'},
    ),
    det5_anode_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Anode HV current of detector 5',
        device = 'det5_anode',
        parameter = 'current',
        fmtstr = '%.1e',
        visibility = {'namespace', 'metadata'},
    ),
    det5_drift = device('nicos.devices.generic.VirtualMotor',
        description = 'Drift HV of detector 5',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (-1200, 0),
        curvalue = 0,
        jitter = 2,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
        visibility = {'namespace', 'metadata'},
    ),
    det5_drift_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Drift HV current of detector 5',
        device = 'det5_drift',
        parameter = 'current',
        fmtstr = '%.1e',
        visibility = {'namespace', 'metadata'},
    ),
    det5_hv = device('nicos_mlz.firepod.devices.detectorhv.DetectorHVChannelSwitch',
        description = 'HV switch of detector 5',
        drift = 'det5_drift',
        anode = 'det5_anode',
        visibility = {'namespace', 'metadata'},
    ),
)
