description = 'Detector 6 HV devices'

group = 'lowlevel'

devices = dict(
    det6_anode = device('nicos.devices.generic.VirtualMotor',
        description = 'Anode HV of detector 6',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (0, 3200),
        curvalue = 0,
        jitter = 2,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
        visibility = {'namespace', 'metadata'},
    ),
    det6_anode_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Anode HV current of detector 6',
        device = 'det6_anode',
        parameter = 'current',
        fmtstr = '%.1e',
        visibility = {'namespace', 'metadata'},
    ),
    det6_drift = device('nicos.devices.generic.VirtualMotor',
        description = 'Drift HV of detector 6',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (-1200, 0),
        curvalue = 0,
        jitter = 2,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
        visibility = {'namespace', 'metadata'},
    ),
    det6_drift_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Drift HV current of detector 6',
        device = 'det6_drift',
        parameter = 'current',
        fmtstr = '%.1e',
        visibility = {'namespace', 'metadata'},
    ),
    det6_hv = device('nicos_mlz.firepod.devices.detectorhv.DetectorHVChannelSwitch',
        description = 'HV switch of detector 6',
        drift = 'det6_drift',
        anode = 'det6_anode',
        visibility = {'namespace', 'metadata'},
    ),
)
