description = 'Detector 8 HV devices'

group = 'lowlevel'

devices = dict(
    det8_anode = device('nicos.devices.generic.VirtualMotor',
        description = 'Anode HV of detector 8',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (0, 2500),
        curvalue = 0,
        jitter = 0.1,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
    ),
    det8_anode_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Anode HV current of detector 8',
        device = 'det8_anode',
        parameter = 'current',
        fmtstr = '%g',
    ),
    det8_drift = device('nicos.devices.generic.VirtualMotor',
        description = 'Drift HV of detector 8',
        precision = 2,
        requires = {'level': 'admin'},
        abslimits = (-1000, 0),
        curvalue = 0,
        jitter = 0.1,
        speed = 2,
        fmtstr = '%.0f',
        unit = 'V',
    ),
    det8_drift_current = device('nicos.devices.generic.ReadonlyParamDevice',
        description = 'Drift HV current of detector 8',
        device = 'det8_drift',
        parameter = 'current',
        fmtstr = '%g',
    ),
)
