[nicos]
user = "data"
group = "unx-lns"
umask = "022"

instrument = "amor"
setup_package = "nicos_sinq"
setup_subdirs = ["amor", "sinq_shared", "/sq_sw/linse/frappy_sinq", "/home/linse"]
services = ["cache", "poller", "daemon", "collector"]

logging_path = "/home/data/nicosdata/logs"

[environment]
NICOSDUMP = "/home/data/nicosdata"
PYTHONPATH = "/sq_sw/linse/frappy:/sq_sw/linse"
