devices = dict(
    DeviceReadable = device('nicos.devices.epics.pyepics.EpicsReadable',
        description = 'Simple readable device',
        readpv = 'TEST:read',
        unit = '',
    ),
    DeviceMoveable = device('nicos.devices.epics.pyepics.EpicsMoveable',
        description = 'Simple moveable device',
        readpv = 'TEST:read',
        writepv = 'TEST:write',
        unit = '',
    ),
    DeviceMoveableWithTarget = device('nicos.devices.epics.pyepics.EpicsMoveable',
        description = 'Simple moveable device',
        readpv = 'TEST:read',
        writepv = 'TEST:write',
        targetpv = 'TEST:target',
        unit = '',
    ),
)
