sysconfig = dict(
    datasinks=['FileWriterControl'],
    experiment='Exp',
)

devices = dict(
    KafkaFileWriter=device('nicos_ess.devices.datasinks.nexussink.NexusFileWriterStatus',
        description='Status for nexus file writing',
        brokers=['someserver:9092'],
        statustopic='TEST_writerStatus',
    ),
    Exp=device('nicos.devices.experiment.Experiment',
        description='experiment object',
        dataroot='data',
        sample='Sample',
    ),
    Sample=device('nicos.devices.sample.Sample',
        description='The currently used sample',
    ),
    NexusStructure=device(
        'nicos_ess.devices.datasinks.nexus_structure.NexusStructureTemplate',
        description='Provides the NeXus structure',
        templatesmodule='nicos_ess.ymir.nexus.nexus_templates',
        templatename='ymir_default',
    ),
    FileWriterStatus=device(
        'nicos_ess.devices.datasinks.file_writer.FileWriterStatus',
        description='Status for file-writer',
        brokers=['someserver:9092'],
        statustopic='TEST_controlTopic',
        unit='',
    ),
    FileWriterControl=device(
        'nicos_ess.devices.datasinks.file_writer.FileWriterControlSink',
        description='Control for file-writer',
        brokers=['someserver:9092'],
        pool_topic='TEST_jobPool',
        nexus='NexusStructure',
        status='FileWriterStatus',
    ),
    motor=device(
        'nicos.devices.generic.VirtualMotor',
        unit='deg',
        curvalue=0,
        abslimits=(0, 5),
    ),
    timer=device(
        'nicos.devices.generic.VirtualTimer',
        visibility=(),
    ),
    ctr1=device(
        'nicos.devices.generic.VirtualCounter',
        visibility=(),
        type='counter',
        countrate=2000.,
        fmtstr='%d',
    ),
    det=device(
        'nicos.devices.generic.Detector',
        timers=['timer'],
        counters=['ctr1'],
        maxage=3,
        pollinterval=0.5,
    ),
)
