name = 'SINQ SANS-LLB'

description = 'Test setup for SANS-LLB devices'

devices = dict(
    dtlz = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (1598.99, 18350.1),
        precision = 0.1,
    ),
    dtlx = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-300, 0.5),
        precision = 0.1,
    ),
    dthz = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (809, 9600),
        precision = 0.1,
    ),
    dthx = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-0.1, 152.65),
        precision = 0.1,
    ),
    dthy = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-0.5, 245.2),
        precision = 0.1,
    ),
    sample_offset_z = device('nicos.devices.generic.VirtualMotor',
        unit = 'mm',
        abslimits = (-50.0, 50.0),
        precision = 0.1,
    ),
    detz=device('nicos_sinq.sans-llb.devices.detector_coupling.SansLlbCoupledDetectors',
                description='Detectors coupled translation, position is low-angle detector distance',
                low_angle_x='dtlx',
                low_angle_z='dtlz',
                sample_offset_z='sample_offset_z',
                high_angle_x='dthx',
                high_angle_y='dthy',
                high_angle_z='dthz',
                # geometry parameters used to calculate x/y position of high angle detector:
                high_angle_opening_x=140.,
                high_angle_opening_y=370.,
                low_angle_frame_x=350.,
                low_angle_frame_y=330.,
                save_distance_z=800.,
    ),
)