description = 'Monochromator CARESS HWB Devices'

group = 'lowlevel'

tango_base = 'tango://motorbox04.stressi.frm2.tum.de:10000/box/'

devices = dict(
    omgm_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel1/motor',
        fmtstr = '%.2f',
        lowlevel = True,
        requires = {'level': 'admin'},
    ),
    omgm_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel1/coder',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    omgm = device('nicos.devices.generic.Axis',
        description = 'OMGM',
        motor = 'omgm_m',
        coder = 'omgm_c',
        precision = 0.005,
    ),
    transm_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel2/motor',
        fmtstr = '%.3f',
        userlimits = (-200, 200),
        lowlevel = True,
        requires = {'level': 'admin'},
    ),
    transm_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel2/coder',
        fmtstr = '%.3f',
        lowlevel = True,
    ),
    transm_a = device('nicos.devices.generic.Axis',
        description = 'HWB TRANSM',
        motor = 'transm_m',
        coder = 'transm_c',
        precision = 0.001,
        lowlevel = True,
    ),
    transm = device('nicos.devices.generic.Switcher',
        description = 'Monochromator changer',
        moveable = 'transm_a',
        mapping = {
            'Si': 0.292,
            'PG': 30.292,
            'Ge': 60.292,
        },
        precision = 0.01,
        unit = '',
        requires = {'level': 'admin'},
    ),
    #  tthm = device('nicos.devices.tango.Motor',
    tthm = device('nicos.devices.generic.ManualMove',
        description = 'Take off angle',
        default = 84.0,
        # tangodevice = tangobase + '/',
        fmtstr = '%.2f',
        unit = 'deg',
        abslimits = (50., 100.),
    ),
    tthm_r = device('nicos_mlz.stressi.devices.wavelength.TransformedMoveable',
        description = 'Base hardware device',
        dev = 'tthm',
        informula = '1./0.956 * x - 11.5 / 0.956',
        outformula = '0.956 * x + 11.5',
        precision = 0.001,
        lowlevel = True,
    ),
    wav = device('nicos_mlz.stressi.devices.wavelength.Wavelength',
        description = 'The incoming wavelength',
        omgm = 'omgm',
        crystal = 'transm',
        base = 'tthm_r',
        plane = '100',
        unit = 'AA',
        fmtstr = '%.2f',
        abslimits = (0.9, 2.5),
        requires = {'level': 'admin'},
    ),
    chim_si_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel6/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_si_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel6/coder',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_si = device('nicos.devices.generic.Axis',
        description = 'CHI Si monochromator',
        motor = 'chim_si_m',
        coder = 'chim_si_c',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    chim_pg_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel7/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_pg_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel7/coder',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_pg = device('nicos.devices.generic.Axis',
        description = 'CHI PG monochromator',
        motor = 'chim_pg_m',
        coder = 'chim_pg_c',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    chim_ge_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel8/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_ge_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel8/coder',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    chim_ge = device('nicos.devices.generic.Axis',
        description = 'CHI Ge monochromator',
        motor = 'chim_ge_m',
        coder = 'chim_ge_c',
        fmtstr = '%.2f',
        precision = 0.01,
    ),
    foc_si_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel3/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    foc_si = device('nicos.devices.generic.Axis',
        description = 'Horizontal focus Si monochromator',
        motor = 'foc_si_m',
        fmtstr = '%.1f',
        precision = 0.1,
    ),
    foc_pg_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel4/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    foc_pg = device('nicos.devices.generic.Axis',
        description = 'Vertical focus PG monochromator',
        motor = 'foc_pg_m',
        fmtstr = '%.1f',
        precision = 0.1,
    ),
    foc_ge_m = device('nicos.devices.tango.Motor',
        tangodevice = tango_base + 'channel5/motor',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    foc_ge_c = device('nicos.devices.tango.Sensor',
        tangodevice = tango_base + 'channel5/coder',
        fmtstr = '%.2f',
        lowlevel = True,
    ),
    foc_ge = device('nicos.devices.generic.Axis',
        description = 'Vertical focus Ge monochromator',
        motor = 'foc_ge_m',
        coder = 'foc_ge_c',
        fmtstr = '%.1f',
        precision = 0.1,
    ),
)
