description = 'Primary slit CARESS HWB Devices'

group = 'lowlevel'

servername = 'VME'

nameservice = 'stressictrl.stressi.frm2'
tangobase = 'tango://motorbox01.stressi.frm2.tum.de:10000/box/'

includes = ['mux']

devices = dict(
    slitm_w = device('nicos.devices.vendor.caress.MuxMotor',
        description = 'HWB SLITM_W',
        fmtstr = '%.2f',
        unit = 'mm',
        coderoffset = 0,
        abslimits = (0, 100),
        nameserver = '%s' % nameservice,
        objname = '%s' % servername,
        config = 'SLITM_W 39 3 1 10 100.0 20 80',
        lowlevel = True,
        pollinterval = 60,
        maxage = 90,
        mux = 'mux',
    ),
    slitm_h = device('nicos.devices.vendor.caress.MuxMotor',
        description = 'HWB SLITM_H',
        fmtstr = '%.2f',
        unit = 'mm',
        coderoffset = 0,
        abslimits = (0, 155),
        nameserver = '%s' % nameservice,
        objname = '%s' % servername,
        config = 'SLITM_H 39 3 1 11 100.0 20 80',
        lowlevel = True,
        pollinterval = 60,
        maxage = 90,
        mux = 'mux',
    ),
    slitm = device('nicos_mlz.stressi.devices.slit.TwoAxisSlit',
        description = 'Monochromator entry slit',
        horizontal = 'slitm_w',
        vertical = 'slitm_h',
        pollinterval = 60,
        maxage = 90,
    ),
    slite = device('nicos.devices.vendor.caress.MuxMotor',
        description = 'HWB SLITE',
        fmtstr = '%.2f',
        unit = 'mm',
        coderoffset = 0,
        abslimits = (0, 70),
        nameserver = '%s' % nameservice,
        objname = '%s' % servername,
        config = 'SLITM_E 39 3 1 12 100.0 20 80',
        pollinterval = 60,
        maxage = 90,
        mux = 'mux',
    ),
    slits_d = device('nicos.devices.tango.Motor',
        description = 'Bottom blade of sample slit',
        tangodevice = tangobase + 'channel2/motor',
        lowlevel = True,
    ),
    slits_u = device('nicos.devices.tango.Motor',
        description = 'Upper blade of the sample slit',
        tangodevice = tangobase + 'channel1/motor',
        lowlevel = True,
    ),
    slits_l = device('nicos.devices.tango.Motor',
        description = 'Left blade of the sample slit',
        tangodevice = tangobase + 'channel3/motor',
        lowlevel = True,
    ),
    slits_r = device('nicos.devices.tango.Motor',
        description = 'Right blade of the sample slit',
        tangodevice = tangobase + 'channel4/motor',
        lowlevel = True,
    ),
    slits = device('nicos.devices.generic.Slit',
        description = 'sample slit 4 blades',
        left = 'slits_l',
        right = 'slits_r',
        bottom = 'slits_d',
        top = 'slits_u',
        opmode = 'centered',
        coordinates = 'opposite',
        parallel_ref = True,
    ),
)
