description = 'Test setup for SINQ AMOR.'

devices = dict(
    slit_controller = device('nicos_sinq.amor.devices.slit.AmorSlitHandler',
        description = 'Logical motors controller',
        xs = 'xs',
        slit1 = 'slit1',
        slit2 = 'slit2',
        slit2z = 'd2z',
        visibility = (),
    ),
    d1l = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 1 left motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d1r = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 1 right motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d1t = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 1 top motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d1b = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 1 bottom motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    xs = device('nicos.devices.generic.VirtualMotor',
        description = 'Sample X position',
        abslimits = (0, 1000),
        unit = 'mm',
        curvalue = 1
    ),
    slit1 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 1',
        opmode = '4blades',
        left = 'd1l',
        right = 'd1r',
        top = 'd1t',
        bottom = 'd1b',
    ),
    divergence = device('nicos_sinq.amor.devices.slit.DivergenceAperture',
        description = 'test device',
        slit = 'slit1',
        distance = 'xs',
        visibility = (),
    ),
    did = device('nicos.devices.generic.DeviceAlias',
        alias = 'divergence.displacement',
    ),
    div = device('nicos.devices.generic.DeviceAlias',
        alias = 'divergence.vertical',
    ),
    dih = device('nicos.devices.generic.DeviceAlias',
        alias = 'divergence.horizontal',
    ),
    d2l = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 2 left motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d2r = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 2 right motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d2t = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 2 top motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d2b = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 2 bottom motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    d2z = device('nicos.devices.generic.virtual.VirtualMotor',
        description = 'Slit 2 top motor',
        abslimits = (-1000, 1000),
        unit = 'mm',
    ),
    slit2 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 2',
        opmode = '4blades_opposite',
        left = 'd2l',
        right = 'd2r',
        top = 'd2t',
        bottom = 'd2b',
    ),
    d2v = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Vertical slit opening',
        motortype = 'd2v',
        controller = 'slit_controller',
        unit = 'mm',
        abslimits = (-1000, 1000),
    ),
    d2h = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Horizontal slit opening ',
        motortype = 'd2h',
        controller = 'slit_controller',
        unit = 'mm',
        abslimits = (-1000, 1000),
    ),
    d2d = device('nicos_sinq.amor.devices.slit.AmorSlitLogicalMotor',
        description = 'Vertical slit displacement',
        motortype = 'd2d',
        controller = 'slit_controller',
        unit = 'mm',
        abslimits = (-1000, 1000),
    ),
)
