[nicos]
user = 'hrpt'
group = 'unx-lns'
umask = '002'

instrument = 'hrpt'
setup_package = 'nicos_sinq'
setup_subdirs = ["hrpt", "sinq_shared", "/sq_sw/linse/frappy_sinq", "/home/linse"]
services = ['cache','poller','daemon']

logging_path = '/home/hrpt/nicos/log'

[environment]
NICOSDUMP = '/home/hrpt/nicosdata'
HRPTHM = 'http://hrpthm/admin'
PYTHONPATH = "/sq_sw/linse/frappy:/sq_sw/linse"
