description = 'TOF counter devices'

group = 'lowlevel'

includes = ['chopper', 'slit']

devices = dict(
    monitor = device('nicos.devices.generic.VirtualCounter',
        description = 'TOFTOF monitor',
        fmtstr = '%d',
        type = 'monitor',
        visibility = (),
        pollinterval = None,
    ),
    timer = device('nicos.devices.generic.VirtualTimer',
        description = 'TOFTOF timer',
        fmtstr = '%.2f',
        unit = 's',
        visibility = (),
        pollinterval = None,
    ),
    timer_mcstas = device('nicos.devices.mcstas.McStasTimer',
        description='McStas virtual neutron counts timer channel',
        mcstas = 'mcstas',
        fmtstr = '%.2f',
        unit = 's',
        visibility = (),
    ),
    image_virtual = device('nicos_mlz.toftof.devices.virtual.VirtualImage',
        description = 'Image data device',
        fmtstr = '%d',
        pollinterval = None,
        visibility = (),
        numinputs = 1006,
        size = (1024, 1024),
        datafile = 'nicos_virt_mlz/toftof/data/test/data.npz',
    ),
    mcstas = device('nicos_virt_mlz.toftof.devices.detector.McStasSimulation',
        description = 'McStas simulation',
        mcstasprog = 'toftof',
        intensityfactor = 10,  # e14,
        sample = 'Sample',
        wavelength = 'chWL',
        speed = 'chSpeed',
        ratio = 'chRatio',
        st = 'chST',
        slit = 'slit',
        neutronspersec = {
            'localhost': 1.12e5,
            'taco6.ictrl.frm2.tum.de': 8.9e+05,
            configdata('config_data.host'): 1.12e5,
        },
    ),
    image = device('nicos_virt_mlz.toftof.devices.detector.Image',
        description = 'Image data device',
        mcstas = 'mcstas',
        mcstasfile = 'detector_output.dat',
        size = (1024, 1024),
        fmtstr = '%d',
        unit = 'cts',
        pollinterval = 86400,
        visibility = (),
    ),
    det = device('nicos_virt_mlz.toftof.devices.Detector',
        description = 'The TOFTOF detector device',
        mcstas = 'mcstas',
        timers = ['timer'],
        monitors = ['monitor'],
        images = ['image'],
        rc = 'rc',
        chopper = 'ch',
        chdelay = 'chdelay',
        maxage = 3,
        pollinterval = None,
        liveinterval = 10.0,
        saveintervals = [30.],
        detinfofile = 'nicos_virt_mlz/toftof/detinfo.dat',
    ),
)
