description = 'Devices from Motor Controller mcu2'

pvprefix = 'SQ:SANS-LLB:mcu2:'

devices = dict(
    sl0yn = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 0 Up',
        motorpv = pvprefix + 'sl0yn',
        errormsgpv = pvprefix + 'sl0yn-MsgTxt',
        precision = 0.01,
        can_disable = True,
    ),
    sl0yp = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 0 down',
        motorpv = pvprefix + 'sl0yp',
        errormsgpv = pvprefix + 'sl0yp-MsgTxt',
        precision = 0.01,
        can_disable = True,
    ),
    sl0xp = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 0 left',
        motorpv = pvprefix + 'sl0xp',
        errormsgpv = pvprefix + 'sl0xp-MsgTxt',
        precision = 0.01,
        can_disable = True,
    ),
    sl0xn = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Slit 0 right',
        motorpv = pvprefix + 'sl0xn',
        errormsgpv = pvprefix + 'sl0xn-MsgTxt',
        precision = 0.01,
        can_disable = True,
    ),
    polpos = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Polariser  translation',
        motorpv = pvprefix + 'pol',
        errormsgpv = pvprefix + 'pol-MsgTxt',
        precision = 0.01,
        can_disable = True,
    ),
    pol = device('nicos.devices.generic.switcher.Switcher',
        description = 'Polariser choice',
        moveable = 'polpos',
        mapping = {
            'out': 32.5,
            'in': 172.5,
            'polariser': 312.5,
        },
        precision = .1,
        blockingmove = True,
    ),
    slit0 = device('nicos.devices.generic.slit.Slit',
        description = 'Slit 0 with left, right, bottom and top motors',
        opmode = '4blades',
        coordinates = 'opposite',
        left = 'sl0xp',
        right = 'sl0xn',
        top = 'sl0yp',
        bottom = 'sl0yn',
        visibility = (),
    ),
    sl0xc = device('nicos_sinq.sans-llb.devices.slit.InvertedXSlitAxis',
        description = 'slit 0 x center position',
        slit = 'slit0',
        unit = 'mm',
    ),
    sl0xw = device('nicos.core.device.DeviceAlias',
        description = 'slit width',
        alias = 'slit0.width',
        devclass = 'nicos.devices.generic.slit.WidthSlitAxis'
    ),
    sl0yw = device('nicos.core.device.DeviceAlias',
        description = 'slit height',
        alias = 'slit0.height',
        devclass = 'nicos.devices.generic.slit.HeightSlitAxis'
    ),
    sl0yc = device('nicos.core.device.DeviceAlias',
        description = 'slit 0 y center position',
        alias = 'slit0.centery',
        devclass = 'nicos.devices.generic.slit.CenterYSlitAxis'
    ),
    attpos = device('nicos_sinq.devices.epics.motor.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Attenuator rotation',
        motorpv = pvprefix + 'attpos',
        errormsgpv = pvprefix + 'attpos-MsgTxt',
        precision = 0.01,
    ),
    att = device('nicos.devices.generic.switcher.Switcher',
        description = 'Attenuator choice',
        moveable = 'attpos',
        mapping = {
            '0': 0,
            '1': -45,
            '2': -90,
            '3': -135,
            '4': -180,
            '5': -225,
            '6': -270,
            '7': -315
        },
        precision = .1,
        blockingmove = True,
    )
)
startupcode = """
sl0xw.alias='slit0.width'
sl0yw.alias='slit0.height'
sl0yc.alias='slit0.centery'
"""
