description = 'Setup for the standard sample table'

pvprefix = 'SQ:SANS-LLB:mcu1:'

devices = dict(
    stom = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample table rotation around Y',
        motorpv = pvprefix + 'stom',
        errormsgpv = pvprefix + 'stom-MsgTxt',
        precision = 0.01,
        can_disable=True,
    ),
    stx = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample table translation along X',
        motorpv = pvprefix + 'stx',
        errormsgpv = pvprefix + 'stx-MsgTxt',
        precision = 0.01,
        can_disable=True,
    ),
    stz = device('nicos.devices.generic.manual.ManualMove',
        description = 'Sample table Z (along the beam, fixed)',
        unit = 'mm',
        abslimits = (0, 170)
    ),
    stgn = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample table goniometer (rotation around X)',
        motorpv = pvprefix + 'stgn',
        errormsgpv = pvprefix + 'stgn-MsgTxt',
        precision = 0.01,
        can_disable=True,
    ),
    sty = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample table translation along Y',
        motorpv = pvprefix + 'sty',
        errormsgpv = pvprefix + 'sty-MsgTxt',
        precision = 0.01,
        can_disable=True,
    ),
    spos = device('nicos_sinq.devices.epics.motor_deprecated.EpicsMotor',
        epicstimeout = 3.0,
        description = 'Sample chnager position',
        motorpv = pvprefix + 'spos',
        errormsgpv = pvprefix + 'spos-MsgTxt',
        precision = 0.01,
        can_disable=True,
    ),
)
