description = 'Base setup file for ORION devices'

group = 'lowlevel'

pvmcu1 = 'SQ:ORION:turboPmac1:'
pvmcu2 = 'SQ:ORION:turboPmac2:'

devices = dict(
    mom1 = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Monochromator 1 rotation',
        motorpv = pvmcu2 + 'mom1',
        fmtstr = '%.3f',
    ),
    gml = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Monochromator lower goniometer',
        motorpv = pvmcu2 + 'gml',
        fmtstr = '%.3f',
    ),
    gmu = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Monochromator upper goniometer',
        motorpv = pvmcu2 + 'gmu',
        fmtstr = '%.3f',
    ),
    som = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Sample rotation',
        motorpv = pvmcu1 + 'som',
        fmtstr = '%.3f',
    ),
    stt = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Two Theta rotation',
        motorpv = pvmcu1 + 'stt',
        fmtstr = '%.3f',
    ),
    sgl = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Sample lower tilt',
        motorpv = pvmcu1 + 'sgl',
        fmtstr = '%.3f',
    ),
    sgu = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Sample upper tilt',
        motorpv = pvmcu1 + 'sgu',
        fmtstr = '%.3f',
    ),
    chi = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Eulerian cradle chi rotation',
        motorpv = pvmcu1 + 'chi',
        fmtstr = '%.3f',
    ),
    phi = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Eulerian cradle phi rotation',
        motorpv = pvmcu1 + 'phi',
        fmtstr = '%.3f',
    ),
    mcv1 = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Monochromator vertical curvature',
        motorpv = pvmcu2 + 'mcv1',
        fmtstr = '%.3f',
    ),
    mono = device('nicos_sinq.orion.devices.MonoSwitcher',
        description = 'monochromator',
        moveable = 'mom1',
        precision = .1,
        mapping= {3.3: 2.08, 1.73: 31.49, 1.32: 21.25},
        unit = 'A',
    ),
)

