description = '3He Joule-Thomson unit from FRM II Sample environment group'

group = 'plugplay'

includes = ['alias_T']

tango_base = f'tango://{setupname}:10000/box/'

devices = {
    f'T_{setupname}_pot': device('nicos.devices.entangle.TemperatureController',
        description = 'The control device of the 3He-pot',
        tangodevice = tango_base + 'lakeshore/control',
        abslimits = (0, 300),
        unit = 'K',
        fmtstr = '%.3f',
        pollinterval = 5,
        maxage = 6,
    ),
    f'T_{setupname}_pot_heaterrange': device('nicos.devices.generic.Switcher',
        description = 'Heater range of 3He-pot',
        moveable = device('nicos.devices.entangle.AnalogOutput',
            tangodevice = tango_base + 'lakeshore/heaterrange',
            description = '',
            visibility = (),
            unit = '',),
        precision = 0.5,
        mapping = {'off': 0, '1 mW': 1, '10 mW': 2, '100 mW': 3,
                  # '1 W': 4, '10 W': 5
                  },
    ),
    f'T_{setupname}_sample': device('nicos.devices.entangle.Sensor',
        description = 'The sample temperature (if installed)',
        tangodevice = tango_base + 'lakeshore/sensorb',
        unit = 'K',
        fmtstr = '%.3f',
        pollinterval = 5,
        maxage = 6,
    ),
    f'T_{setupname}_coldhead_4K_stage': device('nicos.devices.entangle.Sensor',
        description = 'The 2(nd) cooling stage of the coldhead',
        tangodevice = tango_base + 'lakeshore/sensorc',
        unit = 'K',
        fmtstr = '%.3f',
        pollinterval = 5,
        maxage = 6,
    ),
    f'T_{setupname}_coldhead_40K_stage': device('nicos.devices.entangle.Sensor',
        description = 'The 1(st) cooling stage of the coldhead',
        tangodevice = tango_base + 'lakeshore/sensord',
        unit = 'K',
        fmtstr = '%.3f',
        pollinterval = 5,
        maxage = 6,
    ),
    f'{setupname}_p_pot': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure at 3He-pot, also at turbo pump inlet',
        tangodevice = tango_base + 'i7000/p_still',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_inlet': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure forepump inlet, also at turbo pup outlet',
        tangodevice = tango_base + 'i7000/p_inlet',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_outlet': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure forepump outlet, also at compressor inlet',
        tangodevice = tango_base + 'i7000/p_outlet',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_cond': device('nicos.devices.entangle.AnalogInput',
        description = 'Condensing pressure, also at compressor outlet',
        tangodevice = tango_base + 'i7000/p_cond',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_tank': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure in 3He-gas reservoir',
        tangodevice = tango_base + 'i7000/p_dump',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_vac': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure in vacuum dewar',
        tangodevice = tango_base + 'i7000/p_vac',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_flow': device('nicos.devices.entangle.AnalogInput',
        description = 'Gas flow',
        tangodevice = tango_base + 'i7000/flow',
        fmtstr = '%.4g',
        unit = 'ml/min',
        pollinterval = 15,
        maxage = 20,
    ),
    f'{setupname}_p_v15': device('nicos.devices.entangle.AnalogInput',
        description = 'Pressure at pumping side of V15',
        tangodevice = tango_base + 'i7000/p_v15',
        fmtstr = '%.4g',
        pollinterval = 15,
        maxage = 20,
    ),
}

alias_config = {
    'T':  {f'T_{setupname}_pot': 300},
    'Ts': {f'T_{setupname}_pot': 280, f'T_{setupname}_sample': 300},
}

monitor_blocks = dict(
    default = Block('3He insert ' + setupname, [
        BlockRow(
            Field(name='Setpoint', key=f't_{setupname}_pot/setpoint',
                  unitkey='t/unit'),
            Field(name='Target', key=f't_{setupname}_pot/target',
                  unitkey='t/unit'),
        ),
        BlockRow(
            Field(name='Pot', dev=f'T_{setupname}_pot'),
            Field(name='Manual Heater Power', key=f't_{setupname}_pot/heaterpower',
                  unitkey='t/unit'),
            Field(name='Sample', dev=f'T_{setupname}_sample'),
        ),
        BlockRow(
            Field(name='40K stage', dev=f'T_{setupname}_coldhead_40K_stage'),
            Field(name='4K stage', dev=f'T_{setupname}_coldhead_4K_stage'),
        ),
    ], setups=setupname),
    pressures = Block('Pressures ' + setupname, [
        BlockRow(
            Field(dev=f'{setupname}_p_pot', name='Pot', width=10),
            Field(dev=f'{setupname}_p_inlet', name='Inlet', width=10),
        ),
        BlockRow(
            Field(dev=f'{setupname}_p_outlet', name='Outlet', width=10),
            Field(dev=f'{setupname}_p_cond', name='Cond', width=10),
        ),
        BlockRow(
            Field(dev=f'{setupname}_p_tank', name='Tank', width=10),
            Field(dev=f'{setupname}_p_vac', name='Vac', width=10),
        ),
        BlockRow(
            Field(dev=f'{setupname}_flow', name='Flow', width=10),
        ),
    ], setups=setupname),
    plots = Block(setupname, [
        BlockRow(
            Field(widget='nicos.guisupport.plots.TrendPlot',
                  plotwindow=300, width=25, height=25,
                  devices=[f't_{setupname}_pot/setpoint', f't_{setupname}_pot'],
                  names=['Setpoint', 'Regulation'],
                  ),
        ),
    ], setups=setupname)
)
