description = 'LakeShore 350 cryo controller'
group = 'optional'

includes = ['alias_T']

tango_base = 'tango://localhost:10000/20t/'

devices = dict(
    T_vti = device('nicos.devices.entangle.TemperatureController',
        description = 'VTI temperature regulation',
        tangodevice = tango_base + 'ls350/ls_control1',
        pollinterval = 0.7,
        maxage = 3,
    ),
    T_sample = device('nicos.devices.entangle.TemperatureController',
        description = 'Sample temperature regulation',
        tangodevice = tango_base + 'ls350/ls_control2',
        pollinterval = 0.7,
        maxage = 3,
    ),
    T_mainsorb = device('nicos.devices.entangle.TemperatureController',
        description = 'He3 pressure sorb regulation',
        tangodevice = tango_base + 'ls350/ls_control3',
        pollinterval = 0.7,
        maxage = 3,
    ),
    T_minisorb = device('nicos.devices.entangle.TemperatureController',
        description = 'VTI HiVac pressure sorb regulation',
        tangodevice = tango_base + 'ls350/ls_control4',
        pollinterval = 0.7,
        maxage = 3,
    ),
    range_vti = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'channel A heater range',
        tangodevice = tango_base + 'ls350/ls_heaterrange1',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 0,
            '1': 1,
            '2': 2,
            '3': 3,
            '4': 4,
            '5': 5,
        },
        unit = '',
    ),
    range_sample = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'channel B heater range',
        tangodevice = tango_base + 'ls350/ls_heaterrange2',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 0,
            '1': 1,
            '2': 2,
            '3': 3,
        },
        unit = '',
    ),
    range_mainsorb = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'channel C heater range',
        tangodevice = tango_base + 'ls350/ls_heaterrange3',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 0,
            'on': 1,
        },
        unit = '',
    ),
    range_minisorb = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'channel D heater range',
        tangodevice = tango_base + 'ls350/ls_heaterrange4',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 0,
            'on': 1,
        },
        unit = '',
    ),
    power_keithley = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'relay 1 output connected to keithley meters',
        tangodevice = tango_base + 'ls350/relay1',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 1,
            'on': 0,
        },
        unit = '',
    ),
    power_scroll = device('nicos.devices.entangle.NamedDigitalOutput',
        description = 'relay 2 output connected to scroll pump',
        tangodevice = tango_base + 'ls350/relay2',
        pollinterval = 2,
        maxage = 5,
        mapping = {
            'off': 1,
            'on': 0,
        },
        unit = '',
    ),
)

alias_config = {
    'T': {'T_vti': 180},  # lower than default T_ccr5
    'Ts': {'T_sample': 60},
}
