#!/usr/bin/env python
#  -*- coding: utf-8 -*-
# *****************************************************************************
# NICOS, the Networked Instrument Control System of the MLZ
# Copyright (c) 2009-2017 by the NICOS contributors (see AUTHORS)
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Module authors:
#   Pascal Neubert <pascal.neubert@frm2.tum.de>
#
# *****************************************************************************

import argparse
import sys

from os import path

import sip
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)

try:
    from nicos.core import sessions
except ImportError:
    thisfile = path.abspath(__file__)
    sys.path.insert(0, path.normpath(path.join(path.dirname(thisfile), '..')))
    from nicos.core import sessions

from cacheinspector.cacheinspector import CacheInspector, CISession


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--cache', dest='cache', action='store',
                        help='CACHE server:port, defaults to localhost:14869',
                        default='localhost')
    parser.add_argument('-p', '--prefix', dest='prefix', action='store',
                        help='PREFIX is the key prefix; shows only keys with '
                        'this prefix, defaults to no prefix', default='')
    opts = parser.parse_args()

    CISession.run('Inspector', CacheInspector,
                  {'cache': opts.cache, 'prefix': opts.prefix},
                  pidfile=False)

if __name__ == '__main__':
    main()

