# DO NOT EDIT THIS FILE!
#
# Python module CARESS generated by omniidl
# isort:skip_file

from __future__ import absolute_import

import omniORB
omniORB.updateModule("CARESS")

# ** 1. Stub files contributing to this module
import nicos_mlz.delab.devices.corbadevice_idl

# ** 2. Sub-modules

# ** 3. End
