description = 'Sample table setup'

group = 'lowlevel'

devices = dict(
    sample_x = device('nicos.devices.generic.Axis',
        description = 'Sample table x translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-28.45, 30.58),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    sample_y = device('nicos.devices.generic.Axis',
        description = 'Sample table y translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-19.20, 27.8),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    sample_z = device('nicos.devices.generic.Axis',
        description = 'Sample table z translation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-63, 36),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    omega = device('nicos.devices.generic.Axis',
        description = 'Sample table omega rotation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-135.344, 180.567),
            unit = 'deg',
            speed = 1,
        ),
        precision = 0.005,
        fmtstr = '%.3f',
    ),
    phi = device('nicos.devices.generic.Axis',
        description = 'Sample table phi rotation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-15.17, 10.32),
            unit = 'deg',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    chi = device('nicos.devices.generic.Axis',
        description = 'Sample table chi rotation',
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-12.45, 8.58),
            unit = 'deg',
            speed = 1,
        ),
        precision = 0.01,
        fmtstr = '%.2f',
    ),
    detarm = device("nicos.devices.generic.Axis",
        description = "Detector arm rotation angle",
        motor = device('nicos.devices.generic.VirtualMotor',
            abslimits = (-6.06, 117.397),
            unit = 'mm',
            speed = 1,
        ),
        precision = 0.005,
        fmtstr = "%.3f",
    ),
    t2t = device("nicos_mlz.jcns.devices.motor.MasterSlaveMotor",
        description = "2 theta axis moving detarm = 2 * omega",
        master = "omega",
        slave = "detarm",
        scale = 2.,
        fmtstr = "%.3f %.3f",
    ),
)
