description = 'plug-and-play magnet sample environment'
group = 'optional'


devices = dict(
    B_virt  = device('devices.generic.VirtualMotor',
                abslimits = (-10, 10),
                unit = 'T'),

    garfield_onoff    = device('nicos.devices.generic.ManualSwitch',
                               states = ['on', 'off'],
                              ),
    garfield_polarity = device('nicos.devices.generic.ManualSwitch',
                               states = ['+', '-'],
                              ),
    garfield_current = device('devices.generic.VirtualMotor',
                              abslimits = (0, 250),
                              unit = 'A',
                              ramp = 1.,
                             ),
    B_garfield = device('antares.magnet.GarfieldMagnet',
                         description = 'magnetic field device, handling polarity switching and stuff',
                         currentsource = 'garfield_current',
                         onoffswitch = 'garfield_onoff',
                         polswitch = 'garfield_polarity',
                         unit = 'T',
                         calibration = [1e-3, 125, 250**2],
                         abslimits = (-0.5, 0.5),
                        ),

    mira_plus    = device('nicos.devices.generic.ManualSwitch',
                               states = ['on', 'off'],
                              ),
    mira_minus    = device('nicos.devices.generic.ManualSwitch',
                               states = ['on', 'off'],
                              ),
    mira_current = device('devices.generic.VirtualMotor',
                              abslimits = (-250, 250),
                              unit = 'A',
                              ramp = 1.,
                             ),
    B_mira = device('antares.magnet.MiraMagnet',
                         description = 'magnetic field device, handling polarity switching and stuff',
                         currentsource = 'mira_current',
                         plusswitch = 'mira_plus',
                         minusswitch = 'mira_minus',
                         unit = 'T',
                         calibration = [1e-3, 125, 250**2],
                         abslimits = (-0.5, 0.5),
                        ),
)

