description = 'virtual PGAA devices'
group = 'basic'

sysconfig = dict(
    datasinks = ['sink']
)

devices = dict(
    samplemotor = device('devices.generic.VirtualMotor',
                          description = 'Motor to change the sample position',
                          fmtstr = '%7.1f',
                          abslimits = (-5, 356),
                          speed = 10,
                          unit = 'mm',
                          lowlevel = False,
                         ),
    samplepos = device('devices.generic.Switcher',
                       description = 'Sample switcher',
                       moveable = 'samplemotor',
                       mapping  = {1: 0.0,
                                   2: 22.5,
                                   3: 45.0,
                                   4: 67.5,
                                   5: 90.0,
                                   6: 112.5,
                                   7: 135.0,
                                   8: 157.5,
                                   9: 180.0,
                                   10: 202.5,
                                   11: 225.0,
                                   12: 247.5,
                                   13: 270.0,
                                   14: 292.5,
                                   15: 315.0,
                                   16: 337.5,
                                  },
                       precision = 0.1,
                       blockingmove = False,
                       unit = '',
                      ),
    get_ready = device('devices.generic.ManualSwitch',
                       description = '',
                       lowlevel = True,
                       states = [0, 1,],
                       fmtstr = '%d',
                      ),
    set_ready = device('devices.generic.ManualSwitch',
                       description = '',
                       lowlevel = True,
                       states = [0, 1,],
                       fmtstr = '%d',
                      ),
    shutter = device('devices.generic.ManualSwitch',
                     description = 'secondary experiment shutter',
                     states = ['open', 'closed'],
                    ),
    attenuator = device('demo.attenuator.Attenuator',
                        description = 'Attenuator',
                        blades = ['att1', 'att2', 'att3', ],
                       ),
    att1 = device('devices.generic.ManualSwitch',
                  description = 'attenuator 1',
                  states = ['in', 'out',],
                 ),
    att2 = device('devices.generic.ManualSwitch',
                  description = 'attenuator 2',
                  states = ['in', 'out',],
                 ),
    att3 = device('devices.generic.ManualSwitch',
                  description = 'attenuator 3',
                  states = ['in', 'out',],
                 ),
    att = device('pgaa.attenuator.Attenuator',
                 description = 'Attenuator device',
                 moveables = ['att1', 'att2', 'att3', ],
                 readables = None,
                 precision = None,
                 unit = '%',
                 fmtstr = '%.1f',
                 mapping = {100.: ('out', 'out', 'out'),
                            47.: ('out', 'in', 'out'),
                            16.: ('in', 'out', 'out'),
                            7.5: ('in', 'in', 'out'),
                            5.9: ('out', 'out', 'in'),
                            3.5: ('out', 'in', 'in'),
                            2.7: ('in', 'out', 'in'),
                            1.6: ('in', 'in', 'in'),
                           },
                ),
    det = device('pgaa.dspecdemo.DSPec',
                 description = 'DSpec Tango Device',
                 prefix = 'P'
                ),
    detLEGe = device('pgaa.dspecdemo.DSPec',
                     description = 'DSpec Tango Device',
                     prefix = 'L'
                    ),
    sink = device('pgaa.PGAASink.PGAASink',
                  lowlevel = True,
                  settypes = set(['scan']),
                  det1 = 'det',
                  det2 = 'detLEGe',
                  vac = 'att1',
                 ),
)

startupcode = '''
# SetDetectors(det)
SetEnvironment()
printinfo("============================================================")
printinfo("Welcome to the NICOS PGAA demo setup.")
printinfo("============================================================")
'''
