# DO NOT EDIT THIS FILE!
#
# Python module CARESS__POA generated by omniidl

import omniORB
omniORB.updateModule("CARESS__POA")

# ** 1. Stub files contributing to this module
import nicos_mlz.delab.devices.corbadevice_idl

# ** 2. Sub-modules

# ** 3. End
