description = 'Counter devices in the SINQ AMOR.'

pvprefix = 'SQ:AMOR:mota:'

devices = dict(
    com=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter tilt motor',
               motorpv=pvprefix + 'com',
               ),
    coz=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter z translation motor',
               motorpv=pvprefix + 'coz',
               ),
    c3z=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter z position single counter motor',
               motorpv=pvprefix + 'c3z',
               ),
    cox=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter x translation motor',
               motorpv=pvprefix + 'cox',
               ),
    eoz=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter z lift Selene support motor',
               motorpv=pvprefix + 'eoz',
               ),
    xlz=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter z position distance laser motor',
               motorpv=pvprefix + 'xlz',
               ),
    eom=device('nicos_ess.essiip.devices.epics_motor.EpicsMotor',
               epicstimeout=3.0,
               description='Counter omega Selene support motor',
               motorpv=pvprefix + 'eom',
               ),
)
