description = 'Monochroamtor devices SINQ HRPT.'

pvprefix  = 'SQ:HRPT:mota:'
mexprefix = 'SQ:HRPT:motb:'

devices = dict(
    momu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Theta Motor',
               motorpv=pvprefix + 'MOMU',
               errormsgpv=pvprefix + 'MOMU-MsgTxt',
               precision=0.02,
               ),

    mtvu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Upper Translation',
               motorpv=pvprefix + 'MTVU',
               errormsgpv=pvprefix + 'MTVU-MsgTxt',
               precision=0.02,
               ),

    mtpu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Lower Tranlation',
               motorpv=pvprefix + 'MTPU',
               errormsgpv=pvprefix + 'MTPU-MsgTxt',
               precision=0.02,
              ),

    mgvu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Upper Tilt',
               motorpv=pvprefix + 'MGVU',
               errormsgpv=pvprefix + 'MGVU-MsgTxt',
               precision=0.02,
               ),
    mgpu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Lower Tilt',
               motorpv=pvprefix + 'MGPU',
               errormsgpv=pvprefix + 'MGPU-MsgTxt',
               precision=0.02,
              ),

    mcvu=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Upper Monochromator Curvature',
               motorpv=pvprefix + 'MCVU',
               errormsgpv=pvprefix + 'MCVU-MsgTxt',
               precision=0.02,
              ),
    moml=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Theta Motor',
               motorpv=pvprefix + 'MOML',
               errormsgpv=pvprefix + 'MOML-MsgTxt',
               precision=0.02,
               ),

    mtvl=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Upper Translation',
               motorpv=pvprefix + 'MTVL',
               errormsgpv=pvprefix + 'MTVL-MsgTxt',
               precision=0.02,
               ),

    mtpl=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Lower Tranlation',
               motorpv=pvprefix + 'MTPL',
               errormsgpv=pvprefix + 'MTPL-MsgTxt',
               precision=0.02,
                   ),

    mgvl=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Upper Tilt',
               motorpv=pvprefix + 'MGVL',
               errormsgpv=pvprefix + 'MGVL-MsgTxt',
               precision=0.02,
                   ),
    mgpl=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Lower Tilt',
               motorpv=pvprefix + 'MGPL',
               errormsgpv=pvprefix + 'MGPL-MsgTxt',
               precision=0.02,
                   ),

    mcvl=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Lower Monochromator Curvature',
               motorpv=pvprefix + 'MCVL',
               errormsgpv=pvprefix + 'MCVL-MsgTxt',
               precision=0.02,
                   ),

    mexz=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Monochromator Lift Position',
               motorpv=mexprefix + 'MEXZ',
               errormsgpv=mexprefix + 'MEXZ-MsgTxt',
               precision=0.5,
                   ),
    wavelength = device('nicos.devices.generic.manual.ManualMove',
                        description='GE Monochromator',
                        default='1.17',
                        unit = 'A',
                        abslimits=(1,7),
                        )
)
