description = 'Slit 2 devices in the SINQ HRPT.'


pvprefix = 'SQ:HRPT:mote:'

devices = dict(
    brle=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Slit 2 left motor',
               motorpv=pvprefix + 'BRLE',
               errormsgpv=pvprefix + 'BRLE-MsgTxt',
               precision=0.01,
               ),
    brri=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Slit 2 right motor',
               motorpv=pvprefix + 'BRRI',
               errormsgpv=pvprefix + 'BRRI-MsgTxt',
               precision=0.01,
               ),
    brto=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Slit 2 top motor',
               motorpv=pvprefix + 'BRTO',
               errormsgpv=pvprefix + 'BRTO-MsgTxt',
               precision=0.01,
               ),
    brbo=device('nicos_ess.devices.epics.motor.EpicsMotor',
               epicstimeout=3.0,
               description='Slit 2 bottom motor',
               motorpv=pvprefix + 'BRBO',
               errormsgpv=pvprefix + 'BRBO-MsgTxt',
               precision=0.01,
               ),
    slit2=device('nicos.devices.generic.slit.Slit',
                 description='Slit 2 with left, right, bottom and top motors',
                 opmode='4blades',
                 left='brle',
                 right='brri',
                 top='brto',
                 bottom='brbo',
                 lowlevel=True
                 ),
    slit2_opening=device('nicos_sinq.amor.devices.slit.SlitOpening',
                         description='Slit 2 opening controller',
                         slit='slit2',
                         ),
    slit2_width=device('nicos.devices.generic.slit.WidthSlitAxis',
                       description='Slit 2width controller',
                       slit='slit2',
                       unit='mm',
                       requires={'level': 'admin'}
                       ),
)
