description = 'Primary slit devices'

group = 'lowlevel'

devices = dict(
    slits_u = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITS_U',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-10, 43),
        lowlevel = True,
        speed = 1,
    ),
    slits_d = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITS_D',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-43, 10),
        lowlevel = True,
        speed = 1,
    ),
    slits_l = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITS_L',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-26, 10),
        lowlevel = True,
        speed = 1,
    ),
    slits_r = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITS_R',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (-10, 26),
        lowlevel = True,
        speed = 1,
    ),
    slits = device('nicos_mlz.stressi.devices.slit.Slit',
        description = 'sample slit 4 blades',
        left = 'slits_l',
        right = 'slits_r',
        bottom = 'slits_d',
        top = 'slits_u',
        opmode = 'centered',
        pollinterval = 5,
        maxage = 10,
    ),
    slitm_w = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITM_W',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (0, 100),
        lowlevel = True,
        speed = 1,
    ),
    slitm_h = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITM_H',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (0, 155),
        lowlevel = True,
        speed = 1,
    ),
    slitm = device('nicos_mlz.stressi.devices.slit.TwoAxisSlit',
        description = 'Monochromator entry slit',
        horizontal = 'slitm_w',
        vertical = 'slitm_h',
    ),
    slite = device('nicos.devices.generic.VirtualMotor',
        description = 'SLITE',
        fmtstr = '%.2f',
        unit = 'mm',
        abslimits = (0, 70),
        speed = 1,
    ),
)
