includes = ['system', 'detector', 'cascade', 'lakeshore']

devices = dict(
    Sample   = device('nicos.tas.TASSample'),

    mira     = device('nicos.tas.TAS',
                      instrument = 'MIRA',
                      responsible = 'Robert Georgii <robert.georgii@frm2.tum.de>',
                      cell = 'Sample',
                      phi = 't_phi',
                      psi = 't_psi',
                      mono = 't_mono',
                      ana = 't_ana'
                      ),

    t_phi    = device('nicos.virtual.VirtualMotor',
                      abslimits = (-180, 180), 
                      initval = 0,
                      speed = 1,
                      jitter = 0.01,
                      unit = 'deg'),

    t_psi    = device('nicos.virtual.VirtualMotor',
                      abslimits = (0, 360),
                      initval = 0,
                      jitter = 0.05,
                      unit = 'deg'),

    t_mono   = device('nicos.virtual.VirtualMotor',
                      unit = 'A-1',
                      abslimits = (0, 10),
                      jitter = 0.02,
                      initval = 2.662),

    t_ana    = device('nicos.virtual.VirtualMotor',
                      unit = 'A-1',
                      abslimits = (0, 10),
                      jitter = 0.02,
                      initval = 2.662),

    t_ki     = device('nicos.tas.Wavevector',
                      unit = 'A-1',
                      base = 't_mono',
                      tas = 'mira',
                      scanmode = 'CKI',
                      abslimits = (0, 10)),

    t_kf     = device('nicos.tas.Wavevector',
                      unit = 'A-1',
                      base = 't_ana',
                      tas = 'mira',
                      scanmode = 'CKF',
                      abslimits = (0, 10)),

    MonoToni = device('nicos.mira.toni.ModBus',
                      tacodevice = 'mira/rs232/monotoni',
                      tacolog = False,
                      loglevel = 'debug', 
                      lowlevel = True),

#    LeckToni  = device('nicos.mira.toni.ModBus',
#                       tacodevice = 'mira/rs232/lecktoni',
#                       lowlevel = True),
#
    atten1   = device('nicos.mira.toni.Valve',
                      bus = 'MonoToni',
                      addr = 241,
                      channel = 6,
                      states = ['out', 'in']),
    atten2   = device('nicos.mira.toni.Valve',
                      bus = 'MonoToni',
                      addr = 241,
                      channel = 7,
                      states = ['out', 'in']),
    lamfilter = device('nicos.mira.toni.Valve',
                       bus = 'MonoToni',
                       addr = 241,
                       channel = 4,
                       states = ['in', 'out']),
    FOLin     = device('nicos.mira.toni.Valve',
                       bus = 'MonoToni',
                       addr = 241,
                       channel = 0,
                       states = ['out', 'in']),
    FlipperMira1in = device('nicos.mira.toni.Valve',
                       bus = 'MonoToni',
                       addr = 241,
                       channel = 3,
                       states = ['out', 'in']),
    FlipperMira2in = device('nicos.mira.toni.Valve',
                       bus = 'MonoToni',
                       addr = 241,
                       channel = 3,
                       states = ['in', 'out']),


    s3l       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit1/left',
                       abslimits= (-35, 65)),
    s3r       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit1/right',
                       abslimits= (-65, 35)),
    s3b       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit1/bottom',
                       abslimits= (-65, 35)),
    s3t       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit1/top',
                       abslimits= (-35, 65)),

    s3        = device('nicos.slit.Slit',
                       left = 's3l',
                       right = 's3r',
                       bottom = 's3b',
                       top = 's3t',
                       pollinterval = 5,
                       maxage = 10),

    s4l       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit2/left',
                       abslimits= (-35, 65)),
    s4r       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit2/right',
                       abslimits= (-65, 35)),
    s4b       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit2/bottom',
                       abslimits= (-65, 35)),
    s4t       = device('nicos.motor.Motor',
                       lowlevel = True,
                       tacodevice = 'mira/slit2/top',
                       abslimits= (-35, 65)),

    s4        = device('nicos.slit.Slit',
                       left = 's4l',
                       right = 's4r',
                       bottom = 's4b',
                       top = 's4t',
                       pollinterval = 5,
                       maxage = 10),


    # Leckmon   = device('nicos.mira.toni.Leckmon',
    #                    bus = 'LeckToni',
    #                    addr = 0x17,
    #                    unit = ''),
)
