name = 'standard detector and counter card'

devices = dict(
    timer    = device('nicos.detector.FRMTimerChannel',
                      tacodevice = '//mirasrv/mira/frmctr/at',
                      fmtstr = '%.2f',
                      lowlevel = True),
    mon1     = device('nicos.detector.FRMCounterChannel',
                      tacodevice = '//mirasrv/mira/frmctr/a1',
                      type = 'monitor',
                      fmtstr = '%d',
                      lowlevel = True),
    ctr1     = device('nicos.detector.FRMCounterChannel',
                      tacodevice = '//mirasrv/mira/frmctr/a2',
                      type = 'counter',
                      fmtstr = '%d',
                      lowlevel = True),
#    ctr2     = device('nicos.detector.FRMCounterChannel',
#                      tacodevice = '//mirasrv/mira/frmctr/a3',
#                      type = 'counter',
#                      fmtstr = '%d',
#                      lowlevel = True),

    det      = device('nicos.detector.FRMDetector',
                      t  = 'timer',
                      m1 = 'mon1',
                      m2 = None,
                      m3 = None,
                      z1 = 'ctr1',
                      z2 = None,
                      z3 = None,
                      z4 = None,
                      z5 = None,
                      maxage = 3,
                      pollinterval = 0.5),

    DetHV     = device('nicos.mira.iseg.IsegHV',
                       tacodevice = 'mira/network/rs12_2',
                       channel = 1,
                       pollinterval = 10,
                       maxage = 20,
                       abslimits = (0, 950),
                       fmtstr = '%d',
                       ),

    MonHV     = device('nicos.mira.iseg.IsegHV',
                       tacodevice = 'mira/network/rs7_4',
                       channel = 1,
                       abslimits = (0, 500),
                       pollinterval = 10,
                       maxage = 30,
                       fmtstr = '%d',
                       ),
)
