description = 'standard detector and counter card'

includes = ['base']

devices = dict(
    timer    = device('nicos.taco.FRMTimerChannel',
                      tacodevice = '//mirasrv/mira/frmctr/at',
                      fmtstr = '%.2f',
                      lowlevel = True),
    mon1     = device('nicos.taco.FRMCounterChannel',
                      tacodevice = '//mirasrv/mira/frmctr/a1',
                      type = 'monitor',
                      fmtstr = '%d',
                      lowlevel = True),
    mon2     = device('nicos.taco.FRMCounterChannel',
                      tacodevice = '//mirasrv/mira/frmctr/a2',
                      type = 'monitor',
                      fmtstr = '%d',
                      lowlevel = True),
    ctr1     = device('nicos.taco.FRMCounterChannel',
                      tacodevice = '//mirasrv/mira/frmctr/a3',
                      type = 'counter',
                      fmtstr = '%d',
                      lowlevel = True),

    det      = device('nicos.taco.FRMDetector',
                      timer  = 'timer',
                      monitors = ['mon1', 'mon2'],
                      counters = ['ctr1'],
                      fmtstr = 'timer %s, mon1 %s, mon2 %s, ctr1 %s',
                      maxage = 2,
                      pollinterval = 0.5),

    DetHV     = device('nicos.mira.iseg.IsegHV',
                       tacodevice = 'mira/network/rs12_2',
                       channel = 1,
                       pollinterval = 10,
                       maxage = 20,
                       abslimits = (0, 950),
                       fmtstr = '%d',
                       ),

    MonHV     = device('nicos.mira.iseg.IsegHV',
                       tacodevice = 'mira/network/rs7_4',
                       channel = 1,
                       abslimits = (0, 500),
                       pollinterval = 10,
                       maxage = 30,
                       fmtstr = '%d',
                       ),
)
