description = 'PUMA Eulerian cradle with IPC motorbus'
group = 'optional'

includes = ['base']
excludes = ['mono1']

devices = dict(
    co_ephi  = device('devices.taco.Coder',
                      lowlevel = True,
                      tacodevice = '//mirasrv/mira/encoder/ephi',
                      unit = 'deg',
                     ),
    mo_ephi  = device('devices.taco.Motor',
                      lowlevel = True,
                      tacodevice = '//mirasrv/mira/motor/ephi',
                      abslimits = (-355.0, 355.0),
                      unit = 'deg',
                     ),
    ephi     = device('devices.generic.Axis',
                      description = 'Eulerian cradle "phi" axis (the small circle)',
                      motor = 'mo_ephi',
                      coder = 'co_ephi',
                      obs = [],
                      fmtstr = '%.3f',
                      precision = 0.01,
                     ),

    co_echi  = device('devices.taco.Coder',
                      lowlevel = True,
                      tacodevice = '//mirasrv/mira/encoder/echi',
                      unit = 'deg',
                     ),
    mo_echi  = device('devices.taco.Motor',
                      lowlevel = True,
                      tacodevice = '//mirasrv/mira/motor/echi',
                      abslimits = (-355.0, 355.0),
                      unit = 'deg',
                     ),
    echi     = device('devices.generic.Axis',
                      description = 'Eulerian cradle "chi" axis (the big circle)',
                      motor = 'mo_echi',
                      coder = 'co_echi',
                      obs = [],
                      fmtstr = '%.3f',
                      precision = 0.01,
                      offset = -189.99926762282576,
                     ),

    ec       = device('devices.tas.EulerianCradle',
                      description = 'Eulerian cradle abstract device to move to a given scattering plane',
                      tas = 'mira',
                      chi = 'echi',
                      omega = 'ephi',
                      cell = 'Sample',
                     ),
)
