description = 'memograph readout'

includes = []

group = 'optional'

devices = dict(
    t_in_memograph = device('frm2.memograph.MemographValue',
                            hostname = 'memograph02.care.frm2',
                            group = 1,
                            valuename = 'T_in MIRA',
                            description = 'inlet temperature memograph',
                            fmtstr = '%.2F',
                            warnlimits = (-1, 17.5), #-1 no lower value
                            unit = 'degC',
                            #lowlevel = True,
                           ),
    t_out_memograph = device('frm2.memograph.MemographValue',
                             hostname = 'memograph02.care.frm2',
                             group = 1,
                             valuename = 'T_out MIRA',
                             description = 'outlet temperature memograph',
                             fmtstr = '%.2F',
                             unit = 'degC',
                             #lowlevel = True,
                            ),
    p_in_memograph = device('frm2.memograph.MemographValue',
                            hostname = 'memograph02.care.frm2',
                            group = 1,
                            valuename = 'P_in MIRA',
                            description = 'inlet pressure memograph',
                            fmtstr = '%.2F',
                            unit = 'bar',
                            #lowlevel = True,
                           ),
    p_out_memograph = device('frm2.memograph.MemographValue',
                             hostname = 'memograph02.care.frm2',
                             group = 1,
                             valuename = 'P_out MIRA',
                             description = 'outlet pressure memograph',
                             fmtstr = '%.2F',
                             unit = 'bar',
                             #lowlevel = True,
                            ),
    flow_in_memograph = device('frm2.memograph.MemographValue',
                            hostname = 'memograph02.care.frm2',
                            group = 1,
                            valuename = 'FLOW_in MIRA',
                            description = 'inlet flow memograph',
                            fmtstr = '%.2F',
                            warnlimits = (0.2, 100), #100 no upper value
                            unit = 'l/min',
                            #lowlevel = True,
                           ),
    flow_out_memograph = device('frm2.memograph.MemographValue',
                                hostname = 'memograph02.care.frm2',
                                group = 1,
                                valuename = 'FLOW_out MIRA',
                                description = 'outlet flow memograph',
                                fmtstr = '%.2F',
                                unit = 'l/min',
                                #lowlevel = True,
                               ),
    leak_memograph = device('frm2.memograph.MemographValue',
                            hostname = 'memograph02.care.frm2',
                            group = 1,
                            valuename = 'Leak MIRA',
                            description = 'leakage memograph',
                            fmtstr = '%.2F',
                            warnlimits = (-1, 1), #-1 no lower value
                            unit = 'l/min',
                            #lowlevel = True,
                           ),
    cooling_memograph = device('frm2.memograph.MemographValue',
                               hostname = 'memograph02.care.frm2',
                               group = 1,
                               valuename = 'Cooling MIRA',
                               description = 'cooling memograph',
                               fmtstr = '%.2F',
                               unit = 'kW',
                               #lowlevel = True,
                              ),
)
