name = 'MIEZE devices'

devices = dict(
    amp1     = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_2/amp',
                      abslimits = (0, 1)),
    amp2     = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_3/amp',
                      abslimits = (0, 1)),
    amp3     = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_1/amp',
                      abslimits = (0, 1)),
    amp4     = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_4/amp',
                      abslimits = (0, 1)),

    freq1    = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_2/freq',
                      fmtstr = '%.0f',
                      abslimits = (0, 80000000)),
    freq2    = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_3/freq',
                      fmtstr = '%.0f',
                      abslimits = (0, 80000000)),
    freq3    = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_1/freq',
                      fmtstr = '%.0f',
                      abslimits = (0, 80000000)),
    freq4    = device('nicos.mira.agilent.HFDevice',
                      tacodevice = '//mira4/mira/hp33220a_4/freq',
                      fmtstr = '%.0f',
                      abslimits = (0, 80000000)),

    tf3 = device('nicos.virtual.ArbitraryValues', which='freq4',
          steps=(1,1,3,5,7,11,8,4,3,2,1,1,1), unit='ds'),

#    pk2pk1   = device('nicos.io.AnalogInput',
#                      tacodevice = '//mira4/mira/tds2014/ch1_pk2pk'),
#    pk2pk2   = device('nicos.io.AnalogInput',
#                      tacodevice = '//mira4/mira/tds2014/ch2_pk2pk'),
#    pk2pk3   = device('nicos.io.AnalogInput',
#                      tacodevice = '//mira4/mira/tds2014/ch3_pk2pk'),
#    pk2pk4   = device('nicos.io.AnalogInput',
#                      tacodevice = '//mira4/mira/tds2014/ch4_pk2pk'),
#
   # dc1       = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/heinzinger/current',
   #                    abslimits = (0, 100),
   #                    ramp = 0,
   #                    variance = 5,
   #                    fmtstr = '%.2f'),
   # dc2       = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/ntn14000m/current',
   #                    abslimits = (0, 100),
   #                    ramp = 0,
   #                    variance = 5,
   #                    fmtstr = '%.2f'),

   # dc3n25    = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_1/n25cur',
   #                    abslimits = (0, 1),
   #                    fmtstr = '%.2f'),
   # dc3p25    = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_1/p25cur',
   #                    abslimits = (0, 1),
   #                    fmtstr = '%.2f'),
   # dc3p6     = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_1/p6cur',
   #                    abslimits = (0, 5),
   #                    fmtstr = '%.2f'),

   # dc4n25    = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_2/n25cur',
   #                    abslimits = (0, 1),
   #                    fmtstr = '%.2f'),
   # dc4p25    = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_2/p25cur',
   #                    abslimits = (0, 1),
   #                    fmtstr = '%.2f'),
   # dc4p6     = device('nicos.power.CurrentSupply',
   #                    tacodevice = '//mira4/mira/hpe3631a_2/p6cur',
   #                    abslimits = (0, 5),
   #                    fmtstr = '%.2f'),

   # fp1       = device('nicos.io.AnalogInput',
   #                    tacodevice = '//mira4/mira/ag1016/fp01'),
   # rp1       = device('nicos.io.AnalogInput',
   #                    tacodevice = '//mira4/mira/ag1016/rp01'),
   # fp2       = device('nicos.io.AnalogInput',
   #                    tacodevice = '//mira4/mira/ag1016/fp02'),
   # rp2       = device('nicos.io.AnalogInput',
   #                    tacodevice = '//mira4/mira/ag1016/rp02'),

   # Cbox1    = device('nicos.io.BitsDigitalOutput',
   #                   tacodevice = '//mira4/mira/pci2032/dev0',
   #                   startbit = 0,
   #                   bitwidth = 30),
   # Cbox2    = device('nicos.io.BitsDigitalOutput',
   #                   tacodevice = '//mira4/mira/pci2032/dev1',
   #                   startbit = 0,
   #                   bitwidth = 30),

   # Reverse1 = device('nicos.io.PartialDigitalOutput',
   #                   tacodevice = '//mira4/mira/pci2032/dev0',
   #                   startbit = 30,
   #                   bitwidth = 1),
   # Reverse2 = device('nicos.io.PartialDigitalOutput',
   #                   tacodevice = '//mira4/mira/pci2032/dev0',
   #                   startbit = 30,
   #                   bitwidth = 1),

#    mult     = device('nicos.mira.tmca.Channel',
#                      tacodevice = '//mira4/mira/frmtmca/channel',
#                      admin = '//mira4/mira/frmtmca/admin',
#                      maxage = 1,
#                      fmtstr = '%s'),
)
