description = 'sample table'
group = 'lowlevel'

includes = ['alias_sth']

tango_host = 'mira1.mira.frm2:10000'

devices = dict(
    co_stt   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/phi_enc' % tango_host,
                      unit = 'deg',
                     ),
    mo_stt   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/phi_mot' % tango_host,
                      abslimits = (-120, 120),
                      unit = 'deg',
                      precision = 0.002,
                     ),
    stt      = device('mira.axis.HoveringAxis',
                      description = 'sample two-theta angle',
                      abslimits = (-120, 120),
                      motor = 'mo_stt',
                      coder = 'co_stt',
                      obs = [],
                      startdelay = 1,
                      stopdelay = 2,
                      switch = 'air_sample',
                      switchvalues = (0, 1),
                      fmtstr = '%.3f',
                      precision = 0.002,
                     ),

    air_mono   = device('devices.tango.DigitalOutput',
                        tangodevice = 'tango://%s/mira/air/mono' % tango_host,
                        lowlevel = True,
                       ),

    air_sample = device('mira.refcountio.RefcountDigitalOutput',
                        tangodevice = 'tango://%s/mira/air/sample' % tango_host,
                        lowlevel = True,
                       ),

    air_ana    = device('mira.refcountio.RefcountDigitalOutput',
                        tangodevice = 'tango://%s/mira/air/det' % tango_host,
                        lowlevel = True,
                       ),

    co_sth_st = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/om_enc' % tango_host,
                      unit = 'deg',
                     ),
    mo_sth_st = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/om_mot' % tango_host,
                      abslimits = (-180, 180),
                      unit = 'deg',
                      precision = 0.001,
                     ),
    sth_st   = device('devices.generic.Axis',
                      description = 'sample theta angle',
                      motor = 'mo_sth_st',
                      coder = 'co_sth_st',
                      obs = [],
                      fmtstr = '%.3f',
                      precision = 0.001,
                     ),

    co_stz   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/stz_enc' % tango_host,
                      unit = 'mm',
                     ),
    mo_stz   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/stz_mot' % tango_host,
                      abslimits = (0, 40),
                      unit = 'mm',
                      precision = 0.1,
                     ),
    stz      = device('devices.generic.Axis',
                      description = 'sample translation in vertical direction',
                      motor = 'mo_stz',
                      coder = 'co_stz',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.1,
                     ),

    co_stx   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/stx_enc' % tango_host,
                      unit = 'mm',
                     ),
    mo_stx   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/stx_mot' % tango_host,
                      abslimits = (-25, 25),
                      unit = 'mm',
                      precision = 0.01,
                     ),
    stx      = device('devices.generic.Axis',
                      description = 'sample translation along the beam (for sth_st=0)',
                      motor = 'mo_stx',
                      coder = 'co_stx',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),

    co_sty   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sty_enc' % tango_host,
                      unit = 'mm',
                     ),
    mo_sty   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sty_mot' % tango_host,
                      abslimits = (-25, 25),
                      unit = 'mm',
                      precision = 0.01,
                     ),
    sty      = device('devices.generic.Axis',
                      description = 'sample translation horizontally perpendicular to the beam (for sth_st=0)',
                      motor = 'mo_sty',
                      coder = 'co_sty',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),

    co_sgx   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sgx_enc' % tango_host,
                      unit = 'deg',
                     ),
    mo_sgx   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sgx_mot' % tango_host,
                      abslimits = (-5, 5),
                      unit = 'deg',
                      precision = 0.01,
                     ),
    sgx      = device('devices.generic.Axis',
                      description = 'sample tilt around beam axis (for sth_st=0)',
                      motor = 'mo_sgx',
                      coder = 'co_sgx',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),

    co_sgy   = device('devices.tango.Sensor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sgy_enc' % tango_host,
                      unit = 'deg',
                     ),
    mo_sgy   = device('devices.tango.Motor',
                      lowlevel = True,
                      tangodevice = 'tango://%s/mira/sample/sgy_mot' % tango_host,
                      abslimits = (-5, 5),
                      unit = 'deg',
                      precision = 0.01,
                     ),
    sgy      = device('devices.generic.Axis',
                      description = 'sample tilt orthogonal to beam axis (for sth_st=0)',
                      motor = 'mo_sgy',
                      coder = 'co_sgy',
                      obs = [],
                      fmtstr = '%.2f',
                      precision = 0.01,
                     ),
)

alias_config = {
    'sth': {'sth_st': 0},
}
