description = 'sample table'
group = 'lowlevel'

devices = dict(
    phi      = device('devices.taco.HoveringAxis',
                      description = 'sample two-theta',
                      tacodevice = 'mira/axis/phi',
                      abslimits = (-120, 120),
                      startdelay = 1,
                      stopdelay = 2,
                      switch = 'air_sample',
                      switchvalues = (0, 1),
                      fmtstr = '%.3f'),

    air_mono   = device('devices.taco.DigitalOutput',
                        tacodevice = 'mira/phytronio/air_mono',
                        lowlevel = True),

    air_sample = device('mira.refcountio.RefcountDigitalOutput',
                        tacodevice = 'mira/phytronio/air_sample',
                        lowlevel = True),

    air_ana    = device('mira.refcountio.RefcountDigitalOutput',
                        tacodevice = 'mira/phytronio/air_det',
                        lowlevel = True),

    om       = device('devices.taco.Axis',
                      description = 'sample theta',
                      tacodevice = 'mira/axis/om',
                      abslimits = (-180, 180),
                      fmtstr = '%.3f'),
    stx      = device('devices.taco.Axis',
                      description = 'sample translation along the beam',
                      tacodevice = 'mira/axis/stx',
                      abslimits = (-25, 25),
                      fmtstr = '%.2f'),
    sty      = device('devices.taco.Axis',
                      description = 'horizontal sample translation',
                      tacodevice = 'mira/axis/sty',
                      abslimits = (-25, 25),
                      fmtstr = '%.2f'),
    stz      = device('devices.taco.Axis',
                      description = 'vertical sample translation',
                      tacodevice = 'mira/axis/stz',
                      abslimits = (0, 40),
                      fmtstr = '%.2f'),
    sgx      = device('devices.taco.Axis',
                      description = 'sample tilt around beam axis',
                      tacodevice = 'mira/axis/sgx',
                      abslimits = (-5, 5),
                      fmtstr = '%.2f'),
    sgy      = device('devices.taco.Axis',
                      description = 'sample tilt orthogonal to beam axis',
                      tacodevice = 'mira/axis/sgy',
                      abslimits = (-5, 5),
                      fmtstr = '%.2f'),
)
