description = 'Huber sample slits'
group = 'lowlevel'

devices = dict(
    ss1r       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss1/left',
                        abslimits = (-35, 65),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss1l       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss1/right',
                        abslimits = (-65, 35),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss1b       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss1/bottom',
                        abslimits = (-65, 35),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss1t       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss1/top',
                        abslimits = (-35, 65),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),

    ss1        = device('devices.generic.Slit',
                        description = 'First sample slit',
                        left = 'ss1l',
                        right = 'ss1r',
                        bottom = 'ss1b',
                        top = 'ss1t',
                        opmode = 'offcentered',
                        pollinterval = 5,
                        maxage = 10,
                       ),

    ss2r       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss2/left',
                        abslimits = (-35, 65),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss2l       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss2/right',
                        abslimits = (-65, 35),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss2b       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss2/bottom',
                        abslimits = (-65, 35),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),
    ss2t       = device('devices.taco.Motor',
                        lowlevel = True,
                        tacodevice = '//mirasrv/mira/ss2/top',
                        abslimits = (-35, 65),
                        resetcall = 'deviceInit',
                        precision = 0.1,
                       ),

    ss2        = device('devices.generic.Slit',
                        description = 'Second sample slit',
                        left = 'ss2l',
                        right = 'ss2r',
                        bottom = 'ss2b',
                        top = 'ss2t',
                        opmode = 'offcentered',
                        pollinterval = 5,
                        maxage = 10,
                       ),
)
