description = 'Non-electronically adjustable parameters of the detector'

group = 'optional'

devices = dict(
    scintillator = device('nicos.devices.generic.manual.ManualSwitch',
        description = 'Scintillator installed in the camera box',
        states = ['050um LiF:ZnS',
                  '100um LiF:ZnS',
                  '150um LiF:ZnS',
                  '200um LiF:ZnS',
                  '300um LiF:ZnS',
                  '010um Gd2O2S',
                  '020um Gd2O2S',
                  'other',
                  ],
    ),
    lens = device('nicos.devices.generic.manual.ManualSwitch',
        description = 'Lens installed in the camera box',
        states = ['Leica 100mm F2.8',
                  'Leica 100mm with macro adapter',
                  'Zeiss 100mm F1.8',
                  'other',
                  ],
   ),
    pixelsize = device('nicos.devices.generic.manual.ManualMove',
        description = 'Effective pixel size of the detector system in micrometers',
        unit = 'micrometers',
        abslimits = (0,99999999),
    ),
    L_sample = device('nicos.devices.generic.manual.ManualMove',
        description = 'Distance of sample from the pinhole',
        unit = 'mm',
        abslimits = (0,99999999),
    ),
    L_detector = device('nicos.devices.generic.manual.ManualMove',
        description = 'Distance of detector from the pinhole',
        unit = 'mm',
        abslimits = (0,99999999),
    ),
    camerabox = device('nicos.devices.generic.manual.ManualSwitch',
        description = 'Used camera box',
        states = ['Black Box',
                  'Neo Box - 1 mirror config',
                  'Neo Box - 2 mirror config',
                  'Large detector in chamber 2',
                  'other',
                  ],
    ),
)
