description = 'setup for the velocity selector'

tango_base = 'tango://antareshw.antares.frm2:10000/antares/'

devices = dict(
    selector = device('nicos.devices.tango.WindowTimeoutAO',
        description = 'Selector speed control',
        tangodevice = tango_base + 'selector/speed',
        unit = 'rpm',
        fmtstr = '%.0f',
        warnlimits = (0, 3200),
        abslimits = (3100, 21000),
        precision = 50,
        timeout = 600,
    ),
    selector_lambda = device('nicos.devices.vendor.astrium.SelectorLambda',
        description = 'Selector wavelength control',
        seldev = 'selector',
        unit = 'A',
        fmtstr = '%.2f',
        twistangle = 23.5,
        length = 0.25,
        beamcenter = 0.115,
        maxspeed = 21000,
    ),
    selector_lambda_tilt = device('nicos.devices.vendor.astrium.SelectorLambda',
        description = 'Selector center wavelength '
        'control',
        seldev = 'selector',
        unit = 'A',
        fmtstr = '%.2f',
        twistangle = 12.63,
        length = 0.25,
        beamcenter = 0.115,
        maxspeed = 21000,
    ),
    selector_sspeed = device('nicos.devices.tango.AnalogInput',
        description = 'Selector speed read out by optical sensor',
        tangodevice = tango_base + 'selector/sspeed',
        unit = 'Hz',
        fmtstr = '%.1f',
    ),
    selector_vacuum = device('nicos.devices.tango.AnalogInput',
        description = 'Vacuum in the selector',
        tangodevice = tango_base + 'selector/vacuum',
        unit = 'mbar',
        fmtstr = '%.5f',
        warnlimits = (0, 0.005),
    ),
    selector_rtemp = device('nicos.devices.tango.AnalogInput',
        description = 'Temperature of the selector rotor',
        tangodevice = tango_base + 'selector/rotortemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (10, 45),
    ),
    selector_wflow = device('nicos.devices.tango.AnalogInput',
        description = 'Cooling water flow rate through selector',
        tangodevice = tango_base + 'selector/flowrate',
        unit = 'l/min',
        fmtstr = '%.1f',
        warnlimits = (1.5, 10),
    ),
    selector_winlt = device('nicos.devices.tango.AnalogInput',
        description = 'Cooling water temperature at inlet',
        tangodevice = tango_base + 'selector/waterintemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (15, 20),
    ),
    selector_woutt = device('nicos.devices.tango.AnalogInput',
        description = 'Cooling water temperature at outlet',
        tangodevice = tango_base + 'selector/waterouttemp',
        unit = 'degC',
        fmtstr = '%.1f',
        warnlimits = (15, 20),
    ),
    selector_vibrt = device('nicos.devices.tango.AnalogInput',
        description = 'Selector vibration',
        tangodevice = tango_base + 'selector/vibration',
        unit = 'mm/s',
        fmtstr = '%.2f',
        warnlimits = (0, 1),
    ),
    selector_linear = device('nicos.devices.tango.Motor',
        description = 'Selector translation',
        unit = 'mm',
        tangodevice = tango_base + 'fzjs7/Selektor_linear',
        lowlevel = True,
    ),
    selector_inout = device('nicos.devices.generic.Switcher',
        description = 'Moves Selector in and out of beam',
        moveable = 'selector_linear',
        mapping = {'out': 165.0,
                   'in': 0.0},
        fallback = '<undefined>',
        unit = '',
        maxage = 5,
        pollinterval = 3,
        precision = 0.5,
    ),
    selector_tilt = device('nicos.devices.taco.Motor',
        speed = 0.05,
        unit = 'deg',
        description = 'tilt of velocity selector',
        tacodevice = 'antares/copley/m16',
        abslimits = (-5, 5),
        userlimits = (-5, 5),
        fixed = 'Do not move while selector is running!',
        fixedby = ('admin', 20),
        lowlevel = False,
        maxage = 7,
        pollinterval = 3,
    ),
)
