# -*- coding: utf-8 -*-

description = 'sample aperture and table'
group = 'lowlevel'

devices = dict(
    ap_sam_x0 = device('nicos.devices.generic.VirtualMotor',
        description = 'sample aperture horz. blade 0',
        lowlevel = True,
        unit = 'mm',
        abslimits = (-15, 15),
        speed = 1,
        curvalue = 15,
    ),
    ap_sam_y0 = device('nicos.devices.generic.VirtualMotor',
        description = 'sample aperture vert. blade 0',
        lowlevel = True,
        unit = 'mm',
        abslimits = (-15, 15),
        speed = 1,
        curvalue = 15,
    ),
    ap_sam_x1 = device('nicos.devices.generic.VirtualMotor',
        description = 'sample aperture horz. blade 1',
        lowlevel = True,
        unit = 'mm',
        abslimits = (-15, 15),
        speed = 1,
        curvalue = 15,
    ),
    ap_sam_y1 = device('nicos.devices.generic.VirtualMotor',
        description = 'sample aperture vert. blade 1',
        lowlevel = True,
        unit = 'mm',
        abslimits = (-15, 15),
        speed = 1,
        curvalue = 15,
    ),
    ap_sam = device('nicos.devices.generic.Slit',
        description = 'sample aperture',
        coordinates = 'opposite',
        opmode = 'offcentered',
        left = 'ap_sam_x1',
        right = 'ap_sam_x0',
        bottom = 'ap_sam_y0',
        top = 'ap_sam_y1',
    ),
    sam_trans_x = device('nicos.devices.generic.VirtualMotor',
        description = 'sample translation left-right',
        unit = 'mm',
        abslimits = (0, 13*21),
        speed = 1,
        curvalue = 1,
    ),
    sam_trans_y = device('nicos.devices.generic.VirtualMotor',
        description = 'sample translation up-down',
        unit = 'mm',
        abslimits = (0, 100),
        speed = 1,
    ),
)
